import { ValidationError } from "./errors.js";
import { isReservedName } from "./reserved.js";

function buildSchemaRegistry(schemas: string[]): string {
  // Generated files are written directly (not through the template `file()` helper),
  // so relative imports omit the .js extension to match the normalized style.
  const lines = schemas.map((s) => `export * from "./${s}";`);
  return ["// Generated by ghostinit sync. Do not edit manually.", ...lines].join("\n") + "\n";
}

const DYNAMIC_SCHEMA_START = "// ghostinit-sync:module-schemas:start";
const DYNAMIC_SCHEMA_END = "// ghostinit-sync:module-schemas:end";

function buildTableIdentifier(moduleName: string): string {
  return nameFromFileName(moduleName.endsWith("s") ? moduleName : `${moduleName}s`);
}

export function mergeModuleSchemaRegistry(
  existing: string,
  schemas: string[],
  modules: string[],
): string {
  if (
    existing.length === 0 ||
    existing.startsWith("// Generated by ghostinit sync. Do not edit manually.")
  ) {
    return buildSchemaRegistry(schemas);
  }

  const start = existing.indexOf(DYNAMIC_SCHEMA_START);
  const end = existing.indexOf(DYNAMIC_SCHEMA_END);
  const withoutManagedBlock =
    start >= 0 && end >= start
      ? `${existing.slice(0, start).trimEnd()}\n${existing
          .slice(end + DYNAMIC_SCHEMA_END.length)
          .trimStart()}`.trimEnd() + "\n"
      : existing;
  const dynamicSchemas = modules.filter(
    (moduleName) =>
      schemas.includes(moduleName) &&
      !withoutManagedBlock.includes(`from "./${moduleName}"`) &&
      !withoutManagedBlock.includes(`from './${moduleName}'`),
  );
  if (dynamicSchemas.length === 0) return withoutManagedBlock;
  const lines = dynamicSchemas.map(
    (moduleName) => `export { ${buildTableIdentifier(moduleName)} } from "./${moduleName}";`,
  );
  return `${withoutManagedBlock.trimEnd()}\n\n${DYNAMIC_SCHEMA_START}\n${lines.join("\n")}\n${DYNAMIC_SCHEMA_END}\n`;
}

function nameFromFileName(fileName: string): string {
  // kebab-case file name => camelCase export name.
  // Fix: handle digits after hyphen (e.g. foo-1bar should become foo1bar, not remain invalid).
  // Replace -[a-z0-9] and uppercase letters, keep digits as-is.
  let camel = fileName.replace(/-([a-z0-9])/g, (_: string, char: string) => {
    if (/[0-9]/.test(char)) {
      return char;
    }
    return char.toUpperCase();
  });

  // Handle leading digit: prefix underscore to produce a valid identifier.
  if (/^[0-9]/.test(camel)) {
    camel = `_${camel}`;
  }

  // Validate resulting identifier.
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(camel)) {
    throw new ValidationError(`File name "${fileName}" produces invalid identifier "${camel}"`, {
      fileName,
      identifier: camel,
    });
  }

  // Check reserved keywords after transform (both exact and lowercased).
  if (isReservedName(camel) || isReservedName(camel.toLowerCase())) {
    throw new ValidationError(`File name "${fileName}" produces reserved identifier "${camel}"`, {
      fileName,
      identifier: camel,
    });
  }

  return camel;
}

export function buildModuleRegistry(modules: string[]): string {
  const lines =
    modules.length === 0
      ? ["export {};"]
      : modules.map((m) => `export * as ${nameFromFileName(m)} from "./${m}/index";`);
  const separator = modules.length === 0 ? "\n\n" : "\n";
  return `// Generated by ghostinit sync. Do not edit manually.${separator}${lines.join("\n")}\n`;
}

const BUILT_IN_FLAT_PROCEDURES = new Set(["health", "me"]);

export function buildApiRegistry(
  procedures: string[],
  existingContract = "",
  existingRouter = "",
): { contract: string; router: string } {
  const customProcedures = procedures.filter(
    (procedure) => !BUILT_IN_FLAT_PROCEDURES.has(procedure),
  );

  if (existingContract && existingRouter) {
    const customNames = new Set(customProcedures.map(nameFromFileName));
    const contractImportPattern =
      /^import \{ ([A-Za-z_$][\w$]*)Contract \} from "\.\/procedures\/([A-Za-z0-9_-]+)";\r?$/gm;
    const routerImportPattern =
      /^import \{ ([A-Za-z_$][\w$]*) \} from "\.\/procedures\/([A-Za-z0-9_-]+)";\r?$/gm;
    const removedNames = new Set<string>();

    let contract = existingContract.replace(
      contractImportPattern,
      (line, identifier: string, fileName: string) => {
        if (BUILT_IN_FLAT_PROCEDURES.has(fileName) || customNames.has(identifier)) return line;
        removedNames.add(identifier);
        return "";
      },
    );
    let router = existingRouter.replace(
      routerImportPattern,
      (line, identifier: string, fileName: string) => {
        if (BUILT_IN_FLAT_PROCEDURES.has(fileName) || customNames.has(identifier)) return line;
        removedNames.add(identifier);
        return "";
      },
    );

    for (const identifier of removedNames) {
      contract = contract.replace(
        new RegExp(`^  ${identifier}: ${identifier}Contract,\\r?\\n`, "m"),
        "",
      );
      router = router.replace(new RegExp(`^    ${identifier},\\r?\\n`, "m"), "");
    }

    const missingContractImports: string[] = [];
    const missingRouterImports: string[] = [];
    const missingContractEntries: string[] = [];
    const missingRouterEntries: string[] = [];
    for (const procedure of customProcedures) {
      const identifier = nameFromFileName(procedure);
      const contractImport = `import { ${identifier}Contract } from "./procedures/${procedure}";`;
      const routerImport = `import { ${identifier} } from "./procedures/${procedure}";`;
      if (!contract.includes(contractImport)) {
        missingContractImports.push(contractImport);
        missingContractEntries.push(`  ${identifier}: ${identifier}Contract,`);
      }
      if (!router.includes(routerImport)) {
        missingRouterImports.push(routerImport);
        missingRouterEntries.push(`    ${identifier},`);
      }
    }

    if (missingContractImports.length > 0) {
      contract = contract.replace(
        "export const appContract = {",
        `${missingContractImports.join("\n")}\n\nexport const appContract = {\n${missingContractEntries.join("\n")}`,
      );
    }
    if (missingRouterImports.length > 0) {
      router = router.replace(
        'import type { ApiContext } from "./context";',
        `${missingRouterImports.join("\n")}\nimport type { ApiContext } from "./context";`,
      );
      router = router.replace(
        "  implementer.router({",
        `  implementer.router({\n${missingRouterEntries.join("\n")}`,
      );
    }

    return { contract, router };
  }

  const contractImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)}Contract } from "./procedures/${p}";`,
  );
  const routerImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)} } from "./procedures/${p}";`,
  );

  const contractEntries = procedures.map(
    (p) => `  ${nameFromFileName(p)}: ${nameFromFileName(p)}Contract,`,
  );
  const routerEntries = procedures.map((p) => `    ${nameFromFileName(p)},`);

  const contract = `${contractImports.join("\n")}\n\nexport const appContract = {\n${contractEntries.join("\n")}\n};\n`;

  const router = `import { implement, os } from "@orpc/server";\nimport { appContract } from "./contract";\n${routerImports.join("\n")}\nimport type { ApiContext } from "./context";\n\nconst implementer = implement<typeof appContract, ApiContext>(appContract);\n\nexport const appRouter = os.$context<ApiContext>().prefix("/api").router(\n  implementer.router({\n${routerEntries.join("\n")}\n  }),\n);\n`;

  return { contract, router };
}
