/**
 * Project state persistence.
 *
 * Stores a JSON file at .ghostinit/state.json containing the original config,
 * checksums for generated files, and the module registry.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  GHOSTINIT_DIR,
  STATE_FILE,
  stateSchema,
  type State,
  type ProjectConfig,
} from "./config.js";
import type { ChecksumEntry } from "./checksum.js";
import { IncompatibleSchemaError } from "./errors.js";
import { ghostinitVersion } from "../../packages/versions.js";

export function stateDir(root: string): string {
  return join(root, GHOSTINIT_DIR);
}

export function stateFilePath(root: string): string {
  return join(stateDir(root), STATE_FILE);
}

export async function loadState(root: string): Promise<State | undefined> {
  try {
    const text = await readFile(stateFilePath(root), "utf-8");
    const parsed = JSON.parse(text);
    return stateSchema.parse(parsed);
  } catch {
    return undefined;
  }
}

export async function saveState(
  root: string,
  project: ProjectConfig,
  checksums: ChecksumEntry[],
  modules: string[],
  procedures: string[] = [],
): Promise<void> {
  await mkdir(stateDir(root), { recursive: true });

  const existingState = await loadState(root);

  const checksumMap: State["checksums"] = {};
  // Preserve existing checksums deterministically.
  if (existingState) {
    for (const key of Object.keys(existingState.checksums).sort()) {
      checksumMap[key] = existingState.checksums[key];
    }
  }
  // Merge new checksums over old ones.
  for (const entry of checksums) {
    checksumMap[entry.path] = {
      algorithm: entry.algorithm,
      hash: entry.hash,
      size: entry.size,
      path: entry.path,
    };
  }

  const state: State = {
    version: 1,
    project,
    checksums: checksumMap,
    generatedBy: ghostinitVersion,
    generatedAt: new Date().toISOString(),
    modules: [...modules].sort(),
    procedures: [...procedures].sort(),
  };

  await writeFile(stateFilePath(root), `${JSON.stringify(state, null, 2)}\n`, "utf-8");
}

export function validateStateCompatibility(
  current: State | undefined,
  config: ProjectConfig,
): void {
  if (!current) return;
  if (current.project.name !== config.name) {
    throw new IncompatibleSchemaError("Project name in existing state does not match", {
      expected: config.name,
      actual: current.project.name,
    });
  }
  if (current.generatedBy !== ghostinitVersion) {
    throw new IncompatibleSchemaError(
      `GhostInit state generated by incompatible CLI version ${current.generatedBy}`,
      { currentCli: ghostinitVersion },
    );
  }
}
