// @allow-long 437: Expo app config, capability-aware package manifest, and toolchain files form one unit
/**
 * Expo core template — Expo Router + Metro + Babel
 * Minimal mobile app scaffold with oRPC client, better-auth, TanStack Query/Form, shared @repo/* workspaces.
 * Deduplicated via shared.js helpers (packageJson sorts deps, file guards traversal).
 */

import { codeScripts, file, packageJson, type TemplateFile } from "../shared.js";
import * as v from "../versions.js";
import {
  billingProviders,
  hasAddon,
  isAddonInstallerMap,
  type AddonInstallerMap,
  type BillingProviderName,
} from "../../lib/addons.js";
import { mobileGlobalCssContent } from "./fragments/css.js";

export type ExpoFeatureInput =
  | boolean
  | AddonInstallerMap
  | Record<string, { inUse: boolean }>
  | BillingProviderName[];

export interface ExpoCapabilities {
  hasApi: boolean;
  hasAuth: boolean;
  hasBilling: boolean;
  hasAnalytics: boolean;
  hasEmail: boolean;
  hasEve: boolean;
  hasI18n: boolean;
  hasNotifications: boolean;
  hasMessaging: boolean;
  hasStorage: boolean;
  hasFeatureFlags: boolean;
  hasJobs: boolean;
  hasPdf: boolean;
  isConvex: boolean;
}

function resolveHasFeature(input: ExpoFeatureInput = false, feature: string): boolean {
  if (typeof input === "boolean") return input;
  if (Array.isArray(input)) return false;
  const rec = input as Record<string, { inUse?: boolean }>;
  return Boolean(rec[feature]?.inUse);
}

function resolveHasEve(input: ExpoFeatureInput = false): boolean {
  return resolveHasFeature(input, "eve");
}

function resolveHasI18n(input: ExpoFeatureInput = false): boolean {
  return resolveHasFeature(input, "i18n");
}

export function resolveExpoBillingProviders(
  input: ExpoFeatureInput = false,
): BillingProviderName[] {
  if (Array.isArray(input)) return [...new Set(input)];
  if (!isAddonInstallerMap(input)) return [...billingProviders];
  const selected = billingProviders.filter((provider) => hasAddon(input, provider));
  return selected.length > 0 || !hasAddon(input, "billing") ? selected : [...billingProviders];
}

/**
 * Resolve the mobile capability closure once. Transport can be selected without
 * identity, while billing requires both API and identity. Legacy boolean callers
 * retain the historical full-stack output while normalized addon maps are gated.
 */
export function resolveExpoCapabilities(
  input: ExpoFeatureInput = false,
  allowTanstackEve = false,
): ExpoCapabilities {
  if (Array.isArray(input)) {
    return {
      hasApi: true,
      hasAuth: true,
      hasBilling: resolveExpoBillingProviders(input).length > 0,
      hasAnalytics: true,
      hasEmail: true,
      hasEve: false,
      hasI18n: false,
      hasNotifications: false,
      hasMessaging: false,
      hasStorage: false,
      hasFeatureFlags: false,
      hasJobs: false,
      hasPdf: false,
      isConvex: false,
    };
  }
  if (!isAddonInstallerMap(input)) {
    return {
      hasApi: true,
      hasAuth: true,
      hasBilling: true,
      hasAnalytics: true,
      hasEmail: true,
      hasEve: resolveHasEve(input),
      hasI18n: resolveHasI18n(input),
      hasNotifications: resolveHasFeature(input, "notifications"),
      hasMessaging: resolveHasFeature(input, "messaging"),
      hasStorage: resolveHasFeature(input, "storage"),
      hasFeatureFlags: resolveHasFeature(input, "featureFlags"),
      hasJobs: resolveHasFeature(input, "jobs"),
      hasPdf: false,
      isConvex: false,
    };
  }

  const hasBilling = resolveExpoBillingProviders(input).length > 0;
  const hasApi = hasAddon(input, "api") || hasBilling;
  const hasAuth = hasAddon(input, "auth") || hasBilling;
  const hasEve =
    hasAddon(input, "eve") &&
    hasApi &&
    hasAuth &&
    (allowTanstackEve || !hasAddon(input, "tanstack-start")) &&
    !hasAddon(input, "database:none");

  return {
    hasApi,
    hasAuth,
    hasBilling,
    hasAnalytics: hasAddon(input, "analytics"),
    hasEmail: hasAddon(input, "email"),
    hasEve,
    hasI18n: hasAddon(input, "i18n"),
    hasNotifications: hasAddon(input, "notifications"),
    hasMessaging: hasAddon(input, "messaging"),
    hasStorage: hasAddon(input, "storage"),
    hasFeatureFlags: hasAddon(input, "featureFlags") || hasAddon(input, "posthog"),
    hasJobs: hasApi && hasAuth && hasAddon(input, "jobsApi"),
    hasPdf: hasAddon(input, "pdf"),
    isConvex: hasAddon(input, "convex"),
  };
}

export function uniwindTypesDtsContent(): string {
  // The triple-slash reference is what pulls in uniwind/types, which augments
  // react-native's component props with `className`. Without it the stub silently
  // shadowed uniwind's own generated d.ts and every className={...} on a native
  // component failed with TS2769.
  return `// Generated by Uniwind - do not edit
// This file is auto-generated when running expo start
/// <reference types="uniwind/types" />
declare module "uniwind" {}
`;
}

export function uniwindTypesDts(): TemplateFile {
  return file("apps/mobile/uniwind-types.d.ts", uniwindTypesDtsContent());
}

export function uniwindTypesDtsSingle(): TemplateFile {
  return file("uniwind-types.d.ts", uniwindTypesDtsContent());
}

export function expoCoreFiles(
  runtime: "node" | "bun" = "bun",
  hasEveInput: ExpoFeatureInput = false,
  hasI18nInput: ExpoFeatureInput = false,
): TemplateFile[] {
  const hasEve = resolveHasEve(hasEveInput);
  const hasI18n = resolveHasI18n(hasI18nInput ?? hasEveInput);
  const effectiveHasI18n = typeof hasEveInput !== "boolean" ? resolveHasI18n(hasEveInput) : hasI18n;
  const capabilities = {
    ...resolveExpoCapabilities(hasEveInput, true),
    hasI18n: effectiveHasI18n,
  };
  return [
    webPackageMobile(runtime, hasEve, effectiveHasI18n, capabilities),
    appJson(capabilities),
    babelConfig(),
    metroConfig(),
    file("apps/mobile/global.css", mobileGlobalCssContent()),
    file("apps/mobile/uniwind-types.d.ts", uniwindTypesDtsContent()),
    expoEnvDts(),
    tsconfigMobile(),
    // The `test` script runs `bun test tests`; without this file that directory
    // did not exist and the task exited 1 on every fresh project.
    file(
      "apps/mobile/tests/smoke.test.ts",
      `import { describe, it, expect } from "bun:test";
import appJson from "../app.json";

describe("mobile app config", () => {
  it("declares a scheme so Better Auth deep links resolve", () => {
    expect(typeof appJson.expo.scheme).toBe("string");
    expect(appJson.expo.scheme.length).toBeGreaterThan(0);
  });

  it("registers expo-router as a plugin", () => {
    expect(appJson.expo.plugins).toContain("expo-router");
  });
});
`,
    ),
  ];
}

/* ------------------------------------------------------------------ */
/* package.json — apps/mobile                                         */
/* ------------------------------------------------------------------ */

export function webPackageMobile(
  runtime: "node" | "bun" = "bun",
  _hasEve = false,
  _hasI18n = false,
  capabilities: ExpoCapabilities = {
    hasApi: true,
    hasAuth: true,
    hasBilling: true,
    hasAnalytics: true,
    hasEmail: true,
    hasEve: false,
    hasI18n: false,
    hasNotifications: false,
    hasMessaging: false,
    hasStorage: false,
    hasFeatureFlags: false,
    hasJobs: false,
    hasPdf: false,
    isConvex: false,
  },
): TemplateFile {
  return file(
    "apps/mobile/package.json",
    packageJson({
      name: "mobile",
      main: "expo-router/entry",
      version: v.ghostinitVersion,
      packageManager: `bun@${v.runtime.bun}`,
      scripts: {
        dev: "expo start --port 19000",
        android: "expo start --android",
        ios: "expo start --ios",
        web: "expo start --web",
        build: "expo export",
        ...codeScripts({
          // `bun test tests` targeted a directory that was never generated, so the
          // task always exited 1. A tests/ dir with a real smoke test is emitted below.
          // Package management and tests stay on Bun for both execution runtimes.
          test: "bun test tests",
        }),
      },
      dependencies: {
        "@expo/metro-runtime": `~${v.expo["@expo/metro-runtime"]}`,
        ...(capabilities.hasApi
          ? {
              "@orpc/client": `^${v.orpc["@orpc/client"]}`,
              "@orpc/react-query": `^${v.orpc["@orpc/react-query"]}`,
              "@orpc/server": `^${v.orpc["@orpc/server"]}`,
              "@repo/api": "workspace:*",
            }
          : {}),
        "@repo/kernel": "workspace:*",
        "@repo/config": "workspace:*",
        "@repo/ui": "workspace:*",
        "@tanstack/react-query": `^${v.tanstack["@tanstack/react-query"]}`,
        ...(capabilities.hasAuth
          ? {
              "@better-auth/expo": `^${v.auth["@better-auth/expo"]}`,
              "@tanstack/react-form": `^${v.tanstack["@tanstack/react-form"]}`,
              "better-auth": `^${v.auth["better-auth"]}`,
              "expo-network": `~${v.expo["expo-network"]}`,
            }
          : {}),
        ...(capabilities.isConvex
          ? {
              ...(capabilities.hasAuth
                ? { "@convex-dev/better-auth": `^${v.convex["@convex-dev/better-auth"]}` }
                : {}),
              convex: `^${v.convex.convex}`,
            }
          : {}),
        expo: `~${v.expo.expo}`,
        "expo-constants": `~${v.expo["expo-constants"]}`,
        ...(capabilities.hasNotifications ? { "expo-device": `~${v.expo["expo-device"]}` } : {}),
        ...(capabilities.hasPdf || capabilities.hasMessaging
          ? {
              "expo-file-system": `~${v.expo["expo-file-system"]}`,
              "expo-sharing": `~${v.expo["expo-sharing"]}`,
            }
          : {}),
        "expo-linking": `~${v.expo["expo-linking"]}`,
        "expo-router": `~${v.expo["expo-router"]}`,
        "expo-secure-store": `~${v.expo["expo-secure-store"]}`,
        "expo-status-bar": `~${v.expo["expo-status-bar"]}`,
        "expo-web-browser": `~${v.expo["expo-web-browser"]}`,
        "expo-clipboard": `~${v.expo["expo-clipboard"]}`,
        ...(capabilities.hasNotifications
          ? { "expo-notifications": `~${v.expo["expo-notifications"]}` }
          : {}),
        ...(capabilities.hasI18n ? { "expo-localization": `~${v.expo["expo-localization"]}` } : {}),
        "@react-native-community/netinfo": v.expo["@react-native-community/netinfo"],
        "@react-native-async-storage/async-storage":
          v.expo["@react-native-async-storage/async-storage"],
        "@tanstack/query-async-storage-persister": `^${v.tanstack["@tanstack/query-async-storage-persister"]}`,
        "@tanstack/query-persist-client-core": `^${v.tanstack["@tanstack/query-persist-client-core"]}`,
        ...(capabilities.hasAnalytics
          ? { "posthog-react-native": `^${v.analytics["posthog-react-native"]}` }
          : {}),
        react: v.expoReact.react,
        // app.json declares platforms [ios, android, web]; react-native-web lists
        // react-dom as a non-optional peer, and `expo export` (the build script)
        // refuses to start without it.
        "react-dom": v.expoReact["react-dom"],
        "react-native": v.expo["react-native"],
        "react-native-safe-area-context": `~${v.expo["react-native-safe-area-context"]}`,
        "react-native-screens": `~${v.expo["react-native-screens"]}`,
        "react-native-gesture-handler": `~${v.expo["react-native-gesture-handler"]}`,
        "react-native-web": `~${v.expo["react-native-web"]}`,
        "react-native-reanimated": v.reanimated["react-native-reanimated"],
        "react-native-worklets": v.worklets["react-native-worklets"],
        clsx: `^${v.ui.clsx}`,
        "tailwind-merge": `^${v.ui["tailwind-merge"]}`,
        // global.css line 1 is `@import "tailwindcss"` and uniwind declares
        // tailwindcss >=4 as a non-optional peer. Bun does not backfill it in the
        // hoisted workspace, so bundling stopped at "Can't resolve 'tailwindcss'".
        tailwindcss: `^${v.styling.tailwindcss}`,
        "tailwind-variants": `^${v.uniwind["tailwind-variants"]}`,
        "tw-animate-css": `^${v.uniwind["tw-animate-css"]}`,
        uniwind: `^${v.uniwind.uniwind}`,
        zod: `^${v.validation.zod}`,
      },
      devDependencies: {
        "@repo/typescript-config": "workspace:*",
        "@types/node": `^${v.runtime["@types/node"]}`,
        "@types/react": `~${v.expoReact["@types/react"]}`,
        "babel-preset-expo": `~${v.expo["babel-preset-expo"]}`,
        oxfmt: `^${v.tooling.oxfmt}`,
        oxlint: `^${v.tooling.oxlint}`,
        typescript: `~${v.typescript.typescript}`,
      },
    }),
  );
}

/* alias for clarity — consumers may import mobilePackage */
export const mobilePackage = webPackageMobile;
export const expoPackage = webPackageMobile;
export const expoPackageMobile = webPackageMobile;

/* ------------------------------------------------------------------ */
/* app.json                                                          */
/* ------------------------------------------------------------------ */

function sanitizeScheme(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "") || "app";
}

export function expoAppJsonContent(
  projectName = "__PROJECT_NAME__",
  capabilities: Pick<ExpoCapabilities, "hasNotifications"> = { hasNotifications: true },
): string {
  const isPlaceholder = projectName === "__PROJECT_NAME__";
  const scheme = isPlaceholder ? "myapp" : sanitizeScheme(projectName);
  return (
    JSON.stringify(
      {
        expo: {
          name: projectName,
          slug: projectName,
          scheme,
          version: "1.0.0",
          orientation: "portrait",
          userInterfaceStyle: "automatic",
          // No icon/splash/adaptiveIcon/favicon keys: a template generator cannot
          // emit binary PNGs, and pointing at ./assets/*.png files that are never
          // written made `expo prebuild` and EAS builds fail with ENOENT. Expo
          // falls back to its own defaults when these are omitted — add your own
          // artwork and re-add the keys when you have it.
          assetBundlePatterns: ["**/*"],
          ios: {
            supportsTablet: true,
            associatedDomains: [`applinks:${scheme}.example.com`],
          },
          android: {
            adaptiveIcon: {
              backgroundColor: "#ffffff",
            },
            intentFilters: [
              {
                action: "VIEW",
                autoVerify: true,
                data: [{ scheme: "https", host: `${scheme}.example.com`, pathPrefix: "/" }],
                category: ["BROWSABLE", "DEFAULT"],
              },
            ],
          },
          plugins: [
            "expo-router",
            "expo-secure-store",
            ...(capabilities.hasNotifications ? ["expo-notifications"] : []),
          ],
          experiments: {
            typedRoutes: true,
          },
          platforms: ["ios", "android", "web"],
        },
      },
      null,
      2,
    ) + "\n"
  );
}

export const appJsonContent = expoAppJsonContent;

export function appJson(capabilities?: Pick<ExpoCapabilities, "hasNotifications">): TemplateFile {
  return file("apps/mobile/app.json", expoAppJsonContent("__PROJECT_NAME__", capabilities));
}

/** Single-mode reuse: file path differs but content identical — caller can wrap with file(). */
export function expoAppJsonContentSingle(
  capabilities?: Pick<ExpoCapabilities, "hasNotifications">,
): string {
  return expoAppJsonContent("__PROJECT_NAME__", capabilities);
}

export function expoAppJsonSingle(): TemplateFile {
  return file("app.json", expoAppJsonContent());
}

/* ------------------------------------------------------------------ */
/* babel.config.js                                                   */
/* ------------------------------------------------------------------ */

export function babelConfigContent(): string {
  // uniwind exposes ./components, ./metro, ./vite and ./types — there is NO
  // ./babel subpath in its exports map. Listing it made Metro fail on the very
  // first module with ERR_PACKAGE_PATH_NOT_EXPORTED, so `expo start`,
  // `expo export` and `turbo run build` all died before bundling anything.
  // uniwind hooks in through metro.config.js (withUniwind), not through babel.
  return `module.exports = function(api){api.cache(true); return {presets:['babel-preset-expo']};};
`;
}

export function babelConfig(): TemplateFile {
  return file("apps/mobile/babel.config.js", babelConfigContent());
}

export function babelConfigSingle(): TemplateFile {
  return file("babel.config.js", babelConfigContent());
}

/* ------------------------------------------------------------------ */
/* metro.config.js                                                   */
/* ------------------------------------------------------------------ */

export function metroConfigContent(): string {
  return `const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');
const config = getDefaultConfig(__dirname);
module.exports = withUniwindConfig(config, {
  cssEntryFile: './global.css',
  dtsFile: './uniwind-types.d.ts',
});
`;
}

export function metroConfig(): TemplateFile {
  return file("apps/mobile/metro.config.js", metroConfigContent());
}

export function metroConfigSingle(): TemplateFile {
  return file("metro.config.js", metroConfigContent());
}

/* ------------------------------------------------------------------ */
/* expo-env.d.ts                                                     */
/* ------------------------------------------------------------------ */

export function expoEnvDtsContent(): string {
  return '/// <reference types="expo/types" />\n';
}

export function expoEnvDts(): TemplateFile {
  return file("apps/mobile/expo-env.d.ts", expoEnvDtsContent());
}

export function expoEnvDtsSingle(): TemplateFile {
  return file("expo-env.d.ts", expoEnvDtsContent());
}

/* ------------------------------------------------------------------ */
/* tsconfig.json — extends @repo/typescript-config/expo.json         */
/* ------------------------------------------------------------------ */

export function mobileTsconfigContent(): string {
  return (
    JSON.stringify(
      {
        extends: "@repo/typescript-config/expo.json",
        compilerOptions: {
          // Keep workspace packages on one resolver path. Mixing direct paths
          // with Bun workspace links duplicates files under D:/Temp vs D:/temp
          // during direct Windows app typechecks.
          paths: {
            "@/*": ["./src/*"],
          },
        },
        include: [
          "**/*.ts",
          "**/*.tsx",
          ".expo/types/**/*.ts",
          "expo-env.d.ts",
          "uniwind-types.d.ts",
          "global.css",
        ],
        exclude: ["node_modules"],
      },
      null,
      2,
    ) + "\n"
  );
}

export const expoTsconfigContent = mobileTsconfigContent;
export const tsconfigContent = mobileTsconfigContent;

export function tsconfigMobile(): TemplateFile {
  return file("apps/mobile/tsconfig.json", mobileTsconfigContent());
}

export function tsconfigMobileSingle(): TemplateFile {
  return file("tsconfig.json", mobileTsconfigContent());
}
