// @allow-long 334: Expo app config, babel/metro and package manifest emitted as one unit
/**
 * Expo core template — Expo Router + Metro + Babel
 * Minimal mobile app scaffold with oRPC client, better-auth, TanStack Query/Form, shared @repo/* workspaces.
 * Deduplicated via shared.js helpers (packageJson sorts deps, file guards traversal).
 */

import { codeScripts, file, packageJson, type TemplateFile } from "../shared.js";
import * as v from "../versions.js";
import type { AddonInstallerMap, BillingProviderName } from "../../lib/addons.js";
import { mobileGlobalCssContent } from "./fragments/css.js";

type FeatureInput =
  | boolean
  | AddonInstallerMap
  | Record<string, { inUse: boolean }>
  | BillingProviderName[];

function resolveHasFeature(input: FeatureInput = false, feature: string): boolean {
  if (typeof input === "boolean") return input;
  if (Array.isArray(input)) return false;
  const rec = input as Record<string, { inUse?: boolean }>;
  return Boolean(rec[feature]?.inUse);
}

function resolveHasEve(input: FeatureInput = false): boolean {
  return resolveHasFeature(input, "eve");
}

function resolveHasI18n(input: FeatureInput = false): boolean {
  return resolveHasFeature(input, "i18n");
}

export function uniwindTypesDtsContent(): string {
  // The triple-slash reference is what pulls in uniwind/types, which augments
  // react-native's component props with `className`. Without it the stub silently
  // shadowed uniwind's own generated d.ts and every className={...} on a native
  // component failed with TS2769.
  return `// Generated by Uniwind - do not edit
// This file is auto-generated when running expo start
/// <reference types="uniwind/types" />
declare module "uniwind" {}
`;
}

export function uniwindTypesDts(): TemplateFile {
  return file("apps/mobile/uniwind-types.d.ts", uniwindTypesDtsContent());
}

export function uniwindTypesDtsSingle(): TemplateFile {
  return file("uniwind-types.d.ts", uniwindTypesDtsContent());
}

export function expoCoreFiles(
  runtime: "node" | "bun" = "bun",
  hasEveInput: FeatureInput = false,
  hasI18nInput: FeatureInput = false,
): TemplateFile[] {
  const hasEve = resolveHasEve(hasEveInput);
  const hasI18n = resolveHasI18n(hasI18nInput ?? hasEveInput);
  const effectiveHasI18n = typeof hasEveInput !== "boolean" ? resolveHasI18n(hasEveInput) : hasI18n;
  return [
    webPackageMobile(runtime, hasEve, effectiveHasI18n),
    appJson(),
    babelConfig(),
    metroConfig(),
    file("apps/mobile/global.css", mobileGlobalCssContent()),
    file("apps/mobile/uniwind-types.d.ts", uniwindTypesDtsContent()),
    expoEnvDts(),
    tsconfigMobile(),
    // The `test` script runs `bun test tests`; without this file that directory
    // did not exist and the task exited 1 on every fresh project.
    file(
      "apps/mobile/tests/smoke.test.ts",
      `import { describe, it, expect } from "bun:test";
import appJson from "../app.json";

describe("mobile app config", () => {
  it("declares a scheme so Better Auth deep links resolve", () => {
    expect(typeof appJson.expo.scheme).toBe("string");
    expect(appJson.expo.scheme.length).toBeGreaterThan(0);
  });

  it("registers expo-router as a plugin", () => {
    expect(appJson.expo.plugins).toContain("expo-router");
  });
});
`,
    ),
  ];
}

/* ------------------------------------------------------------------ */
/* package.json — apps/mobile                                         */
/* ------------------------------------------------------------------ */

export function webPackageMobile(
  runtime: "node" | "bun" = "bun",
  _hasEve = false,
  _hasI18n = false,
): TemplateFile {
  return file(
    "apps/mobile/package.json",
    packageJson({
      name: "mobile",
      main: "expo-router/entry",
      version: v.ghostinitVersion,
      packageManager: runtime === "bun" ? `bun@${v.runtime.bun}` : `npm@10.8.0`,
      scripts: {
        dev: "expo start --port 19000",
        android: "expo start --android",
        ios: "expo start --ios",
        web: "expo start --web",
        build: "expo export",
        ...codeScripts({
          // `bun test tests` targeted a directory that was never generated, so the
          // task always exited 1. A tests/ dir with a real smoke test is emitted below.
          test: runtime === "bun" ? "bun test tests" : "npm run test:unit",
        }),
      },
      dependencies: {
        "@expo/metro-runtime": `^${v.expo["@expo/metro-runtime"]}`,
        "@orpc/client": `^${v.orpc["@orpc/client"]}`,
        "@orpc/react-query": `^${v.orpc["@orpc/react-query"]}`,
        "@repo/analytics": "workspace:*",
        "@repo/api": "workspace:*",
        "@repo/auth": "workspace:*",
        "@repo/billing": "workspace:*",
        "@repo/config": "workspace:*",
        "@repo/contracts": "workspace:*",
        "@repo/database": "workspace:*",
        "@repo/email": "workspace:*",
        "@repo/kernel": "workspace:*",
        "@repo/modules": "workspace:*",
        "@repo/observability": "workspace:*",
        "@repo/services": "workspace:*",
        "@repo/ui": "workspace:*",
        "@repo/workflows": "workspace:*",
        "@tanstack/react-form": `^${v.tanstack["@tanstack/react-form"]}`,
        "@tanstack/react-query": `^${v.tanstack["@tanstack/react-query"]}`,
        "better-auth": `^${v.auth["better-auth"]}`,
        // src/lib/auth-client.ts imports @better-auth/expo; expo-network is its
        // peer. expo-router's require.context pulls every route, so a missing
        // import here fails the entire bundle, not just one screen.
        "@better-auth/expo": `^${v.auth["@better-auth/expo"]}`,
        "expo-network": `^${v.expo["expo-network"]}`,
        expo: `^${v.expo.expo}`,
        "expo-constants": `^${v.expo["expo-constants"]}`,
        "expo-linking": `^${v.expo["expo-linking"]}`,
        "expo-router": `^${v.expo["expo-router"]}`,
        "expo-secure-store": `^${v.expo["expo-secure-store"]}`,
        "expo-status-bar": `^${v.expo["expo-status-bar"]}`,
        "expo-web-browser": `^${v.expo["expo-web-browser"]}`,
        "expo-clipboard": `^${v.expo["expo-clipboard"]}`,
        react: `^${v.nextStack.react}`,
        // app.json declares platforms [ios, android, web]; react-native-web lists
        // react-dom as a non-optional peer, and `expo export` (the build script)
        // refuses to start without it.
        "react-dom": `^${v.nextStack["react-dom"]}`,
        "react-native": `^${(v.expo["react-native"] as string) ?? "0.81.4"}`,
        "react-native-safe-area-context": `^${v.expo["react-native-safe-area-context"]}`,
        "react-native-web": `^${v.expo["react-native-web"]}`,
        "react-native-reanimated": `^${v.reanimated["react-native-reanimated"]}`,
        "react-native-worklets": `^${v.worklets["react-native-worklets"]}`,
        clsx: `^${v.ui.clsx}`,
        "tailwind-merge": `^${v.ui["tailwind-merge"]}`,
        // global.css line 1 is `@import "tailwindcss"` and uniwind declares
        // tailwindcss >=4 as a non-optional peer. Bun does not backfill it in the
        // hoisted workspace, so bundling stopped at "Can't resolve 'tailwindcss'".
        tailwindcss: `^${v.styling.tailwindcss}`,
        "tailwind-variants": `^${v.uniwind["tailwind-variants"]}`,
        "tw-animate-css": `^${v.uniwind["tw-animate-css"]}`,
        uniwind: `^${v.uniwind.uniwind}`,
        zod: `^${v.validation.zod}`,
      },
      devDependencies: {
        "@repo/typescript-config": "workspace:*",
        "@types/node": `^${v.runtime["@types/node"]}`,
        "@types/react": `^${v.nextStack["@types/react"]}`,
        "babel-preset-expo": `^${v.expo["babel-preset-expo"]}`,
        oxfmt: `^${v.tooling.oxfmt}`,
        oxlint: `^${v.tooling.oxlint}`,
        typescript: `^${v.typescript.typescript}`,
      },
    }),
  );
}

/* alias for clarity — consumers may import mobilePackage */
export const mobilePackage = webPackageMobile;
export const expoPackage = webPackageMobile;
export const expoPackageMobile = webPackageMobile;

/* ------------------------------------------------------------------ */
/* app.json                                                          */
/* ------------------------------------------------------------------ */

function sanitizeScheme(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "") || "app";
}

export function expoAppJsonContent(projectName = "__PROJECT_NAME__"): string {
  const isPlaceholder = projectName === "__PROJECT_NAME__";
  const scheme = isPlaceholder ? "myapp" : sanitizeScheme(projectName);
  return (
    JSON.stringify(
      {
        expo: {
          name: projectName,
          slug: projectName,
          scheme,
          version: "1.0.0",
          orientation: "portrait",
          userInterfaceStyle: "automatic",
          // No icon/splash/adaptiveIcon/favicon keys: a template generator cannot
          // emit binary PNGs, and pointing at ./assets/*.png files that are never
          // written made `expo prebuild` and EAS builds fail with ENOENT. Expo
          // falls back to its own defaults when these are omitted — add your own
          // artwork and re-add the keys when you have it.
          assetBundlePatterns: ["**/*"],
          ios: {
            supportsTablet: true,
          },
          android: {
            adaptiveIcon: {
              backgroundColor: "#ffffff",
            },
          },
          plugins: ["expo-router", "expo-secure-store"],
          experiments: {
            typedRoutes: true,
          },
          platforms: ["ios", "android", "web"],
        },
      },
      null,
      2,
    ) + "\n"
  );
}

export const appJsonContent = expoAppJsonContent;

export function appJson(): TemplateFile {
  return file("apps/mobile/app.json", expoAppJsonContent());
}

/** Single-mode reuse: file path differs but content identical — caller can wrap with file(). */
export function expoAppJsonContentSingle(): string {
  return expoAppJsonContent();
}

export function expoAppJsonSingle(): TemplateFile {
  return file("app.json", expoAppJsonContent());
}

/* ------------------------------------------------------------------ */
/* babel.config.js                                                   */
/* ------------------------------------------------------------------ */

export function babelConfigContent(): string {
  // uniwind exposes ./components, ./metro, ./vite and ./types — there is NO
  // ./babel subpath in its exports map. Listing it made Metro fail on the very
  // first module with ERR_PACKAGE_PATH_NOT_EXPORTED, so `expo start`,
  // `expo export` and `turbo run build` all died before bundling anything.
  // uniwind hooks in through metro.config.js (withUniwind), not through babel.
  return `module.exports = function(api){api.cache(true); return {presets:['babel-preset-expo']};};
`;
}

export function babelConfig(): TemplateFile {
  return file("apps/mobile/babel.config.js", babelConfigContent());
}

export function babelConfigSingle(): TemplateFile {
  return file("babel.config.js", babelConfigContent());
}

/* ------------------------------------------------------------------ */
/* metro.config.js                                                   */
/* ------------------------------------------------------------------ */

export function metroConfigContent(): string {
  return `const { getDefaultConfig } = require('expo/metro-config');
const { withUniwindConfig } = require('uniwind/metro');
const config = getDefaultConfig(__dirname);
module.exports = withUniwindConfig(config, {
  cssEntryFile: './global.css',
  dtsFile: './uniwind-types.d.ts',
});
`;
}

export function metroConfig(): TemplateFile {
  return file("apps/mobile/metro.config.js", metroConfigContent());
}

export function metroConfigSingle(): TemplateFile {
  return file("metro.config.js", metroConfigContent());
}

/* ------------------------------------------------------------------ */
/* expo-env.d.ts                                                     */
/* ------------------------------------------------------------------ */

export function expoEnvDtsContent(): string {
  return '/// <reference types="expo/types" />\n';
}

export function expoEnvDts(): TemplateFile {
  return file("apps/mobile/expo-env.d.ts", expoEnvDtsContent());
}

export function expoEnvDtsSingle(): TemplateFile {
  return file("expo-env.d.ts", expoEnvDtsContent());
}

/* ------------------------------------------------------------------ */
/* src/lib/utils.ts — cn helper                                      */
/* ------------------------------------------------------------------ */

export function expoLibUtilsContent(): string {
  return `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
`;
}

/* ------------------------------------------------------------------ */
/* tsconfig.json — extends @repo/typescript-config/expo.json         */
/* ------------------------------------------------------------------ */

export function mobileTsconfigContent(): string {
  return (
    JSON.stringify(
      {
        extends: "@repo/typescript-config/expo.json",
        compilerOptions: {
          paths: {
            "@/*": ["./src/*"],
            "@repo/*": ["../../packages/*/src"],
          },
        },
        include: [
          "**/*.ts",
          "**/*.tsx",
          ".expo/types/**/*.ts",
          "expo-env.d.ts",
          "uniwind-types.d.ts",
          "global.css",
        ],
        exclude: ["node_modules"],
      },
      null,
      2,
    ) + "\n"
  );
}

export const expoTsconfigContent = mobileTsconfigContent;
export const tsconfigContent = mobileTsconfigContent;

export function tsconfigMobile(): TemplateFile {
  return file("apps/mobile/tsconfig.json", mobileTsconfigContent());
}

export function tsconfigMobileSingle(): TemplateFile {
  return file("tsconfig.json", mobileTsconfigContent());
}
