import {
  convexApiFor,
  convexBillingServerHelpers,
  postgresWebhookClaimHelpers,
  webhookBodyLimitHelpers,
  webhookBodyReadLines,
  webhookEventOrderHelpers,
  type DbImports,
  type ConvexImports,
} from "./shared.js";

type ConvexImp = ConvexImports;

function chargilyIdentityHelpers(): string[] {
  return [
    "function nonEmptyString(value: unknown): string | null {",
    '  return typeof value === "string" && value.trim().length > 0 ? value : null;',
    "}",
    "",
    "function chargilyDeliveryId(payload: Record<string, unknown>, rawBody: Buffer): string {",
    "  // Chargily documents top-level id as the event id; data.id is the checkout id.",
    "  return nonEmptyString(payload.id) ?? nonEmptyString(payload.event_id) ??",
    '    `body_sha256:${createHash("sha256").update(rawBody).digest("hex")}`;',
    "}",
    "",
    'const CHARGILY_COMPLETED_EVENTS = new Set(["checkout.paid", "checkout.completed"]);',
    'const CHARGILY_FAILED_EVENTS = new Set(["checkout.failed", "checkout.canceled", "checkout.cancelled", "checkout.expired"]);',
    'const CHARGILY_COMPLETED_STATUSES = new Set(["paid", "completed"]);',
    'const CHARGILY_FAILED_STATUSES = new Set(["failed", "canceled", "cancelled", "expired"]);',
    "",
    "function isChargilyCompletedEvent(eventType: string, status: string | null): boolean {",
    "  return CHARGILY_COMPLETED_EVENTS.has(eventType) &&",
    "    (status === null || CHARGILY_COMPLETED_STATUSES.has(status));",
    "}",
    "",
    "function isChargilyFailedEvent(eventType: string, status: string | null): boolean {",
    "  return CHARGILY_FAILED_EVENTS.has(eventType) &&",
    "    (status === null || CHARGILY_FAILED_STATUSES.has(status));",
    "}",
  ];
}

function postgresClaimHelpers(): string[] {
  return postgresWebhookClaimHelpers("chargily");
}
function baseChargilyNext(imp: DbImports): string {
  return [
    'import { createHash, randomUUID } from "node:crypto";',
    'import { verifySignature } from "@chargily/chargily-pay";',
    'import { and, eq, isNull, sql } from "drizzle-orm";',
    `import { db } from "${imp.db}";`,
    `import { webhook_events, checkouts, subscriptions } from "${imp.billingSchema}";`,
    `import { logger } from "${imp.observability}";`,
    "",
    ...webhookBodyLimitHelpers(),
    "",
    ...webhookEventOrderHelpers(),
    "",
    "type CheckoutStatus = typeof checkouts.$inferSelect.status;",
    "",
    "function mapChargilyCheckoutStatus(status: string): CheckoutStatus {",
    '  if (status === "paid" || status === "completed") return "completed";',
    '  if (status === "failed" || status === "canceled" || status === "cancelled") return "failed";',
    '  if (status === "expired") return "expired";',
    '  return "pending";',
    "}",
    "",
    "function mapChargilyFailureEvent(eventType: string): CheckoutStatus {",
    '  return eventType === "checkout.expired" ? "expired" : "failed";',
    "}",
    "",
    ...chargilyIdentityHelpers(),
    "",
    ...postgresClaimHelpers(),
    "",
    "export async function POST(req: Request): Promise<Response> {",
    ...webhookBodyReadLines("req"),
    '  const sig = req.headers.get("signature");',
    '  if (!sig) return new Response("Missing signature header", { status: 400 });',
    '  const secret = process.env.CHARGILY_SECRET_KEY ?? process.env.CHARGILY_WEBHOOK_SECRET ?? "";',
    '  if (!secret || secret.startsWith("REPLACE_WITH")) return new Response("CHARGILY_SECRET_KEY missing - server-only", { status: 400 });',
    "  try {",
    '    if (!verifySignature(buf, sig, secret)) return new Response("Invalid signature", { status: 403 });',
    "  } catch (error) {",
    "    logger.error(`[chargily webhook] signature verification failed: ${error instanceof Error ? error.message : String(error)}`);",
    '    return new Response("Invalid signature", { status: 403 });',
    "  }",
    "  let payload: Record<string, unknown>;",
    '  try { payload = JSON.parse(buf.toString("utf-8")) as Record<string, unknown>; }',
    '  catch { return new Response("Invalid JSON payload", { status: 400 }); }',
    '  if (!payload || typeof payload !== "object" || Array.isArray(payload)) return new Response("Invalid webhook payload", { status: 400 });',
    '  const data = payload.data && typeof payload.data === "object" && !Array.isArray(payload.data) ? payload.data as Record<string, unknown> : payload;',
    "  const eventId = chargilyDeliveryId(payload, buf);",
    '  const eventType = nonEmptyString(payload.type) ?? nonEmptyString(payload.event) ?? `checkout.${nonEmptyString(data.status) ?? "updated"}`;',
    "  const eventOccurredAtMs = providerEventMillis(payload.created_at, payload.createdAt, data.created_at, data.updated_at, data.createdAt, data.updatedAt);",
    "  let claim: ClaimResult;",
    "  try { claim = await claimWebhookDelivery(eventId, eventType, payload); }",
    "  catch (error) {",
    "    logger.error(`[chargily webhook] delivery claim failed: ${error instanceof Error ? error.message : String(error)}`);",
    '    return new Response("Idempotency store unavailable", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    '  if (claim.status === "completed") return new Response("already processed", { status: 200 });',
    '  if (claim.status === "in_flight") return new Response("delivery in progress", { status: 503, headers: { "Retry-After": "5" } });',
    "  try {",
    "    const status = nonEmptyString(data.status) ?? nonEmptyString(payload.status);",
    "    const checkoutId = nonEmptyString(data.id);",
    "    const completed = isChargilyCompletedEvent(eventType, status);",
    "    const failed = isChargilyFailedEvent(eventType, status);",
    "    if ((completed || failed) && !checkoutId) throw new Error(`Chargily ${eventType} event did not include data.id`);",
    "    if (checkoutId && (completed || failed || status)) {",
    "      const metadata = (data.metadata ?? payload.metadata) as Record<string, unknown> | undefined;",
    '      const existingCheckout = await db.query.checkouts.findFirst({ where: and(eq(checkouts.provider, "chargily"), eq(checkouts.providerCheckoutId, checkoutId)) });',
    "      const userId = nonEmptyString(metadata?.userId) ?? nonEmptyString(metadata?.chargily_user_id) ?? existingCheckout?.userId ?? null;",
    "      if (!userId) throw new Error(`Chargily ${eventType} event did not include actor ownership`);",
    "      const requestKey = nonEmptyString(metadata?.requestKey);",
    "      const providerEventAt = new Date(requireProviderEventMillis(`Chargily ${eventType}`, eventOccurredAtMs));",
    '      const checkoutStatus = completed ? "completed" as const : failed ? mapChargilyFailureEvent(eventType) : mapChargilyCheckoutStatus(status ?? "pending");',
    '      if (requestKey) await db.update(checkouts).set({ providerCheckoutId: checkoutId, status: checkoutStatus, metadata, providerEventAt, creationState: "ready", creationStartedAt: null, creationLeaseToken: null, updatedAt: new Date() }).where(and(eq(checkouts.userId, userId), eq(checkouts.provider, "chargily"), eq(checkouts.requestKey, requestKey), eq(checkouts.creationState, "creating")));',
    '      const [stored] = await db.insert(checkouts).values({ userId, provider: "chargily", providerCheckoutId: checkoutId, requestKey, status: checkoutStatus, metadata, providerEventAt }).onConflictDoUpdate({ target: [checkouts.provider, checkouts.providerCheckoutId], set: { requestKey, status: checkoutStatus, metadata, providerEventAt, creationState: "ready", creationStartedAt: null, creationLeaseToken: null, updatedAt: new Date() }, setWhere: and(eq(checkouts.userId, userId), sql`${checkouts.providerEventAt} IS NULL OR ${checkouts.providerEventAt} <= ${providerEventAt}`) }).returning({ id: checkouts.id });',
    "      if (!stored && existingCheckout?.userId !== userId) throw new Error(`Chargily checkout ${checkoutId} belongs to another actor`);",
    "      if (completed || failed) {",
    '        const subscriptionStatus = completed ? "active" as const : eventType === "checkout.expired" ? "expired" as const : "canceled" as const;',
    "        await db.insert(subscriptions).values({ userId, provider: \"chargily\", providerSubscriptionId: checkoutId, status: subscriptionStatus, metadata, providerEventAt }).onConflictDoUpdate({ target: [subscriptions.provider, subscriptions.providerSubscriptionId], set: { status: subscriptionStatus, metadata, providerEventAt, updatedAt: new Date() }, setWhere: and(eq(subscriptions.userId, userId), sql`${subscriptions.providerEventAt} IS NULL OR ${subscriptions.providerEventAt} < ${providerEventAt} OR (${subscriptions.providerEventAt} = ${providerEventAt} AND (${subscriptionStatus} IN ('canceled', 'expired') OR ${subscriptions.status} NOT IN ('canceled', 'expired')))` ) });",
    "      }",
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[chargily webhook] handler failed: ${message}`);",
    "    try { await failWebhookDelivery(eventId, claim.leaseToken, message); } catch (releaseError) { logger.error(`[chargily webhook] claim release failed: ${releaseError instanceof Error ? releaseError.message : String(releaseError)}`); }",
    '    return new Response("Webhook handler failed", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    "  try { await completeWebhookDelivery(eventId, claim.leaseToken); }",
    "  catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[chargily webhook] completion failed: ${message}`);",
    "    try { await failWebhookDelivery(eventId, claim.leaseToken, message); } catch (releaseError) { logger.error(`[chargily webhook] claim release failed: ${releaseError instanceof Error ? releaseError.message : String(releaseError)}`); }",
    '    return new Response("Webhook event store unavailable", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    "  logger.info(`[chargily webhook] processed ${eventType} ${eventId}`);",
    '  return new Response("ok", { status: 200 });',
    "}",
  ].join("\n");
}

function baseChargilyConvexNext(imp: DbImports): string {
  const apiSpecifier = convexApiFor(imp, "chargily", "next");
  const dataModelSpecifier = apiSpecifier.replace(/\/api$/, "/dataModel");
  return [
    'import { createHash } from "node:crypto";',
    'import { verifySignature } from "@chargily/chargily-pay";',
    `import { convexClient } from "${imp.db}";`,
    `import { api } from "${apiSpecifier}";`,
    `import type { Id } from "${dataModelSpecifier}";`,
    `import { logger } from "${imp.observability}";`,
    "",
    ...convexBillingServerHelpers(),
    "",
    ...webhookBodyLimitHelpers(),
    "",
    ...webhookEventOrderHelpers(),
    "",
    ...chargilyIdentityHelpers(),
    "",
    "function scalarMetadata(value: unknown): Record<string, string | number | boolean | null> | undefined {",
    '  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;',
    "  const output: Record<string, string | number | boolean | null> = {};",
    "  for (const [key, item] of Object.entries(value)) {",
    '    if (item === null || typeof item === "string" || typeof item === "number" || typeof item === "boolean") output[key] = item;',
    "  }",
    "  return output;",
    "}",
    "",
    "async function failWebhookDelivery(providerEventId: string, leaseToken: string, error: string): Promise<void> {",
    '  await runBillingMutation("failWebhookEvent", { provider: "chargily", providerEventId, leaseToken, error });',
    "}",
    "",
    "export async function POST(req: Request): Promise<Response> {",
    ...webhookBodyReadLines("req"),
    '  const sig = req.headers.get("signature");',
    '  if (!sig) return new Response("Missing signature header", { status: 400 });',
    '  const secret = process.env.CHARGILY_SECRET_KEY ?? process.env.CHARGILY_WEBHOOK_SECRET ?? "";',
    '  if (!secret || secret.startsWith("REPLACE_WITH")) return new Response("CHARGILY_SECRET_KEY missing - server-only", { status: 400 });',
    "  try {",
    '    if (!verifySignature(buf, sig, secret)) return new Response("Invalid signature", { status: 403 });',
    "  } catch (error) {",
    "    logger.error(`[chargily webhook] signature verification failed: ${error instanceof Error ? error.message : String(error)}`);",
    '    return new Response("Invalid signature", { status: 403 });',
    "  }",
    "  let payload: Record<string, unknown>;",
    '  try { payload = JSON.parse(buf.toString("utf-8")) as Record<string, unknown>; }',
    '  catch { return new Response("Invalid JSON payload", { status: 400 }); }',
    '  if (!payload || typeof payload !== "object" || Array.isArray(payload)) return new Response("Invalid webhook payload", { status: 400 });',
    '  const data = payload.data && typeof payload.data === "object" && !Array.isArray(payload.data) ? payload.data as Record<string, unknown> : payload;',
    "  const eventId = chargilyDeliveryId(payload, buf);",
    '  const eventType = nonEmptyString(payload.type) ?? nonEmptyString(payload.event) ?? `checkout.${nonEmptyString(data.status) ?? "updated"}`;',
    "  const eventOccurredAtMs = providerEventMillis(payload.created_at, payload.createdAt, data.created_at, data.updated_at, data.createdAt, data.updatedAt);",
    '  let claim: { status: "claimed"; leaseToken: string } | { status: "completed" } | { status: "in_flight" };',
    '  try { claim = await runBillingMutation("claimWebhookEvent", { provider: "chargily", providerEventId: eventId, type: eventType, payload }); }',
    "  catch (error) {",
    "    logger.error(`[chargily webhook] delivery claim failed: ${error instanceof Error ? error.message : String(error)}`);",
    '    return new Response("Idempotency store unavailable", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    '  if (claim.status === "completed") return new Response("already processed", { status: 200 });',
    '  if (claim.status === "in_flight") return new Response("delivery in progress", { status: 503, headers: { "Retry-After": "5" } });',
    "  try {",
    "    const status = nonEmptyString(data.status) ?? nonEmptyString(payload.status);",
    "    const checkoutId = nonEmptyString(data.id);",
    "    const completed = isChargilyCompletedEvent(eventType, status);",
    "    const failed = isChargilyFailedEvent(eventType, status);",
    "    if ((completed || failed) && !checkoutId) throw new Error(`Chargily ${eventType} event did not include data.id`);",
    "    if (checkoutId && (completed || failed || status)) {",
    "      const metadata = scalarMetadata(data.metadata ?? payload.metadata);",
    "      const userId = nonEmptyString(metadata?.userId) ?? nonEmptyString(metadata?.chargily_user_id);",
    "      const requestKey = nonEmptyString(metadata?.requestKey);",
    "      if (!userId) throw new Error(`Chargily ${eventType} event did not include actor ownership`);",
    "      const providerEventAt = requireProviderEventMillis(`Chargily ${eventType}`, eventOccurredAtMs);",
    '      const checkoutStatus = completed ? "completed" as const : failed ? (eventType === "checkout.expired" ? "expired" as const : "failed" as const) : "pending" as const;',
    '      await runBillingMutation("upsertCheckout", { userId: userId as Id<"users">, provider: "chargily", providerCheckoutId: checkoutId, requestKey, status: checkoutStatus, metadata, providerEventAt });',
    "      if (completed || failed) {",
    '        const subscriptionStatus = completed ? "active" as const : eventType === "checkout.expired" ? "expired" as const : "canceled" as const;',
    '        await runBillingMutation("upsertSubscription", { userId: userId as Id<"users">, provider: "chargily", providerSubscriptionId: checkoutId, status: subscriptionStatus, metadata, providerEventAt });',
    "      }",
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[chargily webhook] handler failed: ${message}`);",
    "    try { await failWebhookDelivery(eventId, claim.leaseToken, message); } catch (releaseError) { logger.error(`[chargily webhook] claim release failed: ${releaseError instanceof Error ? releaseError.message : String(releaseError)}`); }",
    '    return new Response("Webhook handler failed", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    '  try { await runBillingMutation("completeWebhookEvent", { provider: "chargily", providerEventId: eventId, leaseToken: claim.leaseToken }); }',
    "  catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[chargily webhook] completion failed: ${message}`);",
    "    try { await failWebhookDelivery(eventId, claim.leaseToken, message); } catch (releaseError) { logger.error(`[chargily webhook] claim release failed: ${releaseError instanceof Error ? releaseError.message : String(releaseError)}`); }",
    '    return new Response("Webhook event store unavailable", { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    "  logger.info(`[chargily webhook] processed ${eventType} ${eventId}`);",
    '  return new Response("ok", { status: 200 });',
    "}",
  ].join("\n");
}

function asTanstack(source: string): string {
  const handler = source
    .replace(
      'import { createHash, randomUUID } from "node:crypto";',
      'import { createFileRoute } from "@tanstack/react-router";\nimport { createHash, randomUUID } from "node:crypto";',
    )
    .replace(
      'import { createHash } from "node:crypto";',
      'import { createFileRoute } from "@tanstack/react-router";\nimport { createHash } from "node:crypto";',
    )
    .replace(
      "export async function POST(req: Request): Promise<Response> {",
      "async function POST({ request }: { request: Request }): Promise<Response> {",
    )
    .replaceAll("req.headers", "request.headers")
    .replaceAll("rejectDeclaredBodySize(req)", "rejectDeclaredBodySize(request)");
  return `${handler}\nexport const Route = createFileRoute("/api/webhooks/chargily")({ server: { handlers: { POST } } });\n`;
}

export function chargilyNextContent(imp: DbImports): string {
  return (imp as ConvexImp).isConvex ? baseChargilyConvexNext(imp) : baseChargilyNext(imp);
}

export function chargilyNextConvexContent(imp: DbImports): string {
  return baseChargilyConvexNext(imp);
}

export function chargilyTanstackContent(imp: DbImports): string {
  return asTanstack(
    (imp as ConvexImp).isConvex ? baseChargilyConvexNext(imp) : baseChargilyNext(imp),
  );
}

export function chargilyTanstackConvexContent(imp: DbImports): string {
  return asTanstack(baseChargilyConvexNext(imp));
}
