/** Render SDK-value normalization before a verified webhook crosses the Convex transport. */
export function convexWebhookPayloadHelpers(): string[] {
  return [
    "type ConvexWebhookJson = null | boolean | number | string | ConvexWebhookJson[] | { [key: string]: ConvexWebhookJson };",
    "const MAX_CONVEX_WEBHOOK_PAYLOAD_BYTES = 900_000;",
    "",
    "function assertConvexWebhookKey(key: string, path: string): void {",
    '  if (key.length > 1_024 || key.startsWith("$")) throw new Error(`Webhook payload has an unsupported field at ${path}`);',
    "  for (let index = 0; index < key.length; index += 1) {",
    "    const code = key.charCodeAt(index);",
    "    if (code < 32 || code >= 127) throw new Error(`Webhook payload has an unsupported field at ${path}`);",
    "  }",
    "}",
    "",
    "function normalizeConvexWebhookValue(value: unknown, ancestors: WeakSet<object>, path: string): ConvexWebhookJson {",
    '  if (value === null || typeof value === "string" || typeof value === "boolean") return value;',
    '  if (typeof value === "number") {',
    "    if (!Number.isFinite(value)) throw new Error(`Webhook payload has a non-finite number at ${path}`);",
    "    return value;",
    "  }",
    "  if (value instanceof Date) {",
    "    const millis = value.getTime();",
    "    if (!Number.isFinite(millis)) throw new Error(`Webhook payload has an invalid date at ${path}`);",
    "    return value.toISOString();",
    "  }",
    "  if (Array.isArray(value)) {",
    "    if (ancestors.has(value)) throw new Error(`Webhook payload is cyclic at ${path}`);",
    "    ancestors.add(value);",
    "    try {",
    "      return value.map((entry, index) => entry === undefined ? null : normalizeConvexWebhookValue(entry, ancestors, `${path}[${index}]`));",
    "    } finally {",
    "      ancestors.delete(value);",
    "    }",
    "  }",
    '  if (typeof value === "object") {',
    "    if (value instanceof ArrayBuffer || ArrayBuffer.isView(value)) throw new Error(`Webhook payload has unsupported binary data at ${path}`);",
    "    if (ancestors.has(value)) throw new Error(`Webhook payload is cyclic at ${path}`);",
    "    ancestors.add(value);",
    "    try {",
    "      const normalized: Record<string, ConvexWebhookJson> = {};",
    "      const entries = Object.entries(value).sort(([left], [right]) => left === right ? 0 : left < right ? -1 : 1);",
    "      for (const [key, entry] of entries) {",
    "        if (entry === undefined) continue;",
    "        assertConvexWebhookKey(key, `${path}.${key}`);",
    "        normalized[key] = normalizeConvexWebhookValue(entry, ancestors, `${path}.${key}`);",
    "      }",
    "      return normalized;",
    "    } finally {",
    "      ancestors.delete(value);",
    "    }",
    "  }",
    "  throw new Error(`Webhook payload has unsupported ${typeof value} data at ${path}`);",
    "}",
    "",
    "function normalizeConvexWebhookPayload(value: unknown): Record<string, ConvexWebhookJson> {",
    '  const normalized = normalizeConvexWebhookValue(value, new WeakSet<object>(), "$webhook");',
    '  if (!normalized || Array.isArray(normalized) || typeof normalized !== "object") throw new Error("Webhook payload must be an object");',
    "  const serialized = JSON.stringify(normalized);",
    '  if (new TextEncoder().encode(serialized).byteLength > MAX_CONVEX_WEBHOOK_PAYLOAD_BYTES) throw new Error("Webhook payload exceeds the Convex persistence limit");',
    "  return normalized;",
    "}",
  ];
}
