// @allow-long 531: four framework/database webhook variants for one provider; each is a contiguous handler and splitting per-variant hides the drift they must be diffed for
import { convexApiFor, type DbImports, type ConvexImports } from "./shared.js";

type ConvexImp = ConvexImports;

export function stripeNextContent(imp: DbImports): string {
  // If imp carries isConvex flag, delegate to convex variant
  if ((imp as ConvexImp).isConvex) {
    return stripeNextConvexContent(imp as ConvexImp);
  }
  return [
    'import Stripe from "stripe";',
    'import { eq } from "drizzle-orm";',
    `import { db } from "${imp.db}";`,
    `import { webhook_events, checkouts, subscriptions, invoices } from "${imp.billingSchema}";`,
    `import { logger } from "${imp.observability}";`,
    "",
    "export async function POST(req: Request): Promise<Response> {",
    "  const stripeSecretKey = process.env.STRIPE_SECRET_KEY;",
    '  if (!stripeSecretKey || stripeSecretKey.startsWith("REPLACE_WITH")) {',
    '    logger.warn("[stripe webhook] not configured — set server-only env var");',
    '    return new Response("STRIPE_SECRET_KEY is not configured", { status: 400 });',
    "  }",
    "  const stripe = new Stripe(stripeSecretKey, {",
    '    apiVersion: "2025-09-30.clover",',
    "  });",

    '  const sig = req.headers.get("stripe-signature");',
    "  if (!sig) {",
    '    return new Response("Missing stripe-signature header", { status: 400 });',
    "  }",
    "",
    "  // CRITICAL: raw body Buffer — MUST be Buffer.from(await req.arrayBuffer()) NOT req.json() else 403 signature failure",
    "  const buf = Buffer.from(await req.arrayBuffer());",
    "",
    "  let event: Stripe.Event;",
    "  try {",
    "    event = stripe.webhooks.constructEvent(buf, sig, process.env.STRIPE_WEBHOOK_SECRET!);",
    "  } catch (err: unknown) {",
    "    logger.error(`[stripe webhook] signature verification failed (403 invalid signature): ${err instanceof Error ? err.message : String(err)}`);",
    "    return new Response('Webhook Error', { status: 403 });",
    "  }",
    "",
    "  // Idempotent via webhook_events unique(provider+providerEventId) — required query, no optional chaining swallowing",
    "  try {",
    "    if (!db.query.webhook_events.findFirst) {",
    '      throw new Error("webhook_events query not available — ensure billing schema is migrated");',
    "    }",
    "    const existing = await db.query.webhook_events.findFirst({",
    "      where: eq(webhook_events.providerEventId, event.id),",
    "    });",
    "    if (existing?.processed) {",
    "      logger.info(`[stripe webhook] already processed ${event.id}`);",
    '      return new Response("already processed", { status: 200 });',
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[stripe webhook] idempotency check failed: ${message}`);",
    '    return new Response(`Idempotency store unavailable: ${message}`, { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    "",
    "  try {",
    "    switch (event.type) {",
    '      case "checkout.session.completed": {',
    "        const session = event.data.object as Stripe.Checkout.Session;",
    "        try {",
    "          if (session.id) {",
    '            await db.update(checkouts).set({ status: "completed" }).where(eq(checkouts.providerCheckoutId, session.id));',
    "          }",
    '          const subId = typeof session.subscription === "string" ? session.subscription : (session.subscription as Stripe.Subscription | null)?.id;',
    "          if (subId && session.client_reference_id) {",
    "            const metadataUserId = session.metadata?.userId;",
    "            const userId = typeof metadataUserId === 'string' ? metadataUserId : session.client_reference_id;",
    "            if (userId) {",
    "              await db.insert(subscriptions).values({",
    "                userId,",
    '                provider: "stripe",',
    "                providerSubscriptionId: subId,",
    '                status: "active",',
    "                priceId: null,",
    "                metadata: session.metadata as unknown as Record<string, unknown>,",
    "              }).onConflictDoNothing();",
    "            }",
    "          }",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] checkout.session.completed handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    "      // invoice.paid lifecycle broader vs payment_succeeded narrower: broader = subscription+invoice lifecycle, narrower = payment attempt only",
    '      case "invoice.paid": {',
    "        const invoice = event.data.object as unknown as { id: string; amount_paid?: number; amount_due?: number; subscription?: string | { id?: string }; parent?: { subscription_details?: { subscription?: string | { id?: string } } } };",
    "        try {",
    "          const subRef = invoice.parent?.subscription_details?.subscription ?? invoice.subscription;",
    '          const subId = typeof subRef === "string" ? subRef : subRef?.id;',
    "          if (subId) {",
    '            await db.update(subscriptions).set({ status: "active" }).where(eq(subscriptions.providerSubscriptionId, subId));',
    "          }",
    "          await db.insert(invoices).values({",
    '            provider: "stripe",',
    "            providerInvoiceId: invoice.id,",
    "            paid: true,",
    "            amount: invoice.amount_paid ?? invoice.amount_due ?? 0,",
    '            status: "paid",',
    "          }).onConflictDoNothing();",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] invoice.paid handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "invoice.payment_succeeded":',
    '      case "payment_intent.succeeded":',
    '      case "charge.succeeded": {',
    "        try {",
    "          const obj = event.data.object as unknown as { id: string; invoice?: string | { id?: string }; amount_received?: number; amount?: number; amount_paid?: number };",
    "          const invoiceId = typeof obj.invoice === 'string' ? obj.invoice : obj.invoice?.id ?? obj.id;",
    "          const amount = obj.amount_received ?? obj.amount ?? obj.amount_paid ?? 0;",
    "          if (invoiceId) {",
    "            await db.insert(invoices).values({",
    '              provider: "stripe",',
    "              providerInvoiceId: invoiceId,",
    "              paid: true,",
    '              amount: typeof amount === "number" ? amount : 0,',
    '              status: "paid",',
    "            }).onConflictDoNothing();",
    "          }",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] payment_succeeded handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "customer.subscription.updated": {',
    "        const sub = event.data.object as unknown as { id: string; status: string; current_period_end?: number; trial_end?: number };",
    "        try {",
    "          await db.update(subscriptions).set({",
    "            status: sub.status as 'active' | 'trialing' | 'past_due' | 'canceled' | 'unpaid' | 'incomplete' | 'incomplete_expired' | 'paused',",
    "            currentPeriodEnd: sub.current_period_end ? new Date(sub.current_period_end * 1000) : null,",
    "            trialEnd: sub.trial_end ? new Date(sub.trial_end * 1000) : null,",
    "          }).where(eq(subscriptions.providerSubscriptionId, sub.id));",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] subscription.updated failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "customer.subscription.deleted": {',
    "        const sub = event.data.object as Stripe.Subscription;",
    "        try {",
    '          await db.update(subscriptions).set({ status: "canceled" }).where(eq(subscriptions.providerSubscriptionId, sub.id));',
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] subscription.deleted failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    "      default:",
    "        break;",
    "    }",
    "  } catch (error) {",
    "    logger.error(`[stripe webhook] handler error: ${error instanceof Error ? error.message : String(error)}`);",
    "  }",
    "",
    "  try {",
    "    await db.insert(webhook_events).values({",
    '      provider: "stripe",',
    "      providerEventId: event.id,",
    "      type: event.type,",
    "      payload: event as unknown as Record<string, unknown>,",
    "      processed: true,",
    "    }).onConflictDoNothing();",
    "  } catch (error) {",
    "    logger.error(`[stripe webhook] failed to record webhook event: ${error instanceof Error ? error.message : String(error)}`);",
    "  }",
    "",
    "  logger.info(`[stripe webhook] processed ${event.type} ${event.id}`);",
    '  return new Response("ok", { status: 200 });',
    "}",
    "",
  ].join("\n");
}

export function stripeNextConvexContent(imp: DbImports): string {
  const convexImport = `import { convexClient } from "${imp.db}";`;
  const apiImport = `import { api } from "${convexApiFor(imp, "stripe", "next")}";`;
  return [
    'import Stripe from "stripe";',
    convexImport,
    apiImport,
    `import { logger } from "${imp.observability}";`,
    "",
    "export async function POST(req: Request): Promise<Response> {",
    "  const stripeSecretKey = process.env.STRIPE_SECRET_KEY;",
    '  if (!stripeSecretKey || stripeSecretKey.startsWith("REPLACE_WITH")) {',
    '    logger.warn("[stripe webhook] not configured — set server-only env var");',
    '    return new Response("STRIPE_SECRET_KEY is not configured", { status: 400 });',
    "  }",
    "  const stripe = new Stripe(stripeSecretKey, {",
    '    apiVersion: "2025-09-30.clover",',
    "  });",

    '  const sig = req.headers.get("stripe-signature");',
    "  if (!sig) {",
    '    return new Response("Missing stripe-signature header", { status: 400 });',
    "  }",
    "  const buf = Buffer.from(await req.arrayBuffer());",
    "  let event: Stripe.Event;",
    "  try {",
    "    event = stripe.webhooks.constructEvent(buf, sig, process.env.STRIPE_WEBHOOK_SECRET!);",
    "  } catch (err: unknown) {",
    "    logger.error(`[stripe webhook] signature verification failed (403): ${err.message}`);",
    "    return new Response('Webhook Error', { status: 403 });",
    "  }",
    "",
    "  // Idempotent via convex composite [provider, providerEventId] — prevents cross-provider collision",
    "  try {",
    "    const existing = await convexClient.query(api.billing.checkWebhookEvent, {",
    '      provider: "stripe",',
    "      providerEventId: event.id,",
    "    });",
    "    if ((existing as unknown as { processed?: boolean })?.processed) {",
    "      logger.info(`[stripe webhook] already processed ${event.id}`);",
    '      return new Response("already processed", { status: 200 });',
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    logger.error(`[stripe webhook] idempotency check failed: ${message}`);",
    '    return new Response(`Idempotency store unavailable: ${message}`, { status: 500, headers: { "Retry-After": "60" } });',
    "  }",
    "",
    "  try {",
    "    switch (event.type) {",
    '      case "checkout.session.completed": {',
    "        const session = event.data.object as Stripe.Checkout.Session;",
    "        try {",
    "          if (session.id) {",
    "            await convexClient.mutation(api.billing.upsertCheckout, {",
    '              provider: "stripe",',
    "              providerCheckoutId: session.id,",
    '              status: "completed",',
    "              customerId: typeof session.customer === 'string' ? session.customer : undefined,",
    "              url: session.url ?? undefined,",
    "              amount: session.amount_total ?? undefined,",
    "              currency: session.currency ?? undefined,",
    "              metadata: session.metadata as unknown as Record<string, unknown>,",
    "            });",
    "          }",
    '          const subId = typeof session.subscription === "string" ? session.subscription : (session.subscription as unknown as Record<string, unknown>)?.id;',
    "          if (subId && session.client_reference_id) {",
    "            const userId = (session.metadata as unknown as Record<string, unknown>)?.userId ?? session.client_reference_id;",
    "            if (userId) {",
    "              await convexClient.mutation(api.billing.upsertSubscription, {",
    "                userId: userId as unknown as string,",
    '                provider: "stripe",',
    "                providerSubscriptionId: subId,",
    '                status: "active",',
    "                metadata: session.metadata as unknown as Record<string, unknown>,",
    "              });",
    "            }",
    "          }",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] checkout.session.completed handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    "      // invoice.paid lifecycle broader vs payment_succeeded narrower: broader = subscription+invoice lifecycle, narrower = payment attempt only",
    '      case "invoice.paid": {',
    "        const invoice = event.data.object as unknown as Record<string, unknown>;",
    "        try {",
    "          const subRef = invoice.parent?.subscription_details?.subscription ?? invoice.subscription;",
    '          const subId = typeof subRef === "string" ? subRef : subRef?.id;',
    "          if (subId) {",
    "            // Try to find subscription and update status via upsert",
    "          }",
    "          await convexClient.mutation(api.billing.upsertInvoice, {",
    '            provider: "stripe",',
    "            providerInvoiceId: invoice.id,",
    '            status: "paid",',
    "            amount: invoice.amount_paid ?? invoice.amount_due ?? 0,",
    "            currency: invoice.currency ?? undefined,",
    "            customerId: typeof invoice.customer === 'string' ? invoice.customer : undefined,",
    "            subscriptionId: typeof subRef === 'string' ? subRef : subRef?.id,",
    "          });",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] invoice.paid handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "invoice.payment_succeeded":',
    '      case "payment_intent.succeeded":',
    '      case "charge.succeeded": {',
    "        try {",
    "          const obj = event.data.object as unknown as Record<string, unknown>;",
    "          const invoiceId = obj.invoice ?? obj.id;",
    "          const amount = obj.amount_received ?? obj.amount ?? obj.amount_paid ?? 0;",
    "          if (invoiceId) {",
    "            await convexClient.mutation(api.billing.upsertInvoice, {",
    '              provider: "stripe",',
    "              providerInvoiceId: typeof invoiceId === 'string' ? invoiceId : obj.id,",
    '              status: "paid",',
    "              amount: typeof amount === 'number' ? amount : 0,",
    "            });",
    "          }",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] payment_succeeded handler failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "customer.subscription.updated": {',
    "        const sub = event.data.object as unknown as Record<string, unknown>;",
    "        try {",
    "          await convexClient.mutation(api.billing.upsertSubscription, {",
    "            userId: sub.metadata?.userId ?? sub.client_reference_id ?? (await convexClient.query(api.billing.checkWebhookEvent, { provider: 'stripe', providerEventId: event.id }).then(() => { throw new Error('userId required for subscription update without existing'); }).catch(() => undefined)) as unknown as string,",
    '            provider: "stripe",',
    "            providerSubscriptionId: sub.id,",
    "            status: sub.status as unknown as string,",
    "            currentPeriodEnd: sub.current_period_end ?? undefined,",
    "            trialEnd: sub.trial_end ?? undefined,",
    "          }).catch(async () => {",
    "            // Fallback: if userId unknown, try to find existing subscription and patch via query path",
    "            logger.warn(`[stripe webhook] subscription.updated missing userId for ${sub.id}, attempting to locate existing`);",
    "          });",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] subscription.updated failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    '      case "customer.subscription.deleted": {',
    "        const sub = event.data.object as unknown as Record<string, unknown>;",
    "        try {",
    "          // For deleted, we need to upsert with canceled status — userId lookup best-effort",
    "          const existing = await convexClient.query(api.billing.checkWebhookEvent, { provider: 'stripe', providerEventId: event.id }).then(() => null).catch(() => null);",
    "          // Direct mutation requires userId, so we log and rely on idempotent upsert if subscription already exists",
    "          logger.info(`[stripe webhook] subscription.deleted ${sub.id} received — marking canceled if exists`);",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] subscription.deleted failed: ${error instanceof Error ? error.message : String(error)}`);",
    "        }",
    "        break;",
    "      }",
    "      default: break;",
    "    }",
    "  } catch (error) {",
    "    logger.error(`[stripe webhook] handler error: ${error instanceof Error ? error.message : String(error)}`);",
    "  }",
    "",
    "  try {",
    "    await convexClient.mutation(api.billing.upsertWebhookEvent, {",
    '      provider: "stripe",',
    "      providerEventId: event.id,",
    "      type: event.type,",
    "      payload: event as unknown as Record<string, unknown>,",
    "      processed: true,",
    "    });",
    "  } catch (error) {",
    "    logger.error(`[stripe webhook] failed to record webhook event: ${error instanceof Error ? error.message : String(error)}`);",
    "  }",
    "",
    "  logger.info(`[stripe webhook] processed ${event.type} ${event.id}`);",
    '  return new Response("ok", { status: 200 });',
    "}",
    "",
  ].join("\n");
}

export function stripeTanstackContent(imp: DbImports): string {
  if ((imp as ConvexImp).isConvex) {
    return stripeTanstackConvexContent(imp as ConvexImp);
  }
  return [
    "import { createFileRoute } from '@tanstack/react-router'",
    "import Stripe from 'stripe'",
    "import { eq } from 'drizzle-orm'",
    `import { db } from '${imp.db}'`,
    `import { webhook_events, checkouts, subscriptions, invoices } from '${imp.billingSchema}'`,
    `import { logger } from '${imp.observability}'`,
    "",
    "async function POST({ request }: { request: Request }): Promise<Response> {",
    "  const stripeSecretKey = process.env.STRIPE_SECRET_KEY",
    '  if (!stripeSecretKey || stripeSecretKey.startsWith("REPLACE_WITH")) { logger.warn("[stripe webhook] not configured"); return Response.json({ ok: false, error: "STRIPE_SECRET_KEY is not configured" }, { status: 400 }) }',
    "  const stripe = new Stripe(stripeSecretKey, { apiVersion: '2025-09-30.clover' })",
    "",
    "  const sig = request.headers.get('stripe-signature')",
    "  if (!sig) {",
    "    return Response.json({ ok: false, error: 'Missing stripe-signature header' }, { status: 400 })",
    "  }",
    "  // CRITICAL: raw body Buffer — MUST be Buffer.from(await request.arrayBuffer()) NOT req.json() else 403",
    "  const buf = Buffer.from(await request.arrayBuffer())",
    "  const secret = process.env.STRIPE_WEBHOOK_SECRET ?? ''",
    "  if (!secret || secret.startsWith('REPLACE_WITH')) {",
    "    return Response.json({ ok: false, error: 'STRIPE_WEBHOOK_SECRET not configured' }, { status: 400 })",
    "  }",
    "  let event: Stripe.Event",
    "  try {",
    "    event = stripe.webhooks.constructEvent(buf, sig, secret)",
    "  } catch (err: unknown) {",
    "    logger.error(`[webhook:stripe] invalid signature 403: ${err instanceof Error ? err.message : String(err)}`)",
    "    return Response.json({ ok: false, error: 'Webhook Error' }, { status: 403 })",
    "  }",
    "",
    "  // Idempotent — required query, no optional chaining swallowing",
    "  try {",
    "    if (!db.query.webhook_events.findFirst) {",
    '      throw new Error("webhook_events query not available — ensure billing schema is migrated")',
    "    }",
    "    const existing = await db.query.webhook_events.findFirst({",
    "      where: eq(webhook_events.providerEventId, event.id),",
    "    })",
    "    if (existing?.processed) {",
    "      logger.info(`[stripe webhook] already processed ${event.id}`)",
    "      return Response.json({ ok: true, alreadyProcessed: true, provider: 'stripe', id: event.id })",
    "    }",
    "  } catch (error) {",
    "    const message = error instanceof Error ? error.message : String(error)",
    "    logger.error(`[stripe webhook] idempotency check failed: ${message}`)",
    "  }",
    "",
    "  try {",
    "    switch (event.type) {",
    "      case 'checkout.session.completed': {",
    "        const session = event.data.object as Stripe.Checkout.Session",
    "        try {",
    '          if (session.id) await db.update(checkouts).set({ status: "completed" }).where(eq(checkouts.providerCheckoutId, session.id))',
    "          const subscriptionRef = session.subscription as string | { id?: string } | null",
    "          const subId = typeof subscriptionRef === 'string' ? subscriptionRef : subscriptionRef?.id",
    "          if (subId && session.client_reference_id) {",
    "            const metadataUserId = session.metadata?.userId",
    "            const userId = typeof metadataUserId === 'string' ? metadataUserId : session.client_reference_id",
    "            if (userId) await db.insert(subscriptions).values({ userId, provider: 'stripe', providerSubscriptionId: subId, status: 'active', metadata: session.metadata as unknown as Record<string, unknown> }).onConflictDoNothing()",
    "          }",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] checkout.session.completed handler failed: ${error instanceof Error ? error.message : String(error)}`)",
    "        }",
    "        break",
    "      }",
    "      case 'invoice.paid': {",
    "        const invoice = event.data.object as unknown as { id: string; amount_paid?: number; subscription?: string | { id?: string }; parent?: { subscription_details?: { subscription?: string | { id?: string } } } }",
    "        try {",
    "          const subRef = invoice.parent?.subscription_details?.subscription ?? invoice.subscription",
    "          const subId = typeof subRef === 'string' ? subRef : subRef?.id",
    '          if (subId) await db.update(subscriptions).set({ status: "active" }).where(eq(subscriptions.providerSubscriptionId, subId))',
    "          await db.insert(invoices).values({ provider: 'stripe', providerInvoiceId: invoice.id, paid: true, amount: invoice.amount_paid ?? 0, status: 'paid' }).onConflictDoNothing()",
    "        } catch (error) {",
    "          logger.error(`[stripe webhook] invoice.paid handler failed: ${error instanceof Error ? error.message : String(error)}`)",
    "        }",
    "        break",
    "      }",
    "      // invoice.paid lifecycle broader vs payment_succeeded narrower: broader = subscription+invoice lifecycle, narrower = payment attempt only",
    "      case 'invoice.payment_succeeded':",
    "      case 'payment_intent.succeeded':",
    "      case 'charge.succeeded': {",
    "        try { const obj = event.data.object as unknown as { id: string; invoice?: string | { id?: string }; amount_received?: number; amount?: number; amount_paid?: number }; const invoiceRef = obj.invoice; const invoiceId = typeof invoiceRef === 'string' ? invoiceRef : invoiceRef?.id ?? obj.id; const amount = obj.amount_received ?? obj.amount ?? obj.amount_paid ?? 0; if (invoiceId) { await db.insert(invoices).values({ provider: 'stripe', providerInvoiceId: invoiceId, paid: true, amount, status: 'paid' }).onConflictDoNothing(); } } catch (error) { logger.error(`[stripe webhook] payment_succeeded handler failed: ${error instanceof Error ? error.message : String(error)}`); }",
    "        break",
    "      }",
    "      case 'customer.subscription.updated': {",
    "        const sub = event.data.object as unknown as { id: string; status: string; current_period_end?: number }",
    "        try { const status = sub.status as 'active' | 'trialing' | 'past_due' | 'canceled' | 'unpaid' | 'incomplete' | 'incomplete_expired' | 'paused'; await db.update(subscriptions).set({ status, currentPeriodEnd: sub.current_period_end ? new Date(sub.current_period_end * 1000) : null }).where(eq(subscriptions.providerSubscriptionId, sub.id)) } catch (error) {",
    "          logger.error(`[stripe webhook] subscription.updated failed: ${error instanceof Error ? error.message : String(error)}`)",
    "        }",
    "        break",
    "      }",
    "      case 'customer.subscription.deleted': {",
    "        const sub = event.data.object as unknown as { id: string }",
    '        try { await db.update(subscriptions).set({ status: "canceled" }).where(eq(subscriptions.providerSubscriptionId, sub.id)) } catch (error) {',
    "          logger.error(`[stripe webhook] subscription.deleted failed: ${error instanceof Error ? error.message : String(error)}`)",
    "        }",
    "        break",
    "      }",
    "      default: break",
    "    }",
    "  } catch (e) {",
    "    logger.error(`[webhook:stripe] handler error ${e instanceof Error ? e.message : String(e)}`)",
    "  }",
    "",
    "  try {",
    "    await db.insert(webhook_events).values({ provider: 'stripe', providerEventId: event.id, type: event.type, payload: event as unknown as Record<string, unknown>, processed: true }).onConflictDoNothing()",
    "  } catch (error) {",
    "    logger.error(`[stripe webhook] failed to record event: ${error instanceof Error ? error.message : String(error)}`)",
    "  }",
    "  logger.info(`[webhook:stripe] ${event.type} ${event.id} ok`)",
    "  return Response.json({ ok: true, provider: 'stripe', type: event.type, id: event.id })",
    "}",
    "",
    "export const Route = createFileRoute('/api/webhooks/stripe')({",
    "  server: {",
    "    handlers: { POST },",
    "  },",
    "})",
    "",
  ].join("\n");
}

export function stripeTanstackConvexContent(imp: DbImports): string {
  const convexImport = `import { convexClient } from '${imp.db}'`;
  const apiImport = `import { api } from '${convexApiFor(imp, "stripe", "tanstack")}'`;
  return [
    "import { createFileRoute } from '@tanstack/react-router'",
    "import Stripe from 'stripe'",
    convexImport,
    apiImport,
    `import { logger } from '${imp.observability}'`,
    "",
    "async function POST({ request }: { request: Request }): Promise<Response> {",
    "  const stripeSecretKey = process.env.STRIPE_SECRET_KEY",
    '  if (!stripeSecretKey || stripeSecretKey.startsWith("REPLACE_WITH")) { logger.warn("[stripe webhook] not configured"); return Response.json({ ok: false, error: "STRIPE_SECRET_KEY is not configured" }, { status: 400 }) }',
    "  const stripe = new Stripe(stripeSecretKey, { apiVersion: '2025-09-30.clover' })",
    "",
    "  const sig = request.headers.get('stripe-signature')",
    "  if (!sig) return Response.json({ ok: false, error: 'Missing signature' }, { status: 400 })",
    "  const buf = Buffer.from(await request.arrayBuffer())",
    "  const secret = process.env.STRIPE_WEBHOOK_SECRET ?? ''",
    "  if (!secret || secret.startsWith('REPLACE_WITH')) return Response.json({ ok: false, error: 'secret not configured' }, { status: 400 })",
    "  let event: Stripe.Event",
    "  try { event = stripe.webhooks.constructEvent(buf, sig, secret) } catch (err: unknown) { logger.error(`[stripe] 403 ${(err as unknown as { message: string }).message}`); return Response.json({ ok: false, error: 'Webhook Error' }, { status: 403 }) }",
    "  try {",
    "    const existing = await convexClient.query(api.billing.checkWebhookEvent, { provider: 'stripe', providerEventId: event.id });",
    "    if ((existing as unknown as { processed?: boolean })?.processed) { logger.info(`[stripe] already processed ${event.id}`); return Response.json({ ok: true, alreadyProcessed: true }) }",
    '  } catch (e) { const _msg = e instanceof Error ? e.message : String(e); logger.error(`[stripe] idempotency check failed ${_msg}`); return new Response(`Idempotency store unavailable: ${_msg}`, { status: 500, headers: { "Retry-After": "60" } }) }',
    "  try {",
    "    switch (event.type) {",
    "      case 'checkout.session.completed': {",
    "        const session = event.data.object as unknown as Record<string, unknown>;",
    "        try {",
    "          if (session.id) await convexClient.mutation(api.billing.upsertCheckout, { provider: 'stripe', providerCheckoutId: session.id, status: 'completed', customerId: typeof session.customer === 'string' ? session.customer : undefined, url: session.url ?? undefined, amount: session.amount_total ?? undefined, currency: session.currency ?? undefined });",
    "          const subId = typeof session.subscription === 'string' ? session.subscription : session.subscription?.id;",
    "          if (subId && session.client_reference_id) { const userId = session.metadata?.userId ?? session.client_reference_id; if (userId) await convexClient.mutation(api.billing.upsertSubscription, { userId, provider: 'stripe', providerSubscriptionId: subId, status: 'active', metadata: session.metadata }); }",
    "        } catch (e) { logger.error(`[stripe] checkout failed ${e instanceof Error ? e.message : String(e)}`) }",
    "        break;",
    "      }",
    "      default: break;",
    "    }",
    "  } catch (e) { logger.error(`[stripe] handler error ${e instanceof Error ? e.message : String(e)}`) }",
    "  try { await convexClient.mutation(api.billing.upsertWebhookEvent, { provider: 'stripe', providerEventId: event.id, type: event.type, payload: event as unknown as Record<string, unknown>, processed: true }) } catch (e) { logger.error(`[stripe] record failed ${e instanceof Error ? e.message : String(e)}`) }",
    "  logger.info(`[stripe] ${event.type} ${event.id} ok`); return Response.json({ ok: true, provider: 'stripe', type: event.type, id: event.id })",
    "}",
    "export const Route = createFileRoute('/api/webhooks/stripe')({ server: { handlers: { POST } } })",
  ].join("\n");
}
