/** Reference identity, billing, and messaging domain module package. */
import { codeScripts, file, packageJson, tsconfig, type TemplateFile } from "./shared.js";
import { billingApplicationsFiles } from "./billing/applications/billing.js";
import * as v from "./versions.js";

export function modulesPackage(
  runtime: "node" | "bun" = "bun",
  hasBilling = true,
  hasMessaging = false,
): TemplateFile[] {
  return [
    file(
      "packages/modules/package.json",
      packageJson({
        name: "@repo/modules",
        scripts: codeScripts({ test: "bun test" }),
        exports: {
          ".": "./src/index.ts",
          "./*": "./src/*/index.ts",
        },
        dependencies: {
          "@repo/contracts": "workspace:*",
          ...(hasBilling ? { "@repo/kernel": "workspace:*", "@repo/services": "workspace:*" } : {}),
        },
        devDependencies: {
          "bun-types": `^${v.runtime.bun}`,
          ...(runtime === "node" ? { "@types/node": `^${v.runtime["@types/node"]}` } : {}),
          typescript: `^${v.typescript.typescript}`,
        },
      }),
    ),
    file(
      "packages/modules/tsconfig.json",
      tsconfig({
        include: ["src/**/*", "tests/**/*"],
        compilerOptions: {
          types: runtime === "bun" ? ["bun-types"] : ["bun-types/test", "node"],
        },
      }),
    ),
    // Match sync's entrypoint order and never reference an unselected module.
    ...(() => {
      const parts: string[] = [];
      if (hasBilling) parts.push(`export * as billing from "./billing/index";`);
      if (hasMessaging) parts.push(`export * as messaging from "./messaging/index";`);
      parts.push(`export * as identity from "./identity/index";`);
      const exports = parts.join("\n");
      return [
        file(
          "packages/modules/src/index.ts",
          `// Generated by ghostinit sync. Do not edit manually.
${exports}
`,
        ),
      ];
    })(),
    file(
      "packages/modules/src/identity/index.ts",
      `export * from "./domain/index";\nexport * from "./application/index";\nexport type * from "./ports/index";\n`,
    ),
    file(
      "packages/modules/src/identity/domain/types.ts",
      `export interface UserProfile {\n  id: string;\n  email: string;\n  name: string | null;\n}\n`,
    ),
    file(
      "packages/modules/src/identity/domain/index.ts",
      `export { type UserProfile } from "./types.js";\n`,
    ),
    file(
      "packages/modules/src/identity/application/get-profile.ts",
      `import { type UserProfile } from "../domain/types.js";\n\nexport interface GetProfileInput {\n  userId: string;\n}\n\nexport interface GetProfileDeps {\n  findById: (userId: string) => Promise<UserProfile | null>;\n}\n\nexport async function getProfileUseCase(\n  input: GetProfileInput,\n  deps: GetProfileDeps,\n): Promise<UserProfile | null> {\n  return deps.findById(input.userId);\n}\n`,
    ),
    file(
      "packages/modules/src/identity/application/index.ts",
      `export { getProfileUseCase } from "./get-profile.js";\n`,
    ),
    file(
      "packages/modules/src/identity/ports/index.ts",
      `import type { UserProfile } from "../domain/types.js";\n\nexport interface UserRepository {\n  findById(userId: string): Promise<UserProfile | null>;\n}\n`,
    ),
    file(
      "packages/modules/tests/identity/get-profile.test.ts",
      `import { describe, it, expect } from "bun:test";\nimport { getProfileUseCase } from "../../src/identity/application/get-profile.js";\n\ndescribe("getProfileUseCase", () => {\n  it("returns the profile when found", async () => {\n    const profile = { id: "1", email: "a@example.com", name: "A" };\n    const result = await getProfileUseCase(\n      { userId: "1" },\n      { findById: async () => profile },\n    );\n    expect(result).toEqual(profile);\n  });\n\n  it("returns null when missing", async () => {\n    const result = await getProfileUseCase(\n      { userId: "2" },\n      { findById: async () => null },\n    );\n    expect(result).toBeNull();\n  });\n});\n`,
    ),
    ...(hasBilling
      ? [
          file(
            "packages/modules/src/billing/index.ts",
            `export * from "./application/index.js";\n`,
          ),
          file(
            "packages/modules/src/billing/application/index.ts",
            `export { createCheckoutUseCase, type CreateCheckoutUseCaseInput } from "./create-checkout.usecase.js";
export { listSubscriptionsUseCase } from "./list-subscriptions.usecase.js";
export { createPortalSessionUseCase, type CreatePortalSessionUseCaseInput, type PortalSessionRecord } from "./create-portal-session.usecase.js";
`,
          ),
          ...billingApplicationsFiles("monorepo"),
        ]
      : []),
    ...(hasMessaging
      ? [
          file(
            "packages/modules/src/messaging/index.ts",
            `export type { Conversation, Message, MessageAttachment, Participant, TypingIndicator } from "./domain/types.js";\n`,
          ),
          file(
            "packages/modules/src/messaging/domain/types.ts",
            `export interface Conversation { id: string; createdBy: string; createdAt: Date; updatedAt: Date; }\nexport interface Participant { conversationId: string; userId: string; joinedAt: Date; lastReadAt?: Date | null; }\nexport interface Message { id: string; conversationId: string; senderId: string; body?: string | null; replyToId?: string | null; createdAt: Date; }\nexport interface MessageAttachment { id: string; messageId: string; storageKey: string; url: string; mimeType: string; byteSize: number; originalName: string; createdAt: Date; }\nexport interface TypingIndicator { conversationId: string; userId: string; isTyping: boolean; updatedAt: Date; }\n`,
          ),
          file(
            "packages/modules/src/messaging/domain/index.ts",
            `export type { Conversation, Message, MessageAttachment, Participant, TypingIndicator } from "./types.js";\n`,
          ),
        ]
      : []),
  ];
}
