import { codeScripts, file, packageJson, tsconfig, type TemplateFile } from "./shared.js";
import * as v from "./versions.js";

export function modulesPackage(runtime: "node" | "bun" = "bun"): TemplateFile[] {
  return [
    file(
      "packages/modules/package.json",
      packageJson({
        name: "@repo/modules",
        scripts: codeScripts({ test: runtime === "bun" ? "bun test" : "npm run test:unit" }),
        exports: {
          ".": "./src/index.ts",
          "./*": "./src/*/index.ts",
        },
        dependencies: {
          "@repo/contracts": "workspace:*",
        },
        devDependencies: {
          ...(runtime === "bun" ? { "bun-types": `^${v.runtime.bun}` } : {}),
          typescript: `^${v.typescript.typescript}`,
        },
      }),
    ),
    file(
      "packages/modules/tsconfig.json",
      tsconfig({
        include: ["src/**/*", "tests/**/*"],
        compilerOptions: { types: runtime === "bun" ? ["bun-types"] : ["node"] },
      }),
    ),
    file(
      "packages/modules/src/index.ts",
      `// Generated by ghostinit sync. Do not edit manually.\nexport * as identity from "./identity/index";\n`,
    ),
    file(
      "packages/modules/src/identity/index.ts",
      `export * from "./domain/index";\nexport * from "./application/index";\nexport type * from "./ports/index";\n`,
    ),
    file(
      "packages/modules/src/identity/domain/types.ts",
      `export interface UserProfile {\n  id: string;\n  email: string;\n  name: string | null;\n}\n`,
    ),
    file(
      "packages/modules/src/identity/domain/index.ts",
      `export { type UserProfile } from "./types.js";\n`,
    ),
    file(
      "packages/modules/src/identity/application/get-profile.ts",
      `import { type UserProfile } from "../domain/types.js";\n\nexport interface GetProfileInput {\n  userId: string;\n}\n\nexport interface GetProfileDeps {\n  findById: (userId: string) => Promise<UserProfile | null>;\n}\n\nexport async function getProfileUseCase(\n  input: GetProfileInput,\n  deps: GetProfileDeps,\n): Promise<UserProfile | null> {\n  return deps.findById(input.userId);\n}\n`,
    ),
    file(
      "packages/modules/src/identity/application/index.ts",
      `export { getProfileUseCase } from "./get-profile.js";\n`,
    ),
    file(
      "packages/modules/src/identity/ports/index.ts",
      `import type { UserProfile } from "../domain/types.js";\n\nexport interface UserRepository {\n  findById(userId: string): Promise<UserProfile | null>;\n}\n`,
    ),
    file(
      "packages/modules/tests/identity/get-profile.test.ts",
      `import { describe, it, expect } from "bun:test";\nimport { getProfileUseCase } from "../../src/identity/application/get-profile.js";\n\ndescribe("getProfileUseCase", () => {\n  it("returns the profile when found", async () => {\n    const profile = { id: "1", email: "a@example.com", name: "A" };\n    const result = await getProfileUseCase(\n      { userId: "1" },\n      { findById: async () => profile },\n    );\n    expect(result).toEqual(profile);\n  });\n\n  it("returns null when missing", async () => {\n    const result = await getProfileUseCase(\n      { userId: "2" },\n      { findById: async () => null },\n    );\n    expect(result).toBeNull();\n  });\n});\n`,
    ),
  ];
}
