export { forgotPasswordPageSingle, resetPasswordPageSingle } from "./password.js";

export function signInPageSingle(hasEmail = true): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useRouter } from 'next/navigation';",
    "import { useState } from 'react';",
    "import Link from 'next/link';",
    "import { authClient } from '@/lib/auth-client';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';",
    "import { Input } from '@/components/ui/input';",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field';",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form';",
    "import { Spinner } from '@/components/ui/spinner';",
    "",
    "interface SignInForm { email: string; password: string; }",
    "",
    "export default function SignInPage(): React.JSX.Element {",
    "  const router = useRouter();",
    "  const [error, setError] = useState<string | null>(null);",
    "  const form = useForm({",
    "    defaultValues: { email: '', password: '' } as SignInForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null);",
    "      await authClient.signIn.email(",
    "        { email: value.email, password: value.password, callbackURL: '/dashboard' },",
    "        {",
    "          onSuccess(context) { router.push(context.data.twoFactorRedirect ? '/2fa' : '/dashboard'); },",
    "          onError(context) { setError(context.error.message ?? 'Sign in failed'); },",
    "        },",
    "      );",
    "    },",
    "  });",
    "",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link href='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-2'>",
    "            <CardTitle className='text-2xl tracking-tight'>Sign in</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Enter your credentials to access your account. Secure session with httpOnly lax cookies.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Unable to sign in</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup>",
    "                <TanStackField form={form} name='email' validators={{ onSubmit: ({ value }) => (value.includes('@') ? undefined : 'Enter a valid email') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signin-email'>Email</FieldLabel><Input id='signin-email' name={field.name} type='email' placeholder='you@example.com' autoComplete='email' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your account email address.</FieldDescription>}</Field>)}</TanStackField>",
    `                <TanStackField form={form} name='password' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><div className='flex items-center justify-between gap-2'><FieldLabel htmlFor='signin-password'>Password</FieldLabel>${hasEmail ? "<Link href='/forgot-password' className='text-xs text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Forgot?</Link>" : ""}</div><Input id='signin-password' name={field.name} type='password' autoComplete='current-password' required minLength={8} aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : null}</Field>)}</TanStackField>`,
    "              </FieldGroup>",
    "              <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>",
    "                {([canSubmit, isSubmitting]) => (",
    "                  <SubmitButton className='w-full' disabled={!canSubmit || isSubmitting}>",
    "                    {isSubmitting ? <Spinner data-icon='inline-start' /> : null}",
    "                    {isSubmitting ? 'Signing in…' : 'Sign in'}",
    "                  </SubmitButton>",
    "                )}",
    "              </form.Subscribe>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex flex-col gap-3'>",
    "            <div className='flex w-full justify-between text-sm'>",
    ...(hasEmail
      ? [
          "              <Link href='/forgot-password' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Forgot password?</Link>",
        ]
      : []),
    "              <Link href='/sign-up' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Create account</Link>",
    "            </div>",
    "          </CardFooter>",
    "        </Card>",
    "        <p className='text-center text-xs text-muted-foreground max-w-[65ch] mx-auto'>Session cookie httpOnly secure sameSite lax. Rate limit 60/min. Better Auth with admin + 2FA.</p>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function signUpPageSingle(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useRouter } from 'next/navigation';",
    "import { useState } from 'react';",
    "import Link from 'next/link';",
    "import { authClient } from '@/lib/auth-client';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';",
    "import { Input } from '@/components/ui/input';",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field';",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form';",
    "import { Spinner } from '@/components/ui/spinner';",
    "",
    "interface SignUpForm { name: string; email: string; password: string; }",
    "",
    "export default function SignUpPage(): React.JSX.Element {",
    "  const router = useRouter();",
    "  const [error, setError] = useState<string | null>(null);",
    "  const form = useForm({",
    "    defaultValues: { name: '', email: '', password: '' } as SignUpForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null);",
    "      const result = await authClient.signUp.email({ name: value.name, email: value.email, password: value.password, callbackURL: '/dashboard' });",
    "      if (result.error) { setError(result.error.message ?? 'Sign up failed'); return; }",
    "      router.push('/dashboard');",
    "    },",
    "  });",
    "",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link href='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-2'>",
    "            <CardTitle className='text-2xl tracking-tight'>Create account</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Start your workspace. Passwords hashed with scrypt. Secret strength validation length 32+ server side.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Unable to create account</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup>",
    "                <TanStackField form={form} name='name' validators={{ onSubmit: ({ value }) => (value.trim().length >= 1 ? undefined : 'Enter your name') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-name'>Name</FieldLabel><Input id='signup-name' name={field.name} type='text' placeholder='Ada Lovelace' autoComplete='name' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your display name.</FieldDescription>}</Field>)}</TanStackField>",
    "                <TanStackField form={form} name='email' validators={{ onSubmit: ({ value }) => (value.includes('@') ? undefined : 'Enter a valid email') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-email'>Email</FieldLabel><Input id='signup-email' name={field.name} type='email' placeholder='you@example.com' autoComplete='email' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your account email address.</FieldDescription>}</Field>)}</TanStackField>",
    "                <TanStackField form={form} name='password' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-password'>Password</FieldLabel><Input id='signup-password' name={field.name} type='password' autoComplete='new-password' required minLength={8} aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Must be at least 8 characters. Longer is stronger.</FieldDescription>}</Field>)}</TanStackField>",
    "              </FieldGroup>",
    "              <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>",
    "                {([canSubmit, isSubmitting]) => (",
    "                  <SubmitButton className='w-full' disabled={!canSubmit || isSubmitting}>",
    "                    {isSubmitting ? <Spinner data-icon='inline-start' /> : null}",
    "                    {isSubmitting ? 'Creating account…' : 'Create account'}",
    "                  </SubmitButton>",
    "                )}",
    "              </form.Subscribe>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex flex-col gap-3'>",
    "            <div className='flex w-full justify-center text-sm'>",
    "              <Link href='/sign-in' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Already have an account? Sign in</Link>",
    "            </div>",
    "          </CardFooter>",
    "        </Card>",
    "        <p className='text-center text-xs text-muted-foreground max-w-[65ch] mx-auto'>By continuing you agree to our terms. Session cookie httpOnly secure sameSite lax. Better Auth 1.6.23.</p>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}
