export function dashboardPageSingle(): string {
  return [
    "import * as React from 'react';",
    "import { headers } from 'next/headers';",
    "import { redirect } from 'next/navigation';",
    "import Link from 'next/link';",
    "import { auth } from '@/server/auth';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';",
    "import { Badge } from '@/components/ui/badge';",
    "import { Button } from '@/components/ui/button';",
    "import { Separator } from '@/components/ui/separator';",
    "",
    "export default async function DashboardPage(): Promise<React.JSX.Element> {",
    "  const session = await auth.api.getSession({ headers: await headers() });",
    "  if (!session?.user) redirect('/sign-in');",
    "  return (",
    "    <main className='min-h-screen bg-background text-foreground'>",
    "      <div className='mx-auto flex max-w-5xl flex-col gap-8 p-6 md:p-8 lg:p-10'>",
    "        <div className='flex flex-col gap-2'>",
    "          <div className='flex items-center justify-between gap-4'>",
    "            <h1 className='text-2xl font-semibold tracking-tight'>Dashboard</h1>",
    "            <div className='flex items-center gap-2'>",
    "              <Button variant='ghost' size='sm' asChild><Link href='/settings'>Settings</Link></Button>",
    "              <Button variant='outline' size='sm' asChild><Link href='/billing'>Billing</Link></Button>",
    "            </div>",
    "          </div>",
    "          <p className='text-sm text-muted-foreground max-w-[65ch]'>Welcome back. Manage your account, billing, and modules.</p>",
    "        </div>",
    "        <Separator />",
    "        <div className='grid grid-cols-1 gap-4 md:grid-cols-3'>",
    "          <Card className='md:col-span-2'>",
    "            <CardHeader>",
    "              <div className='flex items-center justify-between gap-3'>",
    "                <CardTitle className='text-base'>Profile</CardTitle>",
    "                <Badge variant='secondary' className='capitalize'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> {session.user.role ?? 'user'}</span></Badge>",
    "              </div>",
    "              <CardDescription className='max-w-[60ch]'>Signed in as {session.user.email}. Name {session.user.name ?? 'not set'}.</CardDescription>",
    "            </CardHeader>",
    "            <CardContent className='flex flex-col gap-3'>",
    "              <div className='flex flex-wrap gap-2'>",
    "                <Button variant='outline' size='sm' asChild><Link href='/settings'>Edit profile</Link></Button>",
    "                <Button variant='outline' size='sm' asChild><Link href='/billing'>Billing</Link></Button>",
    "                <Button variant='outline' size='sm' asChild><Link href='/admin'>Admin</Link></Button>",
    "              </div>",
    "            </CardContent>",
    "          </Card>",
    "          <Card>",
    "            <CardHeader>",
    "              <CardTitle className='text-base'>Quick actions</CardTitle>",
    "            </CardHeader>",
    "            <CardContent className='flex flex-col gap-2'>",
    "              <Button variant='outline' size='sm' asChild><Link href='/settings'>Security & 2FA</Link></Button>",
    "              <Button variant='outline' size='sm' asChild><Link href='/billing'>Manage billing</Link></Button>",
    "            </CardContent>",
    "          </Card>",
    "        </div>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}
