import * as v from "../../../versions.js";

export function singleMarketingPage(): string {
  return [
    "import * as React from 'react';",
    "import Link from 'next/link';",
    "import { Button } from '@/components/ui/button';",
    "import { Badge } from '@/components/ui/badge';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';",
    "import { Separator } from '@/components/ui/separator';",
    "import { ThemeToggle } from '@/components/theme-toggle';",
    "",
    "export default function HomePage(): React.JSX.Element {",
    "  return (",
    "    <main className='min-h-screen bg-background text-foreground'>",
    "      <header className='sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur-sm supports-[backdrop-filter]:bg-background/60'>",
    "        <div className='mx-auto flex h-14 max-w-6xl items-center justify-between gap-6 px-6 md:px-8'>",
    "          <Link href='/' className='flex items-center gap-2'>",
    "            <span className='text-sm font-semibold tracking-tight'>__PROJECT_NAME__</span>",
    "            <Badge variant='secondary' className='hidden sm:inline-flex'>single • flat src</Badge>",
    "          </Link>",
    "          <div className='flex items-center gap-2'>",
    "            <ThemeToggle />",
    "            <Button variant='ghost' size='sm' asChild><Link href='/sign-in'>Sign in</Link></Button>",
    "            <Button size='sm' asChild><Link href='/sign-up'>Sign up</Link></Button>",
    "          </div>",
    "        </div>",
    "      </header>",
    "",
    "      <div className='mx-auto flex max-w-5xl flex-col gap-16 p-6 md:gap-24 md:p-10 lg:p-12'>",
    "        <section className='flex flex-col gap-6 pt-8 md:pt-16'>",
    "          <Badge variant='secondary' className='w-fit'>Bun only • Better Auth • Drizzle • Billing flexible</Badge>",
    "          <div className='flex flex-col gap-4'>",
    "            <h1 className='text-4xl font-semibold leading-[1.1] tracking-tight md:text-5xl lg:text-[3.5rem]'>__PROJECT_NAME__</h1>",
    "            <p className='max-w-[65ch] text-lg text-muted-foreground leading-relaxed'>",
    "              Opinionated single all-in-one Next.js starter — flat src/ + server/ + agent/ if eve, Better Auth + Drizzle + Billing flexible any combo, shadcn Base UI semantic tokens, dark mode ready.",
    "            </p>",
    "          </div>",
    "          <div className='flex flex-wrap gap-3'>",
    "            <Button size='lg' asChild><Link href='/sign-up'>Start building</Link></Button>",
    "            <Button size='lg' variant='outline' asChild><Link href='/sign-in'>Sign in</Link></Button>",
    "          </div>",
    `          <div className='flex flex-wrap gap-2 pt-2'>`,
    `            <Badge variant='outline' className='font-mono text-xs'>Next ${v.nextStack.next}</Badge>`,
    `            <Badge variant='outline' className='font-mono text-xs'>React ${v.nextStack.react}</Badge>`,
    `            <Badge variant='outline' className='font-mono text-xs'>Drizzle ${v.database["drizzle-orm"]}</Badge>`,
    `            <Badge variant='outline' className='font-mono text-xs'>Better Auth ${v.auth["better-auth"]}</Badge>`,
    "          </div>",
    "        </section>",
    "",
    "        <Separator />",
    "",
    "        <section className='flex flex-col gap-8'>",
    "          <div className='flex flex-col gap-2'>",
    "            <h2 className='text-2xl font-semibold tracking-tight'>Why single mode</h2>",
    "            <p className='max-w-[60ch] text-sm text-muted-foreground'>Flat src/ structure, no workspaces, single dev server, same design tokens as monorepo.</p>",
    "          </div>",
    "          <div className='grid grid-cols-1 gap-4 md:grid-cols-12'>",
    "            <Card className='md:col-span-7'>",
    "              <CardHeader>",
    "                <CardTitle className='text-base'>Flat all-in-one</CardTitle>",
    "                <CardDescription className='max-w-[60ch]'>src/app + src/server/billing+services+email+db+auth + src/components/ui. No packages/* glob, private type module, path @/* src/*.</CardDescription>",
    "              </CardHeader>",
    "              <CardContent><div className='flex flex-wrap gap-2'><Badge variant='secondary'>src/app</Badge><Badge variant='secondary'>src/server</Badge><Badge variant='secondary'>agent/</Badge></div></CardContent>",
    "            </Card>",
    "            <Card className='md:col-span-5'>",
    "              <CardHeader>",
    "                <CardTitle className='text-base'>Better Auth + 2FA</CardTitle>",
    "                <CardDescription>Auto sign-in false, cookieCache compact httpOnly secure lax, rate limit, TOTP backup codes.</CardDescription>",
    "              </CardHeader>",
    "              <CardContent><p className='text-xs text-muted-foreground font-mono'>authClient.signIn.email callbackURL /dashboard</p></CardContent>",
    "            </Card>",
    "            <Card className='md:col-span-5'>",
    "              <CardHeader>",
    "                <CardTitle className='text-base'>Flexible billing</CardTitle>",
    "                <CardDescription>Any combo none/single/multi/all — Stripe, Chargily EDAHABIA/CIB, Paddle MoR, Polar. Shared billing tables idempotent.</CardDescription>",
    "              </CardHeader>",
    "            </Card>",
    "            <Card className='md:col-span-7'>",
    "              <CardHeader>",
    "                <CardTitle className='text-base'>Design tokens only</CardTitle>",
    "                <CardDescription className='max-w-[60ch]'>OKLCH paper + indigo ≤10% chroma, semantic tokens background foreground primary muted accent destructive border input ring, no hardcoded slate.</CardDescription>",
    "              </CardHeader>",
    "              <CardContent className='flex flex-col gap-3'><div className='flex flex-wrap gap-2'><Badge variant='secondary'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> shadcn</span></Badge><Badge variant='secondary'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> Base UI</span></Badge></div></CardContent>",
    "            </Card>",
    "          </div>",
    "        </section>",
    "",
    "        <Separator />",
    "",
    "        <section className='flex flex-col gap-6 rounded-xl border bg-card p-6 shadow-sm md:p-8'>",
    "          <div className='flex flex-col gap-2'>",
    "            <h2 className='text-lg font-semibold tracking-tight'>Quick start</h2>",
    "            <p className='text-sm text-muted-foreground max-w-[65ch]'>Bun only, secret strength ≥32, single port 3000, withEve hybrid if enabled.</p>",
    "          </div>",
    "          <div className='rounded-md bg-muted p-4 font-mono text-xs leading-relaxed'>",
    "            <div>bunx ghostinit create __PROJECT_NAME__ --mode single</div>",
    "            <div className='text-muted-foreground'>cd __PROJECT_NAME__ && bun install && bun run dev</div>",
    "          </div>",
    "        </section>",
    "",
    "        <footer className='flex flex-col gap-4 border-t pt-8'>",
    "          <div className='flex items-center justify-between gap-4'>",
    "            <span className='text-xs text-muted-foreground'>Built with shadcn + Base UI + Tailwind v4 • OKLCH paper + indigo</span>",
    "            <div className='flex gap-4 text-xs'>",
    "              <Link href='/sign-in' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Sign in</Link>",
    "              <Link href='/billing' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Billing</Link>",
    "            </div>",
    "          </div>",
    "        </footer>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}
