export function singleTwoFactorPageContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useRouter } from 'next/navigation';",
    "import { useState } from 'react';",
    "import Link from 'next/link';",
    "import { authClient } from '@/lib/auth-client';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';",
    "import { Input } from '@/components/ui/input';",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';",
    "import { Badge } from '@/components/ui/badge';",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field';",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form';",
    "",
    "interface TwoFactorForm { code: string; }",
    "",
    "export default function TwoFactorPage(): React.JSX.Element {",
    "  const router = useRouter();",
    "  const [error, setError] = useState<string | null>(null);",
    "  const form = useForm({",
    "    defaultValues: { code: '' } as TwoFactorForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null);",
    "      const result = await authClient.twoFactor.verifyTotp({ code: value.code, trustDevice: true });",
    "      if (result.error) { setError(result.error.message ?? 'Invalid code'); return; }",
    "      router.push('/dashboard');",
    "    },",
    "  });",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link href='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-3'>",
    "            <div className='flex items-center gap-2'>",
    "              <Badge variant='secondary'>2FA</Badge>",
    "              <span className='text-xs text-muted-foreground'>TOTP • trust 30d</span>",
    "            </div>",
    "            <CardTitle className='text-2xl tracking-tight'>Two-factor authentication</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Enter the 6-digit code from your authenticator app. Secure verification with rate limiting and replay protection.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Invalid code</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup>",
    "                <TanStackField form={form} name='code' validators={{ onSubmit: ({ value }) => (/^[0-9]{6}$/.test(value) ? undefined : 'Enter a 6-digit code') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0} className='flex flex-col gap-3'><FieldLabel htmlFor='totp-code' className='text-sm'>Authentication code</FieldLabel><Input id='totp-code' name={field.name} inputMode='numeric' autoComplete='one-time-code' maxLength={6} placeholder='000000' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value.replace(/[^0-9]/g, '').slice(0, 6))} onBlur={field.handleBlur} className='font-mono tracking-widest text-center text-lg h-12' />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription className='max-w-[60ch]'>Open authenticator such as Authy, 1Password, Google Authenticator. Code refreshes every 30s.</FieldDescription>}</Field>)}</TanStackField>",
    "              </FieldGroup>",
    "              <SubmitButton className='w-full'>Verify and continue</SubmitButton>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex justify-between text-sm'>",
    "            <Link href='/sign-in' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Back to sign in</Link>",
    "            <Link href='/settings' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Recovery codes</Link>",
    "          </CardFooter>",
    "        </Card>",
    "        <p className='text-center text-xs text-muted-foreground max-w-[65ch] mx-auto'>Trust device stores secure httpOnly cookie for 30 days. Rate limited 60/min. Works offline TOTP RFC6238.</p>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleAgentPageContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useState } from 'react';",
    "import { useEveAgent } from 'eve/react';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';",
    "import { Badge } from '@/components/ui/badge';",
    "import { Button } from '@/components/ui/button';",
    "import { Input } from '@/components/ui/input';",
    "import { Separator } from '@/components/ui/separator';",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';",
    "",
    "export default function AgentPage(): React.JSX.Element {",
    "  const agent = useEveAgent();",
    "  const [input, setInput] = useState('');",
    '  const isBusy = agent.status === "submitted" || agent.status === "streaming";',
    "  return (",
    "    <main className='min-h-screen bg-background text-foreground'>",
    "      <div className='mx-auto flex max-w-3xl flex-col gap-8 p-6 md:p-8 lg:p-10'>",
    "        <div className='flex flex-col gap-3'>",
    "          <div className='flex items-center gap-3'>",
    "            <h1 className='text-2xl font-semibold tracking-tight'>Eve Durable Agent</h1>",
    "            <Badge variant='secondary'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> durable</span></Badge>",
    "          </div>",
    '          <p className="text-sm text-muted-foreground max-w-[65ch] leading-relaxed">Chat uses Eve agent in <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">agent/</code> — filesystem-first durable backend mounted same-origin via withEve({`{ eveRoot: "./agent" }`}). Tools: scaffold_module, check_architecture, sync_registries, list_modules, db_migrate.</p>',
    "        </div>",
    "        <Separator />",
    "        <Card className='flex flex-col gap-4 p-4'>",
    "          <CardHeader className='p-0'>",
    "            <CardTitle className='text-base'>Conversation</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Mounted same-origin via withEve. Cookie auth flows, zero CORS, single server.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-4 p-0'>",
    "            <div className='flex max-h-96 flex-col gap-2 overflow-y-auto rounded-md border bg-muted/20 p-3'>",
    "              {agent.data.messages.length === 0 ? (<p className='text-sm text-muted-foreground text-center py-6'>No messages yet. Ask to scaffold a module or check architecture.</p>) : (agent.data.messages.map((m: { id: string; role: string; content?: string }) => (<div key={m.id} className={m.role === 'user' ? 'flex justify-end' : 'flex justify-start'}><span className={m.role === 'user' ? 'inline-block max-w-[80%] rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground' : 'inline-block max-w-[80%] rounded-lg bg-muted px-3 py-2 text-sm text-foreground'}>{m.content ?? ''}</span></div>)))}",
    "            </div>",
    "            <form onSubmit={(e) => { e.preventDefault(); if (!input.trim() || isBusy) return; agent.send({ message: input }); setInput(''); }} className='flex gap-2'>",
    "              <Input value={input} onChange={(e) => setInput(e.target.value)} placeholder={isBusy ? 'Agent working...' : 'Ask to scaffold a module, check architecture...'} disabled={isBusy} className='flex-1 bg-background' />",
    "              <Button type='submit' disabled={isBusy || !input.trim()}>{isBusy ? '...' : 'Send'}</Button>",
    "            </form>",
    "            {agent.status === 'streaming' ? <p className='text-xs text-muted-foreground'>Streaming durable workflow...</p> : null}",
    "            {agent.error ? (<Alert variant='destructive'><AlertTitle>Agent error</AlertTitle><AlertDescription className='break-all text-xs'>{String(agent.error)}</AlertDescription></Alert>) : null}",
    "          </CardContent>",
    "        </Card>",
    "        <p className='text-xs text-muted-foreground max-w-[65ch] leading-relaxed'>Hybrid agent/ inside Next root withEve eveRoot ./agent — single dev server, single deploy, same-origin /eve/v1/*, cookie auth flows Better Auth. See agent/docs for guides.</p>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}
