export function singleSignInRouteTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'",
    "import { useState } from 'react'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Button } from '@/components/ui/button'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'",
    "import { Input } from '@/components/ui/input'",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field'",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form'",
    "",
    "export const Route = createFileRoute('/sign-in')({",
    "  component: SignInPage,",
    "})",
    "",
    "interface SignInForm { email: string; password: string; }",
    "",
    "function SignInPage(): React.JSX.Element {",
    "  const navigate = useNavigate()",
    "  const [error, setError] = useState<string | null>(null)",
    "  const form = useForm({",
    "    defaultValues: { email: '', password: '' } as SignInForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null)",
    "      const result = await authClient.signIn.email({ email: value.email, password: value.password, callbackURL: '/dashboard' })",
    "      if (result.error) { setError(result.error.message ?? 'Sign in failed'); return }",
    "      if ((result.data as unknown as { twoFactorRedirect?: boolean } | null)?.twoFactorRedirect) { void navigate({ to: '/2fa' }); return }",
    "      void navigate({ to: '/dashboard' })",
    "    },",
    "  })",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link to='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-2'>",
    "            <CardTitle className='text-2xl tracking-tight'>Sign in</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Enter your credentials to access your account. Secure session with httpOnly lax cookies.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Unable to sign in</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup>",
    "                <TanStackField form={form} name='email' validators={{ onSubmit: ({ value }) => (value.includes('@') ? undefined : 'Enter a valid email') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signin-email'>Email</FieldLabel><Input id='signin-email' name={field.name} type='email' placeholder='you@example.com' autoComplete='email' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your account email address.</FieldDescription>}</Field>)}</TanStackField>",
    "                <TanStackField form={form} name='password' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><div className='flex items-center justify-between gap-2'><FieldLabel htmlFor='signin-password'>Password</FieldLabel><Link to='/forgot-password' className='text-xs text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Forgot?</Link></div><Input id='signin-password' name={field.name} type='password' autoComplete='current-password' required minLength={8} aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : null}</Field>)}</TanStackField>",
    "              </FieldGroup>",
    "              <SubmitButton className='w-full'>Sign in</SubmitButton>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex flex-col gap-3'>",
    "            <div className='flex w-full justify-between text-sm'>",
    "              <Link to='/forgot-password' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Forgot password?</Link>",
    "              <Link to='/sign-up' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Create account</Link>",
    "            </div>",
    "          </CardFooter>",
    "        </Card>",
    "        <p className='text-center text-xs text-muted-foreground max-w-[65ch] mx-auto'>Session cookie httpOnly secure sameSite lax. Rate limit 60/min. Better Auth with admin + 2FA tanstackStartCookies.</p>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleSignUpRouteTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'",
    "import { useState } from 'react'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'",
    "import { Input } from '@/components/ui/input'",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field'",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form'",
    "",
    "export const Route = createFileRoute('/sign-up')({ component: SignUpPage })",
    "",
    "interface SignUpForm { name: string; email: string; password: string; }",
    "",
    "function SignUpPage(): React.JSX.Element {",
    "  const navigate = useNavigate()",
    "  const [error, setError] = useState<string | null>(null)",
    "  const form = useForm({",
    "    defaultValues: { name: '', email: '', password: '' } as SignUpForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null)",
    "      const result = await authClient.signUp.email({ name: value.name, email: value.email, password: value.password, callbackURL: '/dashboard' })",
    "      if (result.error) { setError(result.error.message ?? 'Sign up failed'); return }",
    "      void navigate({ to: '/dashboard' })",
    "    },",
    "  })",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link to='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-2'>",
    "            <CardTitle className='text-2xl tracking-tight'>Create account</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Start your workspace. Passwords hashed with scrypt.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Unable to create account</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup>",
    "                <TanStackField form={form} name='name' validators={{ onSubmit: ({ value }) => (value.trim().length >= 1 ? undefined : 'Enter your name') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-name'>Name</FieldLabel><Input id='signup-name' name={field.name} type='text' placeholder='Ada Lovelace' autoComplete='name' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your display name.</FieldDescription>}</Field>)}</TanStackField>",
    "                <TanStackField form={form} name='email' validators={{ onSubmit: ({ value }) => (value.includes('@') ? undefined : 'Enter a valid email') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-email'>Email</FieldLabel><Input id='signup-email' name={field.name} type='email' placeholder='you@example.com' autoComplete='email' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Your account email address.</FieldDescription>}</Field>)}</TanStackField>",
    "                <TanStackField form={form} name='password' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='signup-password'>Password</FieldLabel><Input id='signup-password' name={field.name} type='password' autoComplete='new-password' required minLength={8} aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Must be at least 8 characters.</FieldDescription>}</Field>)}</TanStackField>",
    "              </FieldGroup>",
    "              <SubmitButton className='w-full'>Create account</SubmitButton>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex flex-col gap-3'><div className='flex w-full justify-center text-sm'><Link to='/sign-in' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Already have an account? Sign in</Link></div></CardFooter>",
    "        </Card>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleForgotPasswordRouteTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { createFileRoute, Link } from '@tanstack/react-router'",
    "import { useState } from 'react'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'",
    "import { Button } from '@/components/ui/button'",
    "import { Input } from '@/components/ui/input'",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field'",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form'",
    "",
    "export const Route = createFileRoute('/forgot-password')({ component: ForgotPasswordPage })",
    "",
    "interface ForgotPasswordForm { email: string; }",
    "",
    "function ForgotPasswordPage(): React.JSX.Element {",
    "  const [status, setStatus] = useState<string | null>(null)",
    "  const [error, setError] = useState<string | null>(null)",
    "  const form = useForm({",
    "    defaultValues: { email: '' } as ForgotPasswordForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null); setStatus(null)",
    "      if (!value.email.includes('@')) { setError('Enter a valid email that contains @'); return }",
    "      const result = await authClient.requestPasswordReset({ email: value.email, redirectTo: '/reset-password' })",
    "      if (result.error) { setError(result.error.message ?? 'Failed to send reset link'); return }",
    "      setStatus('If this email exists, check your inbox for the reset link.')",
    "    },",
    "  })",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-8'>",
    "        <Card>",
    "          <CardHeader><CardTitle>Forgot password</CardTitle><CardDescription>Enter your email and we will send you a link to reset your password. Link expires 1h single use.</CardDescription></CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Unable to send link</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            {status ? (<Alert><AlertTitle>Check your email</AlertTitle><AlertDescription>{status}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup><TanStackField form={form} name='email' validators={{ onSubmit: ({ value }) => (value.includes('@') ? undefined : 'Enter a valid email') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='forgot-email'>Email</FieldLabel><Input id='forgot-email' name={field.name} type='email' placeholder='you@example.com' autoComplete='email' required value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>We send a reset link to this address if it exists.</FieldDescription>}</Field>)}</TanStackField></FieldGroup>",
    "              <SubmitButton className='w-full'>Send reset link</SubmitButton>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter><Link to='/sign-in' className='text-sm text-muted-foreground underline'>Back to sign in</Link></CardFooter>",
    "        </Card>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleResetPasswordRouteTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'",
    "import { useState, useEffect } from 'react'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Button } from '@/components/ui/button'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'",
    "import { Input } from '@/components/ui/input'",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field'",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form'",
    "",
    "export const Route = createFileRoute('/reset-password')({ validateSearch: (search: Record<string, unknown>) => ({ token: typeof search.token === 'string' ? search.token : undefined, error: typeof search.error === 'string' ? search.error : undefined }), component: ResetPasswordPage })",
    "",
    "interface ResetPasswordForm { newPassword: string; confirmPassword: string; }",
    "",
    "function ResetPasswordPage(): React.JSX.Element {",
    "  const navigate = useNavigate()",
    "  const search = Route.useSearch()",
    "  const token = search.token",
    "  const initialError = search.error === 'INVALID_TOKEN' ? 'Invalid or expired reset link. Please request a new one.' : (search.error ?? null)",
    "  const [error, setError] = useState<string | null>(initialError)",
    "  const form = useForm({",
    "    defaultValues: { newPassword: '', confirmPassword: '' } as ResetPasswordForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null)",
    "      if (value.newPassword !== value.confirmPassword) { setError('Passwords do not match'); return }",
    "      if (value.newPassword.length < 8) { setError('Password must be at least 8 characters'); return }",
    "      const result = await authClient.resetPassword({ newPassword: value.newPassword, token: token! })",
    "      if (result.error) { setError(result.error.message ?? 'Failed to reset password'); return }",
    "      void navigate({ to: '/sign-in' })",
    "    },",
    "  })",
    "  if (!token) {",
    "    return (",
    "      <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "        <Card className='w-full max-w-[420px] shadow-sm'>",
    "          <CardHeader><CardTitle className='text-2xl tracking-tight'>Invalid token</CardTitle><CardDescription>The reset link is missing or expired. Request a new one.</CardDescription></CardHeader>",
    "          <CardContent><Link to='/forgot-password' className='text-sm text-primary underline'>Request new link</Link></CardContent>",
    "        </Card>",
    "      </main>",
    "    )",
    "  }",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Card>",
    "          <CardHeader><CardTitle>Reset password</CardTitle><CardDescription>Choose a new password. Link expires in 1 hour and can only be used once.</CardDescription></CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? <Alert variant='destructive'><AlertTitle>Error</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}",
    "            {false ? (<div className='flex flex-col gap-4'><p className='text-sm text-muted-foreground'>No valid token found.</p><Link to='/forgot-password'><Button>Request new link</Button></Link></div>) : (",
    "              <Form form={form} className='flex flex-col gap-6'>",
    "                <FieldGroup>",
    "                  <TanStackField form={form} name='newPassword' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }} >{(field) => (<Field data-invalid={field.state.meta.errors.length > 0}><FieldLabel htmlFor='new-password'>New password</FieldLabel><Input id='new-password' name={field.name} type='password' autoComplete='new-password' required minLength={8} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription>Must be at least 8 characters.</FieldDescription>}</Field>)}</TanStackField>",
    "                  <TanStackField form={form} name='confirmPassword' validators={{ onSubmit: ({ value }) => (value.length >= 8 ? undefined : 'Password must be at least 8 characters') }} >{(field) => (<Field><FieldLabel htmlFor='confirm-password'>Confirm password</FieldLabel><Input id='confirm-password' name={field.name} type='password' required minLength={8} value={field.state.value} onChange={(e) => field.handleChange(e.target.value)} onBlur={field.handleBlur} /><FieldDescription>Must match the new password above.</FieldDescription></Field>)}</TanStackField>",
    "                </FieldGroup>",
    "                <SubmitButton className='w-full'>Reset password</SubmitButton>",
    "              </Form>",
    "            )}",
    "          </CardContent>",
    "          <CardFooter><Link to='/sign-in' className='text-sm underline'>Back to sign in</Link></CardFooter>",
    "        </Card>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleTwoFactorRouteTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'",
    "import { useState } from 'react'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card'",
    "import { Input } from '@/components/ui/input'",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'",
    "import { Badge } from '@/components/ui/badge'",
    "import { FieldGroup, Field, FieldLabel, FieldDescription } from '@/components/ui/field'",
    "import { Form, Field as TanStackField, SubmitButton, useForm } from '@/components/ui/form'",
    "",
    "export const Route = createFileRoute('/2fa')({ component: TwoFactorPage })",
    "interface TwoFactorForm { code: string; }",
    "function TwoFactorPage(): React.JSX.Element {",
    "  const navigate = useNavigate()",
    "  const [error, setError] = useState<string | null>(null)",
    "  const form = useForm({",
    "    defaultValues: { code: '' } as TwoFactorForm,",
    "    onSubmit: async ({ value }) => {",
    "      setError(null)",
    "      const result = await authClient.twoFactor.verifyTotp({ code: value.code, trustDevice: true })",
    "      if (result.error) { setError(result.error.message ?? 'Invalid code'); return }",
    "      void navigate({ to: '/dashboard' })",
    "    },",
    "  })",
    "  return (",
    "    <main className='min-h-screen flex items-center justify-center p-6 bg-background'>",
    "      <div className='w-full max-w-[420px] flex flex-col gap-6'>",
    "        <Link to='/' className='text-sm text-muted-foreground hover:text-foreground'>← Back to home</Link>",
    "        <Card className='shadow-sm'>",
    "          <CardHeader className='flex flex-col gap-3'>",
    "            <div className='flex items-center gap-2'><Badge variant='secondary'>2FA</Badge><span className='text-xs text-muted-foreground'>TOTP • trust 30d</span></div>",
    "            <CardTitle className='text-2xl tracking-tight'>Two-factor authentication</CardTitle>",
    "            <CardDescription className='max-w-[60ch]'>Enter the 6-digit code from your authenticator app.</CardDescription>",
    "          </CardHeader>",
    "          <CardContent className='flex flex-col gap-6'>",
    "            {error ? (<Alert variant='destructive'><AlertTitle>Invalid code</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>) : null}",
    "            <Form form={form} className='flex flex-col gap-6'>",
    "              <FieldGroup><TanStackField form={form} name='code' validators={{ onSubmit: ({ value }) => (/^[0-9]{6}$/.test(value) ? undefined : 'Enter a 6-digit code') }}>{(field) => (<Field data-invalid={field.state.meta.errors.length > 0} className='flex flex-col gap-3'><FieldLabel htmlFor='totp-code' className='text-sm'>Authentication code</FieldLabel><Input id='totp-code' name={field.name} inputMode='numeric' autoComplete='one-time-code' maxLength={6} placeholder='000000' required aria-invalid={field.state.meta.errors.length > 0} value={field.state.value} onChange={(e) => field.handleChange(e.target.value.replace(/[^0-9]/g, '').slice(0, 6))} onBlur={field.handleBlur} className='font-mono tracking-widest text-center text-lg h-12' />{field.state.meta.errors.length > 0 ? <FieldDescription className='text-destructive'>{field.state.meta.errors.join(', ')}</FieldDescription> : <FieldDescription className='max-w-[60ch]'>Open Authy, 1Password, Google Authenticator.</FieldDescription>}</Field>)}</TanStackField></FieldGroup>",
    "              <SubmitButton className='w-full'>Verify and continue</SubmitButton>",
    "            </Form>",
    "          </CardContent>",
    "          <CardFooter className='flex justify-between text-sm'><Link to='/sign-in' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Back to sign in</Link><Link to='/settings' className='text-muted-foreground hover:text-foreground underline-offset-4 hover:underline'>Recovery codes</Link></CardFooter>",
    "        </Card>",
    "        <p className='text-center text-xs text-muted-foreground max-w-[65ch] mx-auto'>Trust device stores secure httpOnly cookie for 30 days. Rate limited 60/min. Works offline TOTP RFC6238.</p>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}
