export function singleDashboardRouteTanstackContent(): string {
  return [
    "import * as React from 'react'",
    "import { createFileRoute, redirect, Link } from '@tanstack/react-router'",
    "import { createServerFn } from '@tanstack/react-start'",
    "import { getRequestHeaders } from '@tanstack/react-start/server'",
    "import { auth } from '@/server/auth'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'",
    "import { Badge } from '@/components/ui/badge'",
    "import { Button } from '@/components/ui/button'",
    "import { Separator } from '@/components/ui/separator'",
    "",
    "const getSessionFn = createServerFn({ method: 'GET' }).handler(async () => {",
    "  const headers = getRequestHeaders() as unknown as Headers",
    "  const session = await (auth as unknown as { api: { getSession: (opts: { headers: Headers }) => Promise<{ user?: { email?: string; name?: string | null; role?: string } } | null> } }).api.getSession({ headers })",
    "  return session ?? null",
    "})",
    "",
    "export const Route = createFileRoute('/dashboard')({",
    "  beforeLoad: async () => {",
    "    const session = await getSessionFn()",
    "    if (!session?.user) { throw redirect({ to: '/sign-in' }) }",
    "    return { session }",
    "  },",
    "  component: DashboardPage,",
    "})",
    "",
    "function DashboardPage(): React.JSX.Element {",
    "  const { session } = Route.useRouteContext() as { session: { user: { email: string; name?: string | null; role?: string } } }",
    "  const user = session?.user",
    "  return (",
    "    <main className='min-h-screen bg-background text-foreground'>",
    "      <div className='mx-auto flex max-w-5xl flex-col gap-8 p-6 md:p-8 lg:p-10'>",
    "        <div className='flex flex-col gap-2'>",
    "          <div className='flex items-center justify-between gap-4'>",
    "            <h1 className='text-2xl font-semibold tracking-tight'>Dashboard</h1>",
    "            <div className='flex items-center gap-2'>",
    "              <Button variant='ghost' size='sm' asChild><Link to='/settings'>Settings</Link></Button>",
    "              <Button variant='outline' size='sm' asChild><Link to='/billing'>Billing</Link></Button>",
    "            </div>",
    "          </div>",
    "          <p className='text-sm text-muted-foreground max-w-[65ch]'>Welcome back. Manage your account, billing, and modules.</p>",
    "        </div>",
    "        <Separator />",
    "        <div className='grid grid-cols-1 gap-4 md:grid-cols-3'>",
    "          <Card className='md:col-span-2'>",
    "            <CardHeader>",
    "              <div className='flex items-center justify-between gap-3'>",
    "                <CardTitle className='text-base'>Profile</CardTitle>",
    "                <Badge variant='secondary' className='capitalize'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> {String(user?.role ?? 'user')}</span></Badge>",
    "              </div>",
    "              <CardDescription className='max-w-[60ch]'>Signed in as {String(user?.email ?? '')}. Name {String(user?.name ?? 'not set')}.</CardDescription>",
    "            </CardHeader>",
    "            <CardContent className='flex flex-col gap-3'>",
    "              <div className='flex flex-wrap gap-2'>",
    "                <Button variant='outline' size='sm' asChild><Link to='/settings'>Edit profile</Link></Button>",
    "                <Button variant='outline' size='sm' asChild><Link to='/billing'>Billing</Link></Button>",
    "                <Button variant='outline' size='sm' asChild><Link to='/admin'>Admin</Link></Button>",
    "              </div>",
    "            </CardContent>",
    "          </Card>",
    "          <Card>",
    "            <CardHeader><CardTitle className='text-base'>Quick actions</CardTitle></CardHeader>",
    "            <CardContent className='flex flex-col gap-2'>",
    "              <Button variant='outline' size='sm' asChild><Link to='/settings'>Security & 2FA</Link></Button>",
    "              <Button variant='outline' size='sm' asChild><Link to='/billing'>Manage billing</Link></Button>",
    "            </CardContent>",
    "          </Card>",
    "        </div>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleSettingsRouteTanstackContent(): string {
  return [
    "import * as React from 'react'",
    "import { createFileRoute, Link, redirect } from '@tanstack/react-router'",
    "import { createServerFn } from '@tanstack/react-start'",
    "import { getRequestHeaders } from '@tanstack/react-start/server'",
    "import { auth } from '@/server/auth'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, Button, Input, Badge, Separator, Alert, AlertTitle, AlertDescription } from '@/components/ui/card'",
    "",
    "const getSessionFn = createServerFn({ method: 'GET' }).handler(async () => {",
    "  const headers = getRequestHeaders() as unknown as Headers",
    "  const session = await (auth as unknown as { api: { getSession: (opts: { headers: Headers }) => Promise<{ user?: { email?: string; name?: string | null; role?: string } } | null> } }).api.getSession({ headers })",
    "  return session ?? null",
    "})",
    "",
    "export const Route = createFileRoute('/settings')({",
    "  beforeLoad: async () => {",
    "    const session = await getSessionFn()",
    "    if (!session?.user) throw redirect({ to: '/sign-in' })",
    "    return { session }",
    "  },",
    "  component: SettingsPage,",
    "})",
    "",
    "function SettingsPage(): React.JSX.Element {",
    "  const { session } = Route.useRouteContext() as { session: { user: { email: string; name?: string | null; role?: string } } }",
    "  const user = session?.user",
    "  return (",
    "    <main className='min-h-screen bg-background p-6 md:p-8'>",
    "      <div className='mx-auto max-w-5xl flex flex-col gap-8'>",
    "        <div className='flex flex-col gap-2'><h1 className='text-2xl font-semibold tracking-tight'>Settings</h1><p className='text-sm text-muted-foreground max-w-[65ch]'>Manage account and workspace preferences. TanStack protected via createServerFn + getRequestHeaders.</p></div>",
    "        <Separator />",
    "        <div className='grid gap-6 md:grid-cols-3'>",
    "          <Card className='md:col-span-2'><CardHeader><CardTitle className='text-base'>Profile</CardTitle><CardDescription className='max-w-[60ch]'>Signed in as {String(user?.email ?? '')}. Role {String(user?.role ?? 'user')}.</CardDescription></CardHeader><CardContent className='flex flex-col gap-4'><div className='flex flex-col gap-2'><span className='text-sm font-medium'>Name</span><Input defaultValue={String(user?.name ?? '')} readOnly /></div><div className='flex items-center gap-2'><Badge variant='secondary'>{String(user?.role ?? 'user')}</Badge><Badge variant='outline'>{String(user?.email ?? '')}</Badge></div><Alert><AlertTitle>Profile editing</AlertTitle><AlertDescription className='max-w-[60ch]'>Use authClient.updateUser from client components. Server route shows protected data via createServerFn pattern per Context7.</AlertDescription></Alert><div className='flex gap-2'><Button variant='outline' size='sm' asChild><Link to='/dashboard'>Dashboard</Link></Button><Button variant='outline' size='sm' asChild><Link to='/billing'>Billing</Link></Button></div></CardContent></Card>",
    "          <Card><CardHeader><CardTitle className='text-base'>Security</CardTitle></CardHeader><CardContent className='flex flex-col gap-2'><Button variant='outline' size='sm' asChild><Link to='/2fa'>Two-factor</Link></Button><Button variant='outline' size='sm' asChild><Link to='/forgot-password'>Reset password</Link></Button></CardContent></Card>",
    "        </div>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleBillingRouteTanstackContent(): string {
  return [
    "import * as React from 'react'",
    "import { createFileRoute, redirect, Link } from '@tanstack/react-router'",
    "import { createServerFn } from '@tanstack/react-start'",
    "import { getRequestHeaders } from '@tanstack/react-start/server'",
    "import { auth } from '@/server/auth'",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent, Badge, Button, Separator, Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyContent } from '@/components/ui/card'",
    "",
    "const getSessionFn = createServerFn({ method: 'GET' }).handler(async () => {",
    "  const headers = getRequestHeaders() as unknown as Headers",
    "  const session = await (auth as unknown as { api: { getSession: (opts: { headers: Headers }) => Promise<{ user?: { role?: string } } | null> } }).api.getSession({ headers })",
    "  return session ?? null",
    "})",
    "",
    "export const Route = createFileRoute('/billing')({",
    "  beforeLoad: async () => {",
    "    const session = await getSessionFn()",
    "    if (!session?.user) throw redirect({ to: '/sign-in' })",
    "    return { session }",
    "  },",
    "  component: BillingPage,",
    "})",
    "",
    "function BillingPage(): React.JSX.Element {",
    "  return (",
    "    <main className='min-h-screen bg-background p-6 md:p-8'>",
    "      <div className='mx-auto max-w-5xl flex flex-col gap-8'>",
    "        <div className='flex items-center justify-between gap-4'><div className='flex flex-col gap-2'><h1 className='text-2xl font-semibold tracking-tight'>Billing</h1><p className='text-sm text-muted-foreground max-w-[65ch]'>Flexible billing — any combo stripe, chargily EDAHABIA, paddle, polar. TanStack Start version.</p></div><Button size='sm' asChild><Link to='/dashboard'>Dashboard</Link></Button></div>",
    "        <Separator />",
    "        <Card><CardHeader><CardTitle className='text-base'>Subscriptions</CardTitle><CardDescription className='max-w-[60ch]'>Idempotent webhook handling, shared tables, oRPC contract-first. Flat src server/ + routes/ TanStack.</CardDescription></CardHeader><CardContent><Empty><EmptyHeader><EmptyTitle>No billing configured</EmptyTitle><EmptyDescription className='max-w-[60ch]'>Add a billing provider via ghostinit add billing. Stripe global, Chargily Algeria EDAHABIA/CIB, Paddle MoR 5%+50c, Polar metering.</EmptyDescription></EmptyHeader><EmptyContent><div className='flex gap-2'><Badge variant='secondary'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> stripe</span></Badge><Badge variant='secondary'><span className='flex items-center gap-1.5'><span className='size-1.5 rounded-full bg-primary' /> chargily</span></Badge><Badge variant='secondary'>paddle</Badge><Badge variant='secondary'>polar</Badge></div></EmptyContent></Empty></CardContent></Card>",
    "      </div>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleNotFoundRouteTanstackContent(): string {
  return [
    "import * as React from 'react'",
    "import { createFileRoute, Link } from '@tanstack/react-router'",
    "import { Button, Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'",
    "",
    "export const Route = createFileRoute('/$notFound')({ component: NotFoundPage })",
    "function NotFoundPage(): React.JSX.Element {",
    "  return (",
    "    <main className='min-h-screen bg-background flex items-center justify-center p-6'>",
    "      <Card className='w-full max-w-[420px] shadow-sm'>",
    "        <CardHeader><CardTitle className='text-2xl tracking-tight'>Page not found</CardTitle><CardDescription className='max-w-[60ch]'>The page you are looking for does not exist or was moved.</CardDescription></CardHeader>",
    "        <CardContent className='flex flex-col gap-3'><Button asChild><Link to='/'>Back to home</Link></Button></CardContent>",
    "      </Card>",
    "    </main>",
    "  )",
    "}",
    "",
  ].join("\n");
}
