export const contractFoundation = {
  tokens: {
    format: "oklch",
    defaultTheme: "light",
    themes: ["light", "dark"],
    names: [
      "background",
      "foreground",
      "card",
      "card-foreground",
      "popover",
      "popover-foreground",
      "primary",
      "primary-foreground",
      "secondary",
      "secondary-foreground",
      "muted",
      "muted-foreground",
      "accent",
      "accent-foreground",
      "destructive",
      "destructive-foreground",
      "border",
      "input",
      "ring",
      "success",
      "warning",
      "code",
      "code-foreground",
      "scrim",
      "radius",
    ],
    contrast: {
      minimumTextRatio: 4.5,
      darkPrimaryForeground: "oklch(0.1949 0.0155 261.6)",
      lightPrimaryForeground: "oklch(0.9965 0.0017 247.8)",
    },
  },
  typography: {
    sans: 'var(--font-geist-sans, -apple-system), BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
    mono: 'var(--font-geist-mono, ui-monospace), SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    bodyRem: 0.9375,
    scaleRatio: 1.2,
    proseMaxCharacters: 65,
    headingTrackingEm: -0.025,
  },
  spacing: {
    unitRem: 0.25,
    controlHeightRem: 2.5,
    topBarHeightRem: 4,
    sidebarWidthRem: 14.5,
    contentMaxRem: 72,
  },
  radius: {
    baseRem: 0.75,
    control: "md",
    surface: "lg",
    status: "sm",
  },
  elevation: {
    default: "border",
    surfaceShadow: "shadow-surface",
    overlayShadow: "shadow-modal",
  },
  semanticStates: [
    { id: "default", required: true },
    { id: "hover", required: true },
    { id: "focus", required: true },
    { id: "active", required: true },
    { id: "disabled", required: true },
    { id: "selected", required: true },
    { id: "loading", required: true },
    { id: "error", required: true },
    { id: "warning", required: true },
    { id: "success", required: true },
    { id: "info", required: true },
  ],
  iconLibrary: {
    web: "lucide-react",
    electron: "lucide-react",
    native: "lucide-react-native",
    sizing: "component-owned",
    buttonPositionAttribute: "data-icon",
  },
  density: {
    default: "comfortable",
    bodySize: "text-[0.9375rem]",
    metadataSize: "xs",
    controlHeight: "h-10",
  },
  motion: {
    fastMs: 150,
    standardMs: 200,
    easing: "cubic-bezier(0.25, 1, 0.5, 1)",
    reducedMotion: "required",
    purpose: "state-only",
  },
  shell: {
    topBar: "h-16 bg-card px-5 sm:px-8 lg:px-10",
    sidebar: "w-58 border-e bg-sidebar",
    content: "max-w-6xl",
    nestedCards: "forbidden",
  },
  navigation: {
    patterns: ["top-bar", "side-nav", "breadcrumb", "tabs"],
    logicalDirections: "required",
    customScrollbars: "forbidden",
  },
  forms: {
    architecture: "tanstack-form",
    layout: "FieldGroup/Field",
    validation: "data-invalid-and-aria-invalid",
    disabled: "data-disabled-and-native-disabled",
  },
  feedback: {
    loading: "skeleton",
    empty: "teaching-empty-state",
    toast: "theme-aware",
    errors: "inline-before-overlay",
  },
} as const;
