export const contractFoundation = {
  tokens: {
    format: "oklch",
    defaultTheme: "dark",
    themes: ["dark", "light"],
    names: [
      "background",
      "foreground",
      "card",
      "card-foreground",
      "popover",
      "popover-foreground",
      "primary",
      "primary-foreground",
      "secondary",
      "secondary-foreground",
      "muted",
      "muted-foreground",
      "accent",
      "accent-foreground",
      "destructive",
      "destructive-foreground",
      "border",
      "input",
      "ring",
      "success",
      "warning",
      "code",
      "code-foreground",
      "radius",
    ],
    contrast: {
      minimumTextRatio: 4.5,
      darkPrimaryForeground: "oklch(0.12 0.02 264)",
      lightPrimaryForeground: "oklch(0.99 0.005 264)",
    },
  },
  typography: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    bodyRem: 0.875,
    scaleRatio: 1.2,
    proseMaxCharacters: 65,
    headingTrackingEm: -0.025,
  },
  spacing: {
    unitRem: 0.25,
    controlHeightRem: 2.25,
    topBarHeightRem: 3.5,
    sidebarWidthRem: 16,
    contentMaxRem: 72,
  },
  radius: {
    baseRem: 0.5,
    control: "md",
    surface: "lg",
    status: "full",
  },
  elevation: {
    default: "border",
    surfaceShadow: "none",
    overlayShadow: "shadow-lg",
  },
  semanticStates: [
    { id: "default", required: true },
    { id: "hover", required: true },
    { id: "focus", required: true },
    { id: "active", required: true },
    { id: "disabled", required: true },
    { id: "selected", required: true },
    { id: "loading", required: true },
    { id: "error", required: true },
    { id: "warning", required: true },
    { id: "success", required: true },
    { id: "info", required: true },
  ],
  iconLibrary: {
    web: "lucide-react",
    electron: "lucide-react",
    native: "lucide-react-native",
    sizing: "component-owned",
    buttonPositionAttribute: "data-icon",
  },
  density: {
    default: "compact",
    bodySize: "sm",
    metadataSize: "xs",
    controlHeight: "h-9",
  },
  motion: {
    fastMs: 150,
    standardMs: 200,
    easing: "cubic-bezier(0.25, 1, 0.5, 1)",
    reducedMotion: "required",
    purpose: "state-only",
  },
  shell: {
    topBar: "h-14 max-w-6xl px-6",
    sidebar: "w-64 border-e bg-card",
    content: "max-w-6xl",
    nestedCards: "forbidden",
  },
  navigation: {
    patterns: ["top-bar", "side-nav", "breadcrumb", "tabs"],
    logicalDirections: "required",
    customScrollbars: "forbidden",
  },
  forms: {
    architecture: "tanstack-form",
    layout: "FieldGroup/Field",
    validation: "data-invalid-and-aria-invalid",
    disabled: "data-disabled-and-native-disabled",
  },
  feedback: {
    loading: "skeleton",
    empty: "teaching-empty-state",
    toast: "theme-aware",
    errors: "inline-before-overlay",
  },
} as const;
