// @allow-long 667: single-mode Expo composition keeps capability closure and flat-path ownership together
import { file, type TemplateFile } from "../../../shared.js";
import { nativeQueryRegressionFile } from "../../../apps/fragments/expo/query-tests.js";
import { authRouteBoundaryCode } from "../../../apps/fragments/api/auth-boundary.js";
import { singleKernelTypesContent } from "../fragments/kernel.js";
import type { BillingProviderName, AddonInstallerMap } from "../../../../lib/addons.js";
import type { RootSecrets } from "../../../root.js";
import { servicesFiles } from "../../../services.js";
import { billingFiles } from "../../../billing-generator.js";
import { billingMoneyFile } from "../../../billing/ui/money.js";
import { emailFiles } from "../../../email.js";
import { eveFiles as genEveFiles } from "../../../eve.js";

import { singlePackageJsonExpo } from "../package.js";
import { filteredEnvExample, filteredEnvLocal } from "../config.js";
import { singleEnvFiles } from "../fragments/env.js";
import {
  expoAppJsonContent,
  babelConfigContent,
  metroConfigContent,
  expoEnvDtsContent,
} from "../../../apps/expo-core.js";
import { expoRootLayoutContent } from "../../../apps/fragments/expo/layout.js";
import { canonicalQueryAuthHookContent } from "../../../apps/fragments/query-auth.js";
import { expoDashboardPageContent } from "../../../apps/expo-pages.js";
import {
  expoFullSettingsContent,
  expoEmailFlowFiles,
  expoIdentityWorkspaceFiles,
} from "../../../apps/fragments/identity-workspace/index.js";
import { expoAnalyticsFile } from "../../../apps/fragments/expo/analytics.js";
import {
  eveProtocolAcceptanceFile,
  eveProtocolFile,
  expoEveFiles,
} from "../../../apps/fragments/eve/index.js";
import { platformI18nFiles } from "../../../apps/fragments/platform-i18n.js";
import { buildExpoMarketingContent } from "../../../apps/fragments/expo/marketing.js";
import {
  expoSignInContent,
  expoSignUpContent,
  expoForgotPasswordContent,
  expoResetPasswordContent,
  expoTwoFactorContent,
} from "../../../apps/fragments/expo/auth.js";
import {
  expoSettingsContent,
  expoNotFoundContent,
} from "../../../apps/fragments/expo/dashboard.js";
import { expoBillingContent } from "../../../apps/fragments/expo/billing.js";
import { mobileGlobalCssContent } from "../../../apps/fragments/css.js";
import { rnrTextContent } from "../../../apps/fragments/expo/rnr/text.js";
import { rnrButtonContent } from "../../../apps/fragments/expo/rnr/button.js";
import { rnrCardContent } from "../../../apps/fragments/expo/rnr/card.js";
import { rnrInputContent } from "../../../apps/fragments/expo/rnr/input.js";
import { rnrLabelContent } from "../../../apps/fragments/expo/rnr/label.js";
import { rnrBadgeContent } from "../../../apps/fragments/expo/rnr/badge.js";
import { rnrAvatarContent } from "../../../apps/fragments/expo/rnr/avatar.js";
import { rnrTabsContent } from "../../../apps/fragments/expo/rnr/tabs.js";
import { rnrDialogContent } from "../../../apps/fragments/expo/rnr/dialog.js";
import { expoAuthClientContent, expoOrpcClientContent } from "../../../apps/fragments/expo/orpc.js";
import {
  expoNativeQueryClientContent,
  expoOfflineHookContent,
  expoPushHookContent,
} from "../../../apps/fragments/expo/native.js";
import { convexClientProviderExpoContent } from "../../../apps/fragments/convex-providers.js";
import {
  expoHeaderContent,
  expoSignOutButtonContent,
} from "../../../apps/fragments/expo/header.js";
import { webhookContent } from "../../../billing/webhooks/factory.js";

import { serverAuthSingle, serverAuthSingleConvex } from "../server/auth.js";
import {
  serverDbIndexSingle,
  serverDbIndexSingleConvex,
  serverDbIndexSingleNone,
  serverDbAuthSchemaStub,
  serverDrizzleConfigSingle,
  serverObservabilitySingle,
  libUtils,
} from "../server/db.js";
import { hasAddon } from "../../../../lib/addons.js";
import { convexDatabaseFiles } from "../../../database/convex.js";
import {
  singleApiContextContent,
  singleApiHealthProcedureContent,
  singleApiMeProcedureContent,
  singleApiContractContent,
  singleApiRouterContent,
  singleApiIndexContent,
  singleApiOpenapiContent,
  singleOrpcRequestSecurityContent,
} from "../api/routes.js";
import { singleApiSupportFiles } from "../api/admin.js";
import { singleBillingApiFiles } from "../api/billing.js";
import { gitignoreSingle, readmeSingle } from "../fragments/docs.js";
import { themeCssContent } from "../../../ui/theme.js";
import * as v from "../../../versions.js";

function uniwindTypesContent(): string {
  return `// Generated by Uniwind - do not edit
// This file is auto-generated when running expo start
/// <reference types="uniwind/types" />
declare module "uniwind" {}
`;
}

function singleExpoTsConfigContent(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2024",
          lib: ["ES2024", "DOM", "DOM.Iterable"],
          jsx: "react-native",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          incremental: true,
          paths: {
            "@/*": ["./src/*"],
            "@/server/*": ["./src/server/*"],
            "@/components/*": ["./src/components/*"],
            "@/lib/*": ["./src/lib/*"],
            "@/hooks/*": ["./src/hooks/*"],
          },
          types: ["expo/types", "bun-types", "node"],
        },
        include: [
          "**/*.ts",
          "**/*.tsx",
          ".expo/types/**/*.ts",
          "expo-env.d.ts",
          "uniwind-types.d.ts",
          "global.css",
          "app/**/*",
          "src/**/*",
        ],
        exclude: ["node_modules", ".expo", "dist"],
      },
      null,
      2,
    ) + "\n"
  );
}

function expoAuthApiContent(): string {
  return [
    'import { auth } from "@/server/auth";',
    "",
    authRouteBoundaryCode(false),
    "",
    'const allowedAuthMethods = new Set(["GET", "POST", "PUT", "PATCH", "DELETE"]);',
    "",
    "async function handle(request: Request): Promise<Response> {",
    "  if (!allowedAuthMethods.has(request.method)) {",
    '    return new Response("Method not allowed", { status: 405 });',
    "  }",
    "  const directPrivilegedRejection = rejectDirectPrivilegedAuthRequest(request);",
    "  if (directPrivilegedRejection) return directPrivilegedRejection;",
    "  const preparedAuthRequest = prepareAuthRequestForRuntime(request);",
    "  if (preparedAuthRequest.rejection) return preparedAuthRequest.rejection;",
    "  return auth.handler(preparedAuthRequest.request);",
    "}",
    "",
    "export const GET = handle;",
    "export const POST = handle;",
    "export const PUT = handle;",
    "export const PATCH = handle;",
    "export const DELETE = handle;",
    "",
  ].join("\n");
}

function expoRpcApiContent(): string {
  return [
    'import { RPCHandler } from "@orpc/server/fetch";',
    'import { OpenAPIHandler } from "@orpc/openapi/fetch";',
    'import { appRouter, createContext, rejectUnsafeOrpcRequest } from "@/server/api";',
    "",
    "const rpcHandler = new RPCHandler(appRouter);",
    "const openapiHandler = new OpenAPIHandler(appRouter);",
    "",
    "async function handle(request: Request): Promise<Response> {",
    "  const requestBoundaryRejection = rejectUnsafeOrpcRequest(request);",
    "  if (requestBoundaryRejection) return requestBoundaryRejection;",
    "  const context = await createContext(request.headers);",
    '  const rpcResult = await rpcHandler.handle(request, { prefix: "/api/rpc", context });',
    "  if (rpcResult.matched && rpcResult.response) {",
    "    const response = rpcResult.response;",
    '    response.headers.set("X-Content-Type-Options", "nosniff");',
    '    response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");',
    "    return response;",
    "  }",
    "  const openApiResult = await openapiHandler.handle(request, { context });",
    "  if (openApiResult.matched && openApiResult.response) {",
    "    const response = openApiResult.response;",
    '    response.headers.set("X-Content-Type-Options", "nosniff");',
    '    response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");',
    "    return response;",
    "  }",
    '  return new Response("Not found", { status: 404 });',
    "}",
    "",
    "export async function GET(req: Request): Promise<Response> { return handle(req); }",
    "export async function POST(req: Request): Promise<Response> { return handle(req); }",
    "export async function PUT(req: Request): Promise<Response> { return handle(req); }",
    "export async function PATCH(req: Request): Promise<Response> { return handle(req); }",
    "export async function DELETE(req: Request): Promise<Response> { return handle(req); }",
    "",
  ].join("\n");
}

function expoHealthApiContent(): string {
  return [
    "export async function GET(): Promise<Response> {",
    '  const body = JSON.stringify({ status: "ok", ok: true, time: new Date().toISOString() });',
    "  return new Response(body, {",
    "    status: 200,",
    "    headers: {",
    '      "Content-Type": "application/json",',
    '      "X-Content-Type-Options": "nosniff",',
    '      "Referrer-Policy": "strict-origin-when-cross-origin",',
    "    },",
    "  });",
    "}",
    "",
  ].join("\n");
}

function expoOpenapiApiContent(): string {
  return [
    'import { generateOpenAPISpec } from "@/server/api/openapi";',
    "",
    "export async function GET(): Promise<Response> {",
    '  if (process.env.NODE_ENV === "production") {',
    '    return new Response("Not found", { status: 404 });',
    "  }",
    "  const spec = await generateOpenAPISpec();",
    '  return new Response(JSON.stringify(spec), { headers: { "Content-Type": "application/json" } });',
    "}",
    "",
  ].join("\n");
}

function expoStripeWebhook(isConvex = false): string {
  return webhookContent(
    "stripe",
    "next",
    "single",
    isConvex ? "convex" : "postgres",
    "app/api/webhooks/stripe+api.ts",
  ).content;
}
function expoChargilyWebhook(isConvex = false): string {
  return webhookContent(
    "chargily",
    "next",
    "single",
    isConvex ? "convex" : "postgres",
    "app/api/webhooks/chargily+api.ts",
  ).content;
}
function expoPaddleWebhook(isConvex = false): string {
  return webhookContent(
    "paddle",
    "next",
    "single",
    isConvex ? "convex" : "postgres",
    "app/api/webhooks/paddle+api.ts",
  ).content;
}
function expoPolarWebhook(isConvex = false): string {
  return webhookContent(
    "polar",
    "next",
    "single",
    isConvex ? "convex" : "postgres",
    "app/api/webhooks/polar+api.ts",
  ).content;
}

function expoUseAuthHook(): string {
  return `import { authClient } from "../lib/auth-client";

export function useAuth() {
  const { data: session, isPending, error, refetch } = authClient.useSession();

  return {
    session: session ?? null,
    user: session?.user ?? null,
    isPending,
    isAuthenticated: !!session?.user,
    error: error ?? null,
    refetch,
  };
}
`;
}

function expoUseBillingHook(): string {
  return `import * as React from "react";
import type { BillingSubscription, UseBillingReturn } from "@/lib/kernel";
import { orpcClient } from "@/lib/orpc";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function optionalString(value: unknown): string | null | undefined {
  return value === null || typeof value === "string" ? value : undefined;
}

function toBillingSubscription(value: unknown): BillingSubscription | undefined {
  if (!isRecord(value)) return undefined;
  const id = typeof value.id === "string" ? value.id : typeof value._id === "string" ? value._id : null;
  if (!id || typeof value.provider !== "string" || typeof value.status !== "string") return undefined;
  return {
    id,
    provider: value.provider,
    status: value.status,
    currentPeriodEnd: optionalString(value.currentPeriodEnd),
    priceId: optionalString(value.priceId),
  };
}

export function useBilling(): UseBillingReturn {
  const [subscriptions, setSubscriptions] = React.useState<BillingSubscription[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const refresh = React.useCallback(async (): Promise<void> => {
    setLoading(true);
    setError(null);
    try {
      const data = await orpcClient.billing.subscriptions();
      setSubscriptions(data.subscriptions.flatMap((value) => {
        const subscription = toBillingSubscription(value);
        return subscription ? [subscription] : [];
      }));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load billing");
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void refresh();
  }, [refresh]);

  const hasActiveSubscription = React.useMemo(
    () => subscriptions.some((s) => s.status === "active" || s.status === "trialing"),
    [subscriptions],
  );

  return { subscriptions, loading, error, refresh, hasActiveSubscription, isLoading: loading };
}
`;
}

function expoUseCopyHook(): string {
  return `import * as React from "react";
import * as Clipboard from "expo-clipboard";
import type { UseCopyReturn } from "@/lib/kernel";

export function useCopy(): UseCopyReturn {
  const [copied, setCopied] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const timeoutRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  React.useEffect(() => {
    return () => {
      if (timeoutRef.current !== null) clearTimeout(timeoutRef.current);
    };
  }, []);

  const copy = React.useCallback(async (text: string): Promise<boolean> => {
    setError(null);
    try {
      await Clipboard.setStringAsync(text);
      setCopied(true);
      if (timeoutRef.current !== null) clearTimeout(timeoutRef.current);
      timeoutRef.current = setTimeout(() => setCopied(false), 2000);
      return true;
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Copy failed");
      return false;
    }
  }, []);

  return { copy, copied, error };
}
`;
}

interface SingleExpoCapabilities {
  hasApi: boolean;
  hasAuth: boolean;
  hasBilling: boolean;
  isConvex: boolean;
  isNone: boolean;
  hasEmail: boolean;
  hasAnalytics: boolean;
  hasMessaging: boolean;
  hasStorage: boolean;
  hasEve: boolean;
  hasI18n: boolean;
  hasNotifications: boolean;
  hasFeatureFlags: boolean;
  hasJobs: boolean;
  hasPdf: boolean;
}

function singleExpoPackageContent(
  projectName: string,
  runtime: "node" | "bun",
  effectiveBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  capabilities: SingleExpoCapabilities,
): string {
  const manifest = JSON.parse(
    singlePackageJsonExpo(
      projectName,
      runtime,
      effectiveBilling,
      hasEve,
      hasI18n,
      capabilities.isConvex,
      capabilities.isNone,
      capabilities.hasAnalytics,
      capabilities.hasNotifications,
    ),
  ) as {
    dependencies: Record<string, string>;
    devDependencies: Record<string, string>;
    scripts: Record<string, string>;
  };

  if (capabilities.hasAuth && !capabilities.isConvex) {
    manifest.dependencies["@better-auth/passkey"] = `^${v.auth["@better-auth/passkey"]}`;
  }
  if (capabilities.hasEmail) {
    manifest.dependencies["react-email"] = `^${v.email["react-email"]}`;
    manifest.dependencies.resend = `^${v.email.resend}`;
  } else {
    delete manifest.dependencies["react-email"];
    delete manifest.dependencies.resend;
  }
  delete manifest.dependencies["posthog-js"];
  delete manifest.dependencies["posthog-node"];
  if (!capabilities.hasAnalytics) delete manifest.dependencies["posthog-react-native"];
  if (capabilities.hasMessaging) {
    manifest.dependencies["expo-file-system"] = `~${v.expo["expo-file-system"]}`;
    manifest.dependencies["expo-sharing"] = `~${v.expo["expo-sharing"]}`;
  }

  if (!capabilities.hasApi) {
    for (const dependency of [
      "@orpc/client",
      "@orpc/contract",
      "@orpc/openapi",
      "@orpc/react-query",
      "@orpc/server",
      "@orpc/zod",
    ]) {
      delete manifest.dependencies[dependency];
    }
  } else {
    // Single Expo keeps its API/services in the root package. Those server
    // modules import the boundary sentinel directly, so the root must own it.
    manifest.dependencies["server-only"] = `^${v.runtime["server-only"]}`;
  }
  if (!capabilities.hasAuth) {
    for (const dependency of [
      "@better-auth/expo",
      "@better-auth/passkey",
      "@convex-dev/better-auth",
      "@tanstack/react-form",
      "better-auth",
      "expo-network",
    ]) {
      delete manifest.dependencies[dependency];
    }
  }
  if (capabilities.isNone) {
    delete manifest.dependencies["drizzle-orm"];
    delete manifest.dependencies.pg;
    delete manifest.devDependencies["@types/pg"];
    delete manifest.devDependencies["drizzle-kit"];
    delete manifest.scripts["db:generate"];
    delete manifest.scripts["db:migrate"];
    delete manifest.scripts["db:push"];
  }

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function singleMobileGlobalCssContent(): string {
  return mobileGlobalCssContent().replace(
    '@import "@repo/ui/theme.css";',
    '@import "./src/styles/theme.css";',
  );
}

function singleHeaderContent(
  hasBilling: boolean,
  hasI18n: boolean,
  hasEve: boolean,
  hasPdf: boolean,
): string {
  const content = expoHeaderContent(hasI18n, hasEve, hasPdf);
  if (hasBilling) return content;
  const billingLabel = hasI18n ? '{t("billing")}' : "Billing";
  return content.replace(
    `              <Link href="/billing" asChild><Button variant="ghost" size="sm"><Text>${billingLabel}</Text></Button></Link>\n`,
    "",
  );
}

function singleExpoScheme(projectName: string): string {
  if (projectName === "__PROJECT_NAME__") return "myapp";
  return projectName.toLowerCase().replace(/[^a-z0-9]/g, "") || "app";
}

export function buildExpoFiles(
  projectName: string,
  runtime: "node" | "bun",
  effectiveBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  secrets: RootSecrets,
  addonMap: AddonInstallerMap,
): TemplateFile[] {
  const isConvex = hasAddon(addonMap, "convex");
  const isNone = hasAddon(addonMap, "database:none");
  const hasBilling = effectiveBilling.length > 0 || hasAddon(addonMap, "billing");
  const hasApi = hasAddon(addonMap, "api") || hasBilling;
  const hasAuth = hasAddon(addonMap, "auth") || hasBilling;
  const hasEmail = hasAddon(addonMap, "email");
  const hasAnalytics = hasAddon(addonMap, "analytics");
  const hasMessaging = hasAddon(addonMap, "messaging");
  // Single native mode has no generated or selected backend host. Its server-backed
  // Family C clients remain unreachable until a remote-host contract exists.
  const hasStorage = false;
  const effectiveHasEve = hasEve || hasAddon(addonMap, "eve");
  const effectiveHasI18n = hasI18n || hasAddon(addonMap, "i18n");
  const hasNotifications = false;
  const hasFeatureFlags = false;
  const hasJobs = false;
  const hasPdf = hasAddon(addonMap, "pdf");
  const hasEveClient =
    effectiveHasEve && hasApi && hasAuth && !hasAddon(addonMap, "tanstack-start") && !isNone;
  const capabilities: SingleExpoCapabilities = {
    hasApi,
    hasAuth,
    hasBilling,
    isConvex,
    isNone,
    hasEmail,
    hasAnalytics,
    hasMessaging,
    hasStorage,
    hasEve: hasEveClient,
    hasI18n: effectiveHasI18n,
    hasNotifications,
    hasFeatureFlags,
    hasJobs,
    hasPdf,
  };
  const files: TemplateFile[] = [];

  files.push(
    file(
      "package.json",
      singleExpoPackageContent(
        projectName,
        runtime,
        effectiveBilling,
        effectiveHasEve,
        effectiveHasI18n,
        capabilities,
      ),
    ),
  );
  files.push(file("app.json", expoAppJsonContent(projectName, capabilities)));
  files.push(file("babel.config.js", babelConfigContent()));
  files.push(file("metro.config.js", metroConfigContent()));
  files.push(file("global.css", singleMobileGlobalCssContent()));
  files.push(file("src/styles/theme.css", themeCssContent()));
  files.push(file("uniwind-types.d.ts", uniwindTypesContent()));
  files.push(file("expo-env.d.ts", expoEnvDtsContent()));
  files.push(file("tsconfig.json", singleExpoTsConfigContent()));
  files.push(
    file(
      "tests/smoke.test.ts",
      `import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

test("declares an Expo Router entrypoint and native quality scripts", () => {
  const manifest = JSON.parse(readFileSync(resolve(import.meta.dir, "../package.json"), "utf8"));
  expect(manifest.main).toBe("expo-router/entry");
  expect(manifest.scripts.typecheck).toBe("tsc --noEmit");
  expect(manifest.scripts.lint).toBe("oxlint --deny-warnings .");
});
`,
    ),
  );

  files.push(file("app/_layout.tsx", expoRootLayoutContent(capabilities)));
  files.push(
    file(
      "app/index.tsx",
      buildExpoMarketingContent({
        hasAuth,
        hasI18n: effectiveHasI18n,
        reduceUnauthenticated: true,
      }),
    ),
  );
  if (hasAuth) {
    files.push(file("app/(auth)/sign-in.tsx", expoSignInContent(hasEmail, effectiveHasI18n)));
    files.push(file("app/(auth)/sign-up.tsx", expoSignUpContent(effectiveHasI18n, hasEmail)));
    if (hasEmail) {
      files.push(
        file("app/(auth)/forgot-password.tsx", expoForgotPasswordContent(effectiveHasI18n)),
      );
      files.push(file("app/(auth)/reset-password.tsx", expoResetPasswordContent(effectiveHasI18n)));
    }
    if (hasEmail) files.push(file("app/2fa.tsx", expoTwoFactorContent(effectiveHasI18n)));
    files.push(file("app/dashboard.tsx", expoDashboardPageContent(capabilities)));
    files.push(
      file(
        "app/settings.tsx",
        capabilities.hasApi
          ? expoFullSettingsContent("single", effectiveHasI18n, hasEmail)
          : expoSettingsContent(effectiveHasI18n, hasEmail),
      ),
    );
    if (capabilities.hasApi) files.push(...expoIdentityWorkspaceFiles("single", effectiveHasI18n));
    if (hasEmail) files.push(...expoEmailFlowFiles("single", effectiveHasI18n));
  }
  if (hasBilling)
    files.push(
      billingMoneyFile("src"),
      file("app/billing.tsx", expoBillingContent("single", effectiveBilling, effectiveHasI18n)),
    );
  files.push(file("app/+not-found.tsx", expoNotFoundContent(effectiveHasI18n)));

  if (hasAuth) {
    files.push(
      file(
        "src/lib/auth-client.ts",
        expoAuthClientContent(projectName, isConvex, "single", hasEmail),
      ),
    );
  }
  if (hasApi) {
    files.push(file("src/server/api/request-security.ts", singleOrpcRequestSecurityContent()));
    files.push(
      file(
        "src/lib/orpc.ts",
        expoOrpcClientContent({
          routerImport: "@/server/api",
          rpcPath: "/api/rpc",
          hasAuth,
          mode: "single",
        }),
      ),
    );
  }
  files.push(file("src/lib/query-client.ts", expoNativeQueryClientContent()));
  files.push(nativeQueryRegressionFile(""));
  files.push(file("src/hooks/use-offline.ts", expoOfflineHookContent()));
  if (hasAuth && hasApi) {
    files.push(file("src/lib/query-auth-scope.ts", canonicalQueryAuthHookContent()));
  }
  if (hasAnalytics) files.push(expoAnalyticsFile("single"));
  if (hasEveClient) {
    files.push(
      eveProtocolFile("expo", "single"),
      ...expoEveFiles("single", effectiveHasI18n),
      eveProtocolAcceptanceFile("expo", "single"),
    );
  }
  if (effectiveHasI18n) files.push(...platformI18nFiles("expo", "single"));
  if (hasNotifications) files.push(file("src/hooks/use-push.ts", expoPushHookContent()));
  if (isConvex) {
    files.push(
      file(
        "src/components/convex-client-provider.tsx",
        convexClientProviderExpoContent(hasAuth, "single"),
      ),
    );
  }
  files.push(file("src/lib/utils.ts", libUtils()));
  files.push(file("src/components/ui/text.tsx", rnrTextContent()));
  files.push(file("src/components/ui/button.tsx", rnrButtonContent()));
  files.push(file("src/components/ui/card.tsx", rnrCardContent()));
  files.push(file("src/components/ui/input.tsx", rnrInputContent()));
  files.push(file("src/components/ui/label.tsx", rnrLabelContent()));
  files.push(file("src/components/ui/badge.tsx", rnrBadgeContent()));
  files.push(file("src/components/ui/avatar.tsx", rnrAvatarContent()));
  files.push(file("src/components/ui/tabs.tsx", rnrTabsContent()));
  files.push(file("src/components/ui/dialog.tsx", rnrDialogContent()));
  if (hasAuth) {
    files.push(
      file(
        "src/components/header.tsx",
        singleHeaderContent(hasBilling, effectiveHasI18n, hasEveClient, capabilities.hasPdf),
      ),
    );
    files.push(
      file("src/components/sign-out-button.tsx", expoSignOutButtonContent(effectiveHasI18n)),
    );
    files.push(file("src/hooks/use-auth.ts", expoUseAuthHook()));
  }
  if (hasBilling) files.push(file("src/hooks/use-billing.ts", expoUseBillingHook()));
  files.push(file("src/hooks/use-copy.ts", expoUseCopyHook()));

  if (isConvex) {
    if (hasAuth) {
      files.push(file("src/server/auth/index.ts", serverAuthSingleConvex()));
      files.push(file("src/server/db/index.ts", serverDbIndexSingleConvex()));
    }
    const convexAll = convexDatabaseFiles(projectName, runtime, "single", {
      auth: hasAuth,
      billing: hasBilling,
      email: hasEmail,
      i18n: effectiveHasI18n,
      mobile: true,
      posts: hasAuth,
    });
    for (const cf of convexAll) {
      if (cf.path.startsWith("convex/") || cf.path === "convex.json") {
        files.push({
          ...cf,
          content: cf.content.replace(/__APP_SCHEME__/g, singleExpoScheme(projectName)),
        });
      }
    }
  } else if (hasAuth) {
    files.push(
      file(
        "src/server/auth/index.ts",
        serverAuthSingle(hasEmail, { expoScheme: singleExpoScheme(projectName) }),
      ),
    );
    if (isNone) {
      files.push(file("src/server/db/index.ts", serverDbIndexSingleNone()));
    } else {
      files.push(file("src/server/db/index.ts", serverDbIndexSingle(hasBilling, hasAuth)));
      files.push(file("src/server/db/schema/auth.ts", serverDbAuthSchemaStub()));
      files.push(file("drizzle.config.ts", serverDrizzleConfigSingle()));
    }
  }
  files.push(file("src/lib/kernel.ts", singleKernelTypesContent()));
  if (hasAuth || hasApi) {
    files.push(file("src/server/observability/index.ts", serverObservabilitySingle()));
  }
  if (hasApi) {
    files.push(
      file(
        "src/server/api/context.ts",
        singleApiContextContent(isConvex, hasAuth, { auth: hasAuth }),
      ),
    );
    files.push(file("src/server/api/procedures/health.ts", singleApiHealthProcedureContent()));
    if (hasAuth) files.push(file("src/server/api/procedures/me.ts", singleApiMeProcedureContent()));
    files.push(
      file(
        "src/server/api/contract.ts",
        singleApiContractContent(false, hasBilling, { auth: hasAuth }),
      ),
    );
    files.push(
      file(
        "src/server/api/router.ts",
        singleApiRouterContent(false, hasBilling, { auth: hasAuth }),
      ),
    );
    files.push(file("src/server/api/index.ts", singleApiIndexContent(false)));
    files.push(file("src/server/api/openapi.ts", singleApiOpenapiContent()));
    if (hasAuth) files.push(...singleApiSupportFiles());
    if (hasBilling) files.push(...singleBillingApiFiles());
  }

  if (hasAuth) files.push(file("app/api/auth/[...auth]+api.ts", expoAuthApiContent()));
  if (hasApi) {
    files.push(file("app/api/rpc/[...path]+api.ts", expoRpcApiContent()));
    files.push(file("app/api/health+api.ts", expoHealthApiContent()));
    files.push(file("app/api/openapi+api.ts", expoOpenapiApiContent()));
  }

  if (effectiveBilling.includes("stripe"))
    files.push(file("app/api/webhooks/stripe+api.ts", expoStripeWebhook(isConvex)));
  if (effectiveBilling.includes("chargily"))
    files.push(file("app/api/webhooks/chargily+api.ts", expoChargilyWebhook(isConvex)));
  if (effectiveBilling.includes("paddle"))
    files.push(file("app/api/webhooks/paddle+api.ts", expoPaddleWebhook(isConvex)));
  if (effectiveBilling.includes("polar"))
    files.push(file("app/api/webhooks/polar+api.ts", expoPolarWebhook(isConvex)));
  if (effectiveBilling.length === 0 && hasAddon(addonMap, "billing")) {
    files.push(file("app/api/webhooks/stripe+api.ts", expoStripeWebhook(isConvex)));
    files.push(file("app/api/webhooks/chargily+api.ts", expoChargilyWebhook(isConvex)));
    files.push(file("app/api/webhooks/paddle+api.ts", expoPaddleWebhook(isConvex)));
    files.push(file("app/api/webhooks/polar+api.ts", expoPolarWebhook(isConvex)));
  }

  files.push(gitignoreSingle());
  files.push(readmeSingle(projectName, false, { apps: ["mobile"] }));
  const dbType = isConvex ? "convex" : isNone ? "none" : "postgres";
  files.push(
    filteredEnvExample(projectName, secrets, effectiveBilling, hasEmail, runtime, dbType, {
      framework: "nextjs",
      hasWeb: false,
      hasMobile: true,
      hasEve: effectiveHasEve,
    }),
  );
  files.push(
    filteredEnvLocal(
      projectName,
      secrets,
      effectiveBilling,
      runtime,
      dbType,
      {
        framework: "nextjs",
        hasWeb: false,
        hasMobile: true,
        hasEve: effectiveHasEve,
      },
      hasEmail,
    ),
  );
  files.push(...singleEnvFiles(addonMap, "expo", hasEmail));

  if (hasApi) {
    files.push(...servicesFiles({ mode: "single", runtime, addons: addonMap }, runtime));
  }

  if (hasBilling) {
    const billingRaw = billingFiles({ mode: "single", runtime, addons: addonMap }, runtime);
    const billingServerOnly = billingRaw.filter(
      (f) => f.path.startsWith("src/server/") || f.path.startsWith("src/server/db/"),
    );
    files.push(...billingServerOnly);
  }

  if (hasEmail) {
    files.push(...emailFiles({ mode: "single", runtime, i18n: effectiveHasI18n }, runtime));
  }

  if (effectiveHasEve) {
    const eveRaw = genEveFiles(projectName, runtime, effectiveBilling);
    const eveMapped = eveRaw.map((f) => ({
      path: f.path.replace(/^apps\/eve\//, "agent/"),
      content: f.content,
    }));
    const filtered = eveMapped.filter((f) => f.path !== "agent/tsconfig.json");
    filtered.push(
      file(
        "agent/tsconfig.json",
        JSON.stringify(
          {
            compilerOptions: {
              target: "ES2024",
              module: "ESNext",
              moduleResolution: "bundler",
              lib: ["ES2024"],
              strict: true,
              esModuleInterop: true,
              skipLibCheck: true,
              forceConsistentCasingInFileNames: true,
              resolveJsonModule: true,
              types: ["node"],
              paths: { "#*": ["./agent/*"], "#evals/*": ["./evals/*"] },
              outDir: "./dist",
              rootDir: ".",
            },
            include: ["agent/**/*", "lib/**/*"],
            exclude: ["node_modules", "dist", ".eve"],
          },
          null,
          2,
        ) + "\n",
      ),
    );
    files.push(...filtered);
  }

  return files;
}

export default buildExpoFiles;
