export function singleLayout(): string {
  return [
    "import * as React from 'react';",
    "import type { Metadata } from 'next';",
    "import { Providers } from '@/components/providers';",
    "import './globals.css';",
    "",
    "export const metadata: Metadata = {",
    "  title: '__PROJECT_NAME__ — GhostInit App',",
    "  description: 'Opinionated single all-in-one Next.js starter with Better Auth + Drizzle + Billing flexible and dark mode',",
    "};",
    "",
    "export default function RootLayout({",
    "  children,",
    "}: Readonly<{ children: React.ReactNode }>) {",
    "  return (",
    "    <html lang='en' suppressHydrationWarning>",
    "      <body className='antialiased bg-background text-foreground'>",
    "        <Providers>{children}</Providers>",
    "      </body>",
    "    </html>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleNotFoundPage(): string {
  return [
    "import Link from 'next/link';",
    "import { Button } from '@/components/ui/button';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';",
    "",
    "export default function NotFound(): React.JSX.Element {",
    "  return (",
    "    <main className='min-h-screen bg-background flex items-center justify-center p-6'>",
    "      <Card className='w-full max-w-[420px] shadow-sm'>",
    "        <CardHeader>",
    "          <CardTitle className='text-2xl tracking-tight'>Page not found</CardTitle>",
    "          <CardDescription className='max-w-[60ch]'>The page you are looking for does not exist or was moved.</CardDescription>",
    "        </CardHeader>",
    "        <CardContent className='flex flex-col gap-3'>",
    "          <Button asChild><Link href='/'>Back to home</Link></Button>",
    "        </CardContent>",
    "      </Card>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleErrorPage(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useEffect } from 'react';",
    "import { Button } from '@/components/ui/button';",
    "import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';",
    "import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';",
    "",
    "export default function Error({ error, reset }: { error: Error & { digest?: string }; reset: () => void; }): React.JSX.Element {",
    "  useEffect(() => { console.error(error); }, [error]);",
    "  return (",
    "    <main className='min-h-screen bg-background flex items-center justify-center p-6'>",
    "      <Card className='w-full max-w-[480px]'>",
    "        <CardHeader>",
    "          <CardTitle>Something went wrong</CardTitle>",
    "          <CardDescription className='max-w-[60ch]'>An unexpected error occurred. You can try again.</CardDescription>",
    "        </CardHeader>",
    "        <CardContent className='flex flex-col gap-4'>",
    "          <Alert variant='destructive'>",
    "            <AlertTitle>Error</AlertTitle>",
    "            <AlertDescription className='truncate max-w-[65ch]'>{error.message}</AlertDescription>",
    "          </Alert>",
    "          <Button onClick={() => reset()}>Try again</Button>",
    "        </CardContent>",
    "      </Card>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleLoadingPage(): string {
  return [
    "import * as React from 'react';",
    "import { Skeleton } from '@/components/ui/skeleton';",
    "",
    "export default function Loading(): React.JSX.Element {",
    "  return (",
    "    <main className='min-h-screen bg-background'>",
    "      <div className='mx-auto flex max-w-5xl flex-col gap-8 p-6 md:p-8'>",
    "        <Skeleton className='h-8 w-32' />",
    "        <Skeleton className='h-64 w-full' />",
    "        <div className='grid gap-4 md:grid-cols-3'>",
    "          <Skeleton className='h-32' />",
    "          <Skeleton className='h-32' />",
    "          <Skeleton className='h-32' />",
    "        </div>",
    "      </div>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}
