/**
 * ghostinit status implementation.
 */

import { ExitCode } from "../lib/errors.js";
import { loadState } from "../lib/state.js";
import { lockPath } from "../lib/lock.js";
import { existsSync } from "node:fs";
import { envelope, printJson } from "../lib/json.js";
import type { GlobalOptions } from "./types.js";

interface StatusReport {
  project: string;
  runtime: string;
  version: string;
  modules: string[];
  generatedAt: string;
  lockActive: boolean;
  // verbose fields
  mode?: string;
  framework?: string;
  billing?: string[];
  database?: string;
  apps?: string[];
  preset?: string;
  cache?: string;
  deploy?: string;
  procedures?: string[];
  checksumCount?: number;
  generatedBy?: string;
}

export async function statusCommand(_args: string[], options: GlobalOptions): Promise<number> {
  const start = Date.now();
  const state = await loadState(options.cwd);
  const lockActive = existsSync(lockPath(options.cwd));

  const isVerbose = Boolean(options.verbose);
  const isList = Boolean(options.list);

  const baseReport: StatusReport = {
    project: state?.project.name ?? "",
    runtime: state?.project.runtime ?? "",
    version: state?.project.version ?? "",
    modules: state?.modules ?? [],
    generatedAt: state?.generatedAt ?? "",
    lockActive,
  };

  let report: StatusReport & Record<string, unknown> = { ...baseReport };

  if (isVerbose && state) {
    report = {
      ...baseReport,
      mode: (state.project as unknown as Record<string, string>).mode ?? "",
      framework: (state.project as unknown as Record<string, string>).framework ?? "",
      billing: (state.project as unknown as Record<string, string[]>).billing ?? [],
      database: (state.project as unknown as Record<string, string>).database ?? "",
      apps: (state.project as unknown as Record<string, string[]>).apps ?? [],
      preset: (state.project as unknown as Record<string, string>).preset ?? "",
      cache: (state.project as unknown as Record<string, string>).cache ?? "",
      deploy: (state.project as unknown as Record<string, string>).deploy ?? "",
      procedures: state.procedures ?? [],
      checksumCount: Object.keys(state.checksums ?? {}).length,
      generatedBy: state.generatedBy ?? "",
    };
  }

  // --list for status: same as verbose but emphasize modules list; kept as alias for compatibility
  if (isList && !isVerbose && state) {
    // treat list as verbose-light: ensure procedures and checksumCount included
    report.procedures = state.procedures ?? [];
    report.checksumCount = Object.keys(state.checksums ?? {}).length;
  }

  if (!state) {
    options.logger.warn("No GhostInit project state found");
  }

  if (options.json) {
    printJson(
      envelope({
        success: !!state,
        exitCode: state ? ExitCode.OK : ExitCode.GENERAL_ERROR,
        data: report,
        command: "status",
        durationMs: Date.now() - start,
      }),
    );
  } else {
    options.logger.info(`Project: ${report.project || "unknown"}`);
    options.logger.info(`Runtime: ${report.runtime || "unknown"}`);
    options.logger.info(`Version: ${report.version || "unknown"}`);
    if (isVerbose && state) {
      options.logger.info(`Mode: ${report.mode}`);
      options.logger.info(`Framework: ${report.framework}`);
      options.logger.info(`Database: ${report.database}`);
      options.logger.info(
        `Billing: ${(report.billing as string[] | undefined)?.join(", ") || "none"}`,
      );
      options.logger.info(`Apps: ${(report.apps as string[] | undefined)?.join(", ") || "none"}`);
      options.logger.info(`Preset: ${report.preset}`);
      options.logger.info(`Cache: ${report.cache}`);
      options.logger.info(`Deploy: ${report.deploy}`);
      options.logger.info(
        `Procedures: ${(report.procedures as string[] | undefined)?.join(", ") || "none"}`,
      );
      options.logger.info(`Checksums: ${report.checksumCount}`);
      options.logger.info(`Generated by: ${report.generatedBy}`);
      options.logger.info(`Generated at: ${report.generatedAt}`);
    } else {
      options.logger.info(`Generated at: ${report.generatedAt || "unknown"}`);
    }
    options.logger.info(`Modules: ${(report.modules || []).join(", ") || "none"}`);
    options.logger.info(`Lock active: ${report.lockActive}`);
    if (isVerbose) {
      options.logger.info(`Run with --json for full machine-readable output`);
    }
  }

  return state ? ExitCode.OK : ExitCode.GENERAL_ERROR;
}
