/**
 * ghostinit sync [--check] implementation.
 *
 * Rebuilds deterministic registries:
 * - packages/modules/src/index.ts
 * - packages/api/src/contract.ts
 * - packages/api/src/router.ts
 */

import { join } from "node:path";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { ExitCode, ValidationError, GhostinitError } from "../lib/errors.js";
import { saveState } from "../lib/state.js";
import { relativeChecksum, hashContent, type ChecksumEntry } from "../lib/checksum.js";
import { acquireLock } from "../lib/lock.js";
import { envelope, printJson } from "../lib/json.js";
import { checkGitStatus, assertCleanGit } from "../lib/git.js";
import { validateProjectForMutation } from "../lib/validate-project.js";
import type { GlobalOptions } from "./types.js";

async function listDirectories(root: string, ...segments: string[]): Promise<string[]> {
  const path = join(root, ...segments);
  if (!existsSync(path)) return [];
  const entries = await readdir(path, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

async function listProcedureFiles(root: string): Promise<string[]> {
  const dir = join(root, "packages", "api", "src", "procedures");
  if (!existsSync(dir)) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".ts"))
    .map((e) => e.name.replace(/\.ts$/, ""))
    .sort();
}

function nameFromFileName(fileName: string): string {
  // kebab-case file name => camelCase export name.
  return fileName.replace(/-([a-z])/g, (_, char) => char.toUpperCase());
}

function buildModuleRegistry(modules: string[]): string {
  const lines = modules.map((m) => `export * as ${nameFromFileName(m)} from "./${m}/index";`);
  return `// Generated by ghostinit sync. Do not edit manually.\n${lines.join("\n")}\n`;
}

function buildApiRegistry(procedures: string[]): { contract: string; router: string } {
  const contractImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)}Contract } from "./procedures/${p}";`,
  );
  const routerImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)} } from "./procedures/${p}";`,
  );

  const contractEntries = procedures.map(
    (p) => `  ${nameFromFileName(p)}: ${nameFromFileName(p)}Contract,`,
  );
  const routerEntries = procedures.map((p) => `    ${nameFromFileName(p)},`);

  const contract = `${contractImports.join("\n")}\n\nexport const appContract = {\n${contractEntries.join("\n")}\n};\n`;

  const router = `import { implement, os } from "@orpc/server";\nimport { appContract } from "./contract";\n${routerImports.join("\n")}\nimport type { ApiContext } from "./context";\n\nconst implementer = implement<typeof appContract, ApiContext>(appContract);\n\nexport const appRouter = os.prefix("/api").router(\n  implementer.router({\n${routerEntries.join("\n")}\n  }),\n);\n`;

  return { contract, router };
}

async function detectFileDrift(
  cwd: string,
  tracked: Record<string, ChecksumEntry>,
): Promise<string[]> {
  const drift: string[] = [];
  for (const [relPath, entry] of Object.entries(tracked)) {
    const absPath = join(cwd, ...relPath.split("/"));
    if (!existsSync(absPath)) {
      drift.push(`${relPath}: missing`);
      continue;
    }
    try {
      const content = await readFile(absPath, "utf-8");
      if (hashContent(content) !== entry.hash) {
        drift.push(`${relPath}: modified externally`);
      }
    } catch (err) {
      drift.push(`${relPath}: unreadable (${err instanceof Error ? err.message : String(err)})`);
    }
  }
  return drift;
}

export async function syncCommand(_args: string[], options: GlobalOptions): Promise<number> {
  const start = Date.now();
  const { release } = await acquireLock(options.cwd, options.logger, { force: options.force });

  try {
    const validation = await validateProjectForMutation(options.cwd);
    if (!validation.valid) {
      if (validation.exitCodeSuggestion === ExitCode.INVALID_STATE) {
        throw new GhostinitError(validation.message, ExitCode.INVALID_STATE, {
          ...validation.details,
          cause: validation.error?.message,
        });
      }
      throw new ValidationError(validation.message);
    }
    const state = validation.state;

    if (!options.force) {
      const gitStatus = await checkGitStatus(options.cwd, options.logger);
      assertCleanGit(gitStatus, options.force, options.logger);
    }

    const modules = await listDirectories(options.cwd, "packages", "modules", "src");
    const procedures = await listProcedureFiles(options.cwd);

    const moduleRegistry = buildModuleRegistry(modules);
    const apiRegistry = buildApiRegistry(procedures);

    const moduleIndexPath = join(options.cwd, "packages", "modules", "src", "index.ts");
    const contractPath = join(options.cwd, "packages", "api", "src", "contract.ts");
    const routerPath = join(options.cwd, "packages", "api", "src", "router.ts");

    const before = {
      modules: await readFile(moduleIndexPath, "utf-8").catch(() => ""),
      contract: await readFile(contractPath, "utf-8").catch(() => ""),
      router: await readFile(routerPath, "utf-8").catch(() => ""),
    };

    const changed =
      before.modules !== moduleRegistry ||
      before.contract !== apiRegistry.contract ||
      before.router !== apiRegistry.router;

    if (options.check) {
      const drift = await detectFileDrift(options.cwd, state.checksums);
      if (drift.length > 0 || changed) {
        const message =
          drift.length > 0
            ? `Generated files are out of sync. Drift: ${drift.join("; ")}`
            : "Generated registries are out of sync. Run `ghostinit sync` to fix.";
        options.logger.error(message);
        if (options.json) {
          printJson(
            envelope({
              success: false,
              exitCode: ExitCode.GENERAL_ERROR,
              error: { message, code: "DRIFT", details: { drift, changed } },
              command: "sync",
              durationMs: Date.now() - start,
            }),
          );
        }
        return ExitCode.GENERAL_ERROR;
      }
      options.logger.info("Generated registries are in sync");
      if (options.json) {
        printJson(
          envelope({
            success: true,
            exitCode: ExitCode.OK,
            data: { modules, procedures, inSync: true },
            command: "sync",
            durationMs: Date.now() - start,
          }),
        );
      }
      return ExitCode.OK;
    }

    if (!changed) {
      options.logger.info("Generated registries are already up to date");
      if (options.json) {
        printJson(
          envelope({
            success: true,
            exitCode: ExitCode.OK,
            data: { modules, procedures, inSync: true },
            command: "sync",
            durationMs: Date.now() - start,
          }),
        );
      }
      return ExitCode.OK;
    }

    await writeFile(moduleIndexPath, moduleRegistry, "utf-8");
    await writeFile(contractPath, apiRegistry.contract, "utf-8");
    await writeFile(routerPath, apiRegistry.router, "utf-8");

    const checksums = [
      relativeChecksum(options.cwd, "packages/modules/src/index.ts", moduleRegistry),
      relativeChecksum(options.cwd, "packages/api/src/contract.ts", apiRegistry.contract),
      relativeChecksum(options.cwd, "packages/api/src/router.ts", apiRegistry.router),
    ];

    await saveState(options.cwd, state.project, checksums, modules, procedures);

    if (options.json) {
      printJson(
        envelope({
          success: true,
          exitCode: ExitCode.OK,
          data: { modules, procedures },
          command: "sync",
          durationMs: Date.now() - start,
        }),
      );
    }

    return ExitCode.OK;
  } finally {
    await release();
  }
}
