/**
 * ghostinit sync [--check] implementation.
 *
 * Rebuilds deterministic registries (module index, API contract/router, and
 * database schema registry):
 * - packages/modules/src/index.ts
 * - packages/api/src/contract.ts
 * - packages/api/src/router.ts
 * - packages/database/src/schema/index.ts
 */

import { join } from "node:path";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { ExitCode, ValidationError, GhostinitError, exitCodeName } from "../lib/errors.js";
import { saveState } from "../lib/state.js";
import { relativeChecksum, hashContent, type ChecksumEntry } from "../lib/checksum.js";
import { acquireLock } from "../lib/lock.js";
import { envelope, printJson } from "../lib/json.js";
import { checkGitStatus, assertCleanGit } from "../lib/git.js";
import { validateProjectForMutation } from "../lib/validate-project.js";
import { loadState } from "../lib/state.js";
import { isReservedName } from "../lib/reserved.js";
import type { GlobalOptions } from "./types.js";

async function readFileSafe(filePath: string): Promise<string> {
  try {
    return await readFile(filePath, "utf-8");
  } catch (err: any) {
    if (err?.code === "ENOENT") {
      return "";
    }
    throw new GhostinitError(
      `Failed to read ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
      ExitCode.GENERAL_ERROR,
      {
        path: filePath,
        code: err?.code ?? "UNKNOWN",
        cause: err instanceof Error ? err.message : String(err),
      },
    );
  }
}

async function listDirectories(root: string, ...segments: string[]): Promise<string[]> {
  const path = join(root, ...segments);
  if (!existsSync(path)) return [];
  const entries = await readdir(path, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

async function listProcedureFiles(root: string): Promise<string[]> {
  const dir = join(root, "packages", "api", "src", "procedures");
  if (!existsSync(dir)) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".ts"))
    .map((e) => e.name.replace(/\.ts$/, ""))
    .sort();
}

async function listSchemaFiles(root: string): Promise<string[]> {
  const dir = join(root, "packages", "database", "src", "schema");
  if (!existsSync(dir)) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".ts") && e.name !== "index.ts")
    .map((e) => e.name.replace(/\.ts$/, ""))
    .sort();
}

function buildSchemaRegistry(schemas: string[]): string {
  // Generated files are written directly (not through the template `file()` helper),
  // so relative imports omit the .js extension to match the normalized style.
  const lines = schemas.map((s) => `export * from "./${s}";`);
  return `// Generated by ghostinit sync. Do not edit manually.\n${lines.join("\n")}\n`;
}

function nameFromFileName(fileName: string): string {
  // kebab-case file name => camelCase export name.
  // Fix: handle digits after hyphen (e.g. foo-1bar should become foo1bar, not remain invalid).
  // Replace -[a-z0-9] and uppercase letters, keep digits as-is.
  let camel = fileName.replace(/-([a-z0-9])/g, (_: string, char: string) => {
    if (/[0-9]/.test(char)) {
      return char;
    }
    return char.toUpperCase();
  });

  // Handle leading digit: prefix underscore to produce a valid identifier.
  if (/^[0-9]/.test(camel)) {
    camel = `_${camel}`;
  }

  // Validate resulting identifier.
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(camel)) {
    throw new ValidationError(`File name "${fileName}" produces invalid identifier "${camel}"`, {
      fileName,
      identifier: camel,
    });
  }

  // Check reserved keywords after transform (both exact and lowercased).
  if (isReservedName(camel) || isReservedName(camel.toLowerCase())) {
    throw new ValidationError(`File name "${fileName}" produces reserved identifier "${camel}"`, {
      fileName,
      identifier: camel,
    });
  }

  return camel;
}

function buildModuleRegistry(modules: string[]): string {
  const lines = modules.map((m) => `export * as ${nameFromFileName(m)} from "./${m}/index";`);
  return `// Generated by ghostinit sync. Do not edit manually.\n${lines.join("\n")}\n`;
}

function buildApiRegistry(procedures: string[]): { contract: string; router: string } {
  const contractImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)}Contract } from "./procedures/${p}";`,
  );
  const routerImports = procedures.map(
    (p) => `import { ${nameFromFileName(p)} } from "./procedures/${p}";`,
  );

  const contractEntries = procedures.map(
    (p) => `  ${nameFromFileName(p)}: ${nameFromFileName(p)}Contract,`,
  );
  const routerEntries = procedures.map((p) => `    ${nameFromFileName(p)},`);

  const contract = `${contractImports.join("\n")}\n\nexport const appContract = {\n${contractEntries.join("\n")}\n};\n`;

  const router = `import { implement, os } from "@orpc/server";\nimport { appContract } from "./contract";\n${routerImports.join("\n")}\nimport type { ApiContext } from "./context";\n\nconst implementer = implement<typeof appContract, ApiContext>(appContract);\n\nexport const appRouter = os.prefix("/api").router(\n  implementer.router({\n${routerEntries.join("\n")}\n  }),\n);\n`;

  return { contract, router };
}

async function detectFileDrift(
  cwd: string,
  tracked: Record<string, ChecksumEntry>,
): Promise<string[]> {
  const entries = Object.entries(tracked);
  // Run in parallel to avoid O(n) sequential awaits + duplicate existsSync IO.
  // Only ENOENT is treated as missing; other errors are reported as unreadable.
  const results = await Promise.all(
    entries.map(async ([relPath, entry]): Promise<string | null> => {
      const absPath = join(cwd, ...relPath.split("/"));
      try {
        const content = await readFile(absPath, "utf-8");
        if (hashContent(content) !== entry.hash) {
          return `${relPath}: modified externally`;
        }
        return null;
      } catch (err: any) {
        if (err?.code === "ENOENT") {
          return `${relPath}: missing`;
        }
        return `${relPath}: unreadable (${err instanceof Error ? err.message : String(err)})`;
      }
    }),
  );
  return results.filter((v): v is string => v !== null);
}

export async function syncCommand(_args: string[], options: GlobalOptions): Promise<number> {
  const start = Date.now();
  const { release } = await acquireLock(options.cwd, options.logger, { force: options.force });

  try {
    const validation = await validateProjectForMutation(options.cwd);
    const state = await (async () => {
      if (validation.valid) return validation.state;
      if (
        options.force &&
        validation.exitCodeSuggestion === ExitCode.INVALID_STATE &&
        validation.details?.drift
      ) {
        options.logger.warn(
          "Drift detected; --force will regenerate registries and overwrite tracked files.",
        );
        const forced = await loadState(options.cwd);
        if (!forced) {
          throw new ValidationError("No GhostInit project state found.");
        }
        return forced;
      }
      if (validation.exitCodeSuggestion === ExitCode.INVALID_STATE) {
        throw new GhostinitError(validation.message, ExitCode.INVALID_STATE, {
          ...validation.details,
          cause: validation.error?.message,
        });
      }
      throw new ValidationError(validation.message);
    })();

    if (!options.force) {
      const gitStatus = await checkGitStatus(options.cwd, options.logger);
      assertCleanGit(gitStatus, options.force, options.logger);
    }

    const modules = await listDirectories(options.cwd, "packages", "modules", "src");
    const procedures = await listProcedureFiles(options.cwd);

    const schemas = await listSchemaFiles(options.cwd);

    const moduleRegistry = buildModuleRegistry(modules);
    const apiRegistry = buildApiRegistry(procedures);
    const schemaRegistry = buildSchemaRegistry(schemas);

    const moduleIndexPath = join(options.cwd, "packages", "modules", "src", "index.ts");
    const contractPath = join(options.cwd, "packages", "api", "src", "contract.ts");
    const routerPath = join(options.cwd, "packages", "api", "src", "router.ts");
    const schemaIndexPath = join(options.cwd, "packages", "database", "src", "schema", "index.ts");

    // Fix Issue 12: only catch ENOENT as empty, re-throw EACCES/EIO etc as GhostinitError via readFileSafe.
    // Also parallelize reads to avoid duplicate IO sequencing.
    const [modulesContent, contractContent, routerContent, schemaIndexContent] = await Promise.all([
      readFileSafe(moduleIndexPath),
      readFileSafe(contractPath),
      readFileSafe(routerPath),
      readFileSafe(schemaIndexPath),
    ]);

    const before = {
      modules: modulesContent,
      contract: contractContent,
      router: routerContent,
      schemaIndex: schemaIndexContent,
    };

    const changed =
      before.modules !== moduleRegistry ||
      before.contract !== apiRegistry.contract ||
      before.router !== apiRegistry.router ||
      before.schemaIndex !== schemaRegistry;

    if (options.check) {
      const drift = await detectFileDrift(options.cwd, state.checksums);
      if (drift.length > 0 || changed) {
        const message =
          drift.length > 0
            ? `Generated files are out of sync. Drift: ${drift.join("; ")}`
            : "Generated registries are out of sync. Run `ghostinit sync` to fix.";
        options.logger.error(message);
        if (options.json) {
          printJson(
            envelope({
              success: false,
              exitCode: ExitCode.DRIFT,
              error: { message, code: exitCodeName(ExitCode.DRIFT), details: { drift, changed } },
              command: "sync",
              durationMs: Date.now() - start,
            }),
          );
        }
        return ExitCode.DRIFT;
      }
      options.logger.info("Generated registries are in sync");
      if (options.json) {
        printJson(
          envelope({
            success: true,
            exitCode: ExitCode.OK,
            data: { modules, procedures, inSync: true },
            command: "sync",
            durationMs: Date.now() - start,
          }),
        );
      }
      return ExitCode.OK;
    }

    if (!changed) {
      options.logger.info("Generated registries are already up to date");
      if (options.json) {
        printJson(
          envelope({
            success: true,
            exitCode: ExitCode.OK,
            data: { modules, procedures, inSync: true },
            command: "sync",
            durationMs: Date.now() - start,
          }),
        );
      }
      return ExitCode.OK;
    }

    // Fix Issue 15: dryRun flag was ignored — skip writes when true.
    if (options.dryRun) {
      const wouldChange: string[] = [];
      if (before.modules !== moduleRegistry) wouldChange.push("packages/modules/src/index.ts");
      if (before.contract !== apiRegistry.contract)
        wouldChange.push("packages/api/src/contract.ts");
      if (before.router !== apiRegistry.router) wouldChange.push("packages/api/src/router.ts");
      if (before.schemaIndex !== schemaRegistry)
        wouldChange.push("packages/database/src/schema/index.ts");

      options.logger.info(
        `[dry-run] Would update ${wouldChange.length} file(s): ${wouldChange.join(", ")}`,
      );
      for (const f of wouldChange) {
        options.logger.info(`[dry-run] Would write ${f}`);
      }
      options.logger.info("[dry-run] Skipping writeFile and saveState");

      if (options.json) {
        printJson(
          envelope({
            success: true,
            exitCode: ExitCode.OK,
            data: { modules, procedures, wouldChange, dryRun: true },
            command: "sync",
            durationMs: Date.now() - start,
          }),
        );
      }
      return ExitCode.OK;
    }

    await writeFile(moduleIndexPath, moduleRegistry, "utf-8");
    await writeFile(contractPath, apiRegistry.contract, "utf-8");
    await writeFile(routerPath, apiRegistry.router, "utf-8");
    await writeFile(schemaIndexPath, schemaRegistry, "utf-8");

    const checksums = [
      relativeChecksum(options.cwd, "packages/modules/src/index.ts", moduleRegistry),
      relativeChecksum(options.cwd, "packages/api/src/contract.ts", apiRegistry.contract),
      relativeChecksum(options.cwd, "packages/api/src/router.ts", apiRegistry.router),
      relativeChecksum(options.cwd, "packages/database/src/schema/index.ts", schemaRegistry),
    ];

    await saveState(options.cwd, state.project, checksums, modules, procedures);

    if (options.json) {
      printJson(
        envelope({
          success: true,
          exitCode: ExitCode.OK,
          data: { modules, procedures },
          command: "sync",
          durationMs: Date.now() - start,
        }),
      );
    }

    return ExitCode.OK;
  } finally {
    await release();
  }
}
