export function headerSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import Link from 'next/link';",
    "import { useRouter } from 'next/navigation';",
    "import { Badge } from '@/components/ui/badge';",
    "import { Button } from '@/components/ui/button';",
    "import { Avatar, AvatarFallback } from '@/components/ui/avatar';",
    "import {",
    "  DropdownMenu,",
    "  DropdownMenuTrigger,",
    "  DropdownMenuContent,",
    "  DropdownMenuItem,",
    "  DropdownMenuLabel,",
    "  DropdownMenuSeparator,",
    "} from '@/components/ui/dropdown-menu';",
    "import { ThemeToggle } from '@/components/theme-toggle';",
    "import { useAuth } from '@/hooks/use-auth';",
    "import { authClient } from '@/lib/auth-client';",
    "",
    "function getInitials(name?: string | null, email?: string | null): string {",
    "  if (name) {",
    "    const parts = name.trim().split(/\\s+/);",
    "    if (parts.length >= 2) {",
    "      return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase();",
    "    }",
    "    return parts[0].slice(0, 2).toUpperCase();",
    "  }",
    "  if (email) return email.slice(0, 2).toUpperCase();",
    '  return "U";',
    "}",
    "",
    "export function Header(): React.JSX.Element {",
    "  const { user, isAuthenticated, isPending } = useAuth();",
    "  const router = useRouter();",
    "  const initials = getInitials(user?.name, user?.email);",
    "  async function handleSignOut(): Promise<void> {",
    "    await authClient.signOut();",
    '    router.push("/");',
    "  }",
    "  return (",
    '    <header className="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur-sm supports-[backdrop-filter]:bg-background/60">',
    '      <div className="mx-auto flex h-14 max-w-6xl items-center justify-between gap-6 px-6 md:px-8">',
    '        <div className="flex items-center gap-6">',
    '          <Link href="/" className="flex items-center gap-2">',
    '            <span className="text-sm font-semibold tracking-tight">GhostInit</span>',
    '            <Badge variant="secondary" className="hidden sm:inline-flex">modular monolith</Badge>',
    "          </Link>",
    "          {isAuthenticated ? (",
    '            <nav className="hidden md:flex items-center gap-1">',
    '              <Button variant="ghost" size="sm" asChild><Link href="/dashboard">Dashboard</Link></Button>',
    '              <Button variant="ghost" size="sm" asChild><Link href="/billing">Billing</Link></Button>',
    '              <Button variant="ghost" size="sm" asChild><Link href="/settings">Settings</Link></Button>',
    '              {user?.role === "admin" ? (',
    '                <Button variant="ghost" size="sm" asChild><Link href="/admin/users">Admin</Link></Button>',
    "              ) : null}",
    "            </nav>",
    "          ) : null}",
    "        </div>",
    '        <div className="flex items-center gap-2">',
    "          <ThemeToggle />",
    "          {isPending ? (",
    '            <div className="size-9 animate-pulse rounded-full bg-muted" aria-hidden />',
    "          ) : isAuthenticated ? (",
    "            <DropdownMenu>",
    "              <DropdownMenuTrigger asChild>",
    '                <Button variant="ghost" size="icon" className="rounded-full" aria-label="User menu">',
    '                  <Avatar className="size-8">',
    '                    <AvatarFallback className="text-xs">{initials}</AvatarFallback>',
    "                  </Avatar>",
    "                </Button>",
    "              </DropdownMenuTrigger>",
    '              <DropdownMenuContent align="end" className="w-56">',
    '                <DropdownMenuLabel className="flex flex-col gap-1">',
    '                  <span className="font-medium truncate">{user?.name ?? "User"}</span>',
    '                  <span className="text-xs font-normal text-muted-foreground truncate">{user?.email}</span>',
    "                </DropdownMenuLabel>",
    "                <DropdownMenuSeparator />",
    '                <DropdownMenuItem onClick={() => router.push("/dashboard")}>Dashboard</DropdownMenuItem>',
    '                <DropdownMenuItem onClick={() => router.push("/billing")}>Billing</DropdownMenuItem>',
    '                <DropdownMenuItem onClick={() => router.push("/settings")}>Settings</DropdownMenuItem>',
    "                <DropdownMenuSeparator />",
    "                <DropdownMenuItem onClick={() => void handleSignOut()}>Sign out</DropdownMenuItem>",
    "              </DropdownMenuContent>",
    "            </DropdownMenu>",
    "          ) : (",
    '            <div className="flex items-center gap-2">',
    '              <Button variant="ghost" size="sm" asChild><Link href="/sign-in">Sign in</Link></Button>',
    '              <Button size="sm" asChild><Link href="/sign-up">Sign up</Link></Button>',
    "            </div>",
    "          )}",
    "        </div>",
    "      </div>",
    "    </header>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleHeaderTanstackContent(): string {
  return [
    '"use client"',
    "",
    "import * as React from 'react'",
    "import { Link, useRouter } from '@tanstack/react-router'",
    "import { Badge } from '@/components/ui/badge'",
    "import { Button } from '@/components/ui/button'",
    "import { Avatar, AvatarFallback } from '@/components/ui/avatar'",
    "import {",
    "  DropdownMenu,",
    "  DropdownMenuTrigger,",
    "  DropdownMenuContent,",
    "  DropdownMenuItem,",
    "  DropdownMenuLabel,",
    "  DropdownMenuSeparator,",
    "} from '@/components/ui/dropdown-menu'",
    "import { ThemeToggle } from '@/components/theme-toggle'",
    "import { useAuth } from '@/hooks/use-auth'",
    "import { authClient } from '@/lib/auth-client'",
    "",
    "function getInitials(name?: string | null, email?: string | null): string {",
    "  if (name) {",
    "    const parts = name.trim().split(/\\s+/)",
    "    if (parts.length >= 2) {",
    "      return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase()",
    "    }",
    "    return parts[0].slice(0, 2).toUpperCase()",
    "  }",
    "  if (email) return email.slice(0, 2).toUpperCase()",
    '  return "U"',
    "}",
    "",
    "export function Header(): React.JSX.Element {",
    "  const { user, isAuthenticated, isPending } = useAuth()",
    "  const router = useRouter()",
    "  const initials = getInitials(user?.name, user?.email)",
    "  async function handleSignOut(): Promise<void> {",
    "    await authClient.signOut()",
    "    router.navigate({ to: '/' })",
    "  }",
    "  return (",
    '    <header className="sticky top-0 z-40 w-full border-b bg-background/80 backdrop-blur-sm supports-[backdrop-filter]:bg-background/60">',
    '      <div className="mx-auto flex h-14 max-w-6xl items-center justify-between gap-6 px-6 md:px-8">',
    '        <div className="flex items-center gap-6">',
    '          <Link to="/" className="flex items-center gap-2">',
    '            <span className="text-sm font-semibold tracking-tight">GhostInit</span>',
    '            <Badge variant="secondary" className="hidden sm:inline-flex">single • tanstack</Badge>',
    "          </Link>",
    "          {isAuthenticated ? (",
    '            <nav className="hidden md:flex items-center gap-1">',
    '              <Button variant="ghost" size="sm" asChild><Link to="/dashboard">Dashboard</Link></Button>',
    '              <Button variant="ghost" size="sm" asChild><Link to="/billing">Billing</Link></Button>',
    '              <Button variant="ghost" size="sm" asChild><Link to="/settings">Settings</Link></Button>',
    '              {user?.role === "admin" ? (',
    '                <Button variant="ghost" size="sm" asChild><Link to="/admin">Admin</Link></Button>',
    "              ) : null}",
    "            </nav>",
    "          ) : null}",
    "        </div>",
    '        <div className="flex items-center gap-2">',
    "          <ThemeToggle />",
    "          {isPending ? (",
    '            <div className="size-9 animate-pulse rounded-full bg-muted" aria-hidden />',
    "          ) : isAuthenticated ? (",
    "            <DropdownMenu>",
    "              <DropdownMenuTrigger asChild>",
    '                <Button variant="ghost" size="icon" className="rounded-full" aria-label="User menu">',
    '                  <Avatar className="size-8">',
    '                    <AvatarFallback className="text-xs">{initials}</AvatarFallback>',
    "                  </Avatar>",
    "                </Button>",
    "              </DropdownMenuTrigger>",
    '              <DropdownMenuContent align="end" className="w-56">',
    '                <DropdownMenuLabel className="flex flex-col gap-1">',
    '                  <span className="font-medium truncate">{user?.name ?? "User"}</span>',
    '                  <span className="text-xs font-normal text-muted-foreground truncate">{user?.email}</span>',
    "                </DropdownMenuLabel>",
    "                <DropdownMenuSeparator />",
    '                <DropdownMenuItem onClick={() => router.navigate({ to: "/dashboard" })}>Dashboard</DropdownMenuItem>',
    '                <DropdownMenuItem onClick={() => router.navigate({ to: "/billing" })}>Billing</DropdownMenuItem>',
    '                <DropdownMenuItem onClick={() => router.navigate({ to: "/settings" })}>Settings</DropdownMenuItem>',
    "                <DropdownMenuSeparator />",
    "                <DropdownMenuItem onClick={() => void handleSignOut()}>Sign out</DropdownMenuItem>",
    "              </DropdownMenuContent>",
    "            </DropdownMenu>",
    "          ) : (",
    '            <div className="flex items-center gap-2">',
    '              <Button variant="ghost" size="sm" asChild><Link to="/sign-in">Sign in</Link></Button>',
    '              <Button size="sm" asChild><Link to="/sign-up">Sign up</Link></Button>',
    "            </div>",
    "          )}",
    "        </div>",
    "      </div>",
    "    </header>",
    "  )",
    "}",
    "",
  ].join("\n");
}

export function singleSignOutButtonTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { useRouter } from '@tanstack/react-router'",
    "import { authClient } from '@/lib/auth-client'",
    "import { Button } from '@/components/ui/button'",
    "export function SignOutButton(): React.JSX.Element {",
    "  const router = useRouter()",
    "  async function handleClick(): Promise<void> { await authClient.signOut(); router.navigate({ to: '/' }) }",
    "  return (<Button variant='outline' onClick={() => void handleClick()}>Sign out</Button>)",
    "}",
    "",
  ].join("\n");
}

export function singleAdminGuardTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { useEffect } from 'react'",
    "import { useRouter } from '@tanstack/react-router'",
    "import { authClient } from '@/lib/auth-client'",
    "export function AdminGuard({ children }: { children: React.ReactNode }): React.JSX.Element | null {",
    "  const router = useRouter()",
    "  const { data: session, isPending } = authClient.useSession()",
    "  useEffect(() => { if (!isPending && session?.user?.role !== 'admin') { router.navigate({ to: '/' }) } }, [isPending, session, router])",
    "  if (isPending || session?.user?.role !== 'admin') return null",
    "  return <>{children}</>",
    "}",
    "",
  ].join("\n");
}
