export function useCopyHookSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { toast } from 'sonner';",
    "",
    "export interface UseCopyReturn {",
    "  copy: (text: string) => Promise<boolean>;",
    "  copied: boolean;",
    "}",
    "",
    "export function useCopy(): UseCopyReturn {",
    "  const [copied, setCopied] = React.useState(false);",
    "  const copy = React.useCallback(async (text: string): Promise<boolean> => {",
    "    try {",
    "      await navigator.clipboard.writeText(text);",
    "      setCopied(true);",
    '      toast.success("Copied to clipboard");',
    "      window.setTimeout(() => setCopied(false), 2000);",
    "      return true;",
    "    } catch {",
    '      toast.error("Failed to copy");',
    "      return false;",
    "    }",
    "  }, []);",
    "  return { copy, copied };",
    "}",
    "",
  ].join("\n");
}

export function useBillingHookSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "",
    "export interface BillingSubscription {",
    "  id: string;",
    "  provider: string;",
    "  status: string;",
    "  currentPeriodEnd?: string | null;",
    "  priceId?: string | null;",
    "}",
    "",
    "export interface UseBillingReturn {",
    "  subscriptions: BillingSubscription[];",
    "  loading: boolean;",
    "  error: string | null;",
    "  refresh: () => Promise<void>;",
    "  hasActiveSubscription: boolean;",
    "  isLoading: boolean;",
    "}",
    "",
    "export function useBilling(): UseBillingReturn {",
    "  const [subscriptions, setSubscriptions] = React.useState<BillingSubscription[]>([]);",
    "  const [loading, setLoading] = React.useState(true);",
    "  const [error, setError] = React.useState<string | null>(null);",
    "  const refresh = React.useCallback(async (): Promise<void> => {",
    "    setLoading(true);",
    "    setError(null);",
    "    try {",
    '      const res = await fetch("/api/billing/subscriptions", { method: "GET" });',
    "      if (!res.ok) {",
    "        throw new Error(`Failed to load billing: ${res.status}`);",
    "      }",
    "      const data = (await res.json()) as { subscriptions?: BillingSubscription[] } | BillingSubscription[];",
    "      const list = Array.isArray(data) ? data : (data.subscriptions ?? []);",
    "      setSubscriptions(list);",
    "    } catch (err) {",
    '      setError(err instanceof Error ? err.message : "Failed to load billing");',
    "    } finally {",
    "      setLoading(false);",
    "    }",
    "  }, []);",
    "  React.useEffect(() => { void refresh(); }, [refresh]);",
    "  const hasActiveSubscription = React.useMemo(() => {",
    '    return subscriptions.some((s) => s.status === "active" || s.status === "trialing");',
    "  }, [subscriptions]);",
    "  return { subscriptions, loading, error, refresh, hasActiveSubscription, isLoading: loading };",
    "}",
    "",
  ].join("\n");
}

export function useAuthHookSingleContent(): string {
  return [
    '"use client";',
    "",
    "import { authClient } from '@/lib/auth-client';",
    "",
    "export function useAuth() {",
    "  const { data: session, isPending, error, refetch } = authClient.useSession();",
    "  return {",
    "    session: session ?? null,",
    "    user: session?.user ?? null,",
    "    isPending,",
    "    isAuthenticated: !!session?.user,",
    "    isPendingAuth: isPending,",
    "    error: error ?? null,",
    "    refetch,",
    "  };",
    "}",
    "",
  ].join("\n");
}
