export function providersSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useState, Suspense } from 'react';",
    "import { QueryClient, QueryClientProvider } from '@tanstack/react-query';",
    "import { ThemeProvider } from '@/components/theme-provider';",
    "import { PostHogProvider } from '@/components/analytics/posthog-provider';",
    "import { PostHogPageView } from '@/components/analytics/posthog-pageview';",
    "import { Toaster } from '@/components/ui/sonner';",
    "",
    "export function Providers({ children }: { children: React.ReactNode }): React.JSX.Element {",
    "  const [queryClient] = useState(() => new QueryClient());",
    "  return (",
    "    <QueryClientProvider client={queryClient}>",
    "      <PostHogProvider>",
    '        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>',
    "          <Suspense fallback={null}>",
    "            <PostHogPageView />",
    "          </Suspense>",
    "          {children}",
    '          <Toaster richColors position="bottom-right" />',
    "        </ThemeProvider>",
    "      </PostHogProvider>",
    "    </QueryClientProvider>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function singleProvidersTanstackContent(): string {
  return [
    '"use client"',
    "import * as React from 'react'",
    "import { useState } from 'react'",
    "import { QueryClient, QueryClientProvider } from '@tanstack/react-query'",
    "import { ThemeProvider } from '@/components/theme-provider'",
    "import { Toaster } from '@/components/ui/sonner'",
    "export function Providers({ children }: { children: React.ReactNode }): React.JSX.Element {",
    "  const [queryClient] = useState(() => new QueryClient())",
    "  return (",
    "    <QueryClientProvider client={queryClient}>",
    "      <ThemeProvider attribute='class' defaultTheme='light' enableSystem={false} disableTransitionOnChange>",
    "        {children}",
    "        <Toaster richColors position='bottom-right' />",
    "      </ThemeProvider>",
    "    </QueryClientProvider>",
    "  )",
    "}",
    "",
  ].join("\n");
}
