export function themeProviderSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { ThemeProvider as NextThemesProvider, type ThemeProviderProps } from 'next-themes';",
    "",
    "export function ThemeProvider({ children, ...props }: ThemeProviderProps): React.JSX.Element {",
    "  return (",
    '    <NextThemesProvider attribute="class" defaultTheme="dark" enableSystem={false} disableTransitionOnChange {...props}>',
    "      {children}",
    "    </NextThemesProvider>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function themeToggleSingleContent(): string {
  return [
    '"use client";',
    "",
    "import * as React from 'react';",
    "import { useTheme } from 'next-themes';",
    "import { Button } from '@/components/ui/button';",
    "import { useSurfaceTranslations } from '@/lib/translations';",
    "",
    "function SunIcon(props: React.SVGProps<SVGSVGElement>): React.JSX.Element {",
    "  return (",
    "    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round' aria-hidden='true' {...props}>",
    '      <circle cx="12" cy="12" r="4" />',
    '      <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41" />',
    "    </svg>",
    "  );",
    "}",
    "",
    "function MoonIcon(props: React.SVGProps<SVGSVGElement>): React.JSX.Element {",
    "  return (",
    "    <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' strokeLinecap='round' strokeLinejoin='round' aria-hidden='true' {...props}>",
    '      <path d="M12 3a6 6 0 0 0 9 9a9 9 0 1 1-9-9Z" />',
    "    </svg>",
    "  );",
    "}",
    "",
    "export function ThemeToggle(): React.JSX.Element {",
    "  const { theme, setTheme } = useTheme();",
    "  const t = useSurfaceTranslations('theme');",
    "  const [mounted, setMounted] = React.useState(false);",
    "  React.useEffect(() => setMounted(true), []);",
    "  if (!mounted) {",
    '    return <Button variant="ghost" size="icon" disabled aria-label={t("toggle")}><span className="size-4" /></Button>;',
    "  }",
    "  return (",
    '    <Button variant="ghost" size="icon" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label={t("toggle")}>',
    '      <SunIcon className="size-4 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" data-icon="inline-start" />',
    '      <MoonIcon className="absolute size-4 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" data-icon="inline-start" />',
    '      <span className="sr-only">{t("toggle")}</span>',
    "    </Button>",
    "  );",
    "}",
    "",
  ].join("\n");
}
