import type { TemplateFile } from "../../shared.js";
import { file } from "../../shared.js";
import type { BillingProviderName, FrameworkName } from "../../../lib/addons.js";

function buildAgentsMdContent(
  projectName: string,
  selectedBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  framework: FrameworkName = "nextjs",
): string {
  const lines: string[] = [];
  lines.push(`# AGENTS.md — ${projectName}`);
  lines.push("");
  lines.push(
    "> Generated by GhostInit monorepo — flexible billing + services + 6 layered + oRPC contract-first + dual modes. Bun only.",
  );
  lines.push("");
  lines.push("## Snapshot");
  lines.push(`- Name: ${projectName}`);
  lines.push(
    "- Mode: monorepo (workspaces apps/* packages/* tooling/* covers packages/services + billing + email via packages/* glob)",
  );
  lines.push("- Runtime: bun only (bun 1.3.14, bunfig.toml hoist false, bun.lock)");
  lines.push(`- Framework: ${framework}`);
  lines.push(
    `- Billing: ${selectedBilling.length ? selectedBilling.join(",") : "none — Empty UI + Add provider button"}`,
  );
  lines.push(`- Eve: ${hasEve ? "enabled hybrid withEve" : "disabled — only AGENTS.md rules"}`);
  lines.push(`- i18n: ${hasI18n ? "enabled next-intl 4.x" : "disabled"}`);
  lines.push(
    "- Stack: Next.js 16.2.10 / TanStack Start 1.168.30 React 19.2.7 TS 7.0.2 Drizzle 0.45.2 Better Auth 1.6.23 oRPC 1.14.7 Zod 4.4.3 Tailwind 4.3.2 Base UI 1.6.0 turbo 2.10.4",
  );
  lines.push("- Type: modular monolith 6-layer layered + capability");
  lines.push("");
  lines.push("## Layers (6) — must respect");
  lines.push("1. **Presentation — apps/web ONLY (+ apps/eve conditional) oRPC contract-first**");
  lines.push(
    "   - apps/web Next 16 App Router transpilePackages @repo/* single port 3000 alias @/*->./src/* @repo/*->packages/*/src via typescript-config paths. Security headers nosniff DENY CSP default-src self. Pages marketing /, auth sign-in/up /2fa /dashboard RSC protected /settings layout nav /admin guard role admin. API routes auth [...all] oRPC api/[...path] RPCHandler+OpenAPIHandler webhooks via Next routes raw Buffer Buffer.from(await request.arrayBuffer()) 4 providers.",
  );
  lines.push(
    `   - Eve hybrid if enabled: withEve({ eveRoot: ../eve }) mounted same-origin rewrite /eve/v1/** zero CORS single deploy cookie auth flows. Agent anthropic/claude-sonnet-5 tools defineTool zod approval always/once/never.`,
  );
  lines.push(
    "2. **API contract — packages/api**: oRPC contract-first context auth.api.getSession health GET ok time me GET user contract router os.prefix(/api) openapi.",
  );
  lines.push(
    "3. **Services — packages/services capability layer 4 default**: business logic Input/Deps(Result) spanning modules+billing+email+database. No business logic leaks into procedures. Integration boundaries stable APIs consumable by oRPC + Server Actions + RSC direct.",
  );
  lines.push(
    "4. **Modules — packages/modules DDD**: src/<name>/ domain/types.ts Entity id domain/index application/index ports/index.ts Port tests/domain-types.test.ts. Per-module DB schema packages/database/src/schema/<name>.ts pgTable pluralized userId FK cascade.",
  );
  lines.push(
    "5. **Vendors / billing — packages/billing layer 5**: flexible any combo none/both/one/all — port stable interface.ts. Shared schema provider enum stripe|chargily|paddle|polar subscriptions checkouts invoices customers products prices license_keys usage_events webhook_events unique provider+providerEventId onConflictDoNothing idempotent.",
  );
  lines.push(
    "   - stripe: checkout.sessions.create billingPortal deep-link constructEvent raw Body sig. chargily: ChargilyClient api_key mode Product->Price->Checkout checkout_url verifySignature HMAC-SHA256 timingSafeEqual server-only manual recurring DB+ eve cron. paddle: Paddle API_KEY transactions.create checkout_url TransactionCompleted raw body. polar: events.ingest validateEvent whsec base64 license keys.",
  );
  lines.push(
    "6. **Infrastructure — packages/database auth config email observability**: Drizzle pool max 20 idle SSL schema/index.ts generated. auth Better Auth emailAndPassword autoSignIn false user delete enabled session cookieCache compact httpOnly secure sameSite lax rateLimit 60 100 IP disabled unless TRUSTED_PROXY. config t3env validation server secrets NEVER client except NEXT_PUBLIC_ tokens. email Resend 4.0.1.",
  );
  lines.push("");
  lines.push(
    `- Billing flexible (${selectedBilling.length ? selectedBilling.join(",") : "none"}): Empty No billing configured + Button Add billing provider when none, Card single when one, TabsList inside Tabs multi/all shared DB idempotent 200 already processed. Env placeholders REPLACE_WITH real via secret() .env.local gitignored t3env server-only.`,
  );
  lines.push(
    "- Billing keys conditional .env.example: RESEND always, billing keys only if chosen else placeholder comment.",
  );
  lines.push("- Email default resend: @repo/email always emitted in monorepo.");
  lines.push(
    "- Services default: packages/services/src/ business logic per generator oRPC contract-first webhooks via Next routes raw Buffer single port.",
  );
  lines.push(
    "- Import alias @ always: @/* -> ./src/* + @repo/* -> packages/*/src via typescript-config paths explicit mappings 15 packages baseUrl explicit.",
  );
  lines.push(
    "- Workspaces: root package.json workspaces [apps/*, packages/*, tooling/*] covers packages/services + billing + email. bunfig.toml hoist false bun.lock.",
  );
  lines.push(
    hasI18n
      ? "- i18n conditional enabled: next-intl routing locales [en,fr,ar] default en localePrefix as-needed localeDetection true request.ts getRequestConfig hasLocale messages timeZone Africa/Algiers navigation config middleware matcher excluding api trpc _next eve."
      : "- i18n conditional disabled: feature optional false default via i18nFiles when enabled routing.ts defineRouting locales en fr ar.",
  );
  lines.push(
    hasEve
      ? "- Eve conditional hybrid enabled: withEve hybrid apps/eve filesystem-separated mounted same-origin rewrite /eve/v1/** zero CORS single dev single deploy cookie auth flows."
      : "- Eve conditional hybrid disabled: apps/eve not emitted unless eve feature, agenticFiles also conditional. When enabled hybrid filesystem-separated mounted same-origin.",
  );
  lines.push(
    "- AgenticFiles + eveFiles conditional if eve: enriched AGENTS.md/CLAUDE.md/cursor/windsurf rules still emitted per task.",
  );
  lines.push(
    "- Dual modes: monorepoFiles returns TemplateFile[] for monorepo must = rootFiles+packageFiles+databasePackage+startDatabaseFiles+authPackage+emailFiles+analyticsFiles+apiPackage+uiPackage+modulesPackage+appsFilesWithConditionalEve+typescriptConfigWithAliases+toolingFiles+servicesFiles+billingFiles conditional+i18nFiles conditional+agenticFiles+eveFiles conditional. oRPC contract-first single port webhooks via Next routes raw Buffer.",
  );
  lines.push(
    "- .env.example conditional: billing keys only if chosen else placeholder comment — RESEND always when email selected, STRIPE etc only when chosen. Implementation filteredEnvExample billingEnvLines conditional server-only NEVER client except NEXT_PUBLIC_ tokens. Single port 3000 no API_PORT.",
  );
  lines.push("");
  lines.push("## Package Roles");
  lines.push("- apps/web presentation Next + oRPC single port webhooks via Next routes raw Buffer");
  lines.push("- apps/eve AI hybrid");
  lines.push("- packages/api oRPC contract");
  lines.push("- packages/auth Better Auth + Resend");
  lines.push("- packages/billing flexible 4 providers");
  lines.push("- packages/database Drizzle");
  lines.push("- packages/email Resend");
  lines.push("- packages/services capability layer 4");
  lines.push("- packages/modules DDD");
  lines.push("- packages/ui shadcn BaseUI");
  lines.push(
    "- packages/config t3env, kernel domain, contracts zod, observability otel, testing bun-test, workflows",
  );
  lines.push("");
  lines.push("## Design System — Unified");
  lines.push("- OKLCH neutrals chroma 0.005-0.01 indigo accent oklch(0.55 0.22 264) ≤10% surface");
  lines.push(
    "- Light + dark via next-themes 0.4.6 @custom-variant dark (&:is(.dark *)) 32 tokens mapped @theme inline",
  );
  lines.push(
    "- Tokens :root --background 0.99 0.002 106 --foreground 0.21 0.01 264 --primary indigo --radius 0.625rem etc. Dark .dark deep tinted.",
  );
  lines.push("- Tailwind v4 @import tailwindcss first line globals.css @custom-variant dark");
  lines.push(
    "- shadcn: semantic tokens only bg-background text-foreground bg-primary etc never raw bg-blue-500 bg-white border-slate-300. Form FieldGroup+Field+FieldLabel+FieldDescription data-invalid aria-invalid InputGroup ToggleGroup 2-7 options. CardHeader>Title Description Action Content Footer. Dialog must include Title a11y. flex gap-* not space-x/y size-* not w-* h-* truncate cn() data-icon inline-start. Avatar must have Fallback Badge secondary TabsTrigger inside TabsList Alert for callouts Empty for empties Separator Skeleton.",
  );
  lines.push(
    "- Every file <300 LOC use components + hooks extracted use-copy use-billing use-auth use-billing-page max 263 lines.",
  );
  lines.push(
    "- Next-themes ThemeProvider attribute class defaultTheme light enableSystem false disableTransitionOnChange Toaster bottom-right ThemeToggle mounted guard Sun Moon icons.",
  );
  lines.push(
    "- Impeccable bans: no side-stripe >1px colored as decoration, no gradient text background-clip:text, no glassmorphism default except header blur, no hero-metric big number+small label+gradient, no identical card grids, no modal as first thought inline disclosure modal only destructive confirm, no nested cards, no animate height/width directly, no decorative motion without state, no inconsistent vocabulary, no em dashes, max 65ch tracking-tight titles, no slate- colors, no bg-white/black raw, no space-x/y, no size w-/h- square, no window.confirm, no inline style display:inline-block, no isPending button prop compose Spinner.",
  );
  lines.push("");
  lines.push("## Quality Gates");
  lines.push(
    "- bun only, tsc --noEmit, oxlint, oxfmt --check, bun test --timeout 100000, bun run build, ghostinit check sync --check, turbo",
  );
  lines.push("");
  lines.push("## Security");
  lines.push(
    ".env.local gitignored real 48-byte base64url ^[A-Za-z0-9_-]+$ length>=32 BETTER_AUTH_SECRET min32 localhost warning autoSignIn false cookieCache compact httpOnly secure sameSite lax rateLimit 60 100 IP disabled unless TRUSTED_PROXY Billing server-only NEVER client except NEXT_PUBLIC_ tokens Chargily server-only logger redacts secret OpenAPI 404 prod auth 405 oRPC security headers nosniff CSP.",
  );
  lines.push("");
  return lines.join("\n") + "\n";
}

export function agentsComposerFiles(
  projectName: string,
  selectedBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  framework: FrameworkName = "nextjs",
): TemplateFile[] {
  const content = buildAgentsMdContent(projectName, selectedBilling, hasEve, hasI18n, framework);
  const agents = file("AGENTS.md", content);
  const claude = file("CLAUDE.md", content);
  const cursor = file(
    ".cursor/rules/ghostinit.mdc",
    [
      "---",
      "description: GhostInit monorepo — DDD oRPC Better Auth Drizzle billing services 6 layers dual modes",
      "globs:",
      '  - "**/*"',
      "alwaysApply: true",
      "---",
      "",
      content,
    ].join("\n"),
  );
  const windsurf = file(".windsurf/rules/ghostinit.md", content);
  return [agents, claude, cursor, windsurf];
}

export { buildAgentsMdContent };
