export function authClientSingle(): string {
  return [
    "import { createAuthClient } from 'better-auth/react';",
    "import { adminClient, twoFactorClient } from 'better-auth/client/plugins';",
    "",
    "export const authClient = createAuthClient({",
    "  plugins: [",
    "    twoFactorClient({",
    "      onTwoFactorRedirect(context) {",
    "        if (context.twoFactorMethods?.includes('totp') && typeof window !== 'undefined') {",
    "          window.location.href = '/2fa';",
    "        }",
    "      },",
    "    }),",
    "    adminClient(),",
    "  ],",
    "});",
    "",
  ].join("\n");
}

export function authClientSingleConvex(): string {
  return [
    "import { createAuthClient } from 'better-auth/react';",
    "import { convexClient } from '@convex-dev/better-auth/client/plugins';",
    "import { adminClient, twoFactorClient } from 'better-auth/client/plugins';",
    "",
    "export const authClient = createAuthClient({",
    "  plugins: [",
    "    convexClient(),",
    "    twoFactorClient({",
    "      onTwoFactorRedirect(context) {",
    "        if (context.twoFactorMethods?.includes('totp') && typeof window !== 'undefined') {",
    "          window.location.href = '/2fa';",
    "        }",
    "      },",
    "    }),",
    "    adminClient(),",
    "  ],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthSingle(hasEmail = true): string {
  return [
    "import { betterAuth } from 'better-auth';",
    "import { drizzleAdapter } from 'better-auth/adapters/drizzle';",
    "import { nextCookies } from 'better-auth/next-js';",
    "import { admin } from 'better-auth/plugins/admin';",
    "import { twoFactor } from 'better-auth/plugins';",
    "import { db } from '@/server/db';",
    "import * as schema from '@/server/db/schema/auth';",
    ...(hasEmail
      ? [
          'import { sendEmail } from "@/server/email";',
          'import ResetPasswordEmail from "@/server/email/templates/ResetPassword";',
          'import VerifyEmail from "@/server/email/templates/VerifyEmail";',
        ]
      : []),
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "export const auth = betterAuth({",
    "  appName: process.env.APP_NAME ?? 'GhostInit',",
    "  secret: _authSecret,",
    "  baseURL: process.env.BETTER_AUTH_URL!,",
    "  database: drizzleAdapter(db, { provider: 'pg', schema }),",
    "  emailAndPassword: {",
    "    enabled: true,",
    "    autoSignInAfterRegistration: false,",
    ...(hasEmail
      ? [
          "    sendResetPassword: async ({ user, url }) => {",
          "      const appName = process.env.APP_NAME ?? 'GhostInit';",
          "      const subject = `Reset your password - ${appName}`;",
          "      await sendEmail(user.email, subject, ResetPasswordEmail,",
          "        { link: url, appName },",
          "      );",
          "    },",
        ]
      : []),
    "  },",
    ...(hasEmail
      ? [
          "  emailVerification: {",
          "    sendOnSignUp: true,",
          "    autoSignInAfterVerification: true,",
          "    sendVerificationEmail: async ({ user, url }) => {",
          "      const appName = process.env.APP_NAME ?? 'GhostInit';",
          "      await sendEmail(user.email, `Verify your email - ${appName}`, VerifyEmail, { link: url, appName });",
          "    },",
          "  },",
        ]
      : []),
    "  plugins: [admin(), twoFactor({ issuer: process.env.BETTER_AUTH_URL! }), nextCookies()],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthTanstackSingle(hasEmail = true): string {
  return [
    "import { betterAuth } from 'better-auth';",
    "import { drizzleAdapter } from 'better-auth/adapters/drizzle';",
    "import { tanstackStartCookies } from 'better-auth/tanstack-start';",
    "import { admin } from 'better-auth/plugins/admin';",
    "import { twoFactor } from 'better-auth/plugins';",
    "import { db } from '@/server/db';",
    "import * as schema from '@/server/db/schema/auth';",
    ...(hasEmail
      ? [
          'import { sendEmail } from "@/server/email";',
          'import ResetPasswordEmail from "@/server/email/templates/ResetPassword";',
          'import VerifyEmail from "@/server/email/templates/VerifyEmail";',
        ]
      : []),
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "export const auth = betterAuth({",
    "  appName: process.env.APP_NAME ?? 'GhostInit',",
    "  secret: _authSecret,",
    "  baseURL: process.env.BETTER_AUTH_URL!,",
    "  database: drizzleAdapter(db, { provider: 'pg', schema }),",
    "  emailAndPassword: {",
    "    enabled: true,",
    "    autoSignInAfterRegistration: false,",
    ...(hasEmail
      ? [
          "    sendResetPassword: async ({ user, url }) => {",
          "      const appName = process.env.APP_NAME ?? 'GhostInit';",
          "      const subject = `Reset your password - ${appName}`;",
          "      await sendEmail(user.email, subject, ResetPasswordEmail,",
          "        { link: url, appName },",
          "      );",
          "    },",
        ]
      : []),
    "  },",
    ...(hasEmail
      ? [
          "  emailVerification: {",
          "    sendOnSignUp: true,",
          "    autoSignInAfterVerification: true,",
          "    sendVerificationEmail: async ({ user, url }) => {",
          "      const appName = process.env.APP_NAME ?? 'GhostInit';",
          "      await sendEmail(user.email, `Verify your email - ${appName}`, VerifyEmail, { link: url, appName });",
          "    },",
          "  },",
        ]
      : []),
    "  plugins: [admin(), twoFactor({ issuer: process.env.BETTER_AUTH_URL! }), tanstackStartCookies()],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthSingleConvex(): string {
  return [
    "// Convex variant — auth lives in convex/auth.ts (createClient + adapter).",
    "// This Next.js handler proxies to Convex site URL for Better Auth routes,",
    "// and provides a getSession helper that queries convex via convexClient.",
    "import { convexClient } from '@/server/db';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "function resolveConvexSiteUrl(): string {",
    "  return (",
    "    process.env.CONVEX_SITE_URL ??",
    "    process.env.SITE_URL ??",
    "    (process.env.NEXT_PUBLIC_CONVEX_URL ? process.env.NEXT_PUBLIC_CONVEX_URL.replace('.cloud', '.site') : '') ??",
    "    ''",
    "  );",
    "}",
    "",
    "export interface SingleAuthSession {",
    "  session: { id: string; userId: string; expiresAt: Date; token: string; createdAt: Date; updatedAt: Date; ipAddress?: string | null; userAgent?: string | null };",
    "  user: { id: string; name: string; email: string; emailVerified: boolean; createdAt: Date; updatedAt: Date; image?: string | null; role?: string; twoFactorEnabled?: boolean };",
    "}",
    "",
    "export const auth = {",
    "  handler: async (request: Request): Promise<Response> => {",
    "    const siteUrl = resolveConvexSiteUrl();",
    "    if (!siteUrl) {",
    '      return new Response("CONVEX_SITE_URL or SITE_URL must be set for convex auth mode", { status: 500 });',
    "    }",
    "    try {",
    "      const incomingUrl = new URL(request.url);",
    "      const target = new URL(incomingUrl.pathname + incomingUrl.search, siteUrl);",
    "      const headers = new Headers(request.headers);",
    "      // Forward but strip host",
    "      headers.delete('host');",
    "      const body = request.method !== 'GET' && request.method !== 'HEAD' ? await request.arrayBuffer() : undefined;",
    "      const res = await fetch(target.toString(), { method: request.method, headers, body });",
    "      // Clone response headers",
    "      const resHeaders = new Headers(res.headers);",
    "      const resBody = await res.arrayBuffer();",
    "      return new Response(resBody, { status: res.status, headers: resHeaders });",
    "    } catch (e) {",
    "      return new Response(`Auth proxy error: ${e instanceof Error ? e.message : String(e)}`, { status: 502 });",
    "    }",
    "  },",
    "  api: {",
    "    getSession: async ({ headers }: { headers: Headers }): Promise<SingleAuthSession | null> => {",
    "      try {",
    "        // In convex mode, session is validated via convex auth query using http client",
    "        // We attempt to call getCurrentUser via convexClient - requires auth cookie forwarding",
    "        // For now return null and rely on client side ConvexBetterAuthProvider",
    "        void headers; void convexClient;",
    "        return null;",
    "      } catch { return null; }",
    "    },",
    "  },",
    "};",
    "",
  ].join("\n");
}

export function serverAuthTanstackSingleConvex(): string {
  return [
    "// Convex variant for TanStack Start - mirrors Next variant",
    "import { convexClient } from '@/server/db';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "function resolveConvexSiteUrl(): string {",
    "  return (",
    "    process.env.CONVEX_SITE_URL ??",
    "    process.env.SITE_URL ??",
    "    (process.env.NEXT_PUBLIC_CONVEX_URL ? process.env.NEXT_PUBLIC_CONVEX_URL.replace('.cloud', '.site') : '') ??",
    "    ''",
    "  );",
    "}",
    "",
    "export interface SingleAuthSession {",
    "  session: { id: string; userId: string; expiresAt: Date; token: string; createdAt: Date; updatedAt: Date; ipAddress?: string | null; userAgent?: string | null };",
    "  user: { id: string; name: string; email: string; emailVerified: boolean; createdAt: Date; updatedAt: Date; image?: string | null; role?: string; twoFactorEnabled?: boolean };",
    "}",
    "",
    "export const auth = {",
    "  handler: async (request: Request): Promise<Response> => {",
    "    const siteUrl = resolveConvexSiteUrl();",
    "    if (!siteUrl) {",
    '      return new Response("CONVEX_SITE_URL or SITE_URL must be set for convex auth mode", { status: 500 });',
    "    }",
    "    try {",
    "      const incomingUrl = new URL(request.url);",
    "      const target = new URL(incomingUrl.pathname + incomingUrl.search, siteUrl);",
    "      const headers = new Headers(request.headers);",
    "      headers.delete('host');",
    "      const body = request.method !== 'GET' && request.method !== 'HEAD' ? await request.arrayBuffer() : undefined;",
    "      const res = await fetch(target.toString(), { method: request.method, headers, body });",
    "      const resHeaders = new Headers(res.headers);",
    "      const resBody = await res.arrayBuffer();",
    "      return new Response(resBody, { status: res.status, headers: resHeaders });",
    "    } catch (e) {",
    "      return new Response(`Auth proxy error: ${e instanceof Error ? e.message : String(e)}`, { status: 502 });",
    "    }",
    "  },",
    "  api: {",
    "    getSession: async ({ headers }: { headers: Headers }): Promise<SingleAuthSession | null> => { void headers; void convexClient; return null; },",
    "  },",
    "};",
    "",
  ].join("\n");
}
