export function authClientSingle(): string {
  return [
    "import { createAuthClient } from 'better-auth/react';",
    "import { adminClient, twoFactorClient } from 'better-auth/client/plugins';",
    "",
    "export const authClient = createAuthClient({",
    "  plugins: [",
    "    twoFactorClient({",
    "      onTwoFactorRedirect(context) {",
    "        if (context.twoFactorMethods?.includes('totp') && typeof window !== 'undefined') {",
    "          window.location.href = '/2fa';",
    "        }",
    "      },",
    "    }),",
    "    adminClient(),",
    "  ],",
    "});",
    "",
  ].join("\n");
}

export function authClientSingleConvex(): string {
  return [
    "import { createAuthClient } from 'better-auth/react';",
    "import { convexClient } from '@convex-dev/better-auth/client/plugins';",
    "import { adminClient, twoFactorClient } from 'better-auth/client/plugins';",
    "",
    "export const authClient = createAuthClient({",
    "  plugins: [",
    "    convexClient(),",
    "    twoFactorClient({",
    "      onTwoFactorRedirect(context) {",
    "        if (context.twoFactorMethods?.includes('totp') && typeof window !== 'undefined') {",
    "          window.location.href = '/2fa';",
    "        }",
    "      },",
    "    }),",
    "    adminClient(),",
    "  ],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthSingle(): string {
  return [
    "import { betterAuth } from 'better-auth';",
    "import { drizzleAdapter } from 'better-auth/adapters/drizzle';",
    "import { nextCookies } from 'better-auth/next-js';",
    "import { admin, twoFactor } from 'better-auth/plugins';",
    "import { db } from '@/server/db';",
    "import * as schema from '@/server/db/schema/auth';",
    "import { sendEmail } from '@/server/email';",
    "import ResetPasswordEmail from '@/server/email/templates/ResetPassword';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "export const auth = betterAuth({",
    "  appName: process.env.APP_NAME ?? 'GhostInit',",
    "  secret: _authSecret,",
    "  baseURL: process.env.BETTER_AUTH_URL!,",
    "  database: drizzleAdapter(db, { provider: 'pg', schema }),",
    "  emailAndPassword: {",
    "    enabled: true,",
    "    autoSignInAfterRegistration: false,",
    "    sendResetPassword: async ({ user, url }) => {",
    "      await sendEmail(user.email, 'Reset password', ResetPasswordEmail, { link: url, appName: process.env.APP_NAME });",
    "    },",
    "  },",
    "  plugins: [admin(), twoFactor({ issuer: process.env.BETTER_AUTH_URL! }), nextCookies()],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthTanstackSingle(): string {
  return [
    "import { betterAuth } from 'better-auth';",
    "import { drizzleAdapter } from 'better-auth/adapters/drizzle';",
    "import { tanstackStartCookies } from 'better-auth/tanstack-start';",
    "import { admin, twoFactor } from 'better-auth/plugins';",
    "import { db } from '@/server/db';",
    "import * as schema from '@/server/db/schema/auth';",
    "import { sendEmail } from '@/server/email';",
    "import ResetPasswordEmail from '@/server/email/templates/ResetPassword';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "export const auth = betterAuth({",
    "  appName: process.env.APP_NAME ?? 'GhostInit',",
    "  secret: _authSecret,",
    "  baseURL: process.env.BETTER_AUTH_URL!,",
    "  database: drizzleAdapter(db, { provider: 'pg', schema }),",
    "  emailAndPassword: {",
    "    enabled: true,",
    "    autoSignInAfterRegistration: false,",
    "    sendResetPassword: async ({ user, url }) => {",
    "      await sendEmail(user.email, 'Reset password', ResetPasswordEmail, { link: url, appName: process.env.APP_NAME });",
    "    },",
    "  },",
    "  plugins: [admin(), twoFactor({ issuer: process.env.BETTER_AUTH_URL! }), tanstackStartCookies()],",
    "});",
    "",
  ].join("\n");
}

export function serverAuthSingleConvex(): string {
  return [
    "// Convex variant — auth lives in convex/auth.ts (createClient + adapter).",
    "// This Next.js handler proxies to Convex site URL for Better Auth routes,",
    "// and provides a getSession helper that queries convex via convexClient.",
    "import { convexClient } from '@/server/db';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "function resolveConvexSiteUrl(): string {",
    "  return (",
    "    process.env.CONVEX_SITE_URL ??",
    "    process.env.SITE_URL ??",
    "    (process.env.NEXT_PUBLIC_CONVEX_URL ? process.env.NEXT_PUBLIC_CONVEX_URL.replace('.cloud', '.site') : '') ??",
    "    ''",
    "  );",
    "}",
    "",
    "export const auth = {",
    "  handler: async (request: Request): Promise<Response> => {",
    "    const siteUrl = resolveConvexSiteUrl();",
    "    if (!siteUrl) {",
    '      return new Response("CONVEX_SITE_URL or SITE_URL must be set for convex auth mode", { status: 500 });',
    "    }",
    "    try {",
    "      const incomingUrl = new URL(request.url);",
    "      const target = new URL(incomingUrl.pathname + incomingUrl.search, siteUrl);",
    "      const headers = new Headers(request.headers);",
    "      // Forward but strip host",
    "      headers.delete('host');",
    "      const body = request.method !== 'GET' && request.method !== 'HEAD' ? await request.arrayBuffer() : undefined;",
    "      const res = await fetch(target.toString(), { method: request.method, headers, body });",
    "      // Clone response headers",
    "      const resHeaders = new Headers(res.headers);",
    "      const resBody = await res.arrayBuffer();",
    "      return new Response(resBody, { status: res.status, headers: resHeaders });",
    "    } catch (e) {",
    "      return new Response(`Auth proxy error: ${e instanceof Error ? e.message : String(e)}`, { status: 502 });",
    "    }",
    "  },",
    "  api: {",
    "    getSession: async ({ headers }: { headers: Headers }) => {",
    "      try {",
    "        // In convex mode, session is validated via convex auth query using http client",
    "        // We attempt to call getCurrentUser via convexClient - requires auth cookie forwarding",
    "        // For now return null and rely on client side ConvexBetterAuthProvider",
    "        const siteUrl = resolveConvexSiteUrl();",
    "        if (!siteUrl) return null;",
    "        const response = await fetch(new URL('/api/auth/get-session', siteUrl), { headers });",
    "        if (!response.ok) return null;",
    "        void convexClient;",
    "        return await response.json();",
    "      } catch { return null; }",
    "    },",
    "  },",
    "};",
    "",
  ].join("\n");
}

export function serverAuthTanstackSingleConvex(): string {
  return [
    "// Convex variant for TanStack Start - mirrors Next variant",
    "import { convexClient } from '@/server/db';",
    "",
    "const _authSecret = process.env.BETTER_AUTH_SECRET!;",
    'if (!_authSecret || _authSecret.length < 32 || _authSecret.startsWith("REPLACE_WITH") || _authSecret === "REPLACE_WITH_A_STRONG_SECRET_AT_LEAST_32_CHARS") {',
    '  throw new Error("BETTER_AUTH_SECRET must be set to a strong random value, not placeholder, at least 32 chars");',
    "}",
    "",
    "function resolveConvexSiteUrl(): string {",
    "  return (",
    "    process.env.CONVEX_SITE_URL ??",
    "    process.env.SITE_URL ??",
    "    (process.env.NEXT_PUBLIC_CONVEX_URL ? process.env.NEXT_PUBLIC_CONVEX_URL.replace('.cloud', '.site') : '') ??",
    "    (process.env.VITE_CONVEX_URL ? process.env.VITE_CONVEX_URL.replace('.cloud', '.site') : '') ??",
    "    ''",
    "  );",
    "}",
    "",
    "export const auth = {",
    "  handler: async (request: Request): Promise<Response> => {",
    "    const siteUrl = resolveConvexSiteUrl();",
    "    if (!siteUrl) {",
    '      return new Response("CONVEX_SITE_URL or SITE_URL must be set for convex auth mode", { status: 500 });',
    "    }",
    "    try {",
    "      const incomingUrl = new URL(request.url);",
    "      const target = new URL(incomingUrl.pathname + incomingUrl.search, siteUrl);",
    "      const headers = new Headers(request.headers);",
    "      headers.delete('host');",
    "      const body = request.method !== 'GET' && request.method !== 'HEAD' ? await request.arrayBuffer() : undefined;",
    "      const res = await fetch(target.toString(), { method: request.method, headers, body });",
    "      const resHeaders = new Headers(res.headers);",
    "      const resBody = await res.arrayBuffer();",
    "      return new Response(resBody, { status: res.status, headers: resHeaders });",
    "    } catch (e) {",
    "      return new Response(`Auth proxy error: ${e instanceof Error ? e.message : String(e)}`, { status: 502 });",
    "    }",
    "  },",
    "  api: {",
    "    getSession: async ({ headers }: { headers: Headers }) => { const siteUrl = resolveConvexSiteUrl(); if (!siteUrl) return null; const response = await fetch(new URL('/api/auth/get-session', siteUrl), { headers }); if (!response.ok) return null; void convexClient; return await response.json(); },",
    "  },",
    "};",
    "",
  ].join("\n");
}
