import {
  identityDataModelBlueprint,
  renderPostgresIdentitySchema,
} from "../../../../domain/data-model/index.js";

export function serverDbIndexSingle(includeBilling = true, includeAuth = true): string {
  const authImport = includeAuth ? "import * as authSchema from './schema/auth';" : "";
  const billingImport = includeBilling ? "import * as billingSchema from './schema/billing';" : "";
  const schemaParts = [includeAuth ? "...authSchema" : "", includeBilling ? "...billingSchema" : ""]
    .filter(Boolean)
    .join(", ");
  return [
    "import { drizzle } from 'drizzle-orm/node-postgres';",
    "import { Pool, type PoolConfig } from 'pg';",
    authImport,
    billingImport,
    "",
    "function buildConnectionString(): string {",
    "  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;",
    "  const user = encodeURIComponent(process.env.POSTGRES_USER ?? 'postgres');",
    "  const password = encodeURIComponent(process.env.POSTGRES_PASSWORD ?? '');",
    "  const host = process.env.POSTGRES_HOST ?? 'localhost';",
    "  const port = process.env.POSTGRES_PORT ?? '5432';",
    "  const database = encodeURIComponent(process.env.POSTGRES_DB ?? process.env.APP_NAME ?? 'ghostinit');",
    "  return `postgresql://${user}:${password}@${host}:${port}/${database}`;",
    "}",
    "",
    "function rejectConnectionStringTlsOverrides(connectionString: string): void {",
    "  if (process.env.DATABASE_SSL !== 'true') return;",
    "  const parsed = new URL(connectionString);",
    "  for (const key of parsed.searchParams.keys()) {",
    "    const normalized = key.toLowerCase();",
    "    if (normalized.startsWith('ssl') || normalized === 'uselibpqcompat') {",
    "      throw new Error('DATABASE_URL must not override TLS parameters when DATABASE_SSL=true');",
    "    }",
    "  }",
    "}",
    "",
    "const connectionString = buildConnectionString();",
    "rejectConnectionStringTlsOverrides(connectionString);",
    "",
    "const configuredPoolSize = Number.parseInt(process.env.DATABASE_POOL_SIZE ?? '20', 10);",
    "if (!Number.isSafeInteger(configuredPoolSize) || configuredPoolSize < 1 || configuredPoolSize > 100) {",
    "  throw new Error('DATABASE_POOL_SIZE must be an integer between 1 and 100');",
    "}",
    "const poolConfig: PoolConfig = {",
    "  connectionString,",
    "  max: configuredPoolSize,",
    "  idleTimeoutMillis: 30_000,",
    "};",
    "if (process.env.DATABASE_SSL === 'true') {",
    "  poolConfig.ssl = process.env.DATABASE_SSL_CA",
    "    ? { ca: process.env.DATABASE_SSL_CA, rejectUnauthorized: true }",
    "    : true;",
    "}",
    "const pool = new Pool(poolConfig);",
    "",
    schemaParts
      ? `export const db = drizzle(pool, { schema: { ${schemaParts} } });`
      : "export const db = drizzle(pool);",
    "",
  ].join("\n");
}

export function serverDbIndexSingleConvex(): string {
  return [
    "import { ConvexHttpClient } from 'convex/browser';",
    "import { env } from '@/lib/env/server';",
    "",
    "function resolveConvexUrl(): string {",
    "  return env.CONVEX_URL;",
    "}",
    "",
    "const url = resolveConvexUrl();",
    "export const convexClient = new ConvexHttpClient(url);",
    "export function getConvexClient(): ConvexHttpClient { return convexClient; }",
    "export const db = convexClient;",
    "",
  ].join("\n");
}

export function serverDbIndexSingleNone(): string {
  return [
    "// database=none - no database client. Replace with your own persistence if needed.",
    'export const DATABASE_DISABLED_MESSAGE = "[ghostinit] database is disabled (--database none). Enable --database postgres or convex to use persistence.";',
    "",
    "export interface DisabledDatabaseClient {",
    "  readonly [property: string]: never;",
    "}",
    "",
    "const disabledDatabaseTarget: DisabledDatabaseClient = Object.create(null);",
    "export const db = new Proxy(disabledDatabaseTarget, {",
    "  get(_target, property): never {",
    "    throw new Error(`${DATABASE_DISABLED_MESSAGE} Attempted to access db.${String(property)}.`);",
    "  },",
    "  set(): never {",
    "    throw new Error(`${DATABASE_DISABLED_MESSAGE} Attempted to mutate db.`);",
    "  },",
    "});",
    "export const convexClient = null;",
    "export function getConvexClient(): null { return null; }",
    "",
  ].join("\n");
}

export function serverDbAuthSchemaStub(): string {
  return renderPostgresIdentitySchema(identityDataModelBlueprint, { quote: "'" });
}

export function serverDbEmptySchema(): string {
  return "// No identity or billing tables were selected.\nexport {};\n";
}

export function serverDrizzleConfigSingle(): string {
  return [
    "import { defineConfig } from 'drizzle-kit';",
    "",
    "function connectionUrl(): string {",
    "  if (process.env.DATABASE_URL) return process.env.DATABASE_URL;",
    "  const user = process.env.POSTGRES_USER ?? 'postgres';",
    "  const password = encodeURIComponent(process.env.POSTGRES_PASSWORD ?? '');",
    "  const host = process.env.POSTGRES_HOST ?? 'localhost';",
    "  const port = process.env.POSTGRES_PORT ?? '5432';",
    "  const database = process.env.POSTGRES_DB ?? process.env.APP_NAME ?? 'ghostinit';",
    "  return `postgresql://${user}:${password}@${host}:${port}/${database}`;",
    "}",
    "",
    "export default defineConfig({",
    "  schema: './src/server/db/schema/**/*.ts',",
    "  out: './drizzle',",
    "  dialect: 'postgresql',",
    "  dbCredentials: { url: connectionUrl() },",
    "});",
    "",
  ].join("\n");
}

export function serverObservabilitySingle(): string {
  return [
    "/* Secret-safe logger — single mode flat, mirrors @repo/observability */",
    'export type LogLevel = "debug" | "info" | "warn" | "error";',
    "",
    "export interface Logger {",
    "  debug: (msg: string, meta?: Record<string, unknown>) => void;",
    "  info: (msg: string, meta?: Record<string, unknown>) => void;",
    "  warn: (msg: string, meta?: Record<string, unknown>) => void;",
    "  error: (msg: string, meta?: Record<string, unknown>) => void;",
    "}",
    "",
    "export const SECRET_SUBSTRINGS = [",
    '  "secret",',
    '  "password",',
    '  "token",',
    '  "auth",',
    '  "bearer",',
    '  "cookie",',
    '  "credential",',
    '  "key",',
    '  "otp",',
    '  "session",',
    '  "signature",',
    '  "private",',
    "] as const;",
    "export const SECRET_PATTERN = /\\b(apikey|api_key|jwt|private_key|database_url|db_url|webhook_secret|client_secret|access_token)\\b/i;",
    "export const URL_SECRET_PARAM_PATTERN = /token|key|secret|password|auth|api|signature/i;",
    "export const SECRET_VALUE_PATTERNS: RegExp[] = [",
    "  /\\b(?:sk|pk|rk|whsec|psk)_[A-Za-z0-9_]{8,}/g,",
    "  /\\bpdl_[A-Za-z0-9_]{8,}/g,",
    "  /\\bpolar_[A-Za-z0-9_]{8,}/g,",
    "  /\\b(?:phc|re)_[A-Za-z0-9_]{16,}/g,",
    "  /\\bBearer\\s+[A-Za-z0-9._~+/-]{12,}=*/gi,",
    "  /\\beyJ[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]{8,}\\.[A-Za-z0-9_-]+/g,",
    "  /\\b([a-z][a-z0-9+.-]*:\\/\\/[^:\\s/]+):[^@\\s]+@/gi,",
    "];",
    "const SECRET_ASSIGNMENT_PATTERN = /\\b([A-Za-z][A-Za-z0-9_.-]{0,63})(\\s*(?:=|:)\\s*)(?:\"[^\"\\r\\n]*\"|'[^'\\r\\n]*'|[^\\s,;&]+)/g;",
    "",
    "export function looksLikeSecret(key: string): boolean {",
    "  const lower = key.toLowerCase();",
    "  for (const needle of SECRET_SUBSTRINGS) {",
    "    if (lower.includes(needle)) return true;",
    "  }",
    "  return SECRET_PATTERN.test(lower);",
    "}",
    "",
    "export function redactSecretValues(text: string): string {",
    "  let out = text;",
    "  for (const pattern of SECRET_VALUE_PATTERNS) {",
    "    out = out.replace(pattern, (match, prefix?: string) => typeof prefix === 'string' ? `${prefix}:***@` : '***');",
    "  }",
    "  out = out.replace(SECRET_ASSIGNMENT_PATTERN, (match, key: string, separator: string) => looksLikeSecret(key) ? `${key}${separator}***` : match);",
    "  return out;",
    "}",
    "",
    "const EMBEDDED_URL_PATTERN = /\\b[a-z][a-z0-9+.-]*:\\/\\/[^\\s<>\"'`]+/gi;",
    "const TRAILING_URL_PUNCTUATION = /[),.;!?]+$/;",
    "function redactUrl(value: string): string {",
    "  try {",
    "    const url = new URL(value);",
    "    let changed = false;",
    "    if (url.username) { url.username = '***'; changed = true; }",
    "    if (url.password) { url.password = '***'; changed = true; }",
    "    for (const param of Array.from(url.searchParams.keys())) {",
    "      if (looksLikeSecret(param)) {",
    '        url.searchParams.set(param, "***");',
    "        changed = true;",
    "      }",
    "    }",
    "    if (url.hash.length > 1) {",
    "      const fragment = new URLSearchParams(url.hash.slice(1));",
    "      let fragmentChanged = false;",
    "      for (const param of Array.from(fragment.keys())) {",
    "        if (looksLikeSecret(param)) { fragment.set(param, '***'); fragmentChanged = true; }",
    "      }",
    "      if (fragmentChanged) { url.hash = fragment.toString(); changed = true; }",
    "    }",
    "    return changed ? url.toString() : value;",
    "  } catch {",
    "    return value;",
    "  }",
    "}",
    "function redactUrlToken(value: string): string {",
    "  return value.replace(EMBEDDED_URL_PATTERN, (candidate) => {",
    '    const trailing = candidate.match(TRAILING_URL_PUNCTUATION)?.[0] ?? "";',
    "    const url = trailing ? candidate.slice(0, -trailing.length) : candidate;",
    "    return `${redactUrl(url)}${trailing}`;",
    "  });",
    "}",
    "",
    'export function redact(value: unknown, key = ""): unknown {',
    '  if (typeof value === "string") {',
    '    if (looksLikeSecret(key)) return "***";',
    "    return redactSecretValues(redactUrlToken(value));",
    "  }",
    "  if (Array.isArray(value)) {",
    "    return value.map((v, i) => redact(v, String(i)));",
    "  }",
    '  if (value && typeof value === "object" && !(value instanceof Date)) {',
    "    const out: Record<string, unknown> = {};",
    "    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {",
    "      out[k] = redact(v, k);",
    "    }",
    "    return out;",
    "  }",
    "  return value;",
    "}",
    "",
    "function defaultLog(level: LogLevel, message: string, meta?: Record<string, unknown>): void {",
    '  const safeMessage = typeof message === "string" ? redactSecretValues(redactUrlToken(message)) : message;',
    "  const safeMeta = meta ? (redact(meta) as Record<string, unknown>) : undefined;",
    "  const line = JSON.stringify({ level, message: safeMessage, time: new Date().toISOString(), ...(safeMeta ? { meta: safeMeta } : {}) });",
    '  if (level === "error") {',
    "    process.stderr.write(`${line}\\n`);",
    "  } else {",
    "    process.stdout.write(`${line}\\n`);",
    "  }",
    "}",
    "",
    "export const logger: Logger = {",
    '  debug: (msg, meta) => defaultLog("debug", msg, meta),',
    '  info: (msg, meta) => defaultLog("info", msg, meta),',
    '  warn: (msg, meta) => defaultLog("warn", msg, meta),',
    '  error: (msg, meta) => defaultLog("error", msg, meta),',
    "};",
    "",
  ].join("\n");
}

export function libUtils(): string {
  return [
    "import { clsx, type ClassValue } from 'clsx';",
    "import { twMerge } from 'tailwind-merge';",
    "export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }",
    "",
  ].join("\n");
}
