export function serverDbIndexSingle(): string {
  return [
    "import { drizzle } from 'drizzle-orm/node-postgres';",
    "import { Pool } from 'pg';",
    "import * as authSchema from './schema/auth';",
    "import * as billingSchema from './schema/billing';",
    "",
    "const pool = new Pool({",
    "  connectionString: process.env.DATABASE_URL ?? `postgres://postgres:${process.env.POSTGRES_PASSWORD}@${process.env.POSTGRES_HOST ?? 'localhost'}:${process.env.POSTGRES_PORT ?? '5432'}/${process.env.POSTGRES_DB ?? 'ghostinit'}`,",
    "  max: Number(process.env.DATABASE_POOL_SIZE ?? '20'),",
    "});",
    "",
    "export const db = drizzle(pool, { schema: { ...authSchema, ...billingSchema } });",
    "",
  ].join("\n");
}

export function serverDbIndexSingleConvex(): string {
  return [
    "import { ConvexHttpClient } from 'convex/browser';",
    "",
    "function resolveConvexUrl(): string {",
    "  if (typeof process !== 'undefined' && process.env) {",
    "    return (",
    "      process.env.CONVEX_URL ??",
    "      process.env.NEXT_PUBLIC_CONVEX_URL ??",
    "      process.env.VITE_CONVEX_URL ??",
    "      process.env.EXPO_PUBLIC_CONVEX_URL ??",
    "      'REPLACE_WITH_CONVEX_URL'",
    "    );",
    "  }",
    "  return 'REPLACE_WITH_CONVEX_URL';",
    "}",
    "",
    "const url = resolveConvexUrl();",
    "export const convexClient = new ConvexHttpClient(url);",
    "export function getConvexClient(): ConvexHttpClient { return convexClient; }",
    "// Back-compat alias: some legacy code imports db, prefer convexClient directly",
    "export const db = convexClient as unknown as any;",
    "",
  ].join("\n");
}

export function serverDbIndexSingleNone(): string {
  return [
    "// database=none - no database client. Replace with your own persistence if needed.",
    "export const db: any = {};",
    "export const convexClient: any = null;",
    "export function getConvexClient(): null { return null; }",
    "",
  ].join("\n");
}

export function serverDbAuthSchemaStub(): string {
  return [
    "import { pgTable, text, timestamp, boolean } from 'drizzle-orm/pg-core';",
    "export const users = pgTable('users', { id: text('id').primaryKey(), name: text('name'), email: text('email').notNull().unique(), emailVerified: boolean('email_verified').default(false), image: text('image'), createdAt: timestamp('created_at').defaultNow(), updatedAt: timestamp('updated_at').defaultNow(), role: text('role').default('user'), twoFactorEnabled: boolean('two_factor_enabled').default(false) });",
    "export const sessions = pgTable('sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull(), token: text('token').notNull(), expiresAt: timestamp('expires_at').notNull() });",
    "export const accounts = pgTable('accounts', { id: text('id').primaryKey(), userId: text('user_id').notNull(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull() });",
    "export const verifications = pgTable('verifications', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at').notNull() });",
    "export const twoFactor = pgTable('two_factor', { id: text('id').primaryKey(), userId: text('user_id').notNull(), secret: text('secret').notNull() });",
    "",
  ].join("\n");
}

export function serverObservabilitySingle(): string {
  return [
    "/* Secret-safe logger — single mode flat, mirrors @repo/observability */",
    'export type LogLevel = "debug" | "info" | "warn" | "error";',
    "",
    "export interface Logger {",
    "  debug: (msg: string, meta?: Record<string, unknown>) => void;",
    "  info: (msg: string, meta?: Record<string, unknown>) => void;",
    "  warn: (msg: string, meta?: Record<string, unknown>) => void;",
    "  error: (msg: string, meta?: Record<string, unknown>) => void;",
    "}",
    "",
    "export const SECRET_SUBSTRINGS = [",
    '  "secret",',
    '  "password",',
    '  "token",',
    '  "auth",',
    '  "bearer",',
    '  "cookie",',
    '  "credential",',
    '  "key",',
    '  "otp",',
    '  "session",',
    '  "signature",',
    '  "private",',
    "] as const;",
    "export const SECRET_PATTERN = /\\\\b(apikey|api_key|jwt|private_key|database_url|db_url|webhook_secret|client_secret|access_token)\\\\b/i;",
    "export const URL_SECRET_PARAM_PATTERN = /token|key|secret|password|auth|api|signature/i;",
    "",
    "export function looksLikeSecret(key: string): boolean {",
    "  const lower = key.toLowerCase();",
    "  for (const needle of SECRET_SUBSTRINGS) {",
    "    if (lower.includes(needle)) return true;",
    "  }",
    "  return SECRET_PATTERN.test(lower);",
    "}",
    "",
    "function redactUrlToken(value: string): string {",
    "  try {",
    "    const url = new URL(value);",
    "    const needsRedaction = url.password || (url.searchParams.toString() && URL_SECRET_PARAM_PATTERN.test(url.search));",
    "    if (!needsRedaction) return value;",
    "    for (const param of Array.from(url.searchParams.keys())) {",
    "      if (looksLikeSecret(param)) {",
    '        url.searchParams.set(param, "***");',
    "      }",
    "    }",
    '    if (url.password) url.password = "***";',
    "    return url.toString();",
    "  } catch {",
    "    return value;",
    "  }",
    "}",
    "",
    'export function redact(value: unknown, key = ""): unknown {',
    '  if (typeof value === "string") {',
    '    if (looksLikeSecret(key)) return "***";',
    "    return redactUrlToken(value);",
    "  }",
    "  if (Array.isArray(value)) {",
    "    return value.map((v, i) => redact(v, String(i)));",
    "  }",
    '  if (value && typeof value === "object" && !(value instanceof Date)) {',
    "    const out: Record<string, unknown> = {};",
    "    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {",
    "      out[k] = redact(v, k);",
    "    }",
    "    return out;",
    "  }",
    "  return value;",
    "}",
    "",
    "function defaultLog(level: LogLevel, message: string, meta?: Record<string, unknown>): void {",
    '  const safeMessage = typeof message === "string" ? redactUrlToken(message) : message;',
    "  const safeMeta = meta ? (redact(meta) as Record<string, unknown>) : undefined;",
    "  const line = JSON.stringify({ level, message: safeMessage, time: new Date().toISOString(), ...(safeMeta ? { meta: safeMeta } : {}) });",
    '  if (level === "error") {',
    "    process.stderr.write(`${line}\\n`);",
    "  } else {",
    "    process.stdout.write(`${line}\\n`);",
    "  }",
    "}",
    "",
    "export const logger: Logger = {",
    '  debug: (msg, meta) => defaultLog("debug", msg, meta),',
    '  info: (msg, meta) => defaultLog("info", msg, meta),',
    '  warn: (msg, meta) => defaultLog("warn", msg, meta),',
    '  error: (msg, meta) => defaultLog("error", msg, meta),',
    "};",
    "",
  ].join("\n");
}

export function libUtils(): string {
  return [
    "import { clsx, type ClassValue } from 'clsx';",
    "import { twMerge } from 'tailwind-merge';",
    "export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }",
    "",
  ].join("\n");
}
