import { singleGlobalsCss } from "../core/css.js";

export function singleNitroConfigTanstackContent(): string {
  return [
    "import { defineNitroConfig } from 'nitropack/config'",
    "",
    "export default defineNitroConfig({",
    "  preset: 'bun',",
    "  routeRules: {",
    "    '/**': {",
    "      headers: {",
    "        'X-Content-Type-Options': 'nosniff',",
    "        'X-Frame-Options': 'DENY',",
    "        'Referrer-Policy': 'strict-origin-when-cross-origin',",
    "        'X-XSS-Protection': '0',",
    "        'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',",
    "        'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',",
    "        'Content-Security-Policy':",
    "          \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://us.i.posthog.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self';\",",
    "      },",
    "    },",
    "  },",
    "})",
    "",
  ].join("\n");
}

export function viteSecurityHeaders(): string {
  return `        '/**': {
          headers: {
            'X-Content-Type-Options': 'nosniff',
            'X-Frame-Options': 'DENY',
            'Referrer-Policy': 'strict-origin-when-cross-origin',
            'X-XSS-Protection': '0',
            'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
            'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
            'Content-Security-Policy':
              "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://us.i.posthog.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self';",
          },
        },`;
}

export function singleViteConfigTanstackContent(): string {
  return [
    "import { defineConfig } from 'vite'",
    "import { tanstackStart } from '@tanstack/react-start/plugin/vite'",
    "import viteReact from '@vitejs/plugin-react'",
    "import tailwindcss from '@tailwindcss/vite'",
    "import { nitro } from 'nitro/vite'",
    "",
    "export default defineConfig({",
    "  server: {",
    "    port: 3000,",
    "  },",
    "  resolve: {",
    "    tsconfigPaths: true,",
    "  },",
    "  plugins: [",
    "    tailwindcss(),",
    "    tanstackStart({",
    "      srcDirectory: 'src',",
    "      router: {",
    "        routesDirectory: 'routes',",
    "      },",
    "    }),",
    "    nitro({",
    "      preset: 'bun',",
    "      routeRules: {",
    "        '/**': {",
    "          headers: {",
    "            'X-Content-Type-Options': 'nosniff',",
    "            'X-Frame-Options': 'DENY',",
    "            'Referrer-Policy': 'strict-origin-when-cross-origin',",
    "            'X-XSS-Protection': '0',",
    "            'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), interest-cohort=()',",
    "            'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',",
    "            'Content-Security-Policy':",
    "              \"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://us.i.posthog.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self';\",",
    "          },",
    "        },",
    "      },",
    "    }),",
    "    viteReact(),",
    "  ],",
    "})",
    "",
  ].join("\n");
}

export function singleRouterTanstackContent(): string {
  return [
    "import { createRouter } from '@tanstack/react-router'",
    "import { QueryClient } from '@tanstack/react-query'",
    "import { routeTree } from './routeTree.gen'",
    "",
    "export function getRouter() {",
    "  const queryClient = new QueryClient({",
    "    defaultOptions: {",
    "      queries: {",
    "        staleTime: 1000 * 60,",
    "      },",
    "    },",
    "  })",
    "",
    "  const router = createRouter({",
    "    routeTree,",
    "    context: {",
    "      queryClient,",
    "    },",
    "    scrollRestoration: true,",
    "    defaultPreload: 'intent',",
    "  })",
    "",
    "  return router",
    "}",
    "",
    "declare module '@tanstack/react-router' {",
    "  interface Register {",
    "    router: ReturnType<typeof getRouter>",
    "  }",
    "}",
    "",
  ].join("\n");
}

export function singleGlobalsCssTanstackContent(): string {
  return singleGlobalsCss();
}

export function singlePostCssTanstackContent(): string {
  return [
    '/** @type {import("postcss-load-config").Config} */',
    "const config = {",
    "  plugins: {",
    '    "@tailwindcss/postcss": {},',
    "  },",
    "};",
    "",
    "export default config;",
    "",
  ].join("\n");
}

export function singleTsConfigTanstackContent(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2024",
          lib: ["ES2024", "DOM", "DOM.Iterable"],
          jsx: "react-jsx",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          resolveJsonModule: true,
          incremental: true,
          baseUrl: ".",
          paths: {
            "@/*": ["./src/*"],
            "@/server/*": ["./src/server/*"],
            "@/components/*": ["./src/components/*"],
            "@/lib/*": ["./src/lib/*"],
          },
        },
        include: ["src/**/*", "vite.config.ts"],
        exclude: ["node_modules", ".output", "dist", ".tanstack"],
      },
      null,
      2,
    ) + "\n"
  );
}

export function singleRootRouteTanstackContent(): string {
  return [
    '/// <reference types="vite/client" />',
    "import * as React from 'react'",
    "import {",
    "  Outlet,",
    "  createRootRouteWithContext,",
    "  HeadContent,",
    "  Scripts,",
    "} from '@tanstack/react-router'",
    "import type { QueryClient } from '@tanstack/react-query'",
    "import { QueryClientProvider } from '@tanstack/react-query'",
    "import { ThemeProvider } from '@/components/theme-provider'",
    "import { Toaster } from '@/components/ui/sonner'",
    "import appCss from '@/styles/app.css?url'",
    "",
    "export const Route = createRootRouteWithContext<{",
    "  queryClient: QueryClient",
    "}>()({",
    "  head: () => ({",
    "    meta: [",
    "      { charSet: 'utf-8' },",
    "      { name: 'viewport', content: 'width=device-width, initial-scale=1' },",
    "      { title: '__PROJECT_NAME__ — GhostInit App' },",
    "    ],",
    "    links: [{ rel: 'stylesheet', href: appCss }],",
    "  }),",
    "  errorComponent: ({ error }) => (",
    "    <RootDocument>",
    "      <main className='min-h-screen bg-background flex items-center justify-center p-6'>",
    "        <div className='rounded-xl border bg-card p-6 shadow-sm max-w-[480px] w-full'>",
    "          <h1 className='text-lg font-semibold tracking-tight'>Something went wrong</h1>",
    "          <p className='text-sm text-muted-foreground max-w-[65ch] mt-2'>{String((error as any)?.message ?? error)}</p>",
    "        </div>",
    "      </main>",
    "    </RootDocument>",
    "  ),",
    "  notFoundComponent: () => (",
    "    <RootDocument>",
    "      <main className='min-h-screen bg-background flex items-center justify-center p-6'>",
    "        <div className='rounded-xl border bg-card p-6 shadow-sm max-w-[420px] w-full'>",
    "          <h1 className='text-2xl font-semibold tracking-tight'>Page not found</h1>",
    "          <p className='text-sm text-muted-foreground max-w-[60ch] mt-2'>The page does not exist.</p>",
    "        </div>",
    "      </main>",
    "    </RootDocument>",
    "  ),",
    "  component: RootComponent,",
    "})",
    "",
    "function RootComponent() {",
    "  const { queryClient } = Route.useRouteContext()",
    "  return (",
    "    <RootDocument>",
    "      <QueryClientProvider client={queryClient}>",
    "        <ThemeProvider attribute='class' defaultTheme='light' enableSystem={false} disableTransitionOnChange>",
    "          <Outlet />",
    "          <Toaster richColors position='bottom-right' />",
    "        </ThemeProvider>",
    "      </QueryClientProvider>",
    "    </RootDocument>",
    "  )",
    "}",
    "",
    "function RootDocument({ children }: { children: React.ReactNode }) {",
    "  return (",
    "    <html lang='en' suppressHydrationWarning>",
    "      <head>",
    "        <HeadContent />",
    "      </head>",
    "      <body className='antialiased bg-background text-foreground'>",
    "        {children}",
    "        <Scripts />",
    "      </body>",
    "    </html>",
    "  )",
    "}",
    "",
  ].join("\n");
}
