#!/usr/bin/env bun
/**
 * Production-grade build pipeline for ghostinit CLI
 *
 * 1. Bun.build bundles src/cli.ts -> dist/cli.js (node target, external oxc-parser)
 * 2. tsc -p src/tsconfig.json emits real .d.ts + .d.ts.map + buildinfo to dist/
 *
 * Previously: `bun build ... && echo 'export {};' > dist/cli.d.ts` produced a fake stub
 * that breaks Turborepo caching and type-checking. This script uses the proper tsc
 * declaration emitter so dist/cli.d.ts is a real compiler output with source maps.
 */

import { existsSync, readFileSync, statSync } from "node:fs";

const localTsc = [process.execPath, "./node_modules/typescript/bin/tsc"] as const;

async function main() {
  const start = performance.now();

  console.log("[build] Step 1/2: Bundling JS with Bun.build()");
  console.log("        entry: ./src/cli.ts -> ./dist/cli.js");

  const result = await Bun.build({
    entrypoints: ["./src/cli.ts"],
    outdir: "./dist",
    target: "node",
    external: ["oxc-parser"],
    minify: false,
    sourcemap: "external",
    naming: "[dir]/[name].[ext]",
    // Keep shebang: Bun preserves it automatically if source has it
  });

  if (!result.success) {
    console.error("[build] Bun.build() failed:");
    for (const log of result.logs) {
      console.error(`  ${log.level}: ${log.message}`);
      if (log.position) {
        console.error(`    at ${log.position.file}:${log.position.line}:${log.position.column}`);
      }
    }
    process.exit(1);
  }

  const bundleKiB = result.outputs.reduce((total, output) => total + output.size, 0) / 1024;
  console.log(
    `[build]   ✓ JS bundle OK (${result.outputs.length} output(s), ${bundleKiB.toFixed(1)} KiB)`,
  );

  console.log(
    "[build] Step 2/3: Building @repo/versions via tsc -p packages/versions/tsconfig.json",
  );
  {
    const proc2 = Bun.spawnSync({
      cmd: [...localTsc, "-p", "packages/versions/tsconfig.json"],
      stdout: "inherit",
      stderr: "inherit",
      cwd: process.cwd(),
    });
    if (proc2.exitCode !== 0) {
      console.error(`[build] @repo/versions build failed (exit ${proc2.exitCode})`);
      process.exit(proc2.exitCode ?? 1);
    }
  }

  console.log("[build] Step 3/3: Emitting declarations via tsc -p src/tsconfig.json");

  // src/tsconfig.json already has emitDeclarationOnly:true, outDir:../dist, rootDir:., composite:true
  // References packages/versions, so its dist must exist (built above)
  const proc = Bun.spawnSync({
    cmd: [...localTsc, "-p", "src/tsconfig.json"],
    stdout: "inherit",
    stderr: "inherit",
    cwd: process.cwd(),
  });

  if (proc.exitCode !== 0) {
    console.error(`[build] tsc declaration emit failed (exit ${proc.exitCode})`);
    process.exit(proc.exitCode ?? 1);
  }

  // Verification
  const dtsPath = "./dist/cli.d.ts";
  if (!existsSync(dtsPath)) {
    console.error(`[build] ✗ Expected ${dtsPath} not found`);
    console.error("        tsc -p src/tsconfig.json should emit it because include is **/*");
    process.exit(1);
  }

  const stat = statSync(dtsPath);
  const content = readFileSync(dtsPath, "utf8");
  const trimmed = content.trim();

  // cli.ts has no exports, so real tsc output IS `export {};` plus source map comment.
  // What we guard against is an empty file or missing sourceMappingURL indicating fake stub.
  // We accept export {} as valid IF it was generated by tsc (has sourcemap comment or > housing)
  const hasSourceMapRef = content.includes("sourceMappingURL");
  const isTooTiny = stat.size < 10;

  if (isTooTiny) {
    console.error(`[build] ✗ ${dtsPath} suspiciously tiny (${stat.size} bytes)`);
    console.error(content.slice(0, 200));
    process.exit(1);
  }

  // If file is exactly `export {};` without sourcemap, it might be the old fake stub.
  // Real tsc output: contains header comment from src/cli.ts + sourcemap ref.
  // Let's warn if no sourcemap but not fail, because composite project might still be valid.
  if (!hasSourceMapRef && trimmed === "export {};") {
    console.warn(
      `[build] ⚠ ${dtsPath} is 'export {};' without sourceMappingURL — might be old stub. Expected tsc to add //# sourceMappingURL.`,
    );
    console.warn("    Checking if declarationMap was emitted...");
    if (!existsSync("./dist/cli.d.ts.map")) {
      console.error(
        "    ✗ Missing ./dist/cli.d.ts.map — declarationMap not emitted, build incomplete",
      );
      process.exit(1);
    }
  }

  const elapsed = ((performance.now() - start) / 1000).toFixed(2);
  console.log(`[build] ✓ Declarations OK (${stat.size} bytes at ${dtsPath})`);
  console.log(`[build] Done in ${elapsed}s — outputs: dist/cli.js + dist/**/*.d.ts`);
}

await main();
