#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const GENERATED_PATH = "src/generation/embedded-template-sources.ts";

function collect(root: string, directory: string): string[] {
  const result: string[] = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) result.push(...collect(root, path));
    else if (entry.isFile() && /\.(?:ts|tsx)$/.test(entry.name)) {
      result.push(relative(root, path).replaceAll("\\", "/"));
    }
  }
  return result;
}

export function embedTemplateSources(root = process.cwd()): void {
  const templateRoot = resolve(root, "src/templates");
  const paths = collect(templateRoot, join(templateRoot, "billing")).sort();
  const entries = paths.map((path) => [
    path,
    readFileSync(join(templateRoot, ...path.split("/")), "utf8"),
  ]);
  const content =
    `// Generated by scripts/embed-template-sources.ts. Do not edit manually.\n` +
    `// Keeps production planning independent from the filesystem.\n` +
    `export const EMBEDDED_TEMPLATE_SOURCES: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(Object.fromEntries(entries), null, 2)});\n`;
  writeFileSync(resolve(root, GENERATED_PATH), content, "utf8");
  const formatted = Bun.spawnSync({
    cmd: [process.execPath, "x", "--no-install", "oxfmt", "--write", GENERATED_PATH],
    cwd: root,
    stdout: "ignore",
    stderr: "pipe",
  });
  if (formatted.exitCode !== 0) {
    throw new Error(`Unable to format ${GENERATED_PATH}: ${formatted.stderr.toString()}`);
  }
}

if (import.meta.main) embedTemplateSources();
