#!/usr/bin/env bun
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { FsTransaction } from "../src/lib/fs.js";

const GENERATED_PATH = "src/generation/embedded-frontend-runtime.ts";

/** Compile the same checked policy engine for the generated Node/Bun lint entrypoint. */
export async function embedFrontendRuntime(root = process.cwd()): Promise<void> {
  const result = await Bun.build({
    entrypoints: [resolve(root, "src/lib/architecture/frontend/runner.ts")],
    target: "node",
    format: "cjs",
    minify: false,
    sourcemap: "none",
    external: ["oxc-parser"],
  });
  if (!result.success || result.outputs.length !== 1) {
    throw new Error(`Unable to bundle the frontend ownership policy: ${result.logs.join("\n")}`);
  }
  const source = (await result.outputs[0]!.text()).replace(/\r\n?/g, "\n");
  const digest = createHash("sha256").update(source).digest("hex");
  const content =
    "// Generated by scripts/embed-frontend-runtime.ts. Do not edit manually.\n" +
    "// CLI checks and generated lint share src/lib/architecture/frontend/index.ts.\n" +
    `export const FRONTEND_OWNERSHIP_RUNTIME_SHA256 = ${JSON.stringify(digest)};\n` +
    `export const FRONTEND_OWNERSHIP_RUNTIME = ${JSON.stringify(source)};\n`;
  const transaction = new FsTransaction(root);
  await transaction.write(GENERATED_PATH, content);
  await transaction.commit();
  const formatted = Bun.spawnSync({
    cmd: [process.execPath, "x", "--no-install", "oxfmt", "--write", GENERATED_PATH],
    cwd: root,
    stdout: "ignore",
    stderr: "pipe",
  });
  if (formatted.exitCode !== 0) {
    throw new Error(`Unable to format ${GENERATED_PATH}: ${formatted.stderr.toString()}`);
  }
}

if (import.meta.main) await embedFrontendRuntime();
