#!/usr/bin/env bun
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createRequire, isBuiltin } from "node:module";
import { resolve } from "node:path";
import { format } from "oxfmt";
import { validation } from "../packages/versions/src/index.js";
import { FsTransaction } from "../src/lib/fs.js";
import { DEPENDENCY_SECURITY_RUNTIME_PATH } from "../src/domain/dependency-security/artifacts.js";

const GENERATED_PATH = "src/generation/embedded-dependency-security-runtime.ts";

export interface DependencySecurityBundleReceipt {
  readonly bytes: number;
  readonly sha256: string;
  readonly inputs: readonly string[];
  readonly externalImports: readonly string[];
}

export interface DependencySecurityRuntimeArtifact {
  readonly source: string;
  readonly moduleContent: string;
  readonly receipt: DependencySecurityBundleReceipt;
}

function rejectCompilerInput(path: string): void {
  const normalized = path.replaceAll("\\", "/");
  if (
    /(?:^|\/)src\/(?:templates|generation|commands)\//.test(normalized) ||
    /(?:^|\/)oxc-parser(?:@|\/|$)/.test(normalized)
  ) {
    throw new Error(
      "Dependency security runtime cannot include compiler or renderer code: " + path,
    );
  }
}

/** Check actual bundle closure, including CommonJS require and dynamic import references. */
export function verifyDependencySecurityBundle(
  source: string,
  metadata: Bun.BuildMetafile,
): DependencySecurityBundleReceipt {
  const inputs = Object.keys(metadata.inputs).sort();
  for (const path of inputs) rejectCompilerInput(path);
  const parser = new Bun.Transpiler({ loader: "js", target: "node" });
  // Bun 1.4 input edges can retain external=true for imports later bundled into
  // the output; only emitted references define runtime dependencies.
  const references = [
    ...parser.scanImports(source),
    ...Object.values(metadata.outputs).flatMap((output) => output.imports),
  ];
  const externalImports = [...new Set(references.map(({ path }) => path))].sort();
  for (const path of externalImports) {
    if (!isBuiltin(path)) {
      throw new Error("Dependency security runtime has a non-builtin external import: " + path);
    }
  }
  return {
    bytes: Buffer.byteLength(source),
    sha256: createHash("sha256").update(source).digest("hex"),
    inputs,
    externalImports,
  };
}

/** Build and render in memory; source and committed artifacts are never modified. */
export async function buildDependencySecurityRuntimeArtifact(
  root = process.cwd(),
): Promise<DependencySecurityRuntimeArtifact> {
  const requirePackage = createRequire(import.meta.url);
  const zodPackage: unknown = JSON.parse(
    readFileSync(requirePackage.resolve("zod/package.json"), "utf8"),
  );
  if (
    typeof zodPackage !== "object" ||
    zodPackage === null ||
    !("name" in zodPackage) ||
    zodPackage.name !== "zod" ||
    !("version" in zodPackage) ||
    zodPackage.version !== validation.zod
  ) {
    throw new Error("Dependency security bundling requires the catalog-pinned Zod package");
  }
  // Bun 1.4 miscompiles the ESM namespace binding used by z.enum(), in both
  // output formats. Resolve the package's published require export instead;
  // it is still bundled, with no application-side Zod dependency.
  const zodRequireEntry = requirePackage.resolve("zod");
  const result = await Bun.build({
    entrypoints: [resolve(root, "src/lib/dependency-security/runtime.ts")],
    target: "node",
    format: "cjs",
    minify: false,
    sourcemap: "none",
    metafile: true,
    throw: false,
    plugins: [
      {
        name: "dependency-security-standalone-boundary",
        setup(build) {
          build.onResolve({ filter: /.*/ }, ({ path }) => {
            if (isBuiltin(path)) return { path, external: true };
            rejectCompilerInput(path);
            if (path === "zod") return { path: zodRequireEntry };
            return undefined;
          });
          build.onLoad({ filter: /.*/ }, ({ path }) => {
            rejectCompilerInput(path);
            return undefined;
          });
        },
      },
    ],
  });
  if (!result.success || result.outputs.length !== 1 || !result.metafile) {
    throw new Error("Unable to bundle the dependency security runtime: " + result.logs.join("\n"));
  }
  const rawSource = (await result.outputs[0]!.text()).replace(/\r\n?/g, "\n");
  const canonicalRuntime = await format(DEPENDENCY_SECURITY_RUNTIME_PATH, rawSource);
  if (canonicalRuntime.errors.length > 0) {
    throw new Error(
      "Unable to format the compiled dependency security runtime: " +
        JSON.stringify(canonicalRuntime.errors),
    );
  }
  const source = canonicalRuntime.code;
  const receipt = verifyDependencySecurityBundle(source, result.metafile);
  const content =
    "// Generated by scripts/embed-dependency-security-runtime.ts. Do not edit manually.\n" +
    "// Host and generated maintenance share src/lib/dependency-security/runtime.ts.\n" +
    `export const DEPENDENCY_SECURITY_RUNTIME_SHA256 = ${JSON.stringify(receipt.sha256)};\n` +
    `export const DEPENDENCY_SECURITY_RUNTIME = ${JSON.stringify(source)};\n`;
  const formatted = await format(GENERATED_PATH, content);
  if (formatted.errors.length > 0) {
    throw new Error("Unable to format " + GENERATED_PATH + ": " + JSON.stringify(formatted.errors));
  }
  return { source, moduleContent: formatted.code, receipt };
}

/** Publish only the validated output of the same read-only build/render recipe. */
export async function embedDependencySecurityRuntime(
  root = process.cwd(),
): Promise<DependencySecurityBundleReceipt> {
  const artifact = await buildDependencySecurityRuntimeArtifact(root);
  const transaction = new FsTransaction(root);
  await transaction.write(GENERATED_PATH, artifact.moduleContent);
  await transaction.commit();
  return artifact.receipt;
}

if (import.meta.main) console.log(JSON.stringify(await embedDependencySecurityRuntime(), null, 2));
