/**
 * Maestro E2E harness for Expo — config + example flow
 * Generated when apps includes mobile
 */

export function maestroConfigContent(): string {
  return `appId: com.ghostinit.\${APP_ID}
---
- launchApp
- tapOn: "Sign In"
- inputText: "test@example.com"
- tapOn: "Continue"
- assertVisible: "Dashboard"
`;
}

export function maestroFlowContent(): string {
  return `# flow: auth.yaml — generated by ghostinit
appId: \${APP_ID}
---
- launchApp:
    clearState: true
- tapOn:
    text: "Sign In"
- inputText: "test@example.com"
- tapOn:
    text: "Password"
- inputText: "password123"
- tapOn:
    text: "Sign In"
- extendedWaitUntil:
    visible: "Dashboard"
    timeout: 10000
- assertVisible: "Billing"
`;
}
