import type { BillingProviderName } from "../../../../lib/addons.js";

export function buildAgentsMdContent(
  projectName: string,
  selectedBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
): string {
  const lines: string[] = [];
  lines.push("# AGENTS.md — " + projectName);
  lines.push("");
  lines.push(
    "> Generated by GhostInit single mode — flat Next.js all-in-one src/ + server/ + agent/ if eve. Bun only.",
  );
  lines.push("");
  lines.push("## Snapshot");
  lines.push("");
  lines.push("- Name: " + projectName);
  lines.push(
    "- Mode: single (flat Next.js all-in-one src/app + server/ + agent/ if eve, no workspaces)",
  );
  lines.push("- Runtime: bun only (bun 1.3.14, bunfig.toml hoist false, bun.lock or npm)");
  lines.push(
    "- Stack: Next.js 16.2.10 App Router React 19.2.7 TS 7.0.2 Drizzle 0.45.2 PG 18.4 Better Auth 1.6.23 Resend 4.0.1 Zod 4.4.3 TanStack Query 5.101.2 Form 1.33.1 Tailwind 4.3.2 Base UI 1.6.0 eve 0.24.6 if chosen",
  );
  lines.push(
    "- Billing: " +
      (selectedBilling.length === 0
        ? "none selected, UI shows No billing configured + Button Add billing provider"
        : selectedBilling.join(",")),
  );
  lines.push("- Features: eve=" + hasEve + " i18n=" + hasI18n);
  lines.push("");
  lines.push("## Package Roles — Single Mode Flat");
  lines.push("");
  lines.push(
    "- **src/app/** UI Layer 1 + Transport: marketing / page.tsx, layout.tsx globals.css tailwind @import, sign-in TanStack Form FieldGroup Field validators email contains @ password >=8 authClient.signIn.email, sign-up, 2fa code regex 6 digits, dashboard RSC protected auth.api.getSession(headers) redirect /sign-in, settings layout, admin guard role admin, billing page tabs per provider via billingUiFiles single mode shadcn Tabs+Card+Table+Badge+Alert+Empty+Sonner, agent page if eve useEveAgent chat, forgot-password page.tsx FieldGroup Field email contains @ authClient.forgetPassword redirectTo /reset-password, reset-password page.tsx FieldGroup Field password >=8 authClient.resetPassword token searchParams",
  );
  lines.push(
    "- **src/server/** capabilities: services/ business logic src/server/services/billing/create-checkout.service.ts transactional boundary BillingProviderPort, email/send-reset-password.service.ts Resend behind port, invoices/create-invoice.service.ts spanning modules belongs services not module, Result ok/err local lib/result.ts",
  );
  lines.push(
    "- **src/server/billing/** vendors layer 5 abstraction: interface.ts port stable, domain/types.ts, schema/billing.ts provider enum billing_provider stripe|chargily|paddle|polar subscriptions checkouts invoices customers products prices license_keys usage_events webhook_events unique provider+providerEventId onConflictDoNothing, providers stripe.ts Stripe(SECRET,{apiVersion:'2025-03-31.basil'}) checkout.sessions.create line_items mode subscription automatic_tax success_url cancel_url billingPortal.sessions.create, chargily.ts ChargilyClient server-only checkout_url edahabia|cib payment_method verifySignature raw Buffer 400 missing 403 invalid, paddle.ts Paddle API_KEY transactions.create checkout url TransactionCompleted paddle-signature unmarshal raw body string, polar.ts Polar accessToken checkouts.create products customerName checkout url events.ingest metering license seats @polar-sh/nextjs Webhooks validateEvent whsec base64",
  );
  lines.push(
    "- **src/server/email/** Resend default: constants.ts EMAIL_FROM, index.ts Resend client warns if REPLACE_WITH placeholder, send.ts wrapper, templates forgot-password.tsx reset-password.tsx HTML tables",
  );
  lines.push(
    "- **src/server/db/** Drizzle pool max 20 idle 30s SSL, schema/auth.ts users sessions accounts verifications twoFactor, schema/billing.ts shared, index.ts builds connectionString from DATABASE_URL or POSTGRES_* fallback",
  );
  lines.push(
    "- **src/server/auth/** Better Auth 1.6.23 emailAndPassword autoSignIn false SECURITY user delete enabled session cookieCache compact httpOnly secure sameSite lax rateLimit memory window 60 max 100 IP disabled unless TRUSTED_PROXY, plugins admin twoFactor nextCookies, sendResetPassword hook Resend via forgotPasswordTemplate",
  );
  lines.push(
    "- **src/lib/** auth-client.ts createAuthClient twoFactorClient onTwoFactorRedirect /2fa adminClient, orpc.ts typed client, utils.ts cn clsx+twMerge",
  );
  lines.push(
    "- **src/components/ui/** shadcn Base UI button card dialog tabs badge alert empty sonner skeleton separator field etc via bunx --bun shadcn@latest add",
  );
  if (hasEve) {
    lines.push(
      '- **agent/** Eve durable backend when hasEve: agent/ folder inside Next root mounted same-origin via withEve({eveRoot:"./agent"}) per task requirement must include withEve and eveRoot ./agent. agent/agent.ts defineAgent anthropic/claude-sonnet-5, instructions.md identity purpose, tools defineTool zod inputSchema execute ctx.session/callId/toolName/abortSignal/getSandbox/getSkill approval always/once/never, skills ghostinit-workflow module-design SKILL.md, channels/eve.ts HTTP default auth vercelOidc localDev, schedules/sync-check.md cron 0 * * * * hourly + billing-renewal.md 0 2 1 * * monthly Chargily checkout-only recurring via DB subscriptions new checkout edahabia cib. Single dev server single deploy cookie auth flows useEveAgent.',
    );
  } else {
    lines.push(
      '- **agent/** not present unless eve feature selected — when enabled via withEve({eveRoot:"./agent"}) hybrid same-origin zero CORS single dev deploy',
    );
  }
  lines.push("");
  lines.push(
    "## Design System — Unified (monorepo + single) — Must Follow — Single Mode Paths src/*",
  );
  lines.push("");
  lines.push("### Overview — single emphases");
  lines.push(
    "- Unified with monorepo — same OKLCH paper white tinted neutrals chroma 0.005-0.01, indigo accent ≤10%, no #000/#fff extremes, 32 tokens, next-themes 0.4.6 @custom-variant dark .dark",
  );
  lines.push(
    "- Single paths: src/components/ui/* vs monorepo packages/ui, src/lib/utils.ts vs packages/ui lib, @/components/ui/* alias vs @repo/ui, src/app/globals.css contains @import tailwindcss and tokens, src/components/theme-provider.tsx + theme-toggle.tsx + providers.tsx same functionality as apps/web/src/components/*",
  );
  lines.push(
    "- Marketing, auth, dashboard, settings, billing, admin pages under src/app/* use same card/badge/alert patterns as monorepo apps/web/*",
  );
  lines.push("");
  lines.push("### Tokens — :root same as monorepo");
  lines.push("- --background: oklch(0.99 0.002 106) paper tinted");
  lines.push("- --foreground: oklch(0.21 0.01 264) deep indigo-gray");
  lines.push("- --primary: 0.55 0.22 264 indigo, --primary-foreground 0.985");
  lines.push("- --secondary: 0.967 0.005 264 tinted gray, muted same 0.967");
  lines.push("- --accent 0.96 0.01 264, destructive 0.58 0.22 27, border 0.92 0.005 264");
  lines.push(
    "- @theme inline mapping identical, @layer base * border-border outline-ring/50 body bg-background text-foreground antialiased",
  );
  lines.push("");
  lines.push("### Dark — .dark");
  lines.push(
    "- --background 0.17 0.01 264, --foreground 0.96 0.005, --card 0.21 0.012, border 10% white",
  );
  lines.push("");
  lines.push("### Tailwind v4");
  lines.push(
    '- @import "tailwindcss"; first line globals.css, @custom-variant dark (&:is(.dark *));',
  );
  lines.push("- postcss.config.mjs @tailwindcss/postcss plugin");
  lines.push("");
  lines.push("### shadcn Composition Rules — Single mode same");
  lines.push(
    "- Use existing src/components/ui/* first — Button Card Badge Alert Tabs Form Field Dialog DropdownMenu Avatar Skeleton Separator Empty Sonner etc",
  );
  lines.push(
    "- Semantic tokens only: bg-background text-foreground bg-primary text-muted-foreground etc never raw bg-blue-500",
  );
  lines.push("- Form: FieldGroup + Field + FieldLabel + FieldDescription/FieldError");
  lines.push("- Full Card: CardHeader/Title/Description/Content/Footer never dump in Content only");
  lines.push("");
  lines.push("### File Architecture <300 lines — Single mode paths");
  lines.push(
    "- EVERY generated file <300 lines — if would exceed split into src/app/<route>/components/* + hooks/* + src/hooks/*",
  );
  lines.push("- Max 263, avg 47, target <60 avg");
  lines.push("- No window.confirm — Dialog with Title Description Footer required");
  lines.push("");
  lines.push("### Next-themes — Single");
  lines.push(
    "- theme-provider.tsx: ThemeProvider as NextThemesProvider attribute class defaultTheme light enableSystem false",
  );
  lines.push(
    "- providers.tsx: Providers 'use client' useState QueryClient QueryClientProvider + ThemeProvider + Toaster",
  );
  lines.push("- theme-toggle.tsx: useTheme mounted guard");
  lines.push("- header.tsx includes ThemeToggle always");
  lines.push("");
  lines.push("### Pages Setup Well — Single paths src/app/*");
  lines.push("- Marketing, Auth, Dashboard, Settings, Billing, Admin, Not-found, Error, Loading");
  lines.push("");
  lines.push("### Billing Flexible — Algeria + Global — Single");
  lines.push(
    "- Chargily Algeria EDAHABIA/CIB server-only checkout-only, Stripe global cards, Paddle MoR 5%+50c, Polar MoR 4%+40c",
  );
  lines.push(
    "- Combos: none => Empty No billing configured; single provider Card single; Chargily+global dual-market",
  );
  lines.push("");
  lines.push("### Constraints — Impeccable Bans — Must Enforce Single");
  lines.push("- No side-stripe border-left >1px colored accent");
  lines.push("- No gradient text background-clip:text");
  lines.push("- No glassmorphism as default decorative blur cards (except header blur allowed)");
  lines.push(
    "- No identical card grids icon+heading+text repeated same col-span — varied md:grid-cols-12 7/5 asymmetry",
  );
  lines.push("- No em dashes — use commas colons periods");
  lines.push(
    "- Typography cap body 65-75ch max-w-[65ch], hierarchy ≥1.25 scale, tracking-tight titles only",
  );
  lines.push("- No slate- colors never border-slate-300 bg-slate — use border-border bg-muted");
  lines.push("- No bg-white bg-black raw — bg-background bg-card");
  lines.push("- No space-x/y — flex gap, No w-* h-* for square icons — size-*");
  lines.push(
    "- No window.confirm/prompt — Dialog, No inline style display:inline-block — className",
  );
  lines.push("");
  lines.push("### Agent Guidance New Components — Single");
  lines.push("- Before new component search existing src/components/ui/*");
  lines.push(
    "- If need new use Base UI primitive @base-ui/react/* + cva + cn() + data-slot + semantic tokens only, file <300 lines",
  );
  lines.push("");
  lines.push("## Quality Gates");
  lines.push("");
  lines.push("- bun only, tsc --noEmit typecheck, oxlint lint, oxfmt --check format:check");
  lines.push("- bun test --timeout 100000 test, bun run build next build");
  lines.push("- ghostinit check — architecture checker, ghostinit sync --check, ghostinit doctor");
  lines.push("");
  lines.push("## Security");
  lines.push(
    ".env.local gitignored real 48-byte base64url secrets validated ^[A-Za-z0-9_-]+$ length>=32. BETTER_AUTH_SECRET min32 localhost warning autoSignIn false cookieCache compact httpOnly secure sameSite lax rateLimit 60 100 IP disabled unless TRUSTED_PROXY. Billing server-only NEVER client except NEXT_PUBLIC_ publishable/client tokens. Chargily server-only! logger redacts secret. OpenAPI 404 prod, auth 405, security headers nosniff Referrer-Policy CSP default-src self.",
  );
  lines.push("");
  lines.push("## Notes for Codex / Claude / Cursor / Windsurf");
  lines.push("- No workspaces in package.json — private true type module single");
  lines.push("- Import alias @/* -> ./src/*, @/server/* -> ./src/server/* etc via tsconfig paths");
  lines.push("");
  return lines.join("\n") + "\n";
}
