import { file, type TemplateFile } from "../../../shared.js";
import type { BillingProviderName } from "../../../../lib/addons.js";
import { buildAgentsMdContent } from "./agents-content.js";

export { buildAgentsMdContent } from "./agents-content.js";

export function updatedAgentsMd(
  projectName: string,
  selectedBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  hasEmail = true,
): TemplateFile {
  const content = buildAgentsMdContent(projectName, selectedBilling, hasEve, hasI18n, hasEmail);
  return file("AGENTS.md", content);
}

export function claudeMdFromAgents(agentsFile: TemplateFile): TemplateFile {
  return file("CLAUDE.md", agentsFile.content);
}
export function cursorRulesFromAgents(agentsFile: TemplateFile): TemplateFile {
  const headerLines = [
    "---",
    'description: GhostInit single flat — Next.js DDD oRPC Better Auth Drizzle billing services layered + agent/ withEve({eveRoot:"./agent"})',
    "globs:",
    '  - "**/*"',
    "alwaysApply: true",
    "---",
    "",
  ];
  return file(".cursor/rules/ghostinit.mdc", headerLines.join("\n") + agentsFile.content);
}
export function windsurfFromAgents(agentsFile: TemplateFile): TemplateFile {
  return file(".windsurf/rules/ghostinit.md", agentsFile.content);
}

export function gitignoreSingle(): TemplateFile {
  return file(
    ".gitignore",
    [
      "# Dependencies and artifacts",
      "node_modules",
      "dist",
      ".next",
      "*.map",
      "*.tsbuildinfo",
      "",
      "# GhostInit internal state",
      ".ghostinit/",
      ".ghostinit.lock",
      "",
      "# Environment files - never commit secrets",
      ".env",
      ".env.local",
      ".env.*.local",
      ".env.production",
      ".env.development",
      ".DS_Store",
      "*.log",
      "coverage",
      "playwright-report",
      "test-results",
      "",
    ].join("\n"),
  );
}

export function readmeSingle(projectName: string): TemplateFile {
  return file(
    "README.md",
    [
      "# " + projectName,
      "",
      "Generated by [GhostInit](https://github.com/ghostinit/ghostinit) — single all-in-one flat Next.js mode.",
      "",
      "## Getting Started",
      "",
      "```bash",
      "cp .env.example .env.local",
      "bun install",
      "docker compose up -d",
      "bun run db:generate",
      "bun run db:migrate",
      "bun run dev",
      "```",
      "",
      'Flat structure: `src/app/` UI, `src/server/` capabilities billing/services/email/db/auth, `src/components/ui/` shadcn, `agent/` eve durable if enabled with `withEve({ eveRoot: "./agent" })`.',
      "",
      "## Billing",
      "",
      "Flexible billing providers any combo none/both/one/all: stripe, chargily, paddle, polar. Env placeholders REPLACE_WITH... real secrets via secret() 48-byte base64url gitignored.",
      "",
      "## Quality Gates",
      "",
      "- `bun run typecheck`",
      "- `bun run lint` + `format:check`",
      "- `bun test`",
      "- `bun run build`",
      "- `ghostinit check`",
      "- `ghostinit sync --check`",
      "",
    ].join("\n"),
  );
}
