import { file, type TemplateFile } from "../../../shared.js";
import { generatedGitignoreContent } from "../../../gitignore.js";
import * as v from "../../../versions.js";
import type { AppName, BillingProviderName, FrameworkName } from "../../../../lib/addons.js";
import { buildAgentsMdContent } from "./agents-content.js";
import type { SingleAgentDocsOptions } from "./agents-content.js";

export { buildAgentsMdContent } from "./agents-content.js";

export function updatedAgentsMd(
  projectName: string,
  selectedBilling: BillingProviderName[],
  hasEve: boolean,
  hasI18n: boolean,
  hasEmail = true,
  framework: FrameworkName = "nextjs",
  options: SingleAgentDocsOptions = {},
): TemplateFile {
  const content = buildAgentsMdContent(
    projectName,
    selectedBilling,
    hasEve,
    hasI18n,
    hasEmail,
    framework,
    options,
  );
  return file("AGENTS.md", content);
}

export function claudeMdFromAgents(agentsFile: TemplateFile): TemplateFile {
  return file("CLAUDE.md", agentsFile.content);
}
export function cursorRulesFromAgents(agentsFile: TemplateFile): TemplateFile {
  const headerLines = [
    "---",
    "description: GhostInit single-mode generated-project rules",
    "globs:",
    '  - "**/*"',
    "alwaysApply: true",
    "---",
    "",
  ];
  return file(".cursor/rules/ghostinit.mdc", headerLines.join("\n") + agentsFile.content);
}
export function windsurfFromAgents(agentsFile: TemplateFile): TemplateFile {
  return file(".windsurf/rules/ghostinit.md", agentsFile.content);
}

export function gitignoreSingle(): TemplateFile {
  return file(".gitignore", generatedGitignoreContent());
}

export interface SingleReadmeOptions {
  framework?: FrameworkName;
  hasEve?: boolean;
  apps?: readonly AppName[];
}

export function readmeSingle(
  projectName: string,
  hasEmail = true,
  options: SingleReadmeOptions = {},
): TemplateFile {
  const framework = options.framework ?? "nextjs";
  const apps = options.apps?.length ? options.apps : (["web"] as const);
  const nativeApp =
    apps.length === 1 && (apps[0] === "mobile" || apps[0] === "desktop") ? apps[0] : undefined;
  if (nativeApp !== undefined) {
    const label = nativeApp === "mobile" ? "Expo mobile" : "Electron desktop";
    const structure =
      nativeApp === "mobile"
        ? "`app/` contains Expo routes and `src/` contains client components and local adapters."
        : "`src/main.ts` and `src/preload.ts` isolate privileged Electron APIs; `src/renderer/` contains the client UI.";
    return file(
      "README.md",
      [
        "# " + projectName,
        "",
        `Generated by [GhostInit](https://github.com/ghostinit/ghostinit) as a single-package ${label} frontend.`,
        "",
        `Dependency installs reject package versions published less than ${v.supplyChain.minimumReleaseAgeSeconds} seconds ago. The generated \`bunfig.toml\` has no minimum-release-age exclusions.`,
        "",
        "This target does not generate a backend host, database adapter, provider SDK, webhook, or remote-backend selection contract. Use monorepo mode with `--apps web," +
          nativeApp +
          "` when auth, API, billing, messaging, storage, PDF, Eve, notifications, remote feature flags, jobs, or other server-backed capabilities are required.",
        "",
        "## Getting Started",
        "",
        "```bash",
        "bun run install:verified # use bun run install:bootstrap only for fresh --no-install output",
        "bun run dev",
        "bun run typecheck",
        "bun run lint",
        "bun run build",
        "```",
        "",
        structure,
        "Client-local analytics and i18n remain available when selected. Keep server credentials out of the native bundle.",
        "",
      ].join("\n"),
    );
  }
  const isTanstack = framework === "tanstack-start";
  const frameworkLabel = isTanstack ? "TanStack Start" : "Next.js";
  const applicationPaths = isTanstack
    ? "`src/routes/` UI, `src/server/` backend capabilities, and `src/components/ui/` shared primitives"
    : "`src/app/` UI, `src/server/` backend capabilities, and `src/components/ui/` shared primitives";
  const eveDescription = !options.hasEve
    ? []
    : isTanstack
      ? [
          "",
          "## Eve",
          "",
          "The project root is the Eve application root and `agent/` contains the authored durable-agent surface. This TanStack Start output does not generate a framework mounting adapter; run Eve as a standalone backend and configure clients with its host when needed.",
          "",
          "Use `bun run eve:dev` and `bun run eve:start` for the standalone Eve process. The TanStack Start web process remains a separate host.",
        ]
      : [
          "",
          "## Eve",
          "",
          "The project root is the Eve application root and `agent/` contains the authored durable-agent surface. `next.config.ts` uses `withEve(config)`, which discovers `agent/` and exposes the Eve HTTP routes on the Next.js origin while Eve remains a separate backend runtime.",
          "",
          "`bun run dev` and `bun run start` own the integrated Next.js and Eve lifecycle. Use `bun run eve:dev` or `bun run eve:start` only for explicit backend diagnostics. Outside Vercel, `bun run build` builds Eve before Next.js; Vercel lets `withEve` build its generated service.",
        ];
  return file(
    "README.md",
    [
      "# " + projectName,
      "",
      `Generated by [GhostInit](https://github.com/ghostinit/ghostinit) in single-package ${frameworkLabel} mode.`,
      "",
      `Dependency installs reject package versions published less than ${v.supplyChain.minimumReleaseAgeSeconds} seconds ago. The generated \`bunfig.toml\` has no minimum-release-age exclusions.`,
      "",
      "## Getting Started",
      "",
      "```bash",
      "# GhostInit already generated .env.local; review vendor placeholders without overwriting its self-issued secrets.",
      "bun run install:verified # use bun run install:bootstrap only for fresh --no-install output",
      "docker compose --env-file .env.local up -d",
      "bun run db:generate",
      "bun run db:migrate",
      "bun run dev",
      "```",
      "",
      `Application structure: ${applicationPaths}${hasEmail ? ", including the selected email capability" : ""}.`,
      ...(hasEmail
        ? []
        : [
            "Email/password signup, sign-in, verification, magic-link, and reset are disabled because the email capability is not selected. Configure Google or GitHub OAuth credentials, or regenerate with email enabled.",
          ]),
      ...eveDescription,
      "",
      "## Billing",
      "",
      "Flexible billing providers any combo none/both/one/all: stripe, chargily, paddle, polar. Env placeholders REPLACE_WITH... real secrets via secret() 48-byte base64url gitignored.",
      "",
      "## Quality Gates",
      "",
      "- `bun run typecheck`",
      "- `bun run lint` + `format:check`",
      "- `bun test`",
      "- `bun run build`",
      "- `ghostinit check`",
      "- `ghostinit sync --check`",
      "",
    ].join("\n"),
  );
}
