import type { ProjectMode } from "../../../lib/addons.js";
import { authNetworkSecurityHelpers, durableAuthRateLimitConfig } from "../../auth-security.js";
import {
  profileUpdateValidationContent,
  profileUpdateValidationImports,
} from "../../auth-profile.js";

export function convexAuthContent(
  mode: ProjectMode,
  hasEmail = true,
  hasI18n = false,
  hasMobile = false,
  hasManualBilling = false,
): string {
  void mode;
  const authEmailLocaleLines = !hasEmail
    ? []
    : hasI18n
      ? [
          'type AuthEmailLocale = "en" | "fr" | "ar";',
          "function normalizeAuthEmailLocale(value: unknown): AuthEmailLocale | null {",
          '  if (typeof value !== "string") return null;',
          "  const language = value.trim().toLowerCase().split(/[-_]/, 1)[0];",
          '  return language === "en" || language === "fr" || language === "ar" ? language : null;',
          "}",
          "function authEmailLocale(request?: Request): AuthEmailLocale {",
          '  const cookie = request?.headers.get("cookie");',
          '  for (const entry of cookie?.split(";") ?? []) {',
          '    const separator = entry.indexOf("=");',
          '    if (separator < 0 || entry.slice(0, separator).trim() !== "NEXT_LOCALE") continue;',
          "    try {",
          "      const locale = normalizeAuthEmailLocale(decodeURIComponent(entry.slice(separator + 1).trim()));",
          "      if (locale) return locale;",
          "    } catch {}",
          "  }",
          '  const accepted = request?.headers.get("accept-language");',
          "  const preferences: Array<{ locale: AuthEmailLocale; quality: number; order: number }> = [];",
          '  accepted?.split(",").forEach((entry, order) => {',
          '    const [tag = "", ...parameters] = entry.trim().split(";");',
          "    const locale = normalizeAuthEmailLocale(tag);",
          "    if (!locale) return;",
          '    const parameter = parameters.find((value) => value.trim().startsWith("q="));',
          "    const parsed = parameter ? Number.parseFloat(parameter.trim().slice(2)) : 1;",
          "    const quality = Number.isFinite(parsed) ? parsed : 0;",
          "    if (quality > 0) preferences.push({ locale, quality, order });",
          "  });",
          "  preferences.sort((left, right) => right.quality - left.quality || left.order - right.order);",
          '  return preferences[0]?.locale ?? "en";',
          "}",
          "",
        ]
      : [
          'type AuthEmailLocale = "en";',
          'function authEmailLocale(_request?: Request): AuthEmailLocale { return "en"; }',
          "",
        ];
  return [
    'import { createClient, type AuthFunctions, type GenericCtx } from "@convex-dev/better-auth";',
    'import { convex, crossDomain } from "@convex-dev/better-auth/plugins";',
    'import { components, internal } from "./_generated/api";',
    'import type { DataModel } from "./_generated/dataModel";',
    'import { betterAuth, type BetterAuthOptions } from "better-auth/minimal";',
    ...profileUpdateValidationImports.split("\n"),
    'import { twoFactor } from "better-auth/plugins/two-factor";',
    ...(hasMobile ? ['import { expo } from "@better-auth/expo";'] : []),
    ...(hasEmail ? ['import { magicLink } from "better-auth/plugins/magic-link";'] : []),
    'import { ConvexError } from "convex/values";',
    'import authConfig from "./auth.config";',
    'import { query } from "./_generated/server";',
    ...(hasManualBilling
      ? ['import { assertManualPaymentDeletionAllowed } from "./manualPaymentRetention";']
      : []),
    "",
    "// Env validation — no insecure https://example.com fallback, require SITE_URL",
    "function requireEnv(name: string): string {",
    "  const value = process.env[name];",
    '  if (!value || value.startsWith("REPLACE_WITH") || value.trim() === "") {',
    "    throw new Error(`[convex/auth] Missing required env ${name}. Set it in the target Convex deployment environment or dashboard`);",
    "  }",
    "  return value;",
    "}",
    "",
    "function optionalEnv(name: string): string | undefined {",
    "  const v = process.env[name];",
    '  if (!v || v.startsWith("REPLACE_WITH")) return undefined;',
    "  return v;",
    "}",
    "",
    "function isLocalHostname(hostname: string): boolean {",
    '  return hostname === "localhost" || hostname === "127.0.0.1" || hostname === "0.0.0.0" || hostname === "::1" || hostname === "[::1]";',
    "}",
    "",
    "function requireHttpUrl(name: string, value: string): string {",
    "  let parsed: URL;",
    "  try {",
    "    parsed = new URL(value);",
    "  } catch {",
    "    throw new Error(`[convex/auth] ${name} must be a valid absolute URL`);",
    "  }",
    '  if (parsed.protocol !== "https:" && parsed.protocol !== "http:") {',
    "    throw new Error(`[convex/auth] ${name} must use http or https`);",
    "  }",
    '  if (parsed.protocol !== "https:" && !isLocalHostname(parsed.hostname)) {',
    "    throw new Error(`[convex/auth] ${name} must use https unless it targets localhost`);",
    "  }",
    '  return parsed.toString().replace(/\\/$/, "");',
    "}",
    "",
    "function resolveSiteUrl(): string {",
    "  const url = process.env.SITE_URL ?? process.env.CONVEX_SITE_URL;",
    '  if (!url || url.startsWith("REPLACE_WITH") || url === "https://example.com") {',
    '    throw new Error("[convex/auth] SITE_URL or CONVEX_SITE_URL must be set to your app URL (e.g. https://app.example.test or http://localhost:3000). No insecure fallback allowed.");',
    "  }",
    '  return requireHttpUrl("SITE_URL", url);',
    "}",
    "",
    "function validateSecret(secret: string | undefined): string {",
    '  if (!secret || secret.length < 32 || secret.startsWith("REPLACE_WITH")) {',
    '    throw new Error("BETTER_AUTH_SECRET must be set to a strong random value (>=32 chars), not placeholder");',
    "  }",
    "  return secret;",
    "}",
    "",
    "const siteUrl = resolveSiteUrl();",
    "",
    ...authNetworkSecurityHelpers.split("\n"),
    ...profileUpdateValidationContent().split("\n"),
    "",
    "// The installed Convex component has a static schema. Only advertise the plugin it contains.",
    'export const selectedIdentityPlugins = ["two-factor"] as const;',
    'export const rejectedIdentityPlugins = ["admin", "passkey", "organization"] as const;',
    "",
    "const authFunctions: AuthFunctions = internal.auth;",
    "",
    "// Identity and app-user records live in separate stores. These idempotent triggers",
    "// synchronize identity fields, but application authorization fails closed until the",
    "// mapping exists; no cross-store atomicity is assumed.",
    "export const authComponent = createClient<DataModel>(components.betterAuth, {",
    "  authFunctions,",
    "  verbose: false,",
    "  triggers: {",
    "    user: {",
    "      onCreate: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    "        const identity = {",
    "          authId: authUser._id,",
    "          name: authUser.name,",
    "          email: authUser.email,",
    "          emailVerified: authUser.emailVerified,",
    "          image: authUser.image ?? undefined,",
    "          twoFactorEnabled: authUser.twoFactorEnabled ?? undefined,",
    "          updatedAt: authUser.updatedAt,",
    "        };",
    "        if (existing) {",
    "          await ctx.db.patch(existing._id, identity);",
    "          return;",
    "        }",
    '        await ctx.db.insert("users", {',
    "          ...identity,",
    '          role: "user",',
    "          banned: false,",
    "          createdAt: authUser.createdAt,",
    "        });",
    "      },",
    "      onUpdate: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    "        const identity = {",
    "          authId: authUser._id,",
    "          name: authUser.name,",
    "          email: authUser.email,",
    "          emailVerified: authUser.emailVerified,",
    "          image: authUser.image ?? undefined,",
    "          twoFactorEnabled: authUser.twoFactorEnabled ?? undefined,",
    "          updatedAt: authUser.updatedAt,",
    "        };",
    "        if (existing) {",
    "          await ctx.db.patch(existing._id, identity);",
    "          return;",
    "        }",
    '        await ctx.db.insert("users", {',
    "          ...identity,",
    '          role: "user",',
    "          banned: false,",
    "          createdAt: authUser.createdAt,",
    "        });",
    "      },",
    "      onDelete: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    ...(hasManualBilling
      ? [
          "        if (existing) {",
          "          await assertManualPaymentDeletionAllowed(ctx, existing._id);",
          "          await ctx.db.delete(existing._id);",
          "        }",
        ]
      : ["        if (existing) await ctx.db.delete(existing._id);"]),
    "      },",
    "    },",
    "  },",
    "});",
    "",
    "export const { onCreate, onUpdate, onDelete } = authComponent.triggersApi();",
    "",
    ...authEmailLocaleLines,
    "export const createAuthOptions = (ctx: GenericCtx<DataModel>) => {",
    '  const baseURL = requireHttpUrl("CONVEX_SITE_URL", process.env.CONVEX_SITE_URL ?? siteUrl);',
    '  const betterAuthUrl = requireHttpUrl("BETTER_AUTH_URL", optionalEnv("BETTER_AUTH_URL") ?? siteUrl);',
    "  const trustedOrigins = new Set([new URL(siteUrl).origin, new URL(betterAuthUrl).origin]);",
    ...(hasMobile ? ['  trustedOrigins.add("__APP_SCHEME__://");'] : []),
    "  const authNetworkSecurity = resolveAuthNetworkSecurity(",
    "    betterAuthUrl,",
    '    optionalEnv("TRUSTED_PROXY"),',
    "  );",
    '  const googleClientId = optionalEnv("GOOGLE_CLIENT_ID");',
    '  const googleClientSecret = optionalEnv("GOOGLE_CLIENT_SECRET");',
    '  const githubClientId = optionalEnv("GITHUB_CLIENT_ID");',
    '  const githubClientSecret = optionalEnv("GITHUB_CLIENT_SECRET");',
    ...(hasEmail
      ? [
          "  async function enqueueAuthEmail(",
          '    kind: "verification" | "password-reset" | "magic-link",',
          "    to: string,",
          "    url: string,",
          "    locale: AuthEmailLocale,",
          "  ): Promise<void> {",
          '    if (!("scheduler" in ctx)) {',
          '      console.error("[convex/auth] Auth email scheduling requires a mutation or action context");',
          "      return;",
          "    }",
          "    await ctx.scheduler",
          "      .runAfter(0, internal.authEmail.send, { kind, to, url, locale })",
          '      .catch(() => console.error("[convex/auth] Auth email scheduling failed"));',
          "  }",
        ]
      : []),
    "  if (isLocalHostname(new URL(siteUrl).hostname)) {",
    '    trustedOrigins.add("http://localhost:3000");',
    '    trustedOrigins.add("http://localhost:3001");',
    "  }",
    "  return {",
    "    baseURL,",
    "    trustedOrigins: [...trustedOrigins],",
    '    secret: validateSecret(process.env.BETTER_AUTH_SECRET ?? requireEnv("BETTER_AUTH_SECRET")),',
    "    database: authComponent.adapter(ctx),",
    ...(hasEmail
      ? [
          "    emailAndPassword: {",
          "      enabled: true,",
          "      revokeSessionsOnPasswordReset: true,",
          "      requireEmailVerification: true,",
          "      autoSignIn: false,",
          "      sendResetPassword: async ({ user, url }, request) => {",
          '        await enqueueAuthEmail("password-reset", user.email, url, authEmailLocale(request));',
          "      },",
          "    },",
          "    emailVerification: {",
          "      sendOnSignUp: true,",
          "      sendOnSignIn: true,",
          "      autoSignInAfterVerification: true,",
          "      sendVerificationEmail: async ({ user, url }, request) => {",
          '        await enqueueAuthEmail("verification", user.email, url, authEmailLocale(request));',
          "      },",
          "    },",
        ]
      : [
          "    // Email delivery is absent, so credential ownership cannot be verified.",
          "    // Keep OAuth available but remove every password signup/signin/reset endpoint.",
          "    emailAndPassword: { enabled: false },",
        ]),
    "    socialProviders: {",
    "      ...(googleClientId && googleClientSecret ? { google: { clientId: googleClientId, clientSecret: googleClientSecret } } : {}),",
    "      ...(githubClientId && githubClientSecret ? { github: { clientId: githubClientId, clientSecret: githubClientSecret } } : {}),",
    "    },",
    "    account: {",
    "      encryptOAuthTokens: true,",
    "      // Convex auth emits no verified-email delivery or trusted social-provider config.",
    "      // Disable implicit linking so an unverified password account can never capture OAuth ownership.",
    "      accountLinking: {",
    "        enabled: false,",
    "        disableImplicitLinking: true,",
    "        requireLocalEmailVerified: true,",
    "      },",
    "    },",
    ...durableAuthRateLimitConfig.split("\n").map((line) => `  ${line}`),
    "    advanced: {",
    "      trustedProxyHeaders: authNetworkSecurity.trustedProxyHeaders,",
    "      ipAddress: authNetworkSecurity.ipAddress,",
    "    },",
    "    plugins: [",
    "      profileUpdateValidation(),",
    ...(hasMobile ? ["      expo(),"] : []),
    "      // The stock component lacks account-lockout columns, so keep its schema-safe",
    "      // five-attempt signed-challenge lockout plus database-backed /two-factor rate limits.",
    "      twoFactor({ issuer: betterAuthUrl, twoFactorCookieMaxAge: 600, accountLockout: { enabled: false } }),",
    ...(hasEmail
      ? [
          "      magicLink({",
          '        storeToken: "hashed",',
          "        sendMagicLink: async ({ email, url }, context) => {",
          '          await enqueueAuthEmail("magic-link", email, url, authEmailLocale(context?.request));',
          "        },",
          "      }),",
        ]
      : []),
    "      crossDomain({ siteUrl }),",
    "      convex({ authConfig }),",
    "    ],",
    "  } satisfies BetterAuthOptions;",
    "};",
    "",
    "export const createAuth = (ctx: GenericCtx<DataModel>) => betterAuth(createAuthOptions(ctx));",
    "",
    "// Identity-only queries. Application features authorize through users.me/lib/auth.",
    "export const getCurrentUser = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.safeGetAuthUser(ctx);",
    "    return user ?? null;",
    "  },",
    "});",
    "",
    "export const getCurrentUserOrThrow = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.safeGetAuthUser(ctx);",
    '    if (!user) throw new ConvexError({ code: "UNAUTHENTICATED", message: "Not authenticated" });',
    "    return user;",
    "  },",
    "});",
    "",
    "export async function getAuthUser(ctx: GenericCtx<DataModel>) {",
    "  return await authComponent.getAuthUser(ctx);",
    "}",
    "",
  ].join("\n");
}
