/**
 * convex/auth.ts — Better Auth component wiring and required-env guards.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexAuthContent(): string {
  return [
    'import { createClient, type GenericCtx } from "@convex-dev/better-auth";',
    'import { convex, crossDomain } from "@convex-dev/better-auth/plugins";',
    'import { components } from "./_generated/api";',
    'import { DataModel } from "./_generated/dataModel";',
    'import { betterAuth, type BetterAuthOptions } from "better-auth/minimal";',
    'import { ConvexError } from "convex/values";',
    'import authConfig from "./auth.config";',
    'import { query } from "./_generated/server";',
    "",
    "// ------------------------------------------------------------------",
    "// Env validation — no insecure https://example.com fallback, require SITE_URL",
    "// ------------------------------------------------------------------",
    "function requireEnv(name: string): string {",
    "  const value = process.env[name];",
    '  if (!value || value.startsWith("REPLACE_WITH") || value.trim() === "") {',
    "    throw new Error(`[convex/auth] Missing required env ${name}. Set it in Convex dashboard or .env.local`);",
    "  }",
    "  return value;",
    "}",
    "",
    "function optionalEnv(name: string): string | undefined {",
    "  const v = process.env[name];",
    '  if (!v || v.startsWith("REPLACE_WITH")) return undefined;',
    "  return v;",
    "}",
    "",
    "function resolveSiteUrl(): string {",
    "  const url = process.env.SITE_URL ?? process.env.CONVEX_SITE_URL;",
    '  if (!url || url.startsWith("REPLACE_WITH") || url === "https://example.com") {',
    '    throw new Error("[convex/auth] SITE_URL or CONVEX_SITE_URL must be set to your app URL (e.g. https://example.com or http://localhost:3000). No insecure fallback allowed.");',
    "  }",
    "  return url;",
    "}",
    "",
    "function validateSecret(secret: string | undefined): string {",
    '  if (!secret || secret.length < 32 || secret.startsWith("REPLACE_WITH")) {',
    '    throw new Error("BETTER_AUTH_SECRET must be set to a strong random value (>=32 chars), not placeholder");',
    "  }",
    "  return secret;",
    "}",
    "",
    "const siteUrl = resolveSiteUrl();",
    "",
    "export const authComponent = createClient<DataModel>(components.betterAuth, {",
    "  verbose: false,",
    "});",
    "",
    "export const createAuthOptions = (ctx: GenericCtx<DataModel>) => {",
    "  const baseURL = process.env.CONVEX_SITE_URL ?? siteUrl;",
    '  const betterAuthUrl = optionalEnv("BETTER_AUTH_URL") ?? siteUrl;',
    "  return {",
    "    baseURL,",
    '    trustedOrigins: [siteUrl, betterAuthUrl, "http://localhost:3000", "http://localhost:3001"].filter(Boolean) as string[],',
    '    secret: validateSecret(process.env.BETTER_AUTH_SECRET ?? requireEnv("BETTER_AUTH_SECRET")),',
    "    database: authComponent.adapter(ctx),",
    "    emailAndPassword: {",
    "      enabled: true,",
    "      requireEmailVerification: false,",
    "      autoSignInAfterRegistration: false,",
    "    },",
    "    plugins: [crossDomain({ siteUrl }), convex({ authConfig })],",
    "  } satisfies BetterAuthOptions;",
    "};",
    "",
    "export const createAuth = (ctx: GenericCtx<DataModel>) => betterAuth(createAuthOptions(ctx));",
    "",
    "// ------------------------------------------------------------------",
    "// Queries — getCurrentUser + preload helpers",
    "// ------------------------------------------------------------------",
    "export const getCurrentUser = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.getAuthUser(ctx);",
    "    return user ?? null;",
    "  },",
    "});",
    "",
    "export const getCurrentUserOrThrow = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.getAuthUser(ctx);",
    '    if (!user) throw new ConvexError({ code: "UNAUTHENTICATED", message: "Not authenticated" });',
    "    return user;",
    "  },",
    "});",
    "",
    "// Helper for use in other files when GenericCtx available",
    "export async function getAuthUser(ctx: GenericCtx<DataModel>) {",
    "  return await authComponent.getAuthUser(ctx);",
    "}",
    "",
  ].join("\n");
}
