/**
 * convex/auth.ts — Better Auth component wiring and required-env guards.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

import type { ProjectMode } from "../../../lib/addons.js";

export function convexAuthContent(mode: ProjectMode): string {
  const accessImports =
    mode === "monorepo"
      ? [
          'import { admin } from "better-auth/plugins/admin";',
          'import { ac, roles } from "@repo/auth/access";',
        ]
      : ['import { admin } from "better-auth/plugins/admin";'];
  const adminPlugin =
    mode === "monorepo" ? 'admin({ ac, roles, adminRoles: ["admin", "superAdmin"] })' : "admin()";
  return [
    'import { createClient, type AuthFunctions, type GenericCtx } from "@convex-dev/better-auth";',
    'import { convex, crossDomain } from "@convex-dev/better-auth/plugins";',
    'import { components, internal } from "./_generated/api";',
    'import type { DataModel } from "./_generated/dataModel";',
    'import { betterAuth, type BetterAuthOptions } from "better-auth/minimal";',
    ...accessImports,
    'import { ConvexError } from "convex/values";',
    'import authConfig from "./auth.config";',
    'import { query } from "./_generated/server";',
    "",
    "// ------------------------------------------------------------------",
    "// Env validation — no insecure https://example.com fallback, require SITE_URL",
    "// ------------------------------------------------------------------",
    "function requireEnv(name: string): string {",
    "  const value = process.env[name];",
    '  if (!value || value.startsWith("REPLACE_WITH") || value.trim() === "") {',
    "    throw new Error(`[convex/auth] Missing required env ${name}. Set it in Convex dashboard or .env.local`);",
    "  }",
    "  return value;",
    "}",
    "",
    "function optionalEnv(name: string): string | undefined {",
    "  const v = process.env[name];",
    '  if (!v || v.startsWith("REPLACE_WITH")) return undefined;',
    "  return v;",
    "}",
    "",
    "function resolveSiteUrl(): string {",
    "  const url = process.env.SITE_URL ?? process.env.CONVEX_SITE_URL;",
    '  if (!url || url.startsWith("REPLACE_WITH") || url === "https://example.com") {',
    '    throw new Error("[convex/auth] SITE_URL or CONVEX_SITE_URL must be set to your app URL (e.g. https://example.com or http://localhost:3000). No insecure fallback allowed.");',
    "  }",
    "  return url;",
    "}",
    "",
    "function validateSecret(secret: string | undefined): string {",
    '  if (!secret || secret.length < 32 || secret.startsWith("REPLACE_WITH")) {',
    '    throw new Error("BETTER_AUTH_SECRET must be set to a strong random value (>=32 chars), not placeholder");',
    "  }",
    "  return secret;",
    "}",
    "",
    "const siteUrl = resolveSiteUrl();",
    "",
    "const authFunctions: AuthFunctions = internal.auth;",
    "",
    "export const authComponent = createClient<DataModel>(components.betterAuth, {",
    "  authFunctions,",
    "  verbose: false,",
    "  triggers: {",
    "    user: {",
    "      onCreate: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    "        const identity = {",
    "          authId: authUser._id,",
    "          name: authUser.name,",
    "          email: authUser.email,",
    "          emailVerified: authUser.emailVerified,",
    "          image: authUser.image ?? undefined,",
    "          twoFactorEnabled: authUser.twoFactorEnabled ?? undefined,",
    "          updatedAt: authUser.updatedAt,",
    "        };",
    "        if (existing) {",
    "          await ctx.db.patch(existing._id, identity);",
    "          return;",
    "        }",
    '        await ctx.db.insert("users", {',
    "          ...identity,",
    '          role: "user",',
    "          banned: false,",
    "          createdAt: authUser.createdAt,",
    "        });",
    "      },",
    "      onUpdate: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    "        const identity = {",
    "          authId: authUser._id,",
    "          name: authUser.name,",
    "          email: authUser.email,",
    "          emailVerified: authUser.emailVerified,",
    "          image: authUser.image ?? undefined,",
    "          twoFactorEnabled: authUser.twoFactorEnabled ?? undefined,",
    "          updatedAt: authUser.updatedAt,",
    "        };",
    "        if (existing) {",
    "          await ctx.db.patch(existing._id, identity);",
    "          return;",
    "        }",
    '        await ctx.db.insert("users", {',
    "          ...identity,",
    '          role: "user",',
    "          banned: false,",
    "          createdAt: authUser.createdAt,",
    "        });",
    "      },",
    "      onDelete: async (ctx, authUser) => {",
    "        const existing = await ctx.db",
    '          .query("users")',
    '          .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "          .unique();",
    "        if (existing) await ctx.db.delete(existing._id);",
    "      },",
    "    },",
    "  },",
    "});",
    "",
    "export const { onCreate, onUpdate, onDelete } = authComponent.triggersApi();",
    "",
    "export const createAuthOptions = (ctx: GenericCtx<DataModel>) => {",
    "  const baseURL = process.env.CONVEX_SITE_URL ?? siteUrl;",
    '  const betterAuthUrl = optionalEnv("BETTER_AUTH_URL") ?? siteUrl;',
    "  return {",
    "    baseURL,",
    '    trustedOrigins: [siteUrl, betterAuthUrl, "http://localhost:3000", "http://localhost:3001"].filter(Boolean) as string[],',
    '    secret: validateSecret(process.env.BETTER_AUTH_SECRET ?? requireEnv("BETTER_AUTH_SECRET")),',
    "    database: authComponent.adapter(ctx),",
    "    emailAndPassword: {",
    "      enabled: true,",
    "      requireEmailVerification: false,",
    "      autoSignIn: false,",
    "    },",
    `    plugins: [${adminPlugin}, crossDomain({ siteUrl }), convex({ authConfig })],`,
    "  } satisfies BetterAuthOptions;",
    "};",
    "",
    "export const createAuth = (ctx: GenericCtx<DataModel>) => betterAuth(createAuthOptions(ctx));",
    "",
    "// ------------------------------------------------------------------",
    "// Queries — getCurrentUser + preload helpers",
    "// ------------------------------------------------------------------",
    "export const getCurrentUser = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.getAuthUser(ctx);",
    "    return user ?? null;",
    "  },",
    "});",
    "",
    "export const getCurrentUserOrThrow = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const user = await authComponent.getAuthUser(ctx);",
    '    if (!user) throw new ConvexError({ code: "UNAUTHENTICATED", message: "Not authenticated" });',
    "    return user;",
    "  },",
    "});",
    "",
    "// Helper for use in other files when GenericCtx available",
    "export async function getAuthUser(ctx: GenericCtx<DataModel>) {",
    "  return await authComponent.getAuthUser(ctx);",
    "}",
    "",
  ].join("\n");
}
