/**
 * convex/billing.ts — billing mutations/queries with composite idempotency.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexBillingContent(): string {
  return [
    'import { v } from "convex/values";',
    'import { internalMutation, internalQuery, query } from "./_generated/server";',
    'import { paginationOptsValidator } from "convex/server";',
    'import { ConvexError } from "convex/values";',
    'import { requireActor, requireAdminActor } from "./lib/auth";',
    "",
    "// ------------------------------------------------------------------",
    "// Validators — same as schema.ts, tight unions, metadata as record",
    "// ------------------------------------------------------------------",
    'const billingProvider = v.union(v.literal("stripe"), v.literal("chargily"), v.literal("paddle"), v.literal("polar"));',
    'const subscriptionStatus = v.union(v.literal("active"), v.literal("trialing"), v.literal("past_due"), v.literal("canceled"), v.literal("unpaid"), v.literal("incomplete"), v.literal("incomplete_expired"), v.literal("paused"), v.literal("expired"), v.literal("on_trial"), v.literal("trial_ended"));',
    'const checkoutStatus = v.union(v.literal("pending"), v.literal("paid"), v.literal("completed"), v.literal("failed"), v.literal("open"), v.literal("expired"));',
    'const invoiceStatus = v.union(v.literal("draft"), v.literal("open"), v.literal("paid"), v.literal("void"), v.literal("uncollectible"));',
    'const recurringInterval = v.union(v.literal("month"), v.literal("year"), v.literal("week"), v.literal("day"), v.literal("one_time"));',
    "const metadataValidator = v.optional(v.record(v.string(), v.union(v.string(), v.number(), v.boolean(), v.null())));",
    "function checkoutStatusRank(status: string): number {",
    '  if (status === "completed" || status === "paid") return 3;',
    '  if (status === "failed" || status === "expired") return 2;',
    "  return 1;",
    "}",
    "",
    "function assertWebhookPayload(payload: unknown): void {",
    "  let serialized: string | undefined;",
    "  try { serialized = JSON.stringify(payload); } catch {",
    '    throw new ConvexError({ code: "INVALID_PAYLOAD", message: "Webhook payload must be serializable" });',
    "  }",
    '  if (serialized === undefined) throw new ConvexError({ code: "INVALID_PAYLOAD", message: "Webhook payload must be serializable" });',
    "  // Convex limits documents by encoded bytes, not JavaScript UTF-16 code units.",
    '  if (new TextEncoder().encode(serialized).byteLength > 900_000) throw new ConvexError({ code: "PAYLOAD_TOO_LARGE", message: "Webhook payload exceeds 900k" });',
    "}",
    "",
    "// ------------------------------------------------------------------",
    "// webhook_events — composite idempotency [provider, providerEventId]",
    "// postgres uniqueness unique(provider, providerEventId) mirrored via composite index",
    "// ------------------------------------------------------------------",
    "export const upsertWebhookEvent = internalMutation({",
    "  args: {",
    "    provider: billingProvider,",
    "    providerEventId: v.string(),",
    "    type: v.string(),",
    "    payload: v.any(), // Stripe arbitrary JSON — size-checked below",
    "    processed: v.optional(v.boolean()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    if (args.providerEventId.trim().length === 0) throw new ConvexError({ code: "VALIDATION_ERROR", message: "providerEventId required" });',
    "    assertWebhookPayload(args.payload);",
    "    // Composite idempotency check — prevents cross-provider collision",
    '    const existing = await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", args.providerEventId)).unique();',
    "    if (existing) {",
    "      if (args.processed && !existing.processed) {",
    "        await ctx.db.patch(existing._id, { processed: true, processedAt: Date.now(), processingStartedAt: undefined, leaseToken: undefined, lastError: undefined });",
    "      }",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("webhook_events", { provider: args.provider, providerEventId: args.providerEventId, type: args.type, payload: args.payload, processed: args.processed ?? false, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const claimWebhookEvent = internalMutation({",
    "  args: {",
    "    provider: billingProvider,",
    "    providerEventId: v.string(),",
    "    type: v.string(),",
    "    payload: v.any(),",
    "    leaseToken: v.string(),",
    "    leaseMs: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    "    const providerEventId = args.providerEventId.trim();",
    '    if (!providerEventId) throw new ConvexError({ code: "VALIDATION_ERROR", message: "providerEventId required" });',
    '    if (!args.leaseToken.trim()) throw new ConvexError({ code: "VALIDATION_ERROR", message: "leaseToken required" });',
    "    assertWebhookPayload(args.payload);",
    '    const duplicateLease = await ctx.db.query("webhook_events").withIndex("by_leaseToken", (q) => q.eq("leaseToken", args.leaseToken)).first();',
    '    if (duplicateLease) throw new ConvexError({ code: "WEBHOOK_LEASE_COLLISION", message: "Webhook lease token collision" });',
    "    const now = Date.now();",
    "    const leaseMs = Math.max(1_000, Math.min(args.leaseMs ?? 300_000, 900_000));",
    '    const existing = await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", providerEventId)).unique();',
    '    if (existing?.processed) return { status: "completed" as const, id: existing._id };',
    "    if (existing?.processingStartedAt && existing.processingStartedAt > now - leaseMs) {",
    '      return { status: "in_flight" as const, id: existing._id };',
    "    }",
    "    if (existing) {",
    "      await ctx.db.patch(existing._id, { type: args.type, payload: args.payload, leaseToken: args.leaseToken, processingStartedAt: now, attemptCount: (existing.attemptCount ?? 0) + 1, lastError: undefined });",
    '      return { status: "claimed" as const, id: existing._id, leaseToken: args.leaseToken };',
    "    }",
    '    const id = await ctx.db.insert("webhook_events", { provider: args.provider, providerEventId, type: args.type, payload: args.payload, processed: false, attemptCount: 1, leaseToken: args.leaseToken, processingStartedAt: now, createdAt: now });',
    '    return { status: "claimed" as const, id, leaseToken: args.leaseToken };',
    "  },",
    "});",
    "",
    "export const completeWebhookEvent = internalMutation({",
    "  args: { provider: billingProvider, providerEventId: v.string(), leaseToken: v.string() },",
    "  handler: async (ctx, args) => {",
    "    const providerEventId = args.providerEventId.trim();",
    '    if (!providerEventId || !args.leaseToken.trim()) throw new ConvexError({ code: "VALIDATION_ERROR", message: "providerEventId and leaseToken required" });',
    '    const existing = await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", providerEventId)).unique();',
    '    if (!existing) throw new ConvexError({ code: "WEBHOOK_CLAIM_MISSING", message: "Webhook delivery must be claimed before completion" });',
    '    if (existing.leaseToken !== args.leaseToken) throw new ConvexError({ code: "WEBHOOK_LEASE_STALE", message: "Webhook lease no longer belongs to this worker" });',
    "    await ctx.db.patch(existing._id, { processed: true, processedAt: Date.now(), processingStartedAt: undefined, leaseToken: undefined, lastError: undefined });",
    "    return existing._id;",
    "  },",
    "});",
    "",
    "export const failWebhookEvent = internalMutation({",
    "  args: { provider: billingProvider, providerEventId: v.string(), leaseToken: v.string(), error: v.string() },",
    "  handler: async (ctx, args) => {",
    "    const providerEventId = args.providerEventId.trim();",
    '    if (!providerEventId || !args.leaseToken.trim()) throw new ConvexError({ code: "VALIDATION_ERROR", message: "providerEventId and leaseToken required" });',
    '    const existing = await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", providerEventId)).unique();',
    "    if (!existing || existing.processed) return existing?._id ?? null;",
    '    if (existing.leaseToken !== args.leaseToken) throw new ConvexError({ code: "WEBHOOK_LEASE_STALE", message: "Webhook lease no longer belongs to this worker" });',
    "    await ctx.db.patch(existing._id, { processingStartedAt: undefined, leaseToken: undefined, lastError: args.error.slice(0, 2_000) });",
    "    return existing._id;",
    "  },",
    "});",
    "",
    "export const markWebhookProcessed = internalMutation({",
    '  args: { id: v.id("webhook_events"), processedAt: v.optional(v.number()) },',
    "  handler: async (ctx, args) => {",
    "    await ctx.db.patch(args.id, { processed: true, processedAt: args.processedAt ?? Date.now(), processingStartedAt: undefined, leaseToken: undefined, lastError: undefined });",
    "    return args.id;",
    "  },",
    "});",
    "",
    "export const getWebhookEvent = internalQuery({",
    "  args: { provider: billingProvider, providerEventId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", args.providerEventId)).unique();',
    "  },",
    "});",
    "",
    "export const checkWebhookEvent = internalQuery({",
    "  args: { provider: billingProvider, providerEventId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", args.providerEventId)).unique();',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// customers — idempotent by [provider, providerCustomerId]",
    "// unique email enforcement via query check (Convex no unique index)",
    "// ------------------------------------------------------------------",
    "export const upsertCustomer = internalMutation({",
    "  args: {",
    "    email: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    providerCustomerId: v.string(),",
    '    userId: v.id("users"),',
    "    name: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    if (args.email && !args.email.includes("@")) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Invalid email" });',
    '    const existing = await ctx.db.query("customers").withIndex("by_provider_providerCustomerId", (q) => q.eq("provider", args.provider).eq("providerCustomerId", args.providerCustomerId)).unique();',
    "    if (existing) {",
    '      if (existing.userId && args.userId && existing.userId !== args.userId) throw new ConvexError({ code: "CUSTOMER_OWNER_CONFLICT", message: "Provider customer is already bound to another actor" });',
    "      await ctx.db.patch(existing._id, { email: args.email, name: args.name, metadata: args.metadata, userId: existing.userId ?? args.userId });",
    "      return existing.providerCustomerId;",
    "    }",
    "    if (args.userId) {",
    '      const actorCustomer = await ctx.db.query("customers").withIndex("by_userId_provider", (q) => q.eq("userId", args.userId).eq("provider", args.provider)).first();',
    "      if (actorCustomer) {",
    "        await ctx.db.patch(actorCustomer._id, { email: args.email, name: args.name, metadata: args.metadata });",
    "        return actorCustomer.providerCustomerId;",
    "      }",
    "    }",
    '    await ctx.db.insert("customers", { email: args.email, provider: args.provider, providerCustomerId: args.providerCustomerId, userId: args.userId, name: args.name, metadata: args.metadata, createdAt: Date.now() });',
    "    return args.providerCustomerId;",
    "  },",
    "});",
    "",
    "export const getCustomerByProviderId = internalQuery({",
    "  args: { provider: billingProvider, providerCustomerId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("customers").withIndex("by_provider_providerCustomerId", (q) => q.eq("provider", args.provider).eq("providerCustomerId", args.providerCustomerId)).unique();',
    "  },",
    "});",
    "",
    "export const getCustomerForActor = query({",
    "  args: { provider: billingProvider },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    '    return await ctx.db.query("customers").withIndex("by_userId_provider", (q) => q.eq("userId", actor._id).eq("provider", args.provider)).first();',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// subscriptions — idempotent by [provider, providerSubscriptionId]",
    "// ------------------------------------------------------------------",
    "export const upsertSubscription = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    status: subscriptionStatus,",
    "    priceId: v.optional(v.string()),",
    "    productId: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    canceledAt: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    "    if (existing) {",
    '      if (existing.userId !== args.userId) throw new ConvexError({ code: "SUBSCRIPTION_OWNER_CONFLICT", message: "Provider subscription is already bound to another actor" });',
    "      if (existing.providerEventAt !== undefined && (args.providerEventAt === undefined || args.providerEventAt < existing.providerEventAt)) return existing._id;",
    '      if (existing.providerEventAt === args.providerEventAt && (existing.status === "canceled" || existing.status === "expired") && (args.status === "active" || args.status === "trialing" || args.status === "on_trial")) return existing._id;',
    "      await ctx.db.patch(existing._id, { status: args.status, priceId: args.priceId, productId: args.productId, customerId: args.customerId, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, canceledAt: args.canceledAt, metadata: args.metadata, providerEventAt: args.providerEventAt ?? existing.providerEventAt, updatedAt: Date.now() });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("subscriptions", { userId: args.userId, provider: args.provider, providerSubscriptionId: args.providerSubscriptionId, status: args.status, priceId: args.priceId, productId: args.productId, customerId: args.customerId, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, canceledAt: args.canceledAt, metadata: args.metadata, providerEventAt: args.providerEventAt, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const getSubscriptionByProviderId = internalQuery({",
    "  args: { provider: billingProvider, providerSubscriptionId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    "  },",
    "});",
    "",
    "// Fence remote provider reads independently of webhook arrival order. A later",
    "// claim invalidates every earlier reader before it can commit stale entitlement state.",
    "export const claimProviderSubscriptionState = internalMutation({",
    "  args: { provider: billingProvider, providerSubscriptionId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    "    if (!existing) return null;",
    "    const providerStateVersion = (existing.providerStateVersion ?? 0) + 1;",
    '    if (!Number.isSafeInteger(providerStateVersion)) throw new ConvexError({ code: "SUBSCRIPTION_STATE_VERSION_EXHAUSTED", message: "Provider subscription state version is invalid" });',
    "    await ctx.db.patch(existing._id, { providerStateVersion });",
    "    return { providerStateVersion, userId: existing.userId };",
    "  },",
    "});",
    "",
    "export const commitProviderSubscriptionState = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    providerStateVersion: v.number(),",
    "    status: subscriptionStatus,",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    '    if (!existing || existing.userId !== args.userId || existing.providerStateVersion !== args.providerStateVersion) throw new ConvexError({ code: "SUBSCRIPTION_STATE_SUPERSEDED", message: "A newer provider subscription reconciliation won" });',
    "    await ctx.db.patch(existing._id, { status: args.status, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, metadata: args.metadata, updatedAt: Date.now() });",
    "    return existing._id;",
    "  },",
    "});",
    "",
    "export const cancelProviderSubscriptionState = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    providerStateVersion: v.number(),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    '    if (!existing || existing.userId !== args.userId || existing.providerStateVersion !== args.providerStateVersion) throw new ConvexError({ code: "SUBSCRIPTION_STATE_SUPERSEDED", message: "A newer provider subscription reconciliation won" });',
    '    await ctx.db.patch(existing._id, { status: "canceled", metadata: args.metadata, providerEventAt: args.providerEventAt ?? existing.providerEventAt, canceledAt: args.providerEventAt ?? Date.now(), updatedAt: Date.now() });',
    "    return existing._id;",
    "  },",
    "});",
    "",
    "export const createProviderSubscriptionState = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    status: subscriptionStatus,",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    '    if (existing) throw new ConvexError({ code: "SUBSCRIPTION_STATE_SUPERSEDED", message: "Provider subscription state was created concurrently" });',
    '    return await ctx.db.insert("subscriptions", { userId: args.userId, provider: args.provider, providerSubscriptionId: args.providerSubscriptionId, status: args.status, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, metadata: args.metadata, providerEventAt: args.providerEventAt, providerStateVersion: 0, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const updateSubscriptionStatus = internalMutation({",
    "  args: {",
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    status: subscriptionStatus,",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "    authoritative: v.optional(v.boolean()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    '    if (!existing) throw new ConvexError({ code: "SUBSCRIPTION_NOT_FOUND", message: "Subscription mapping not found" });',
    "    if (!args.authoritative && existing.providerEventAt !== undefined && (args.providerEventAt === undefined || args.providerEventAt < existing.providerEventAt)) return existing._id;",
    '    if (!args.authoritative && existing.providerEventAt === args.providerEventAt && (existing.status === "canceled" || existing.status === "expired") && (args.status === "active" || args.status === "trialing" || args.status === "on_trial")) return existing._id;',
    "    await ctx.db.patch(existing._id, { status: args.status, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, metadata: args.metadata, providerEventAt: args.providerEventAt ?? existing.providerEventAt, updatedAt: Date.now() });",
    "    return existing._id;",
    "  },",
    "});",
    "",
    "const CHECKOUT_CREATION_LEASE_MS = 5 * 60 * 1_000;",
    "",
    "export const claimCheckoutIntent = internalMutation({",
    '  args: { userId: v.id("users"), provider: billingProvider, requestKey: v.string(), leaseToken: v.string() },',
    "  handler: async (ctx, args) => {",
    "    const requestKey = args.requestKey.trim();",
    '    if (!requestKey || !args.leaseToken.trim()) throw new ConvexError({ code: "VALIDATION_ERROR", message: "requestKey and leaseToken required" });',
    '    const existing = await ctx.db.query("checkouts").withIndex("by_user_provider_requestKey", (q) => q.eq("userId", args.userId).eq("provider", args.provider).eq("requestKey", requestKey)).first();',
    '    if (existing?.creationState === "ready" && existing.providerCheckoutId && existing.url) return { status: "completed" as const, checkout: { id: existing.providerCheckoutId, url: existing.url } };',
    "    if (existing) {",
    '      if (existing.creationStartedAt !== undefined && existing.creationStartedAt > Date.now() - CHECKOUT_CREATION_LEASE_MS) return { status: "in_flight" as const };',
    '      await ctx.db.patch(existing._id, { creationState: "creating", creationStartedAt: Date.now(), creationLeaseToken: args.leaseToken });',
    '      return { status: "claimed" as const, leaseToken: args.leaseToken };',
    "    }",
    '    await ctx.db.insert("checkouts", { userId: args.userId, provider: args.provider, requestKey, creationState: "creating", creationStartedAt: Date.now(), creationLeaseToken: args.leaseToken, status: "pending", createdAt: Date.now() });',
    '    return { status: "claimed" as const, leaseToken: args.leaseToken };',
    "  },",
    "});",
    "",
    "export const completeCheckoutIntent = internalMutation({",
    '  args: { userId: v.id("users"), provider: billingProvider, requestKey: v.string(), leaseToken: v.string(), providerCheckoutId: v.string(), url: v.string() },',
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("checkouts").withIndex("by_user_provider_requestKey", (q) => q.eq("userId", args.userId).eq("provider", args.provider).eq("requestKey", args.requestKey)).first();',
    '    if (!existing) throw new ConvexError({ code: "CHECKOUT_INTENT_MISSING", message: "Checkout intent was not claimed" });',
    '    if (existing.creationState === "ready" && existing.providerCheckoutId === args.providerCheckoutId) { if (existing.url !== args.url) await ctx.db.patch(existing._id, { url: args.url }); return existing._id; }',
    '    if (existing.creationLeaseToken !== args.leaseToken) throw new ConvexError({ code: "CHECKOUT_INTENT_STALE", message: "Checkout intent lease no longer belongs to this request" });',
    '    await ctx.db.patch(existing._id, { providerCheckoutId: args.providerCheckoutId, url: args.url, creationState: "ready", creationStartedAt: undefined, creationLeaseToken: undefined });',
    "    return existing._id;",
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// checkouts — idempotent by [provider, providerCheckoutId]",
    "// ------------------------------------------------------------------",
    "export const upsertCheckout = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerCheckoutId: v.string(),",
    "    requestKey: v.optional(v.string()),",
    "    status: checkoutStatus,",
    "    customerId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("checkouts").withIndex("by_provider_providerCheckoutId", (q) => q.eq("provider", args.provider).eq("providerCheckoutId", args.providerCheckoutId)).unique();',
    "    if (!existing && args.userId && args.requestKey) {",
    '      const intent = await ctx.db.query("checkouts").withIndex("by_user_provider_requestKey", (q) => q.eq("userId", args.userId).eq("provider", args.provider).eq("requestKey", args.requestKey)).first();',
    '      if (intent?.providerCheckoutId && intent.providerCheckoutId !== args.providerCheckoutId) throw new ConvexError({ code: "CHECKOUT_REQUEST_CONFLICT", message: "Checkout request key already completed with another provider checkout" });',
    '      if (intent) { await ctx.db.patch(intent._id, { providerCheckoutId: args.providerCheckoutId, status: args.status, customerId: args.customerId, url: args.url, amount: args.amount, currency: args.currency, metadata: args.metadata, providerEventAt: args.providerEventAt, creationState: "ready", creationStartedAt: undefined, creationLeaseToken: undefined }); return intent._id; }',
    "    }",
    "    if (existing) {",
    '      if (existing.userId && args.userId && existing.userId !== args.userId) throw new ConvexError({ code: "CHECKOUT_OWNER_CONFLICT", message: "Provider checkout is already bound to another actor" });',
    "      if (existing.providerEventAt !== undefined && (args.providerEventAt === undefined || args.providerEventAt < existing.providerEventAt)) return existing._id;",
    "      if (existing.providerEventAt === args.providerEventAt && checkoutStatusRank(existing.status) > checkoutStatusRank(args.status)) return existing._id;",
    '      await ctx.db.patch(existing._id, { userId: existing.userId ?? args.userId, requestKey: existing.requestKey ?? args.requestKey, status: args.status, customerId: args.customerId, url: args.url, amount: args.amount, currency: args.currency, metadata: args.metadata, providerEventAt: args.providerEventAt ?? existing.providerEventAt, creationState: "ready", creationStartedAt: undefined, creationLeaseToken: undefined });',
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("checkouts", { userId: args.userId, provider: args.provider, providerCheckoutId: args.providerCheckoutId, requestKey: args.requestKey, creationState: "ready", status: args.status, customerId: args.customerId, url: args.url, amount: args.amount, currency: args.currency, metadata: args.metadata, providerEventAt: args.providerEventAt, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// invoices — idempotent by [provider, providerInvoiceId]",
    "// ------------------------------------------------------------------",
    "export const upsertInvoice = internalMutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerInvoiceId: v.string(),",
    "    status: invoiceStatus,",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    subscriptionId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "    providerEventAt: v.optional(v.number()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("invoices").withIndex("by_provider_providerInvoiceId", (q) => q.eq("provider", args.provider).eq("providerInvoiceId", args.providerInvoiceId)).unique();',
    "    if (existing) {",
    '      if (existing.userId !== args.userId) throw new ConvexError({ code: "INVOICE_OWNER_CONFLICT", message: "Provider invoice is already bound to another actor" });',
    "      if (existing.providerEventAt !== undefined && (args.providerEventAt === undefined || args.providerEventAt < existing.providerEventAt)) return existing._id;",
    '      if (existing.status === "paid" && args.status !== "paid") return existing._id;',
    "      await ctx.db.patch(existing._id, { status: args.status, amount: args.amount, currency: args.currency, customerId: args.customerId, subscriptionId: args.subscriptionId, url: args.url, metadata: args.metadata, providerEventAt: args.providerEventAt ?? existing.providerEventAt });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("invoices", { userId: args.userId, provider: args.provider, providerInvoiceId: args.providerInvoiceId, status: args.status, amount: args.amount, currency: args.currency, customerId: args.customerId, subscriptionId: args.subscriptionId, url: args.url, metadata: args.metadata, providerEventAt: args.providerEventAt, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// usage_events + products/prices helpers — missing indexes now added",
    "// ------------------------------------------------------------------",
    "export const recordUsageEvent = internalMutation({",
    "  args: {",
    '    subscriptionId: v.optional(v.id("subscriptions")),',
    "    name: v.string(),",
    "    credits: v.optional(v.number()),",
    "    externalCustomerId: v.optional(v.string()),",
    "    organizationId: v.optional(v.string()),",
    "    externalId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    timestamp: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.insert("usage_events", { subscriptionId: args.subscriptionId, name: args.name, credits: args.credits, externalCustomerId: args.externalCustomerId, organizationId: args.organizationId, externalId: args.externalId, provider: args.provider, timestamp: args.timestamp, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const upsertProduct = internalMutation({",
    "  args: {",
    "    name: v.string(),",
    "    provider: billingProvider,",
    "    providerProductId: v.optional(v.string()),",
    "    description: v.optional(v.string()),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    "    if (args.providerProductId) {",
    '      const existing = await ctx.db.query("products").withIndex("by_provider_providerProductId", (q) => q.eq("provider", args.provider).eq("providerProductId", args.providerProductId!)).unique();',
    "      if (existing) {",
    "        await ctx.db.patch(existing._id, { name: args.name, description: args.description, active: args.active, metadata: args.metadata, updatedAt: Date.now() });",
    "        return existing._id;",
    "      }",
    "    }",
    '    return await ctx.db.insert("products", { name: args.name, provider: args.provider, providerProductId: args.providerProductId, description: args.description, active: args.active, metadata: args.metadata, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const upsertPrice = internalMutation({",
    "  args: {",
    '    productId: v.optional(v.id("products")),',
    "    providerPriceId: v.optional(v.string()),",
    "    providerProductId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    unitAmount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    recurringInterval: v.optional(recurringInterval),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    "    if (args.providerPriceId) {",
    '      const existing = await ctx.db.query("prices").withIndex("by_provider_providerPriceId", (q) => q.eq("provider", args.provider).eq("providerPriceId", args.providerPriceId!)).unique();',
    "      if (existing) {",
    "        await ctx.db.patch(existing._id, { productId: args.productId, providerProductId: args.providerProductId, unitAmount: args.unitAmount, currency: args.currency, recurringInterval: args.recurringInterval, active: args.active, metadata: args.metadata });",
    "        return existing._id;",
    "      }",
    "    }",
    '    return await ctx.db.insert("prices", { productId: args.productId, providerPriceId: args.providerPriceId, providerProductId: args.providerProductId, provider: args.provider, unitAmount: args.unitAmount, currency: args.currency, recurringInterval: args.recurringInterval, active: args.active, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// Queries for billing dashboard",
    "export const listCustomers = query({",
    "  args: { paginationOpts: paginationOptsValidator, provider: v.optional(billingProvider) },",
    "  handler: async (ctx, args) => {",
    "    await requireAdminActor(ctx);",
    '    const q = args.provider ? ctx.db.query("customers").withIndex("by_provider", (q) => q.eq("provider", args.provider!)) : ctx.db.query("customers");',
    '    return await q.order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const listSubscriptions = query({",
    "  args: { paginationOpts: paginationOptsValidator },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    '    const q = ctx.db.query("subscriptions").withIndex("by_userId", (q) => q.eq("userId", actor._id));',
    '    return await q.order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const getBillingSnapshot = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    const actor = await requireActor(ctx);",
    '    const subscriptions = await ctx.db.query("subscriptions").withIndex("by_userId", (q) => q.eq("userId", actor._id)).collect();',
    '    const invoices = await ctx.db.query("invoices").withIndex("by_userId", (q) => q.eq("userId", actor._id)).collect();',
    '    const usagePages = await Promise.all(subscriptions.map((subscription) => ctx.db.query("usage_events").withIndex("by_subscriptionId", (q) => q.eq("subscriptionId", subscription._id)).collect()));',
    '    const licensePages = await Promise.all(subscriptions.map((subscription) => ctx.db.query("license_keys").withIndex("by_subscriptionId", (q) => q.eq("subscriptionId", subscription._id)).collect()));',
    "    return { subscriptions, invoices, usageEvents: usagePages.flat(), licenseKeys: licensePages.flat() };",
    "  },",
    "});",
    "",
  ].join("\n");
}
