/**
 * convex/billing.ts — billing mutations/queries with composite idempotency.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexBillingContent(): string {
  return [
    'import { v } from "convex/values";',
    'import { mutation, query } from "./_generated/server";',
    'import { paginationOptsValidator } from "convex/server";',
    'import { ConvexError } from "convex/values";',
    "",
    "// ------------------------------------------------------------------",
    "// Validators — same as schema.ts, tight unions, metadata as record",
    "// ------------------------------------------------------------------",
    'const billingProvider = v.union(v.literal("stripe"), v.literal("chargily"), v.literal("paddle"), v.literal("polar"));',
    'const subscriptionStatus = v.union(v.literal("active"), v.literal("trialing"), v.literal("past_due"), v.literal("canceled"), v.literal("unpaid"), v.literal("incomplete"), v.literal("incomplete_expired"), v.literal("paused"), v.literal("expired"), v.literal("on_trial"), v.literal("trial_ended"));',
    'const checkoutStatus = v.union(v.literal("pending"), v.literal("paid"), v.literal("completed"), v.literal("failed"), v.literal("open"), v.literal("expired"));',
    'const invoiceStatus = v.union(v.literal("draft"), v.literal("open"), v.literal("paid"), v.literal("void"), v.literal("uncollectible"));',
    'const licenseKeyStatus = v.union(v.literal("active"), v.literal("revoked"), v.literal("expired"));',
    'const recurringInterval = v.union(v.literal("month"), v.literal("year"), v.literal("week"), v.literal("day"), v.literal("one_time"));',
    "const metadataValidator = v.optional(v.record(v.string(), v.union(v.string(), v.number(), v.boolean(), v.null())));",
    "",
    "// ------------------------------------------------------------------",
    "// webhook_events — composite idempotency [provider, providerEventId]",
    "// postgres uniqueness unique(provider, providerEventId) mirrored via composite index",
    "// ------------------------------------------------------------------",
    "export const upsertWebhookEvent = mutation({",
    "  args: {",
    "    provider: billingProvider,",
    "    providerEventId: v.string(),",
    "    type: v.string(),",
    "    payload: v.any(), // Stripe arbitrary JSON — size-checked below",
    "    processed: v.optional(v.boolean()),",
    "  },",
    "  handler: async (ctx, args) => {",
    '    if (args.providerEventId.trim().length === 0) throw new ConvexError({ code: "VALIDATION_ERROR", message: "providerEventId required" });',
    "    // Composite idempotency check — prevents cross-provider collision",
    '    const existing = await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", args.providerEventId)).unique();',
    "    if (existing) {",
    "      return existing._id;",
    "    }",
    "    // Payload size guard — Convex doc limit 1MB, keep 900k headroom",
    "    try {",
    "      const payloadStr = JSON.stringify(args.payload);",
    '      if (payloadStr.length > 900_000) throw new ConvexError({ code: "PAYLOAD_TOO_LARGE", message: "Webhook payload exceeds 900k" });',
    "    } catch {",
    "      // If JSON.stringify fails, still allow but log — payload may contain circular? v.any() already validated as serializable by Convex",
    "    }",
    '    return await ctx.db.insert("webhook_events", { provider: args.provider, providerEventId: args.providerEventId, type: args.type, payload: args.payload, processed: args.processed ?? false, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const markWebhookProcessed = mutation({",
    '  args: { id: v.id("webhook_events"), processedAt: v.optional(v.number()) },',
    "  handler: async (ctx, args) => {",
    "    await ctx.db.patch(args.id, { processed: true, processedAt: args.processedAt ?? Date.now() });",
    "    return args.id;",
    "  },",
    "});",
    "",
    "export const getWebhookEvent = query({",
    "  args: { provider: billingProvider, providerEventId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("webhook_events").withIndex("by_provider_event", (q) => q.eq("provider", args.provider).eq("providerEventId", args.providerEventId)).unique();',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// customers — idempotent by [provider, providerCustomerId]",
    "// unique email enforcement via query check (Convex no unique index)",
    "// ------------------------------------------------------------------",
    "export const upsertCustomer = mutation({",
    "  args: {",
    "    email: v.string(),",
    "    provider: billingProvider,",
    "    providerCustomerId: v.string(),",
    '    userId: v.optional(v.id("users")),',
    "    name: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    if (!args.email.includes("@")) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Invalid email" });',
    '    const existing = await ctx.db.query("customers").withIndex("by_provider_providerCustomerId", (q) => q.eq("provider", args.provider).eq("providerCustomerId", args.providerCustomerId)).unique();',
    "    if (existing) {",
    "      await ctx.db.patch(existing._id, { email: args.email, name: args.name, metadata: args.metadata, userId: args.userId ?? existing.userId });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("customers", { email: args.email, provider: args.provider, providerCustomerId: args.providerCustomerId, userId: args.userId, name: args.name, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const getCustomerByProviderId = query({",
    "  args: { provider: billingProvider, providerCustomerId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("customers").withIndex("by_provider_providerCustomerId", (q) => q.eq("provider", args.provider).eq("providerCustomerId", args.providerCustomerId)).unique();',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// subscriptions — idempotent by [provider, providerSubscriptionId]",
    "// ------------------------------------------------------------------",
    "export const upsertSubscription = mutation({",
    "  args: {",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    status: subscriptionStatus,",
    "    priceId: v.optional(v.string()),",
    "    productId: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    canceledAt: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    "    if (existing) {",
    "      await ctx.db.patch(existing._id, { status: args.status, priceId: args.priceId, productId: args.productId, customerId: args.customerId, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, canceledAt: args.canceledAt, metadata: args.metadata, updatedAt: Date.now() });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("subscriptions", { userId: args.userId, provider: args.provider, providerSubscriptionId: args.providerSubscriptionId, status: args.status, priceId: args.priceId, productId: args.productId, customerId: args.customerId, currentPeriodEnd: args.currentPeriodEnd, trialEnd: args.trialEnd, canceledAt: args.canceledAt, metadata: args.metadata, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const getSubscriptionByProviderId = query({",
    "  args: { provider: billingProvider, providerSubscriptionId: v.string() },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.query("subscriptions").withIndex("by_provider_providerSubscriptionId", (q) => q.eq("provider", args.provider).eq("providerSubscriptionId", args.providerSubscriptionId)).unique();',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// checkouts — idempotent by [provider, providerCheckoutId]",
    "// ------------------------------------------------------------------",
    "export const upsertCheckout = mutation({",
    "  args: {",
    '    userId: v.optional(v.id("users")),',
    "    provider: billingProvider,",
    "    providerCheckoutId: v.string(),",
    "    status: checkoutStatus,",
    "    customerId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("checkouts").withIndex("by_provider_providerCheckoutId", (q) => q.eq("provider", args.provider).eq("providerCheckoutId", args.providerCheckoutId)).unique();',
    "    if (existing) {",
    "      await ctx.db.patch(existing._id, { status: args.status, customerId: args.customerId, url: args.url, amount: args.amount, currency: args.currency, metadata: args.metadata });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("checkouts", { userId: args.userId, provider: args.provider, providerCheckoutId: args.providerCheckoutId, status: args.status, customerId: args.customerId, url: args.url, amount: args.amount, currency: args.currency, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// invoices — idempotent by [provider, providerInvoiceId]",
    "// ------------------------------------------------------------------",
    "export const upsertInvoice = mutation({",
    "  args: {",
    '    userId: v.optional(v.id("users")),',
    "    provider: billingProvider,",
    "    providerInvoiceId: v.string(),",
    "    status: invoiceStatus,",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    subscriptionId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    const existing = await ctx.db.query("invoices").withIndex("by_provider_providerInvoiceId", (q) => q.eq("provider", args.provider).eq("providerInvoiceId", args.providerInvoiceId)).unique();',
    "    if (existing) {",
    "      await ctx.db.patch(existing._id, { status: args.status, amount: args.amount, currency: args.currency, customerId: args.customerId, subscriptionId: args.subscriptionId, url: args.url, metadata: args.metadata });",
    "      return existing._id;",
    "    }",
    '    return await ctx.db.insert("invoices", { userId: args.userId, provider: args.provider, providerInvoiceId: args.providerInvoiceId, status: args.status, amount: args.amount, currency: args.currency, customerId: args.customerId, subscriptionId: args.subscriptionId, url: args.url, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// usage_events + products/prices helpers — missing indexes now added",
    "// ------------------------------------------------------------------",
    "export const recordUsageEvent = mutation({",
    "  args: {",
    '    subscriptionId: v.optional(v.id("subscriptions")),',
    "    name: v.string(),",
    "    credits: v.optional(v.number()),",
    "    externalCustomerId: v.optional(v.string()),",
    "    organizationId: v.optional(v.string()),",
    "    externalId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    timestamp: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    '    return await ctx.db.insert("usage_events", { subscriptionId: args.subscriptionId, name: args.name, credits: args.credits, externalCustomerId: args.externalCustomerId, organizationId: args.organizationId, externalId: args.externalId, provider: args.provider, timestamp: args.timestamp, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const upsertProduct = mutation({",
    "  args: {",
    "    name: v.string(),",
    "    provider: billingProvider,",
    "    providerProductId: v.optional(v.string()),",
    "    description: v.optional(v.string()),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    "    if (args.providerProductId) {",
    '      const existing = await ctx.db.query("products").withIndex("by_provider_providerProductId", (q) => q.eq("provider", args.provider).eq("providerProductId", args.providerProductId!)).unique();',
    "      if (existing) {",
    "        await ctx.db.patch(existing._id, { name: args.name, description: args.description, active: args.active, metadata: args.metadata, updatedAt: Date.now() });",
    "        return existing._id;",
    "      }",
    "    }",
    '    return await ctx.db.insert("products", { name: args.name, provider: args.provider, providerProductId: args.providerProductId, description: args.description, active: args.active, metadata: args.metadata, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const upsertPrice = mutation({",
    "  args: {",
    '    productId: v.optional(v.id("products")),',
    "    providerPriceId: v.optional(v.string()),",
    "    providerProductId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    unitAmount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    recurringInterval: v.optional(recurringInterval),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "  },",
    "  handler: async (ctx, args) => {",
    "    if (args.providerPriceId) {",
    '      const existing = await ctx.db.query("prices").withIndex("by_provider_providerPriceId", (q) => q.eq("provider", args.provider).eq("providerPriceId", args.providerPriceId!)).unique();',
    "      if (existing) {",
    "        await ctx.db.patch(existing._id, { productId: args.productId, providerProductId: args.providerProductId, unitAmount: args.unitAmount, currency: args.currency, recurringInterval: args.recurringInterval, active: args.active, metadata: args.metadata });",
    "        return existing._id;",
    "      }",
    "    }",
    '    return await ctx.db.insert("prices", { productId: args.productId, providerPriceId: args.providerPriceId, providerProductId: args.providerProductId, provider: args.provider, unitAmount: args.unitAmount, currency: args.currency, recurringInterval: args.recurringInterval, active: args.active, metadata: args.metadata, createdAt: Date.now() });',
    "  },",
    "});",
    "",
    "// Queries for billing dashboard",
    "export const listCustomers = query({",
    "  args: { paginationOpts: paginationOptsValidator, provider: v.optional(billingProvider) },",
    "  handler: async (ctx, args) => {",
    '    const q = args.provider ? ctx.db.query("customers").withIndex("by_provider", (q) => q.eq("provider", args.provider!)) : ctx.db.query("customers");',
    '    return await q.order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const listSubscriptions = query({",
    '  args: { paginationOpts: paginationOptsValidator, userId: v.optional(v.id("users")) },',
    "  handler: async (ctx, args) => {",
    '    const q = args.userId ? ctx.db.query("subscriptions").withIndex("by_userId", (q) => q.eq("userId", args.userId!)) : ctx.db.query("subscriptions");',
    '    return await q.order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
  ].join("\n");
}
