/**
 * convex/http.ts — HTTP router mounting the auth handler.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexHttpContent(): string {
  return [
    'import { httpRouter } from "convex/server";',
    'import { httpAction } from "./_generated/server";',
    'import { authComponent, createAuth } from "./auth";',
    'import { api } from "./_generated/api";',
    "",
    "const http = httpRouter();",
    "",
    "// Better Auth routes",
    "authComponent.registerRoutes(http, createAuth);",
    "",
    "// ------------------------------------------------------------------",
    "// Health check — used by @repo/database healthCheck() and load balancers",
    "// ------------------------------------------------------------------",
    "http.route({",
    '  path: "/api/health",',
    '  method: "GET",',
    "  handler: httpAction(async () => {",
    "    return new Response(",
    '      JSON.stringify({ ok: true, timestamp: Date.now(), service: "convex" }),',
    '      { status: 200, headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } },',
    "    );",
    "  }),",
    "});",
    "",
    "http.route({",
    '  path: "/api/health",',
    '  method: "OPTIONS",',
    "  handler: httpAction(async () => {",
    "    return new Response(null, {",
    "      status: 204,",
    "      headers: {",
    '        "Access-Control-Allow-Origin": "*",',
    '        "Access-Control-Allow-Methods": "GET, OPTIONS",',
    '        "Access-Control-Allow-Headers": "Content-Type, Authorization",',
    "      },",
    "    });",
    "  }),",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// CORS preflight for auth — required for crossDomain cookie flow",
    "// crossDomain plugin needs credentials true",
    "// ------------------------------------------------------------------",
    "http.route({",
    '  pathPrefix: "/api/auth/",',
    '  method: "OPTIONS",',
    "  handler: httpAction(async (_, request) => {",
    '    const origin = request.headers.get("Origin") ?? "*";',
    "    return new Response(null, {",
    "      status: 204,",
    "      headers: {",
    '        "Access-Control-Allow-Origin": origin,',
    '        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",',
    '        "Access-Control-Allow-Headers": "Content-Type, Authorization, Cookie",',
    '        "Access-Control-Allow-Credentials": "true",',
    "      },",
    "    });",
    "  }),",
    "});",
    "",
    "// ------------------------------------------------------------------",
    "// Billing webhook httpActions — Convex-native alternative",
    "// Raw signature verification ideally stays in Next.js route (needs Buffer),",
    "// but these endpoints provide idempotent storage via api.billing.upsertWebhookEvent",
    "// and return 200 quickly. Next.js route can call convex mutation directly too.",
    "// ------------------------------------------------------------------",
    "function corsHeaders(origin: string | null) {",
    "  return {",
    '    "Content-Type": "application/json",',
    '    "Access-Control-Allow-Origin": origin ?? "*",',
    '    "Access-Control-Allow-Methods": "POST, GET, OPTIONS",',
    '    "Access-Control-Allow-Headers": "Content-Type, Authorization, Stripe-Signature, X-Chargily-Signature, Paddle-Signature, Polar-Signature",',
    "  };",
    "}",
    "",
    "http.route({",
    '  path: "/api/webhooks/stripe",',
    '  method: "POST",',
    "  handler: httpAction(async (ctx, request) => {",
    '    const origin = request.headers.get("Origin");',
    "    try {",
    "      const payload = await request.json();",
    "      const eventId = (payload as unknown as Record<string, unknown>)?.id ?? (payload as unknown as Record<string, unknown>)?.providerEventId ?? `evt_${Date.now()}`;",
    '      const type = (payload as unknown as Record<string, unknown>)?.type ?? "unknown";',
    "      await ctx.runMutation(api.billing.upsertWebhookEvent, {",
    '        provider: "stripe",',
    "        providerEventId: String(eventId),",
    "        type: String(type),",
    "        payload,",
    "        processed: false,",
    "      });",
    '      return new Response(JSON.stringify({ received: true, provider: "stripe", eventId }), {',
    "        status: 200,",
    "        headers: corsHeaders(origin),",
    "      });",
    "    } catch (e) {",
    '      return new Response(JSON.stringify({ error: "Invalid payload" }), { status: 400, headers: corsHeaders(origin) });',
    "    }",
    "  }),",
    "});",
    "",
    "// Generic handlers for chargily/paddle/polar",
    'const webhookProviders = ["chargily", "paddle", "polar"] as const;',
    "for (const provider of webhookProviders) {",
    "  http.route({",
    "    path: `/api/webhooks/${provider}`,",
    '    method: "POST",',
    "    handler: httpAction(async (ctx, request) => {",
    '      const origin = request.headers.get("Origin");',
    "      try {",
    "        const payload = await request.json();",
    "        const anyPayload = payload as unknown as Record<string, unknown>;",
    "        const eventId = anyPayload?.id ?? anyPayload?.event_id ?? anyPayload?.providerEventId ?? `${provider}_${Date.now()}`;",
    '        const type = anyPayload?.type ?? anyPayload?.event ?? "unknown";',
    "        await ctx.runMutation(api.billing.upsertWebhookEvent, {",
    "          provider,",
    "          providerEventId: String(eventId),",
    "          type: String(type),",
    "          payload,",
    "          processed: false,",
    "        });",
    "        return new Response(JSON.stringify({ received: true, provider, eventId }), {",
    "          status: 200,",
    "          headers: corsHeaders(origin),",
    "        });",
    "      } catch {",
    '        return new Response(JSON.stringify({ error: "Invalid payload" }), { status: 400, headers: corsHeaders(origin) });',
    "      }",
    "    }),",
    "  });",
    "}",
    "",
    "export default http;",
    "",
  ].join("\n");
}
