/**
 * convex/http.ts — HTTP router mounting the auth handler.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexHttpContent(hasAuth = true): string {
  return [
    'import { httpRouter } from "convex/server";',
    'import { httpAction } from "./_generated/server";',
    ...(hasAuth ? ['import { authComponent, createAuth } from "./auth";'] : []),
    "",
    "const http = httpRouter();",
    "",
    ...(hasAuth
      ? ["// Better Auth routes", "authComponent.registerRoutes(http, createAuth);"]
      : []),
    "",
    "// ------------------------------------------------------------------",
    "// Health check — used by @repo/database healthCheck() and load balancers",
    "// ------------------------------------------------------------------",
    "http.route({",
    '  path: "/api/health",',
    '  method: "GET",',
    "  handler: httpAction(async () => {",
    "    return new Response(",
    '      JSON.stringify({ ok: true, timestamp: Date.now(), service: "convex" }),',
    '      { status: 200, headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } },',
    "    );",
    "  }),",
    "});",
    "",
    "http.route({",
    '  path: "/api/health",',
    '  method: "OPTIONS",',
    "  handler: httpAction(async () => {",
    "    return new Response(null, {",
    "      status: 204,",
    "      headers: {",
    '        "Access-Control-Allow-Origin": "*",',
    '        "Access-Control-Allow-Methods": "GET, OPTIONS",',
    '        "Access-Control-Allow-Headers": "Content-Type, Authorization",',
    "      },",
    "    });",
    "  }),",
    "});",
    "",
    ...(hasAuth
      ? [
          "// ------------------------------------------------------------------",
          "// CORS preflight for auth — required for crossDomain cookie flow",
          "// crossDomain plugin needs credentials true",
          "// ------------------------------------------------------------------",
          "http.route({",
          '  pathPrefix: "/api/auth/",',
          '  method: "OPTIONS",',
          "  handler: httpAction(async (_, request) => {",
          '    const origin = request.headers.get("Origin") ?? "*";',
          "    return new Response(null, {",
          "      status: 204,",
          "      headers: {",
          '        "Access-Control-Allow-Origin": origin,',
          '        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",',
          '        "Access-Control-Allow-Headers": "Content-Type, Authorization, Cookie",',
          '        "Access-Control-Allow-Credentials": "true",',
          "      },",
          "    });",
          "  }),",
          "});",
          "",
        ]
      : []),
    "// Provider webhooks are intentionally not mounted here. The framework route",
    "// owns raw-body signature verification before it calls Convex mutations.",
    "// A JSON-parsing Convex endpoint would create an unsigned bypass.",
    "",
    "export default http;",
    "",
  ].join("\n");
}
