/**
 * convex/lib/auth.ts — app-owned Convex actor lookup and authorization guards.
 *
 * Better Auth owns identity. The mapped users table owns application IDs,
 * roles, and bans; feature functions must authorize against that table.
 */

export function convexLibAuthContent(): string {
  return [
    'import { ConvexError } from "convex/values";',
    'import type { Doc } from "../_generated/dataModel";',
    'import type { MutationCtx, QueryCtx } from "../_generated/server";',
    'import { authComponent } from "../auth";',
    "",
    "type DatabaseCtx = QueryCtx | MutationCtx;",
    "",
    'export async function findUserByAuthId(ctx: DatabaseCtx, authId: string): Promise<Doc<"users"> | null> {',
    "  return await ctx.db",
    '    .query("users")',
    '    .withIndex("by_authId", (query) => query.eq("authId", authId))',
    "    .unique();",
    "}",
    "",
    'export function isUserBanned(user: Doc<"users">, now = Date.now()): boolean {',
    "  return user.banned && (user.banExpires === undefined || user.banExpires > now);",
    "}",
    "",
    "// Returns null when Better Auth cannot validate a current session. A missing mapping fails closed.",
    'export async function findCurrentActor(ctx: DatabaseCtx): Promise<Doc<"users"> | null> {',
    "  const authUser = await authComponent.safeGetAuthUser(ctx);",
    "  if (!authUser) return null;",
    "  const actor = await findUserByAuthId(ctx, authUser._id);",
    "  if (!actor) {",
    '    throw new ConvexError({ code: "AUTH_MAPPING_MISSING", message: "Authenticated identity has no app user mapping" });',
    "  }",
    "  if (isUserBanned(actor)) {",
    '    throw new ConvexError({ code: "USER_BANNED", message: "This account is banned" });',
    "  }",
    "  return actor;",
    "}",
    "",
    'export async function requireActor(ctx: DatabaseCtx): Promise<Doc<"users">> {',
    "  const actor = await findCurrentActor(ctx);",
    '  if (!actor) throw new ConvexError({ code: "UNAUTHENTICATED", message: "Authentication required" });',
    "  return actor;",
    "}",
    "",
    'export async function requireAdminActor(ctx: DatabaseCtx): Promise<Doc<"users">> {',
    "  const actor = await requireActor(ctx);",
    '  if (actor.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Admin only" });',
    "  return actor;",
    "}",
    "",
  ].join("\n");
}
