/**
 * convex/posts.ts — posts queries and mutations.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexPostsContent(): string {
  return [
    'import { v } from "convex/values";',
    'import { query, mutation } from "./_generated/server";',
    'import type { Doc } from "./_generated/dataModel";',
    'import { paginationOptsValidator } from "convex/server";',
    'import { ConvexError } from "convex/values";',
    'import { requireActor } from "./lib/auth";',
    "",
    "// CRUD with auth guard throwing UNAUTHENTICATED + pagination via by_userId_createdAt index",
    "export const list = query({",
    "  args: {",
    "    paginationOpts: paginationOptsValidator,",
    '    userId: v.optional(v.id("users")),',
    "  },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    "    const targetUserId = args.userId ?? actor._id;",
    '    if (targetUserId !== actor._id && actor.role !== "admin") {',
    '      throw new ConvexError({ code: "FORBIDDEN", message: "Cannot list other users posts" });',
    "    }",
    '    return await ctx.db.query("posts").withIndex("by_userId_createdAt", (q) => q.eq("userId", targetUserId)).order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const get = query({",
    '  args: { id: v.id("posts") },',
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    "    const post = await ctx.db.get(args.id);",
    '    if (!post) throw new ConvexError({ code: "NOT_FOUND", message: "Post not found" });',
    '    if (post.userId !== actor._id && actor.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Forbidden" });',
    "    return post;",
    "  },",
    "});",
    "",
    "export const create = mutation({",
    "  args: {",
    "    title: v.string(),",
    "    content: v.string(),",
    "  },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    "    const title = args.title.trim();",
    "    const content = args.content;",
    '    if (title.length < 3) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Title must be >=3 chars" });',
    '    if (title.length > 200) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Title too long (max 200)" });',
    '    if (content.trim().length < 1) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Content required" });',
    '    if (content.length > 100_000) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Content too large (max 100k)" });',
    '    return await ctx.db.insert("posts", { userId: actor._id, title, content, createdAt: Date.now(), updatedAt: Date.now() });',
    "  },",
    "});",
    "",
    "export const update = mutation({",
    "  args: {",
    '    id: v.id("posts"),',
    "    title: v.optional(v.string()),",
    "    content: v.optional(v.string()),",
    "  },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    "    const post = await ctx.db.get(args.id);",
    '    if (!post) throw new ConvexError({ code: "NOT_FOUND", message: "Post not found" });',
    '    if (post.userId !== actor._id && actor.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Forbidden" });',
    '    const updates: Partial<Pick<Doc<"posts">, "title" | "content" | "updatedAt">> = { updatedAt: Date.now() };',
    "    if (args.title !== undefined) {",
    "      const t = args.title.trim();",
    '      if (t.length < 3) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Title >=3" });',
    '      if (t.length > 200) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Title too long" });',
    "      updates.title = t;",
    "    }",
    "    if (args.content !== undefined) {",
    '      if (args.content.trim().length < 1) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Content required" });',
    '      if (args.content.length > 100_000) throw new ConvexError({ code: "VALIDATION_ERROR", message: "Content too large" });',
    "      updates.content = args.content;",
    "    }",
    "    await ctx.db.patch(args.id, updates);",
    "    return await ctx.db.get(args.id);",
    "  },",
    "});",
    "",
    "export const remove = mutation({",
    '  args: { id: v.id("posts") },',
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    "    const post = await ctx.db.get(args.id);",
    '    if (!post) throw new ConvexError({ code: "NOT_FOUND", message: "Post not found" });',
    '    if (post.userId !== actor._id && actor.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Forbidden" });',
    "    await ctx.db.delete(args.id);",
    "    return { deleted: true, id: args.id };",
    "  },",
    "});",
    "",
  ].join("\n");
}
