/**
 * convex/schema.ts — hardened tables, composite indexes, tight validators.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexSchemaContent(): string {
  return [
    'import { defineSchema, defineTable } from "convex/server";',
    'import { v } from "convex/values";',
    "",
    "// ------------------------------------------------------------------",
    "// Validators — tight unions, no loose v.string() for statuses",
    "// metadata uses v.record instead of v.any() to avoid 1MB DoS and log leak",
    "// payload in webhook_events intentionally v.any() for Stripe arbitrary JSON,",
    "// but mutation checks size <900k",
    "// ------------------------------------------------------------------",
    'const billingProvider = v.union(v.literal("stripe"), v.literal("chargily"), v.literal("paddle"), v.literal("polar"));',
    "const subscriptionStatus = v.union(",
    '  v.literal("active"),',
    '  v.literal("trialing"),',
    '  v.literal("past_due"),',
    '  v.literal("canceled"),',
    '  v.literal("unpaid"),',
    '  v.literal("incomplete"),',
    '  v.literal("incomplete_expired"),',
    '  v.literal("paused"),',
    '  v.literal("expired"),',
    '  v.literal("on_trial"),',
    '  v.literal("trial_ended"),',
    ");",
    'const checkoutStatus = v.union(v.literal("pending"), v.literal("paid"), v.literal("completed"), v.literal("failed"), v.literal("open"), v.literal("expired"));',
    'const invoiceStatus = v.union(v.literal("draft"), v.literal("open"), v.literal("paid"), v.literal("void"), v.literal("uncollectible"));',
    'const licenseKeyStatus = v.union(v.literal("active"), v.literal("revoked"), v.literal("expired"));',
    'const recurringInterval = v.union(v.literal("month"), v.literal("year"), v.literal("week"), v.literal("day"), v.literal("one_time"));',
    "",
    "// Metadata tightened: record<string, string|number|boolean|null> - no v.any()",
    "const metadataValidator = v.optional(",
    "  v.record(v.string(), v.union(v.string(), v.number(), v.boolean(), v.null())),",
    ");",
    "",
    "export default defineSchema({",
    "  users: defineTable({",
    "    name: v.optional(v.string()),",
    "    email: v.string(),",
    "    emailVerified: v.optional(v.number()),",
    "    image: v.optional(v.string()),",
    '    role: v.optional(v.union(v.literal("user"), v.literal("admin"))),',
    "    banned: v.optional(v.boolean()),",
    "    banReason: v.optional(v.string()),",
    "    banExpires: v.optional(v.number()),",
    "    twoFactorEnabled: v.optional(v.boolean()),",
    "    createdAt: v.optional(v.number()),",
    "    updatedAt: v.optional(v.number()),",
    '  }).index("by_email", ["email"]),',
    "",
    "  accounts: defineTable({",
    '    userId: v.id("users"),',
    "    provider: v.string(),",
    "    providerAccountId: v.string(),",
    "    accessToken: v.optional(v.string()),",
    "    refreshToken: v.optional(v.string()),",
    "    idToken: v.optional(v.string()),",
    "    scope: v.optional(v.string()),",
    "    createdAt: v.optional(v.number()),",
    '  }).index("by_userId", ["userId"]).index("by_providerAccountId", ["provider", "providerAccountId"]),',
    "",
    "  sessions: defineTable({",
    '    userId: v.id("users"),',
    "    token: v.string(),",
    "    expiresAt: v.number(),",
    "    ipAddress: v.optional(v.string()),",
    "    userAgent: v.optional(v.string()),",
    '    impersonatedBy: v.optional(v.id("users")),',
    "    createdAt: v.optional(v.number()),",
    '  }).index("by_token", ["token"]).index("by_userId", ["userId"]),',
    "",
    "  verifications: defineTable({",
    "    identifier: v.string(),",
    "    value: v.string(),",
    "    expiresAt: v.number(),",
    "    createdAt: v.optional(v.number()),",
    '  }).index("by_identifier", ["identifier"]),',
    "",
    "  twoFactor: defineTable({",
    '    userId: v.id("users"),',
    "    secret: v.string(),",
    "    backupCodes: v.string(),",
    "    verified: v.optional(v.boolean()),",
    "    failedVerificationCount: v.optional(v.number()),",
    "    lockedUntil: v.optional(v.number()),",
    '  }).index("by_userId", ["userId"]),',
    "",
    "  products: defineTable({",
    "    name: v.string(),",
    "    provider: billingProvider,",
    "    providerProductId: v.optional(v.string()),",
    "    description: v.optional(v.string()),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "    updatedAt: v.optional(v.number()),",
    '  }).index("by_provider", ["provider"]).index("by_providerProductId", ["providerProductId"]).index("by_provider_providerProductId", ["provider", "providerProductId"]),',
    "",
    "  prices: defineTable({",
    '    productId: v.optional(v.id("products")),',
    "    providerPriceId: v.optional(v.string()),",
    "    providerProductId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    unitAmount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    recurringInterval: v.optional(recurringInterval),",
    "    active: v.optional(v.boolean()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    '  }).index("by_productId", ["productId"]).index("by_provider", ["provider"]).index("by_providerPriceId", ["providerPriceId"]).index("by_provider_providerPriceId", ["provider", "providerPriceId"]),',
    "",
    "  customers: defineTable({",
    '    userId: v.optional(v.id("users")),',
    "    email: v.string(),",
    "    provider: billingProvider,",
    "    providerCustomerId: v.string(),",
    "    name: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "  })",
    '    .index("by_email", ["email"])',
    '    .index("by_userId", ["userId"])',
    '    .index("by_providerCustomerId", ["providerCustomerId"])',
    '    .index("by_provider", ["provider"])',
    '    .index("by_provider_providerCustomerId", ["provider", "providerCustomerId"])',
    '    .index("by_provider_email", ["provider", "email"]),',
    "",
    "  subscriptions: defineTable({",
    '    userId: v.id("users"),',
    "    provider: billingProvider,",
    "    providerSubscriptionId: v.string(),",
    "    status: subscriptionStatus,",
    "    priceId: v.optional(v.string()),",
    "    productId: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    currentPeriodEnd: v.optional(v.number()),",
    "    trialEnd: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    canceledAt: v.optional(v.number()),",
    "    createdAt: v.optional(v.number()),",
    "    updatedAt: v.optional(v.number()),",
    "  })",
    '    .index("by_userId", ["userId"])',
    '    .index("by_provider", ["provider"])',
    '    .index("by_providerSubscriptionId", ["providerSubscriptionId"])',
    '    .index("by_provider_providerSubscriptionId", ["provider", "providerSubscriptionId"])',
    '    .index("by_userId_status", ["userId", "status"]),',
    "",
    "  checkouts: defineTable({",
    '    userId: v.optional(v.id("users")),',
    "    provider: billingProvider,",
    "    providerCheckoutId: v.string(),",
    "    status: checkoutStatus,",
    "    customerId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "  })",
    '    .index("by_userId", ["userId"])',
    '    .index("by_providerCheckoutId", ["providerCheckoutId"])',
    '    .index("by_provider_providerCheckoutId", ["provider", "providerCheckoutId"])',
    '    .index("by_provider", ["provider"]),',
    "",
    "  invoices: defineTable({",
    '    userId: v.optional(v.id("users")),',
    "    provider: billingProvider,",
    "    providerInvoiceId: v.string(),",
    "    status: invoiceStatus,",
    "    amount: v.optional(v.number()),",
    "    currency: v.optional(v.string()),",
    "    customerId: v.optional(v.string()),",
    "    subscriptionId: v.optional(v.string()),",
    "    url: v.optional(v.string()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "  })",
    '    .index("by_userId", ["userId"])',
    '    .index("by_providerInvoiceId", ["providerInvoiceId"])',
    '    .index("by_provider_providerInvoiceId", ["provider", "providerInvoiceId"])',
    '    .index("by_provider", ["provider"])',
    '    .index("by_subscriptionId", ["subscriptionId"]),',
    "",
    "  license_keys: defineTable({",
    '    subscriptionId: v.id("subscriptions"),',
    "    key: v.string(),",
    "    status: licenseKeyStatus,",
    "    provider: billingProvider,",
    "    name: v.optional(v.string()),",
    "    expiresAt: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "    updatedAt: v.optional(v.number()),",
    '  }).index("by_subscriptionId", ["subscriptionId"]).index("by_key", ["key"]).index("by_provider", ["provider"]),',
    "",
    "  usage_events: defineTable({",
    '    subscriptionId: v.optional(v.id("subscriptions")),',
    "    name: v.string(),",
    "    credits: v.optional(v.number()),",
    "    externalCustomerId: v.optional(v.string()),",
    "    organizationId: v.optional(v.string()),",
    "    externalId: v.optional(v.string()),",
    "    provider: billingProvider,",
    "    timestamp: v.optional(v.number()),",
    "    metadata: metadataValidator,",
    "    createdAt: v.optional(v.number()),",
    "  })",
    '    .index("by_subscriptionId", ["subscriptionId"])',
    '    .index("by_externalCustomerId", ["externalCustomerId"])',
    '    .index("by_provider", ["provider"])',
    '    .index("by_name", ["name"])',
    '    .index("by_provider_externalCustomerId", ["provider", "externalCustomerId"]),',
    "",
    "  webhook_events: defineTable({",
    "    provider: billingProvider,",
    "    providerEventId: v.string(),",
    "    type: v.string(),",
    "    // Stripe payload arbitrary JSON — keep v.any() but size-checked in mutation (<900k)",
    "    payload: v.any(),",
    "    processed: v.boolean(),",
    "    createdAt: v.optional(v.number()),",
    "    processedAt: v.optional(v.number()),",
    "  })",
    '    .index("by_provider_event", ["provider", "providerEventId"])',
    '    .index("by_provider", ["provider"])',
    '    .index("by_processed", ["processed"])',
    '    .index("by_providerEventId", ["providerEventId"]),',
    "",
    "  posts: defineTable({",
    '    userId: v.id("users"),',
    "    title: v.string(),",
    "    content: v.string(),",
    "    createdAt: v.optional(v.number()),",
    "    updatedAt: v.optional(v.number()),",
    '  }).index("by_userId", ["userId"]).index("by_createdAt", ["createdAt"]).index("by_userId_createdAt", ["userId", "createdAt"]),',
    "});",
    "",
  ].join("\n");
}
