/**
 * convex/users.ts — app-user queries and guarded administration mutations.
 *
 * Better Auth IDs are resolved to app-owned Convex users before authorization.
 */

export function convexUsersContent(): string {
  return [
    'import { paginationOptsValidator } from "convex/server";',
    'import { ConvexError, v } from "convex/values";',
    'import type { Doc } from "./_generated/dataModel";',
    'import { internalMutation, mutation, query, type MutationCtx } from "./_generated/server";',
    'import { findCurrentActor, findUserByAuthId, isUserBanned, requireActor, requireAdminActor } from "./lib/auth";',
    "",
    'const userRole = v.union(v.literal("user"), v.literal("admin"));',
    "",
    'async function requireTarget(ctx: MutationCtx, authId: string): Promise<Doc<"users">> {',
    '  if (authId.trim().length === 0) throw new ConvexError({ code: "VALIDATION_ERROR", message: "authId is required" });',
    "  const target = await findUserByAuthId(ctx, authId);",
    '  if (!target) throw new ConvexError({ code: "NOT_FOUND", message: "User mapping not found" });',
    "  return target;",
    "}",
    "",
    'async function requireAnotherActiveAdmin(ctx: MutationCtx, target: Doc<"users">): Promise<void> {',
    '  if (target.role !== "admin" || isUserBanned(target)) return;',
    "  const admins = await ctx.db",
    '    .query("users")',
    '    .withIndex("by_role", (query) => query.eq("role", "admin"))',
    "    .collect();",
    "  const hasOtherActiveAdmin = admins.some(",
    "    (candidate) => candidate._id !== target._id && !isUserBanned(candidate),",
    "  );",
    "  if (!hasOtherActiveAdmin) {",
    '    throw new ConvexError({ code: "LAST_ADMIN", message: "The last active admin cannot be removed" });',
    "  }",
    "}",
    "",
    "// Public request boundary: null means unauthenticated; missing mappings and bans fail closed.",
    "export const me = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    return await findCurrentActor(ctx);",
    "  },",
    "});",
    "",
    "export const getCurrentUser = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    return await requireActor(ctx);",
    "  },",
    "});",
    "",
    "export const list = query({",
    "  args: { paginationOpts: paginationOptsValidator },",
    "  handler: async (ctx, args) => {",
    "    await requireAdminActor(ctx);",
    '    return await ctx.db.query("users").order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const setRoleByAuthId = mutation({",
    "  args: { authId: v.string(), role: userRole },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireAdminActor(ctx);",
    "    const target = await requireTarget(ctx, args.authId);",
    "    if (target.role === args.role) return target;",
    '    if (target.role === "admin" && args.role !== "admin") {',
    "      await requireAnotherActiveAdmin(ctx, target);",
    "    }",
    '    if (target._id === actor._id && args.role !== "admin") {',
    '      throw new ConvexError({ code: "SELF_DEMOTION", message: "Admins cannot demote themselves" });',
    "    }",
    "    const now = Date.now();",
    "    await ctx.db.patch(target._id, { role: args.role, updatedAt: now });",
    '    await ctx.db.insert("admin_audit_events", {',
    '      actor: { kind: "user", userId: actor._id, authId: actor.authId },',
    "      targetUserId: target._id,",
    "      targetAuthId: target.authId,",
    '      event: { type: "user.role.changed", previousRole: target.role, nextRole: args.role },',
    "      createdAt: now,",
    "    });",
    "    return await ctx.db.get(target._id);",
    "  },",
    "});",
    "",
    "export const setBannedByAuthId = mutation({",
    "  args: { authId: v.string(), banned: v.boolean(), reason: v.optional(v.string()) },",
    "  handler: async (ctx, args) => {",
    "    const actor = await requireAdminActor(ctx);",
    "    const target = await requireTarget(ctx, args.authId);",
    "    if (target.banned === args.banned) return target;",
    '    if (args.banned && target.role === "admin") {',
    "      await requireAnotherActiveAdmin(ctx, target);",
    "    }",
    "    if (args.banned && target._id === actor._id) {",
    '      throw new ConvexError({ code: "SELF_BAN", message: "Admins cannot ban themselves" });',
    "    }",
    "    const suppliedReason = args.reason?.trim();",
    "    if (suppliedReason && suppliedReason.length > 500) {",
    '      throw new ConvexError({ code: "VALIDATION_ERROR", message: "Ban reason must be at most 500 characters" });',
    "    }",
    '    const reason = args.banned ? suppliedReason || "Banned by administrator" : undefined;',
    "    const now = Date.now();",
    "    await ctx.db.patch(target._id, {",
    "      banned: args.banned,",
    "      banReason: reason,",
    "      banExpires: undefined,",
    "      updatedAt: now,",
    "    });",
    '    await ctx.db.insert("admin_audit_events", {',
    '      actor: { kind: "user", userId: actor._id, authId: actor.authId },',
    "      targetUserId: target._id,",
    "      targetAuthId: target.authId,",
    "      event: {",
    '        type: "user.ban.changed",',
    "        previousBanned: target.banned,",
    "        nextBanned: args.banned,",
    "        reason,",
    "      },",
    "      createdAt: now,",
    "    });",
    "    return await ctx.db.get(target._id);",
    "  },",
    "});",
    "",
    "// Internal-only bootstrap primitive. It is absent from the public `api` client surface.",
    "// Invoke it only from trusted Convex deployment/server tooling; no client secret is minted.",
    "export const seedFirstAdmin = internalMutation({",
    "  args: { authId: v.string() },",
    "  handler: async (ctx, args) => {",
    "    const target = await requireTarget(ctx, args.authId);",
    "    const existingAdmin = await ctx.db",
    '      .query("users")',
    '      .withIndex("by_role", (query) => query.eq("role", "admin"))',
    "      .first();",
    "    if (existingAdmin) {",
    '      throw new ConvexError({ code: "BOOTSTRAP_CLOSED", message: "An admin already exists" });',
    "    }",
    "    if (isUserBanned(target)) {",
    '      throw new ConvexError({ code: "USER_BANNED", message: "A banned user cannot be bootstrapped" });',
    "    }",
    "    const now = Date.now();",
    '    await ctx.db.patch(target._id, { role: "admin", updatedAt: now });',
    '    await ctx.db.insert("admin_audit_events", {',
    '      actor: { kind: "bootstrap" },',
    "      targetUserId: target._id,",
    "      targetAuthId: target.authId,",
    '      event: { type: "user.role.changed", previousRole: target.role, nextRole: "admin" },',
    "      createdAt: now,",
    "    });",
    "    return await ctx.db.get(target._id);",
    "  },",
    "});",
    "",
    "export const getById = query({",
    '  args: { id: v.id("users") },',
    "  handler: async (ctx, args) => {",
    "    const actor = await requireActor(ctx);",
    '    if (actor._id !== args.id && actor.role !== "admin") {',
    '      throw new ConvexError({ code: "FORBIDDEN", message: "Forbidden" });',
    "    }",
    "    const user = await ctx.db.get(args.id);",
    '    if (!user) throw new ConvexError({ code: "NOT_FOUND", message: "User not found" });',
    "    return user;",
    "  },",
    "});",
    "",
  ].join("\n");
}
