/**
 * convex/users.ts — user queries.
 *
 * Extracted verbatim from database/convex.ts, which had grown past 1100 LOC.
 */

export function convexUsersContent(): string {
  return [
    'import { v } from "convex/values";',
    'import { query, type QueryCtx } from "./_generated/server";',
    'import type { Doc } from "./_generated/dataModel";',
    'import { paginationOptsValidator } from "convex/server";',
    'import { ConvexError } from "convex/values";',
    'import { authComponent } from "./auth";',
    "",
    'async function findCurrentUser(ctx: QueryCtx): Promise<Doc<"users"> | null> {',
    "  const authUser = await authComponent.safeGetAuthUser(ctx);",
    "  if (!authUser) return null;",
    "  return await ctx.db",
    '    .query("users")',
    '    .withIndex("by_authId", (query) => query.eq("authId", authUser._id))',
    "    .unique();",
    "}",
    "",
    'async function requireCurrentUser(ctx: QueryCtx): Promise<Doc<"users">> {',
    "  const user = await findCurrentUser(ctx);",
    '  if (!user) throw new ConvexError({ code: "UNAUTHENTICATED", message: "Not authenticated" });',
    "  return user;",
    "}",
    "",
    "// Public request boundary — returns the app-owned user or null.",
    "export const me = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    return await findCurrentUser(ctx);",
    "  },",
    "});",
    "",
    "export const getCurrentUser = query({",
    "  args: {},",
    "  handler: async (ctx) => {",
    "    return await requireCurrentUser(ctx);",
    "  },",
    "});",
    "",
    "// Admin list guarded — requires admin role, demonstrates pagination",
    "export const list = query({",
    "  args: { paginationOpts: paginationOptsValidator },",
    "  handler: async (ctx, args) => {",
    "    const user = await requireCurrentUser(ctx);",
    '    if (user.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Admin only" });',
    '    return await ctx.db.query("users").order("desc").paginate(args.paginationOpts);',
    "  },",
    "});",
    "",
    "export const getById = query({",
    '  args: { id: v.id("users") },',
    "  handler: async (ctx, args) => {",
    "    const current = await requireCurrentUser(ctx);",
    '    if (current._id !== args.id && current.role !== "admin") throw new ConvexError({ code: "FORBIDDEN", message: "Forbidden" });',
    "    return await ctx.db.get(args.id);",
    "  },",
    "});",
    "",
  ].join("\n");
}
