// @allow-long 330: versioned organization tables and operation ownership stay auditable as one fragment
import { entity, field, foreignKey, index, operation, unique } from "../builders.js";
import type { DataEntityBlueprint, DataOperationBlueprint } from "../types.js";

export const organizationIdentityEntities = [
  entity({
    id: "organizations",
    ownership: { authority: "better-auth", plugin: "organization", ownerField: "id" },
    storage: {
      kind: "table",
      postgresTable: "organizations",
      postgresExport: "organizations",
      betterAuthModel: "organization",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("name", "name", "text", { required: true }),
      field("slug", "slug", "text", { required: true, unique: true }),
      field("logo", "logo", "text"),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
      field("updatedAt", "updated_at", "timestamp", { required: true, default: "now" }),
      field("metadata", "metadata", "text"),
    ],
    indexes: [index("organizations_slug_idx", ["slug"], true)],
    constraints: [unique("organizations_slug_unique", ["slug"])],
    lifecycle: { createdAt: "createdAt", deletion: "explicit" },
    operationIds: [
      "identity.organization.create",
      "identity.organization.list",
      "identity.organization.get",
      "identity.organization.find-by-slug",
      "identity.organization.set-active",
      "identity.organization.update",
      "identity.organization.delete",
    ],
  }),
  entity({
    id: "members",
    ownership: {
      authority: "better-auth",
      plugin: "organization",
      ownerField: "userId",
      tenantField: "organizationId",
    },
    storage: {
      kind: "table",
      postgresTable: "members",
      postgresExport: "members",
      betterAuthModel: "member",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("organizationId", "organization_id", "text", {
        required: true,
        reference: { entity: "organizations", field: "id", onDelete: "cascade" },
      }),
      field("userId", "user_id", "text", {
        required: true,
        reference: { entity: "users", field: "id", onDelete: "cascade" },
      }),
      field("role", "role", "text", { required: true, default: "member" }),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
      field("updatedAt", "updated_at", "timestamp", { required: true, default: "now" }),
    ],
    indexes: [
      index("members_organization_idx", ["organizationId"]),
      index("members_user_idx", ["userId"]),
      index("members_organization_user_idx", ["organizationId", "userId"], true),
    ],
    constraints: [
      foreignKey("members_organization_fk", ["organizationId"], "organizations", "id", "cascade"),
      foreignKey("members_user_fk", ["userId"], "users", "id", "cascade"),
      unique("members_organization_user_unique", ["organizationId", "userId"]),
    ],
    lifecycle: { createdAt: "createdAt", deletion: "cascade" },
    operationIds: [
      "identity.member.add",
      "identity.member.list",
      "identity.member.get",
      "identity.member.get-by-id",
      "identity.member.count-owners",
      "identity.member.update-role",
      "identity.member.remove",
    ],
  }),
  entity({
    id: "invitations",
    ownership: {
      authority: "better-auth",
      plugin: "organization",
      ownerField: "inviterId",
      tenantField: "organizationId",
    },
    storage: {
      kind: "table",
      postgresTable: "invitations",
      postgresExport: "invitations",
      betterAuthModel: "invitation",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("organizationId", "organization_id", "text", {
        required: true,
        reference: { entity: "organizations", field: "id", onDelete: "cascade" },
      }),
      field("email", "email", "varchar", { maxLength: 255, required: true }),
      field("role", "role", "text"),
      field("teamId", "team_id", "text", {
        reference: { entity: "teams", field: "id", onDelete: "set-null" },
      }),
      field("status", "status", "text", { required: true, default: "pending" }),
      field("expiresAt", "expires_at", "timestamp", { required: true }),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
      field("inviterId", "inviter_id", "text", {
        required: true,
        reference: { entity: "users", field: "id", onDelete: "restrict" },
      }),
      field("acceptedByUserId", "accepted_by_user_id", "text", {
        reference: { entity: "users", field: "id", onDelete: "set-null" },
      }),
      field("acceptedMemberId", "accepted_member_id", "text", {
        reference: { entity: "members", field: "id", onDelete: "set-null" },
      }),
      field("updatedAt", "updated_at", "timestamp", { required: true, default: "now" }),
    ],
    indexes: [
      index("invitations_organization_idx", ["organizationId"]),
      index("invitations_email_idx", ["email"]),
      index("invitations_expires_at_idx", ["expiresAt"]),
    ],
    constraints: [
      foreignKey(
        "invitations_organization_fk",
        ["organizationId"],
        "organizations",
        "id",
        "cascade",
      ),
      foreignKey("invitations_team_fk", ["teamId"], "teams", "id", "set-null"),
      foreignKey("invitations_inviter_fk", ["inviterId"], "users", "id", "restrict"),
      foreignKey("invitations_accepted_user_fk", ["acceptedByUserId"], "users", "id", "set-null"),
      foreignKey(
        "invitations_accepted_member_fk",
        ["acceptedMemberId"],
        "members",
        "id",
        "set-null",
      ),
    ],
    lifecycle: { createdAt: "createdAt", expiresAt: "expiresAt", deletion: "expire" },
    operationIds: [
      "identity.invitation.create",
      "identity.invitation.list",
      "identity.invitation.get",
      "identity.invitation.find-pending",
      "identity.invitation.accept",
      "identity.invitation.reject",
      "identity.invitation.cancel",
      "identity.invitation.expire",
    ],
  }),
  entity({
    id: "teams",
    ownership: {
      authority: "better-auth",
      plugin: "organization",
      tenantField: "organizationId",
    },
    storage: {
      kind: "table",
      postgresTable: "teams",
      postgresExport: "teams",
      betterAuthModel: "team",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("name", "name", "text", { required: true }),
      field("organizationId", "organization_id", "text", {
        required: true,
        reference: { entity: "organizations", field: "id", onDelete: "cascade" },
      }),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
      field("updatedAt", "updated_at", "timestamp", { required: true, default: "now" }),
    ],
    indexes: [
      index("teams_organization_idx", ["organizationId"]),
      index("teams_organization_name_idx", ["organizationId", "name"], true),
    ],
    constraints: [
      foreignKey("teams_organization_fk", ["organizationId"], "organizations", "id", "cascade"),
      unique("teams_organization_name_unique", ["organizationId", "name"]),
    ],
    lifecycle: { createdAt: "createdAt", updatedAt: "updatedAt", deletion: "cascade" },
    operationIds: [
      "identity.team.create",
      "identity.team.list",
      "identity.team.get",
      "identity.team.find-by-name",
      "identity.team.set-active",
      "identity.team.update",
      "identity.team.delete",
    ],
  }),
  entity({
    id: "teamMembers",
    ownership: {
      authority: "better-auth",
      plugin: "organization",
      ownerField: "userId",
      tenantField: "teamId",
    },
    storage: {
      kind: "table",
      postgresTable: "team_members",
      postgresExport: "teamMembers",
      betterAuthModel: "teamMember",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("teamId", "team_id", "text", {
        required: true,
        reference: { entity: "teams", field: "id", onDelete: "cascade" },
      }),
      field("userId", "user_id", "text", {
        required: true,
        reference: { entity: "users", field: "id", onDelete: "cascade" },
      }),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
    ],
    indexes: [
      index("team_members_team_idx", ["teamId"]),
      index("team_members_user_idx", ["userId"]),
      index("team_members_team_user_idx", ["teamId", "userId"], true),
    ],
    constraints: [
      foreignKey("team_members_team_fk", ["teamId"], "teams", "id", "cascade"),
      foreignKey("team_members_user_fk", ["userId"], "users", "id", "cascade"),
      unique("team_members_team_user_unique", ["teamId", "userId"]),
    ],
    lifecycle: { createdAt: "createdAt", deletion: "cascade" },
    operationIds: [
      "identity.team-member.add",
      "identity.team-member.list",
      "identity.team-member.get",
      "identity.team-member.remove",
    ],
  }),
  entity({
    id: "organizationRoles",
    ownership: {
      authority: "better-auth",
      plugin: "organization",
      tenantField: "organizationId",
    },
    storage: {
      kind: "table",
      postgresTable: "organization_roles",
      postgresExport: "organizationRoles",
      betterAuthModel: "organizationRole",
    },
    fields: [
      field("id", "id", "text", { primaryKey: true, required: true }),
      field("organizationId", "organization_id", "text", {
        required: true,
        reference: { entity: "organizations", field: "id", onDelete: "cascade" },
      }),
      field("role", "role", "text", { required: true }),
      field("permission", "permission", "text", { required: true }),
      field("createdAt", "created_at", "timestamp", { required: true, default: "now" }),
      field("updatedAt", "updated_at", "timestamp", { default: "now" }),
    ],
    indexes: [
      index("organization_roles_organization_idx", ["organizationId"]),
      index("organization_roles_org_role_idx", ["organizationId", "role"], true),
    ],
    constraints: [
      foreignKey(
        "organization_roles_organization_fk",
        ["organizationId"],
        "organizations",
        "id",
        "cascade",
      ),
      unique("organization_roles_org_role_unique", ["organizationId", "role"]),
    ],
    lifecycle: { createdAt: "createdAt", updatedAt: "updatedAt", deletion: "cascade" },
    operationIds: [
      "identity.rbac.role.create",
      "identity.rbac.role.list",
      "identity.rbac.role.update",
      "identity.rbac.role.delete",
      "identity.rbac.permission.check",
    ],
  }),
] as const satisfies readonly DataEntityBlueprint[];

export const organizationIdentityOperations = [
  operation("identity.organization.create", "organizations", "create", "authenticated"),
  operation("identity.organization.list", "organizations", "read", "authenticated"),
  operation("identity.organization.get", "organizations", "read", "member"),
  operation("identity.organization.find-by-slug", "organizations", "read", "authenticated"),
  operation("identity.organization.set-active", "organizations", "update", "member"),
  operation("identity.organization.update", "organizations", "update", "administrator"),
  operation("identity.organization.delete", "organizations", "delete", "owner"),
  operation("identity.member.add", "members", "create", "administrator"),
  operation("identity.member.list", "members", "read", "member"),
  operation("identity.member.get", "members", "read", "member"),
  operation("identity.member.get-by-id", "members", "read", "member"),
  operation("identity.member.count-owners", "members", "read", "administrator"),
  operation("identity.member.update-role", "members", "update", "administrator"),
  operation("identity.member.remove", "members", "delete", "administrator"),
  operation("identity.invitation.create", "invitations", "create", "administrator"),
  operation("identity.invitation.list", "invitations", "read", "member"),
  operation("identity.invitation.get", "invitations", "read", "member"),
  operation("identity.invitation.find-pending", "invitations", "read", "administrator"),
  operation("identity.invitation.accept", "invitations", "update", "invited-user"),
  operation("identity.invitation.reject", "invitations", "update", "invited-user"),
  operation("identity.invitation.cancel", "invitations", "delete", "administrator"),
  operation("identity.invitation.expire", "invitations", "delete", "system"),
  operation("identity.team.create", "teams", "create", "administrator"),
  operation("identity.team.list", "teams", "read", "member"),
  operation("identity.team.get", "teams", "read", "member"),
  operation("identity.team.find-by-name", "teams", "read", "member"),
  operation("identity.team.set-active", "teams", "update", "member"),
  operation("identity.team.update", "teams", "update", "administrator"),
  operation("identity.team.delete", "teams", "delete", "administrator"),
  operation("identity.team-member.add", "teamMembers", "create", "administrator"),
  operation("identity.team-member.list", "teamMembers", "read", "member"),
  operation("identity.team-member.get", "teamMembers", "read", "member"),
  operation("identity.team-member.remove", "teamMembers", "delete", "administrator"),
  operation("identity.rbac.role.create", "organizationRoles", "create", "administrator"),
  operation("identity.rbac.role.list", "organizationRoles", "read", "member"),
  operation("identity.rbac.role.update", "organizationRoles", "update", "administrator"),
  operation("identity.rbac.role.delete", "organizationRoles", "delete", "administrator"),
  operation("identity.rbac.permission.check", "organizationRoles", "execute", "member"),
] as const satisfies readonly DataOperationBlueprint[];
