import { fullDesktopCapabilities, type DesktopCapabilities } from "../model.js";

export function desktopRouteTreeGenContent(
  capabilities: DesktopCapabilities = fullDesktopCapabilities,
): string {
  const routes = [
    { name: "IndexRoute", path: "index", enabled: true },
    { name: "DashboardRoute", path: "dashboard", enabled: capabilities.hasAuth },
    { name: "AgentRoute", path: "agent", enabled: capabilities.hasEve },
    { name: "SettingsRoute", path: "settings", enabled: capabilities.hasAuth },
    {
      name: "WorkspaceRoute",
      path: "workspace",
      enabled: capabilities.hasAuth && capabilities.hasApi,
    },
    { name: "MessagesRoute", path: "messages", enabled: capabilities.hasMessaging },
    {
      name: "NotificationsRoute",
      path: "notifications",
      enabled: capabilities.hasNotifications,
    },
    { name: "StorageRoute", path: "storage", enabled: capabilities.hasStorage },
    {
      name: "FeatureFlagsRoute",
      path: "feature-flags",
      enabled: capabilities.hasFeatureFlags,
    },
    { name: "JobsRoute", path: "jobs", enabled: capabilities.hasJobs },
    { name: "BillingRoute", path: "billing", enabled: capabilities.hasBilling },
    { name: "PdfRoute", path: "pdf", enabled: capabilities.hasPdf },
    { name: "AdminRoute", path: "admin", enabled: capabilities.hasAdmin },
    { name: "AdminUsersRoute", path: "admin.users", enabled: capabilities.hasAdmin },
    {
      name: "AdminUsersCreateRoute",
      path: "admin.users.create",
      enabled: capabilities.hasAdmin,
    },
    {
      name: "TwoFactorRoute",
      path: "2fa",
      enabled: capabilities.hasAuth && capabilities.hasEmail,
    },
    {
      name: "ForgotPasswordRoute",
      path: "forgot-password",
      enabled: capabilities.hasAuth && capabilities.hasEmail,
    },
    {
      name: "ResetPasswordRoute",
      path: "reset-password",
      enabled: capabilities.hasAuth && capabilities.hasEmail,
    },
    {
      name: "MagicLinkRoute",
      path: "magic-link",
      enabled: capabilities.hasAuth && capabilities.hasEmail,
    },
    {
      name: "VerifyEmailRoute",
      path: "verify-email",
      enabled: capabilities.hasAuth && capabilities.hasEmail,
    },
    { name: "SignInRoute", path: "sign-in", enabled: capabilities.hasAuth },
    { name: "SignUpRoute", path: "sign-up", enabled: capabilities.hasAuth },
  ].filter(({ enabled }) => enabled);
  const imports = routes
    .map(({ name, path }) => `import { Route as ${name} } from "./routes/${path}";`)
    .join("\n");
  const children = routes.map(({ name }) => name).join(", ");

  return `// This file is generated by @tanstack/router-plugin. Do not edit manually.
import { Route as RootRoute } from "./routes/__root";
${imports}

export const routeTree = RootRoute.addChildren([${children}]);
`;
}
