import { describe, expect, test } from "bun:test";
import { resolveCreateConfig } from "../../src/commands/create/resolution";
import { sanitizeLegacyCapabilityOutput } from "../../src/generation/capability-output-sanitizer";
import type { TemplateFile } from "../../src/templates/shared";

function resolved(
  options: {
    billing?: readonly "stripe"[];
    featureFlags?: "none" | "posthog";
    preset?: "custom" | "saas";
  } = {},
) {
  const billing = [...(options.billing ?? [])];
  const featureFlags = options.featureFlags ?? "none";
  const result = resolveCreateConfig({
    name: "sanitizer-fixture",
    runtime: "bun",
    mode: "single",
    framework: "nextjs",
    billing,
    features: [],
    database: billing.length > 0 ? "postgres" : "none",
    databaseWasExplicit: true,
    apps: ["web"],
    preset: options.preset ?? (billing.length > 0 ? "saas" : "custom"),
    cache: "none",
    deploy: "none",
    withAuth: billing.length > 0,
    withApi: billing.length > 0 || featureFlags === "posthog",
    withEmail: false,
    withAnalytics: false,
    withEve: false,
    withI18n: false,
    withPdf: false,
    withMessaging: false,
    withStorage: false,
    withNotifications: false,
    featureFlags,
    withJobs: false,
  });
  if (!result.ok) throw new Error(result.message);
  return result.resolvedConfig;
}

function sanitize(files: readonly TemplateFile[], config = resolved()): TemplateFile[] {
  return sanitizeLegacyCapabilityOutput(files, config);
}

describe("legacy capability output sanitizer", () => {
  test("removes disabled auth, storage, billing, and database-none leaf files", () => {
    const removed = [
      "src/lib/access.ts",
      "src/lib/storage.ts",
      "src/lib/storage-server.ts",
      "packages/database/src/schema/auth.ts",
      "packages/database/src/schema/posts.ts",
      "src/server/db/schema/auth.ts",
      "src/server/db/schema/posts.ts",
      "packages/database/src/schema/billing.ts",
      "packages/database/src/schema/enums.ts",
      "src/server/db/schema/billing.ts",
      "src/server/db/schema/enums.ts",
      "packages/services/src/invoice/create.ts",
      "src/server/services/invoice/create.ts",
    ];
    const adjacent = [
      "src/lib/accessibility.ts",
      "src/lib/storage-helper.ts",
      "packages/services/src/invoice-preview.ts",
    ];
    const output = sanitize(
      [...removed, ...adjacent].map((path) => ({ path, content: "export const marker = true;\n" })),
    );
    const paths = output.map(({ path }) => path);

    for (const path of removed) expect(paths, path).not.toContain(path);
    for (const path of adjacent) expect(paths, path).toContain(path);
  });

  test("removes capability barrel entries independent of quote style", () => {
    const output = sanitize([
      {
        path: "packages/kernel/src/index.ts",
        content:
          "export type {\n  AdminUser,\n  UserRole,\n} from './admin';\nexport type { Billing } from \"./billing.js\";\nexport { ok } from './result';\n",
      },
      {
        path: "packages/modules/src/index.ts",
        content:
          "export * as identity from './identity/index.js';\nexport * as catalog from './catalog';\n",
      },
      {
        path: "packages/services/src/index.ts",
        content: "export * as invoice from './invoice/index';\nexport * as core from './core';\n",
      },
    ]);
    const content = output.map((file) => file.content).join("\n");

    expect(content).not.toMatch(/admin|billing|identity|invoice/);
    expect(content).toContain("./result");
    expect(content).toContain("./catalog");
    expect(content).toContain("./core");
  });

  test("keeps an authless modules entry point lintable", () => {
    const output = sanitize([
      {
        path: "packages/modules/src/index.ts",
        content:
          '// Generated by ghostinit sync. Do not edit manually.\nexport * as identity from "./identity/index.js";\n',
      },
    ]);

    expect(output[0]?.content).toBe(
      "// Generated by ghostinit sync. Do not edit manually.\n\nexport {};\n",
    );
  });

  test("intersects public environment variables with the selected app targets", () => {
    const output = sanitize(
      [
        {
          path: ".env.local",
          content:
            "  export NEXT_PUBLIC_APP_URL = http://localhost:3000\nVITE_APP_URL=http://localhost:3000\nBETTER_AUTH_SECRET=disabled\n",
        },
        {
          path: "turbo.json",
          content: `${JSON.stringify({ globalEnv: ["NEXT_PUBLIC_*", "VITE_*", "BETTER_AUTH_SECRET"] })}\n`,
        },
      ],
      resolved(),
    );
    const dotenv = output.find(({ path }) => path === ".env.local")?.content ?? "";
    const turbo = JSON.parse(output.find(({ path }) => path === "turbo.json")?.content ?? "{}") as {
      globalEnv?: string[];
    };

    expect(dotenv).toContain("NEXT_PUBLIC_APP_URL");
    expect(dotenv).not.toContain("VITE_APP_URL");
    expect(dotenv).not.toContain("BETTER_AUTH_SECRET");
    expect(turbo.globalEnv).toEqual(["NEXT_PUBLIC_*"]);
  });

  test("does not retain another target's public billing credentials", () => {
    const output = sanitize(
      [
        {
          path: ".env.example",
          content:
            "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_example\nVITE_STRIPE_PUBLISHABLE_KEY=pk_test_example\n",
        },
      ],
      resolved({ billing: ["stripe"], preset: "saas" }),
    );
    const dotenv = output[0]?.content ?? "";

    expect(dotenv).toContain("NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY");
    expect(dotenv).not.toContain("VITE_STRIPE_PUBLISHABLE_KEY");
  });

  test("keeps shared rate-limit storage for authenticated transport without the cache capability", () => {
    const output = sanitize(
      [
        {
          path: ".env.example",
          content:
            "UPSTASH_REDIS_REST_URL=REPLACE_WITH_UPSTASH_REDIS_REST_URL\nUPSTASH_REDIS_REST_TOKEN=REPLACE_WITH_UPSTASH_REDIS_REST_TOKEN\n",
        },
      ],
      resolved({ billing: ["stripe"], preset: "saas" }),
    );

    expect(output[0]?.content).toContain("UPSTASH_REDIS_REST_URL");
    expect(output[0]?.content).toContain("UPSTASH_REDIS_REST_TOKEN");
  });

  test("retains analytics-disable policy keys for the PostHog feature-flag provider", () => {
    const output = sanitize(
      [
        {
          path: ".env.example",
          content:
            "ANALYTICS_DISABLED=false\nNEXT_PUBLIC_ANALYTICS_DISABLED=false\nVITE_ANALYTICS_DISABLED=false\n",
        },
      ],
      resolved({ featureFlags: "posthog", preset: "custom" }),
    );
    const dotenv = output[0]?.content ?? "";

    expect(dotenv).toContain("ANALYTICS_DISABLED=false");
    expect(dotenv).toContain("NEXT_PUBLIC_ANALYTICS_DISABLED=false");
    expect(dotenv).not.toContain("VITE_ANALYTICS_DISABLED");
  });

  test("rejects active environment keys without an ownership rule", () => {
    expect(() =>
      sanitize([{ path: ".env.local", content: "UNMAPPED_VENDOR_SECRET=do-not-keep\n" }]),
    ).toThrow("has no capability or target ownership rule");
  });
});
