import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { syncCommand } from "../../src/commands/sync";
import { Logger } from "../../src/lib/logger";
import { ghostinitVersion } from "../../packages/versions";
import type { GlobalOptions } from "../../src/commands/types";

function syncOptions(cwd: string): GlobalOptions {
  return {
    cwd,
    json: false,
    yes: true,
    force: true,
    dryRun: false,
    noInstall: true,
    runtime: "bun",
    kind: undefined,
    check: false,
    logger: new Logger({ quiet: true }),
  };
}

function writeProject(root: string): void {
  mkdirSync(join(root, ".ghostinit"), { recursive: true });
  const config = {
    name: "syncdemo",
    runtime: "bun" as const,
    version: "0.1.0",
    generatedAt: new Date().toISOString(),
  };
  writeFileSync(
    join(root, ".ghostinit", "state.json"),
    JSON.stringify(
      {
        version: 1,
        project: config,
        checksums: {},
        generatedBy: ghostinitVersion,
        generatedAt: config.generatedAt,
        modules: [],
        procedures: [],
      },
      null,
      2,
    ),
    "utf-8",
  );
  mkdirSync(join(root, "packages", "modules", "src"), { recursive: true });
  mkdirSync(join(root, "packages", "database", "src", "schema"), { recursive: true });
  mkdirSync(join(root, "packages", "api", "src", "procedures"), { recursive: true });
  writeFileSync(
    join(root, "packages", "modules", "src", "index.ts"),
    "// Generated by ghostinit sync. Do not edit manually.\n",
    "utf-8",
  );
  writeFileSync(
    join(root, "packages", "api", "src", "contract.ts"),
    "export const appContract = {};\n",
    "utf-8",
  );
  writeFileSync(
    join(root, "packages", "api", "src", "router.ts"),
    "export const appRouter = {};\n",
    "utf-8",
  );
}

describe("sync command", () => {
  let root: string;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "ghostinit-sync-"));
    writeProject(root);
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it("rebuilds the database schema index from schema files", async () => {
    writeFileSync(
      join(root, "packages", "database", "src", "schema", "auth.ts"),
      "export const users = {};\n",
      "utf-8",
    );
    writeFileSync(
      join(root, "packages", "database", "src", "schema", "posts.ts"),
      "export const posts = {};\n",
      "utf-8",
    );

    const options = syncOptions(root);
    const code = await syncCommand([], options);
    expect(code).toBe(0);

    const schemaIndex = join(root, "packages", "database", "src", "schema", "index.ts");
    const content = readFileSync(schemaIndex, "utf-8");
    expect(content).toContain('export * from "./auth";');
    expect(content).toContain('export * from "./posts";');
    expect(content.startsWith("// Generated by ghostinit sync")).toBe(true);
  });
});
